### ISSUE TITLE
部署直链后网页访问播放不了任何视频 都是显示没有兼容的流

### ISSUE THREAD

**Issue by suraxiuxiu** [bpking1/embyExternalUrl#106]
用原生8096端口可以正常播放  用代理端口就播放不了任何视频 但是打开外部播放器能正常播放 安卓端emby也能播放
是网页端emby没法解码吗 视频用alist网页是能直接播放的  emby网页全都不能播放有点不方便

**Comment by chen3861229** [comment]
媒体来源都是115网盘吗？这样的话Web浏览器播放不了就是正常的，因为直链后的地址115没有给允许跨域的标识，浏览器对此限制严格，可以参考文档装浏览器拓展解决

**Comment by suraxiuxiu** [comment]
> 媒体来源都是115网盘吗？这样的话Web浏览器播放不了就是正常的，因为直链后的地址115没有给允许跨域的标识，浏览器对此限制严格， 1.可以参考文档装浏览器拓展解决 2.使用对应平台客户端不存在此问题，windows也用客户端 3.或者添加此参数禁用115路径的直链，使用nginx中转原始emby的流量解决
> 
> ```
> // 禁用直链的规则,将转给原始媒体服务器处理,字幕和图片没有走直链,不用添加
> // 参数1: 匹配类型或来源(字符串参数类型) "0": 文件路径(Item.Path)
> // 参数2: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
> // 参数3: 匹配目标
> // 参数4: 是否处理alist响应链接
> const disableRedirectRule = [
>   ["0", 0, "/xxx/115"], // 根据自身实际路径填写
> ];
> ```
谢谢 解决了 
顺便问一下 edge浏览器有办法播放emby的hevc编码的视频吗  这类视频一样提示无法兼容的流

**Comment by chen3861229** [comment]
edge目前是chrome内核的，几年前的版本就支持硬解hevc了，不过和硬件存在兼容性问题，我朋友很老的笔记本就是hevc整体画面很黑，是装了个第三方的hevc拓展才正常的，最近几年的新硬件不用，不过也不存在播放不了的情况，尝试升级下edge版本和显卡驱动，或者猜测是音频格式web端不支持，我很久之前测试了aac和flac之类常见的都是可以的，dts的话只是没声音，但是画面正常，偶尔会出现问题，所以我朋友都转客户端使用了

**Comment by suraxiuxiu** [comment]
> edge目前是chrome内核的，几年前的版本就支持硬解hevc了，不过和硬件存在兼容性问题，我朋友很老的笔记本就是hevc整体画面很黑，是装了个第三方的hevc拓展才正常的，最近几年的新硬件不用，不过也不存在播放不了的情况，尝试升级下edge版本和显卡驱动，或者猜测是音频格式web端不支持，我很久之前测试了aac和flac之类常见的都是可以的，dts的话只是没声音，但是画面正常，偶尔会出现问题，所以我朋友都转客户端使用了
> 
> 下面都是默认的，没有进行过更改
> 
> 输入网址【edge://gpu/】 ![image](https://private-user-images.githubusercontent.com/42368856/323280600-bd64e5c1-cb7f-40e8-8546-2d2d93040281.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjAxNDEsIm5iZiI6MTcxMzQxOTg0MSwicGF0aCI6Ii80MjM2ODg1Ni8zMjMyODA2MDAtYmQ2NGU1YzEtY2I3Zi00MGU4LTg1NDYtMmQyZDkzMDQwMjgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA1NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3ZThjMjZiM2M0ODczZmRjZTg3Y2JmOGUyZTMzODE1YjAxNGM5MTEyZWY5ZDdkYmJmNzkxOGZhN2FmNTJlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DQcPi4iBvcmQcxOQelERB0OjpeIy11WHAgHjsA9iYAI)
> 
> 输入网址【edge://flags/】 ![image](https://private-user-images.githubusercontent.com/42368856/323281486-743712c0-e924-40d8-9fd1-735174362169.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MjAxNDEsIm5iZiI6MTcxMzQxOTg0MSwicGF0aCI6Ii80MjM2ODg1Ni8zMjMyODE0ODYtNzQzNzEyYzAtZTkyNC00MGQ4LTlmZDEtNzM1MTc0MzYyMTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA1NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmOTFjZTk3ZTcwNTFhZDYzZTlmYzYwMDg0YTZmNjlhMzAzMzQwN2ExYTM4OTQ2NGU3M2EwYjdlZDZiN2IxNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oP0J9ECYgunvBmlkASJQYyylu6hFUpLwc2yZWll7QS4)
> 
> 不确定是否有用，可以尝试一下 https://microsoftedge.microsoft.com/addons/detail/h265ify/hpamdcillfipbkdijibjoojnofelpgjb

好 谢谢 我检查了一下 edge的这些选项和你截图的都一样  hevc和硬解是启用的  但是无法播放任何hevc的视频 不单止emby
但是Chrome又能正常播放 很迷惑 我再折腾一下..
顺便问一下客户端是用emby官方的吗?  Window客户端没充钱不给看视频= =

**Comment by chen3861229** [comment]
那你这和我另外一个朋友差不多，是edge的兼容性问题，他也是chrome正常，试下那个h265ify的拓展，然后微软商店里也有个hevc的系统插件，虽然显示收费8块，但是网上有个其他链接进去网页版商店是免费的，也可以装完试试。
客户端全用的xx版。。

**Comment by chen3861229** [comment]
https://t.me/EmbyNoisyX

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by suraxiuxiu** [comment]
> 那你这和我另外一个朋友差不多，是edge的兼容性问题，他也是chrome正常，试下那个h265ify的拓展，然后微软商店里也有个hevc的系统插件，虽然显示收费8块，但是网上有个其他链接进去网页版商店是免费的，也可以装完试试。 客户端全用的xx版。。

新电脑的edge咋折腾都没用 另一个旧办公本上的edge秒开hevc.. 给我整不会了  最后装了个beta版edge就能直接打开了 迷惑  
总之谢谢啦

**Comment by Katou-Kouseki** [comment]
有个疑问想请教一下大佬，alist中播放同样是调用的115直链，不会出现播放失败的问题。是因为emby的web端播放拉胯吗(

**Comment by chen3861229** [comment]
不是的，是实现原理不同，导致浏览器默认跨域拦截，alist播放跨域视频是独立请求的，因为web端是alist自己的，所以可以解决，但是emby的web一般是没法修改的(当然可以装脚本或拓展解决)，302后浏览器会有个调用链路分析，装外部播放器脚本或者使用对应平台客户端都可以规避115的这个问题
