### ISSUE TITLE
nginx反代的8095端口的emby上手动修改封面时会无限转圈，但是默认端口进去可以正常修改

### ISSUE THREAD

**Issue by zoooo0** [bpking1/embyExternalUrl#11]

**Comment by bpking1** [comment]
参考 #23   修改emby.conf 文件

**Comment by clggwater** [comment]
> 参考 #23 修改emby.conf 文件

同emby，请问该如何修改？总会有几个电视剧或者电影，用8095端口丢失封面图，是否可以修正这个bug呢

如果手动查找封面图，8095端口没法修改图片，转圈。
