### ISSUE TITLE
NAS文件允许转码，云盘直链拦截转码选项

### ISSUE THREAD

**Issue by envyafish** [bpking1/embyExternalUrl#115]
如题。如何配置constant.js 可以达到这个效果。
NAS文件在emby客户端中可以选择分辨率，而直链的文件则不可以选择

**Comment by chen3861229** [comment]
需要更新下代码，这个选项刚添加
````
const routeRule = [
  ["transcode", "filePath", 0, "/mnt/sda3"], // 这里填NAS文件的路径开头
]
const transcodeConfig = {
  enable: true,
  redirectTransOptEnable: false, // 302的直链文件是否保留码率选择,不保留客户端将无法手动切换至转码
}
````

**Comment by envyafish** [comment]
已解决

**Comment by envyafish** [comment]
转码好像是成功了，但是服务端的控制台，或者客户端的媒体信息都无法展示转码信息。但是肉眼可见的是 画质降了

**Comment by chen3861229** [comment]
嗯，画质有变化就是走了转码了，因为分离转码这个实现方式原因，所以客户端看到的信息可能不是很准确，新代码已经强制传递了转码标识到目标服务上，目标服务上目前看到的是正确的信息，但是也没有转码进度，因为转码是api直接调用的，媒体服务内部自己没做监控，后期可能会对路由的结果对接下客户端设备的弹窗通知
