### ISSUE TITLE
emby2Alist

### ISSUE THREAD

**Issue by sq1018** [bpking1/embyExternalUrl#119]
已解决

**Comment by chen3861229** [comment]
好的，解决了就行，关于问到的docker前置条件，是因为本项目配置文件一直改动较大，所以没做容器封装，编排的是官方的nginx镜像，所以需要手动把脚本文件移动进去

**Comment by 277383761** [comment]
> 好的，解决了就行，关于问到的docker前置条件，是因为本项目配置文件一直改动较大，所以没做容器封装，编排的是官方的nginx镜像，所以需要手动把脚本文件移动进去

你这改动的不是一般的大,我上上次的配置拉下来配置好后,外网直链,内网不直链.后来更新了一次emby至4.9.0.16以后,内网也变成了直链,然后我以为也更新一下你的配置试试看,没想到就不能成功了.哈哈.又回退到了内外网都会直链的备份.

**Comment by chen3861229** [comment]
功能新增期间，这样很正常咯，还是建议如果用着稳定的话，升级版本还是新建一个容器比较保险

**Comment by 277383761** [comment]
> 功能新增期间，这样很正常咯，还是建议如果用着稳定的话，升级版本还是新建一个容器比较保险

哈哈,emby升到4.9以后,元数据就不再兼容往期版本了,我是回不去的了.
