### ISSUE TITLE
plex2alist配置疑问

### ISSUE THREAD

**Issue by arthurxj** [bpking1/embyExternalUrl#123]
用的是plex和云服务器，没找到针对plex的说明文件，配置的时候下面这段没搞懂，如果可以请帮忙解答一下，非常感谢

> ### docker部署的任选以下一种
> xxx为示例目录名,请根据自身情况修改
> 
> 前置条件1: 需要手动创建目录
> ````
> /xxx/nginx-emby/log
> /xxx/nginx-emby/embyCache
> ````
> 前置条件2: 需要手动移动项目配置文件
> ````
> 将本项目xxx2Alist/nginx/下所有文件移动到/xxx/nginx-emby/config/下面
> ````

我的文件放在目录：/root/plex2Alist/
前置条件1：是否创建/root/nginx-plex/log/、/root/nginx-plex/plexCache/ 这两个目录
前置条件2：是否将目录/root/plex2Alist/下的nginx目录移至/root/nginx-plex/下，并改名为config

**Comment by arthurxj** [comment]
另一个问题是，挂载视频文件在alist根目录的“影视”文件夹下，对应cd2挂载本地目录为“data/影视”，即mountPath：/data/影视，drivePath：/影视，但是没有找到drivePath设置，请解惑，谢谢

**Comment by chen3861229** [comment]
不好意思，因为plex反代和emby一样，所以就省略了些说明，不需要这个目录/root/nginx-plex/plexCache/，plex没加缓存
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/025e72ba-538c-4712-b8ca-bd5b1323fce4)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/5c71e637-57f5-42c7-b03a-352e7501b3ab)

**Comment by chen3861229** [comment]
2.mountPath是针对挂载工具的路径前缀，应该填mountPath：/data，这样就会把媒体服务中路径中的/data截取去掉，用/影视/xxx去alist进行查询了

**Comment by arthurxj** [comment]
谢谢，解答，但是还是没有尝试成功，日志显示：
nginx: [emerg] cannot load certificate "/etc/nginx/conf.d/cert/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/nginx/conf.d/cert/fullchain.pem, r) error:10000080:BIO routines::no such file)

**Comment by arthurxj** [comment]
ngnix-plex 和ngnix-emby可以共存吗，生成一个容易就会自动删除另一个

**Comment by arthurxj** [comment]
emby文件结构如下:
/root/emby2Alist/docker
   				   ├── docker-compose.yml
   				   ├── nginx-emby.syno.json
   				   └───nginx-emby
   				               ├── nginx.conf		       
   				               ├── log
                                               │         └── /
   				               ├── embyCache
                                               │         └── /
   				               └── conf.d
                                                           ├── constant.js
   				                           ├── emby.js	   
   				                           ├── emby-live.js
   				                           ├── emby-transcode.js
   				                           ├── emby.conf
   				                           ├── proxy.conf
                                                           ├── api
                                                           │        ├── emby-api.js
                                                           │        └── alist-api.js
                                                           └── common
                                                                      ├── events.js
                                                                      ├── periodics.js
                                                                      └── util.js

plex文件结构如下:
/root/plex2Alist/docker
                           ├── docker-compose.yml
   	          	   ├── nginx-plex.syno.json
                           └───nginx-plex
                                               ├── nginx.conf		       
   				               ├── log
   	                                       │        └── /
   				               └── conf.d
                                                             ├── constant.js
                                                             ├── plex.js	                                        
                                                             ├── plex.conf
                                                             ├── proxy.conf             
                                                             ├── api
                                                             │         └── alist-api.js
                                                             └── common
                                                                            ├── events.js
                                                                            ├── periodics.js
                                                                            └── util.js

**Comment by arthurxj** [comment]
emby文件结构如下:
/root/emby2Alist/docker
   				   ├── docker-compose.yml
                   ├── nginx-emby.syno.json
   				   └───nginx-emby
   		                       ├── nginx.conf		       
   				               ├── log
   	                           │    └── /
   				               ├── embyCache
   	                           │    └── /
   				               └── conf.d
                                       ├── constant.js
   				                       ├── emby.js	   
   				                       ├── emby-live.js
   				                       ├── emby-transcode.js
   				                       ├── emby.conf
   				                       ├── proxy.conf
                                       ├── api
                                       │     ├── emby-api.js
                                       │     └── alist-api.js
                                       └── common
                                             ├── events.js
                                             ├── periodics.js
                                             └── util.js

plex文件结构如下:
/root/plex2Alist/docker
   				   ├── docker-compose.yml
   	          	   ├── nginx-plex.syno.json
   				   └───nginx-plex
   		                       ├── nginx.conf		       
   				               ├── log
   	                           │    └── /
   				               └── conf.d
                                       ├── constant.js
   				                       ├── plex.js	                                        
   				                       ├── plex.conf
   				                       ├── proxy.conf             
                                       ├── api
                                       │     └── alist-api.js
                                       └── common
                                             ├── events.js
                                             ├── periodics.js
                                             └── util.js

**Comment by arthurxj** [comment]
![image](https://github.com/bpking1/embyExternalUrl/assets/165980162/ad2ee3c9-3571-41ca-b992-0484cf44f206)

**Comment by arthurxj** [comment]
emby可以正常直链，非常成功，plex还没安装好，请帮忙看看，plex比emby刮削好几个档次

**Comment by chen3861229** [comment]
可以共存的，路径结构没问题，日志中是缺少SSL证书文件，plex在某些客户端上强制https，例如ios官方客户端，所以默认了https的配置，如果有域名和证书的话，把自己的证书放在配置文件中的路径位置，如果没有的话把https相关的配置都注释掉就行了

**Comment by arthurxj** [comment]
搞不定，感觉设置都到位了还是不行

**Comment by arthurxj** [comment]
nginx-plex日志显示，32410端口与plex默认的端口冲突，改成别的端口日志正常，但是仍然不能直链，请问你们是怎么能够看到plex读取的是哪个地址呢
> /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
> /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
> 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
> /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
> /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
> /docker-entrypoint.sh: Configuration complete; ready for start up
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] bind() to 0.0.0.0:32410 failed (98: Address already in use)
> nginx: [emerg] still could not bind()

**Comment by arthurxj** [comment]
设置总算搞成了，有两处设置端口是要修改的，我这里暂时修改为8095，然后用8095端口访问即直链（32400应该是正常访问）
![image](https://github.com/bpking1/embyExternalUrl/assets/165980162/a93caf64-3e7a-41f6-8fb9-f24de67aeb9f)

**Comment by arthurxj** [comment]
![image](https://github.com/bpking1/embyExternalUrl/assets/165980162/7533c92e-3399-4e37-82dd-c951151f5e96)

**Comment by chen3861229** [comment]
>32410端口与plex默认的端口冲突
多谢提供反馈，能解决了就好，之后我加一下plex的配置说明吧

**Comment by arthurxj** [comment]
> >32410端口与plex默认的端口冲突
> 
> 多谢提供反馈，能解决了就好，之后我加一下plex的配置说明吧

非常感谢你的回复和辛苦创作。
如果写配置说明，我记得还有一个小bug，好像是运行docker_compose之后会自动生成一个ngnix.conf的文件夹，需要手动删除后再复制同名配置文件过去，否则无法覆盖。
我的安装方法比较笨，先运行一遍docker_compose，再复制文件就位修改，重启容器看日志没有提示缺文件，再删除容器重新生成一遍。
还有一个小问题就是我这边没法做到emby-ngnix与plex-ngnix两个容器共存，创建其中一个会删除另外一个，考虑的emby的高内存占有率和渣刮削就没研究把emby删掉了。

**Comment by chen3861229** [comment]
1.不好意思了，之前改漏掉了映射路径，动手能力很强，这样暂时处理是正确的
https://github.com/bpking1/embyExternalUrl/issues/127

2.共存是把两个 services 块复制到一个compose文件中了吗？service 名称不一样，和挂载的路径不一样，就不会相互覆盖冲突了

**Comment by whistle003** [comment]
大佬，请问证书配置具体应该怎么操作呢，我下载腾讯云的证书，配置了不生效，https访问打不开呢？

**Comment by chen3861229** [comment]
1.把 plex.conf 中 https 的注释打开
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/059bb6cd-ddf8-4ec7-bd60-c66e0f91046b)

2.然后确保证书的路径能对上就行了
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/64de815b-f523-4bad-9ac9-ad48d07d7acd)
