### ISSUE TITLE
docker日志提示default.conf文件不存在

### ISSUE THREAD

**Issue by czpkaka** [bpking1/embyExternalUrl#127]
nginx-emby用docker运行后，访问不了8091端口，查看日志提示default.conf文件不存在。这个文件是建docker时生成的还是要从作者仓库下载？仓库里好像也没有
![9538c9ffbca47af5159d3d0b3d112d7](https://github.com/bpking1/embyExternalUrl/assets/155758558/66698da3-f624-42b0-ad68-150ddebb4a66)

https://invites.fun/assets/files/2024-04-29/1714408791-555537-e0a3e14f20c692351753790a143bc76.png
https://invites.fun/assets/files/2024-04-30/1714439511-979435-image.png

**Comment by chen3861229** [comment]
不好意思，compose中文件路径之前改漏掉了，导致没有映射上nginx.conf所以默认找default.conf这个不存在的文件去了，需要改下映射路径或者暂时手动把文件复制进去了
1ed385e455a71ca4437f0a048dfb36a5e445d510

**Comment by czpkaka** [comment]
> 不好意思，compose中文件路径之前改漏掉了，导致没有映射上nginx.conf所以默认找default.conf这个不存在的文件去了，需要改下映射路径或者暂时手动把文件复制进去了 [1ed385e](https://github.com/bpking1/embyExternalUrl/commit/1ed385e455a71ca4437f0a048dfb36a5e445d510)
大佬，我还是不理解。nginx.conf我有映射呀，我要怎么修改呢。手动复制文件又要去哪里找文件呢，我网上复制了几个都不行，提示打包的版本不对

**Comment by chen3861229** [comment]
我是群晖手动部署的，可以参考下文件路径
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/fb6d66c2-de02-4e9e-8050-41412d9c079a)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/7d176e88-2199-4345-a3af-2a1f10c7063a)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/4a2e2d7c-e3cf-4656-a1f6-c2a705326ce3)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/47962dc5-a71e-452a-9c96-1cef3f099d6e)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/fd239cec-a353-47c4-8049-3afe4bd7ccaa)

**Comment by czpkaka** [comment]
可我就是用compose了，文件路径也没错呀，愁死我了
![image](https://github.com/bpking1/embyExternalUrl/assets/155758558/43201074-5818-4e54-99ab-1165e9eda310)
![image](https://github.com/bpking1/embyExternalUrl/assets/155758558/24ec7e98-b272-4900-9260-30f3607d50f1)
![image](https://github.com/bpking1/embyExternalUrl/assets/155758558/0e7d2709-99ce-436e-bff9-d717f0dd9e7e)
![image](https://github.com/bpking1/embyExternalUrl/assets/155758558/794dd76f-ab39-4ae9-b522-12de555c30ba)

**Comment by chen3861229** [comment]
实在不行，把emby.conf改名成default.conf吧，看下能不能启动

**Comment by czpkaka** [comment]
我改了，我麻了
![image](https://github.com/bpking1/embyExternalUrl/assets/155758558/e427ebe5-b235-44fb-b491-2d09ad4ef8ff)

**Comment by chen3861229** [comment]
试下删除这个容器重新 compose 部署一下呢，如果还是不行，我感觉还是手动部署下比较简单，可以参考下
https://github.com/bpking1/embyExternalUrl/issues/123

**Comment by czpkaka** [comment]
找人拷贝了一份default文件后可以直链了，不过时灵时不灵的，还有时候要加载几十秒才能播放。不知道是不是哪里配置错了

**Comment by chen3861229** [comment]
1.时灵时不灵这个可能和Web浏览器有关，换用对应平台客户端可能会好一些
2.一般来说不会这么长时间，nginx和alist在同一局域网可能会改善一些
