### ISSUE TITLE
请教如何能添加kodi的支持呢？

### ISSUE THREAD

**Issue by raylapse** [bpking1/embyExternalUrl#129]
安卓TV端，并实现真正的direct play，比如iso不转stream.mkv

**Comment by raylapse** [comment]
另外docker运行后，我在网页端下部影视数据库链接那里可以看到是成功了
但是emby win或者emby android tv都看不到这个，是哪里还不对？

**Comment by chen3861229** [comment]
> 安卓TV端，并实现真正的direct play，比如iso不转stream.mkv

这个默认的文件名称不重要的，emby和jellyfin都是通过url的路径层级匹配走下载的，如果是后缀名导致播放器媒体类型判断失败，之后我复现优化一下

**Comment by chen3861229** [comment]
外置链接这个，需要用 nginx 反代的端口才能看到修改后的内容的，然后支持情况我测试了下，安卓老 TV 版不支持的，因为原本就没有显示外置数据库的链接，其他官方客户端都是支持的，然后 TV 需要注意，点击外置播放器按钮是跳转 http/https 的，这个和系统的 web view 实现方式有关，电视都是没有浏览器的，我也不太清楚 tv 内置的谷歌 web view 支持情况，所以大概率电视客户端不支持这个

**Comment by raylapse** [comment]
我这两天看了下，可能我的盒子和tv端版本也有点问题。
现在的情况是tv端开启调用三方播放器后，有个弹窗出来，能正常看到kodi了，并且如果是iso的话服务端关闭转码，emby返回的是original.iso，kodi可以正常播放了。
所以只剩下bdmv了，bdmv貌似从机制上讲，调用第三方就是不现实的吧，多文件？

**Comment by raylapse** [comment]
谢谢大佬解答，赞
