### ISSUE TITLE
要是能让115直链也能emby网页就好了

### ISSUE THREAD

**Issue by chaomarks** [bpking1/embyExternalUrl#130]
alist能网页，为啥emby不可以呢

**Comment by chen3861229** [comment]
这个是实现原理不同，没办法，alist的网页前端是自己的，可以支持跨域链接给播放器组件，而emby和jellyfin这边各平台客户端比较复杂，不是通用的一套，目前只能装浏览器拓展改响应头支持跨域或者用对应平台客户端了

**Comment by LunaticXJ** [comment]
大佬，如果emby网页端不能播放115直链，那是否可以支持配置成emby网页端走本地路径播放呢，不知道怎么配置

**Comment by chen3861229** [comment]
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#6115-%E5%86%85%E5%AE%B9%E6%97%A0%E6%B3%95-web-%E7%AB%AF%E6%92%AD%E6%94%BE

**Comment by LunaticXJ** [comment]
你好，按FAQ修改了配置文件还是不行，配置文件和日志如下，麻烦帮忙看下哈
[constant.js.txt](https://github.com/bpking1/embyExternalUrl/files/15500089/constant.js.txt)
[MediaLinker.log](https://github.com/bpking1/embyExternalUrl/files/15500091/MediaLinker.log)
