### ISSUE TITLE
救救救救，整好几天了没整明白呜呜呜/emby/System/Info, the NJS VM is destroyed ===

### ISSUE THREAD

**Issue by yizhiakuya** [bpking1/embyExternalUrl#132]
`2024/05/04 19:12:54 [warn] 20#20: *25 js: default modify direct play supports all true
2024/05/04 19:12:54 [warn] 20#20: *25 js: modify direct play info
2024/05/04 19:12:54 [warn] 20#20: *25 js: 86ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"2868a15be2c058e0e6650334beed8897","Path":"/media/CloudDrive/WebDAV/onecloud/动画/冰海战记 (2019)/Season 1/冰海战记 - S01E01 - 这里以外的另一个地方.mkv","Type":"Default","Container":"mkv","Size":1966121818,"Name":"冰海战记 - S01E01 - 这里以外的另一个地方","IsRemote":false,"RunTimeTicks":17067090000,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[{"Codec":"hevc","ColorSpace":"bt709","TimeBase":"1/1000","VideoRange":"SDR","DisplayTitle":"1080p HEVC","IsInterlaced":false,"BitRate":9215967,"BitDepth":10,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"Main 10","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","PixelFormat":"yuv420p10le","Level":123,"IsAnamorphic":false,"AttachmentSize":0},{"Codec":"flac","Language":"jpn","TimeBase":"1/1000","DisplayTitle":"Japanese FLAC stereo (Default)","DisplayLanguage":"Japanese","IsInterlaced":false,"ChannelLayout":"stereo","BitDepth":24,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","AttachmentSize":0},{"Codec":"aac","Language":"jpn","TimeBase":"1/1000","DisplayTitle":"Japanese AAC stereo","DisplayLanguage":"Japanese","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":192000,"Channels":2,"SampleRate":48000,"IsDefault":false,"IsForced":false,"Profile":"LC","Type":"Audio","Index":2,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","AttachmentSize":0},{"Codec":"ass","Language":"srd","DisplayTitle":"
2024/05/04 19:12:54 [warn] 20#20: *25 js: === /emby/Items/64/PlaybackInfo, the NJS VM is destroyed ===
2024/05/04 19:12:54 [warn] 20#20: *21 js: redirect2Pan, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
2024/05/04 19:12:54 [warn] 20#20: *21 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/05/04 19:12:54 [warn] 20#20: *21 js: mount emby file path: /media/CloudDrive/WebDAV/onecloud/动画/冰海战记 (2019)/Season 1/冰海战记 - S01E01 - 这里以外的另一个地方.mkv
2024/05/04 19:12:54 [warn] 20#20: *21 js: hit proxy, not xxxMountPath first: ["/mnt"]
2024/05/04 19:12:54 [warn] 20#20: *21 js: use original link
2024/05/04 19:12:54 [warn] 20#20: *21 js: routeL1Dict add: [2868a15be2c058e0e6650334beed8897] : [@root]
2024/05/04 19:12:54 [warn] 20#20: *21 js: === /emby/videos/64/冰海战记 - S01E01 - 这里以外的另一个地方.mkv, the NJS VM is destroyed ===
`

**Comment by chen3861229** [comment]
>the NJS VM is destroyed ===

这个只是做日志内容分割的，是正常情况
主要是需要看下，这个的配置
````
// rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule
// 如果没有挂载,全部使用strm文件,此项填[""],必须要是数组
const embyMountPath = ["/mnt"];
````

**Comment by yizhiakuya** [comment]
虽然看不懂您的代码，不过我自己生成了alist的strm地址，然后正常挂载emby正常播放，再用您的nginx反代一下就可以了，请问这个js的逻辑是不是生成strm文件到网盘视频文件的同目录下，所以需要填写webdav挂载的本地路径，我的路径是
`/usr/local/clouddrive2/cloudnas/CloudDrive/WebDAV`
然后下一层就是alicoud和onecloud的网盘路径，但是貌似一直没有生成strm文件，可以播放但是一直都不是获取的直链，我通过手动复制alist的直链链接然后挂载到emby再用您的反代就可以了

**Comment by chen3861229** [comment]
xxx2Alist 只是用来劫持播放请求到网盘文件上的，虽然支持 strm 的直链播放，不过生成 strm 文件需要另外的工具，隔壁有很多,
如果不需要 strm 特性，可以不用 strm 的，根据路径截取和映射可以直接匹配到网盘文件
````
const embyMountPath = ["/usr/local/clouddrive2/cloudnas/CloudDrive/WebDAV"];
````

**Comment by yizhiakuya** [comment]
谢谢大佬，我这个路径填emby容器中的那个挂载路径就好了/media，然后现在遇到个非常奇怪的问题，就是同一部电影，在两个机器上，一个就直链，一个就代理，直链的是在家里的小linux上，在vps里边搭建的emby就无法直链那个电影，但是其他的大部分都没问题，也有一些电影有同样的问题
`53ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"bc07f1ea06bede79baf370914ffcb4f2","Path":"/media/onecloud/emby/电影/1917 (2019)/1917 (2019) 1080p AC3.mkv","Type":"Default","Container":"mkv","Size":11146859692,"Name":"1080p AC3","IsRemote":false,"RunTimeTicks":71381440000,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[{"Codec":"h264","Language":"eng","TimeBase":"1/1000","VideoRange":"SDR","DisplayTitle":"1080p H264","DisplayLanguage":"English","NalLengthSize":"4","IsInterlaced":false,"BitRate":12492726,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"Height":800,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":"Video","AspectRatio":"2.40:1","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","PixelFormat":"yuv420p","Level":41,"IsAnamorphic":false,"AttachmentSize":0},{"Codec":"ac3","Language":"eng","TimeBase":"1/1000","Title":"英语","DisplayTitle":"English AC3 5.1 (Default)","DisplayLanguage":"English","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":448000,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","AttachmentSize":0},{"Codec":"ass","Language":"chi","TimeBase":"1/1000","Title":"chs&eng","DisplayTitle":"Chinese Simplified (Default ASS)","DisplayLanguage":"Chinese Simplified","IsInterlaced":false,"IsDefault":true,"IsForced":false,"Type":"Subtitle","Index":2,"IsExternal":false,"DeliveryMethod":"External","DeliveryUrl":"/Videos/1191/bc07f1ea06bede79baf370914ffcb4f2/Subtitles/2/0/Stream.ass?api_key=5e3f79c1c11d4ff5b7827af8f1cccefc","IsExternalUrl":false,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Protocol":"Fil
2024/05/17 22:28:27 [warn] 20#20: *356 js: === /emby/Items/1191/PlaybackInfo, the NJS VM is destroyed ===
2024/05/17 22:28:27 [warn] 20#20: *356 js: redirect2Pan, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
2024/05/17 22:28:27 [warn] 20#20: *356 js: hit routeCache L1: https://xx5xl-my.sharepoint.com/personal/megumin_xx5xl_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=cf802550-d201-4c72-be15-7f4a6d34ca43&Translate=false&tempauth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfZGlzcGxheW5hbWUiOiJhbGlzdCIsImF1ZCI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC94eDV4bC1teS5zaGFyZXBvaW50LmNvbUA5OGQ1ZTQwYi01ZmVkLTQwMDMtOWFiMy0xN2UyYThmNjk4ZDIiLCJjaWQiOiJqN3FzdEE2V29FK201UFU1M04zWUZnPT0iLCJlbmRwb2ludHVybCI6IjR5Y2JGWjlDazdwTVVsanVheEtLdnpXSWtRL051Q3JsNm9halhZQmtIT009IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTgiLCJleHAiOiIxNzE1OTg4MDUzIiwiaXBhZGRyIjoiMjAuMTkwLjE0NC4xNzAiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5hbWVpZCI6IjI1ZGJhMzNlLWNkYTItNGUwZS1hNjkzLTAyMWU2NjE4ZGFjMEA5OGQ1ZTQwYi01ZmVkLTQwMDMtOWFiMy0xN2UyYThmNjk4ZDIiLCJuYmYiOiIxNzE1OTg0NDUzIiwicm9sZXMiOiJhbGxmaWxlcy53cml0ZSBhbGxmaWxlcy5yZWFkIiwic2l0ZWlkIjoiWldNd05EbGhaVE10TVRGbU9DMDBOakUyTFRrME9Ua3ROalEwTnpWalptWXpORGc0IiwidHQiOiIxIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiJ9.Oj6brZuBD-fgkuqVwrQ2KMbB_B0HZwqEzC64_B6OYDE&ApiVersion=2.0
2024/05/17 22:28:27 [warn] 20#20: *356 js: redirect to: https://xx5xl-my.sharepoint.com/personal/megumin_xx5xl_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=cf802550-d201-4c72-be15-7f4a6d34ca43&Translate=false&tempauth=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcHBfZGlzcGxheW5hbWUiOiJhbGlzdCIsImF1ZCI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC94eDV4bC1teS5zaGFyZXBvaW50LmNvbUA5OGQ1ZTQwYi01ZmVkLTQwMDMtOWFiMy0xN2UyYThmNjk4ZDIiLCJjaWQiOiJqN3FzdEE2V29FK201UFU1M04zWUZnPT0iLCJlbmRwb2ludHVybCI6IjR5Y2JGWjlDazdwTVVsanVheEtLdnpXSWtRL051Q3JsNm9halhZQmtIT009IiwiZW5kcG9pbnR1cmxMZW5ndGgiOiIxNTgiLCJleHAiOiIxNzE1OTg4MDUzIiwiaXBhZGRyIjoiMjAuMTkwLjE0NC4xNzAiLCJpc2xvb3BiYWNrIjoiVHJ1ZSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5hbWVpZCI6IjI1ZGJhMzNlLWNkYTItNGUwZS1hNjkzLTAyMWU2NjE4ZGFjMEA5OGQ1ZTQwYi01ZmVkLTQwMDMtOWFiMy0xN2UyYThmNjk4ZDIiLCJuYmYiOiIxNzE1OTg0NDUzIiwicm9sZXMiOiJhbGxmaWxlcy53cml0ZSBhbGxmaWxlcy5yZWFkIiwic2l0ZWlkIjoiWldNd05EbGhaVE10TVRGbU9DMDBOakUyTFRrME9Ua3ROalEwTnpWalptWXpORGc0IiwidHQiOiIxIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiJ9.Oj6brZuBD-fgkuqVwrQ2KMbB_B0HZwqEzC64_B6OYDE&ApiVersion=2.0`

![image](https://github.com/bpking1/embyExternalUrl/assets/81675725/dcea79e4-716d-4857-9db8-774d09520754)

**Comment by yizhiakuya** [comment]
啊，好想知道了，4.8版本就没问题，4.7版本就会出现这种情况，但是4.8版本用弹幕的插件用不了，唉

**Comment by chen3861229** [comment]
1.应该和 emby 版本没太大关系，是不是两个 nginx 的配置不太一样，特别是路由规则这块，这条是让内网设备优先走代理的，新版是保持默认注释的情况
````
const routeRule = [
   // docker 注意必须为 host 模式,不然此变量全部为内网ip,判断无效,nginx 内置变量不带$,客户端地址($remote_addr)
  // ["r.variables.remote_addr", 0, strHead.lanIp],
];
````
2.弹幕插件那个不知道是不是用的同一个，4.8 + 的问题其实 pr 里有人修复了，我这边 fork 的一个 develop 分支也是稍微整合了一下,如果不是同个插件，可以忽略这段话
https://github.com/chen3861229/dd-danmaku/tree/develop
