### ISSUE TITLE
直链的脚本越来越复杂了.建议精简下

### ISSUE THREAD

**Issue by 277383761** [bpking1/embyExternalUrl#140]
或者把须要配置的文件放在外头,而且里头备注一下哪些要改的部分显示在最上头.
其它几乎不用改动的配置文件就扔到某个文件夹下得了.
越改头越大了,哈哈哈.深怕哪个文件没改或漏改

**Comment by chen3861229** [comment]
多谢建议了，其实直链正常只需要改必填项那 7 个参数和 http/s 的 conf 就行了，
conf 的已经做了拆分了，constant.js 的话暂时应该不会有太大的变化了，如果之后参数增多了，我再拆分下吧，目前参数不是太多，有时候参照查看对比方便点儿

**Comment by 277383761** [comment]
> 多谢建议了，其实直链正常只需要改必填项那 7 个参数和 http/s 的 conf 就行了， conf 的已经做了拆分了，constant.js 的话暂时应该不会有太大的变化了，如果之后参数增多了，我再拆分下吧，目前参数不是太多，有时候参照查看对比方便点儿

哈哈,如果能出个webUI就更方便了.必填项显示出来,其它全部隐藏在UI后

**Comment by chen3861229** [comment]
UI 的话工作量有些大了，其实主要是因为我是后端开发，我看有人用图形化的 nginx 成功的，可以尝试下这个 Nginx Proxy Manager
