### ISSUE TITLE
能支持Alist网页版么？

### ISSUE THREAD

**Issue by jxyun99** [bpking1/embyExternalUrl#141]
路由上部署的Alist网盘，但是alist自带的网页播放器，各种功能不足，不能设置字幕，不能设置音频等等，以前在nas上部署的emby挺好用的，可以调用外部播放器，但现在不用nas了，所以想问一下这个有办法改成支持alist网页版么（alist自带的那几个播放器不是很好用，没emby版的全）？

**Comment by chen3861229** [comment]
这个需要花些时间研究下了，主要还是不是专业前端

**Comment by chen3861229** [comment]
做了一个简单支持
https://greasyfork.org/zh-CN/scripts/494829

**Comment by jxyun99** [comment]
> 做了一个简单支持 https://greasyfork.org/zh-CN/scripts/494829

PC上测试了一下，PC上只安装了potplayer和恒星播放器，都能调起播放器，但是两者都无法播放，对比了一下Alist自带一下，发现potplayer按钮的url链接都一样啊，但是自带的能播放，你的脚本却无法播放。不明所以

**Comment by chen3861229** [comment]
编码问题，应该已经修复了
95766aae0d513980bd7965bf0e4446f9491ada36

**Comment by jxyun99** [comment]
> 编码问题，应该已经修复了 [95766aa](https://github.com/bpking1/embyExternalUrl/commit/95766aae0d513980bd7965bf0e4446f9491ada36)

测试了，ok，强！！！

**Comment by jxyun99** [comment]
最后再冒昧的问一下，这个js脚本可以直接集成到alist中么？我看黑裙中的emby中是可以直接集成embyExternalUrl JS脚本的，
测试在alist的全局-自定义头部设置中插入js引用<script src="http://192.168.31.241/alistWebLaunchExternalPlayer.js"></script>，脚本没起效果

**Comment by chen3861229** [comment]
已经修复
1d69df2833713ce18e6000d4d622a9639f5ad456

alist 设置 -> 全局 -> 自定义头部, 仓库二选一，也可用你本地的加载快很多
````
<script src="https://fastly.jsdelivr.net/gh/chen3861229/embyExternalUrl@main/embyWebAddExternalUrl/alistWebLaunchExternalPlayer.js"></script>
<!-- <script src="https://fastly.jsdelivr.net/gh/bpking1/embyExternalUrl@main/embyWebAddExternalUrl/alistWebLaunchExternalPlayer.js"></script> -->
````

**Comment by chen3861229** [comment]
217 行那里，默认的是免费版的，需要自己注释下，打开下边的 pro 版包名的，之后看想办法优化下吧

**Comment by jxyun99** [comment]
> 217 行那里，默认的是免费版的，需要自己注释下，打开下边的 pro 版包名的，之后看想办法优化下吧

应该不是这个原因，因为我安装装的就是免费版mxPlayer，自带的能调用mxPlayer，我看了一下代码，async function getMXUrl(mediaInfo) {} 这个最前面是不是多了async ？？

**Comment by chen3861229** [comment]
大意了。。可能是这个原因
