### ISSUE TITLE
使用最近更新的版本后不缓存图片和字幕

### ISSUE THREAD

**Issue by fzlzl** [bpking1/embyExternalUrl#142]
使用最近更新的版本后不缓存图片和字幕，embyCache文件夹里images和subtitles一直为空，几个月前的版本能成功缓存

**Comment by chen3861229** [comment]
已做修复
5a0a5bad7fa0800a08058cf87f20dd602056ad4b

**Comment by fzlzl** [comment]
感谢大佬
