### ISSUE TITLE
README文档有段话不太理解，不知道在这里提问合不合适

### ISSUE THREAD

**Issue by Oliv1a** [bpking1/embyExternalUrl#144]
看到README里有这么一段话（如下），其中提到“为0是没限制,缺点是整库扫持续时间会达到一周,但是不会触发熔断”，如果这个限制值设为30，那就是每30秒才请求一次是吧？那理论上该值越大越安全是吧，那设为0该怎么理解呢？没有限制后反而不会触发熔断吗？非常感谢！

3.alist一定要开启115网盘驱动的限制速率,它的限制比较严格,一扫库必定熔断,默认为2【限制所有 api 请求速率(1r/[limit_rate]s)】, 意味着2秒内只处理1个请求,个人设置为1也是没问题的,此为最小值,为0是没限制,缺点是整库扫持续时间会达到一周,但是不会触发熔断,比较安全, 阿里网盘的熔断机制相对宽松很多,除非一次性文件太多,但是截止当前,alist并没有当前网盘的限流参数

**Comment by chen3861229** [comment]
1.确实这里语序有点问题，"为0是没限制"，单纯只是说明下 0 的含义，正确语序是前面说的设置为 1 ，后边的没错，是代表单位时间秒的间隔，这个时间需要根据自己对请求的延迟容忍情况和网盘安全评估了
