### ISSUE TITLE
无法获取正确的播放链接

### ISSUE THREAD

**Issue by felix-klk** [bpking1/embyExternalUrl#15]
//author: @bpking  https://github.com/bpking1/embyExternalUrl
let serverAddr = 'https://x.x.top:30443';        //外网emby地址
const tags = ['BluRay', 'REMUX', 'WEB-DL'];                 //添加视频tag
const groups = ['CMCT', 'WIKI', 'Z0N3', 'EbP', 'PTer', 'EPSILON', 'FRDS', 'SMURF'];   //添加制作组

let api_key = '';
let domain = '';
let oriData = '';
const redirectKey = 'redirect2external'; 请问大佬这里是否需要填写 apikey跟下面的选项

现在无法获取正确的播放链接 使用油猴脚本就可以获取到正确的链接

**Comment by bulesky89857** [comment]
一样的问题 ,获取的链接没有端口号,不知道怎么设置
