### ISSUE TITLE
大佬请教plex如何配置https证书

### ISSUE THREAD

**Issue by whistle003** [bpking1/embyExternalUrl#154]
目前我是腾讯云申请的免费证书，下载nginx证书包获取到四个文件，我把其中的pem和key后缀的证书文件路径配置在https.conf文件中，打不开https://域名+端口
ssl_certificate      /etc/nginx/conf.d/cert/fullchain.pem;  ## Location of your public PEM file.
ssl_certificate_key  /etc/nginx/conf.d/cert/privkey.key;  ## Location of your private PEM file.
![image](https://github.com/bpking1/embyExternalUrl/assets/64147479/126c1019-b309-4ae0-b419-492ad1f72fa6)

![image](https://github.com/bpking1/embyExternalUrl/assets/64147479/8a76c004-6bfc-41b5-9a27-9f743feca9c5)

请问可能是什么原因吗？

**Comment by chen3861229** [comment]
1.把 plex.conf 中 https 的注释打开
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/059bb6cd-ddf8-4ec7-bd60-c66e0f91046b)

2.然后确保证书的路径能对上就行了
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/64de815b-f523-4bad-9ac9-ad48d07d7acd)

**Comment by whistle003** [comment]
> 1.把 plex.conf 中 https 的注释打开 ![image](https://private-user-images.githubusercontent.com/42368856/330399137-059bb6cd-ddf8-4ec7-bd60-c66e0f91046b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTg4NTgsIm5iZiI6MTcxNTY5ODU1OCwicGF0aCI6Ii80MjM2ODg1Ni8zMzAzOTkxMzctMDU5YmI2Y2QtZGRmOC00ZWM3LWJkNjAtYzY2ZTBmOTEwNDZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE0NTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMDg4NGZjYWMzNjZkNDY5ZTZhZWIxZWZlNWJlZjk5YTE4N2IxYWUxMTc3MWYzOWVlOTVjZTU3ZjM4NDg5NzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yj0kE5Tq8cYjHUHkWg0ca0XuJQzt7uEVH1g5q714nak)
> 
> 2.然后确保证书的路径能对上就行了 ![image](https://private-user-images.githubusercontent.com/42368856/330399598-64de815b-f523-4bad-9ac9-ad48d07d7acd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2OTg4NTgsIm5iZiI6MTcxNTY5ODU1OCwicGF0aCI6Ii80MjM2ODg1Ni8zMzAzOTk1OTgtNjRkZTgxNWItZjUyMy00YmFkLTlhYzktYWQ0OGQwN2Q3YWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE0VDE0NTU1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTg4OGIwZGU4OTdmNzA1NDkyN2JmMjA1ZDUzMTc1MTI0N2UzOTU1MjBiODMxOWE4OWZlNmI2OTg0MzE0NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3qopeQCwfmUNobhC7OCt5mxjbew9xbjMTd0yGYIh5j8)
打开如上内容后，报错如下：
![image](https://github.com/bpking1/embyExternalUrl/assets/64147479/2fefde81-3cb9-442b-a29a-69f9dfa5c5d3)

**Comment by tnanstar** [comment]
![Snipaste_2024-05-14_23-20-44](https://github.com/bpking1/embyExternalUrl/assets/111693416/ed1a9747-f05a-47cf-a2ec-2d5650809d3f)
![Snipaste_2024-05-14_23-20-24](https://github.com/bpking1/embyExternalUrl/assets/111693416/dede7a98-b870-42c9-8a84-a3d325e52e3d)
![Snipaste_2024-05-14_23-20-06](https://github.com/bpking1/embyExternalUrl/assets/111693416/2b3828a5-d04e-406b-b869-b63906bb3802)
一的 页面打不开 显示服务器掉线 请问是否还要修改其他地方
