### ISSUE TITLE
不知现在是否兼容jellyfin。

### ISSUE THREAD

**Issue by Next-Page-Vi** [bpking1/embyExternalUrl#16]
我成功配置了反向代理，并且再8097端口打开了jellyfin的webui界面，但是没有看见外部播放按钮，但是我不确定此项目现在是否兼容jellyfin，很难进行进一步的故障排除。

**Comment by bpking1** [comment]
暂时不支持jellyfin

**Comment by 21tc-sea** [comment]
> 暂时不支持jellyfin

大佬，请问现在支持jellyfin了吗？我也是反代成功了，jellyfin没有第三方播放器的按钮

**Comment by ssyangchn** [comment]
+1希望作者大大支持下jellyfin

**Comment by chen3861229** [comment]
已做兼容
77d96a2dea8d7f6c3276cc32eae0b8ef67de0e21
