### ISSUE TITLE
直链能支持bdmv文件夹类型的原盘吗？

### ISSUE THREAD

**Issue by lw6644700** [bpking1/embyExternalUrl#164]
之前试了其它几个直链的教程都是单个文件的视频或者iso的原盘可以播放，到了文件夹的原盘就播放不了，这个插件也是一样吗？还是可以支持文件夹得原盘直链啊？

**Comment by chen3861229** [comment]
是一样的，多个文件没办法处理的，只能用原始服务播放了

**Comment by lw6644700** [comment]
以后有没有可能支持这种多文件的原盘文件夹直链呀？

> 是一样的，多个文件没办法处理的，只能用原始服务播放了

**Comment by chen3861229** [comment]
看了下，没办法支持的，emby 原本不支持 BDMV 的文件夹播放，官方提示内容就是转成 mkv 之类容器的格式再入库，如果是第三方播放器那就更没法兼容了
