### ISSUE TITLE
大佬请教能否设置软链接的直链

### ISSUE THREAD

**Issue by cyay10** [bpking1/embyExternalUrl#165]
视频文件.mp4 是通过 cd2创建的软链接。

/volume1/CloudNAS/CloudDrive2/115/A-电影/搏击俱乐部(1999).mp4  cd2中的115视频路径

创建软链接并刮削的目录为【也是emby读取的目录】
/volume2/disk/115-电影/电影/搏击俱乐部 (1999)/搏击俱乐部 (1999).mp4

设置
embyMountPath = ["/volume2/disk"];
alist挂载路径为 /115

日志出现

翻译成中文 2024/05/18 16:36:21 [warn] 22#22: *53 js: === /emby/Items/94017/PlaybackInfo, the NJS VM is destroyed ===
2024/05/18 16:36:21 [warn] 22#22: *55 js: redirect2Pan, UA: libmpv
2024/05/18 16:36:21 [warn] 22#22: *55 js: itemInfoUri: http://192.168.0.5:8096/Items?Ids=1b2c2bee19d35de7c90f43e4c6ec8eaf&Fields=Path,MediaSources&Limit=1&api_key=723f7a69e8d74736aec99d9ccf2af122
2024/05/18 16:36:22 [warn] 22#22: *55 js: 24ms, fetchEmbyFilePath async function cost
2024/05/18 16:36:22 [warn] 22#22: *55 js: notLocal: false
2024/05/18 16:36:22 [warn] 22#22: *55 js: mount emby file path: /volume2/disk/115-电影/电影/哥斯拉大战金刚2：帝国崛起 (2024)/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4
2024/05/18 16:36:22 [warn] 22#22: *55 js: embyPathMapping: [[0,0,"/volume2/disk",""]]
2024/05/18 16:36:22 [warn] 22#22: *55 js: strMapping replace: /volume2/disk => 
2024/05/18 16:36:22 [warn] 22#22: *55 js: mapped emby file path: /115-电影/电影/哥斯拉大战金刚2：帝国崛起 (2024)/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4
2024/05/18 16:36:22 [warn] 22#22: *55 js: 28ms, fetchAlistPathApi async function cost
2024/05/18 16:36:22 [warn] 22#22: *55 js: fetchAlistPathApi, UA: libmpv
2024/05/18 16:36:22 [warn] 22#22: *55 js: alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /115-电影/电影/哥斯拉大战金刚2：帝国崛起 (2024)/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4
2024/05/18 16:36:22 [warn] 22#22: *55 js: will req alist /api/fs/list to rerty
2024/05/18 16:36:22 [warn] 22#22: *55 js: try to fetch alist path from /115/115-电影/电影/哥斯拉大战金刚2：帝国崛起 (2024)/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4
2024/05/18 16:36:22 [error] 22#22: *55 js: fail to fetch alist resource: not found,fallback use original link
2024/05/18 16:36:22 [warn] 22#22: *55 js: use original link
2024/05/18 16:36:22 [warn] 22#22: *55 js: routeL1Dict add: [/emby/videos/94017/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4:1b2c2bee19d35de7c90f43e4c6ec8eaf] : [@root]
2024/05/18 16:36:22 [warn] 22#22: *55 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/2/00/0000000002 while reading upstream, client: 172.17.0.12, server: default, request: "GET /emby/videos/94017/stream/%E5%93%A5%E6%96%AF%E6%8B%89%E5%A4%A7%E6%88%98%E9%87%91%E5%88%9A2%EF%BC%9A%E5%B8%9D%E5%9B%BD%E5%B4%9B%E8%B5%B7%20(2024)%20-%202160p.mp4?UserId=cc1edabed16b4fa0b58a26da8658e30b&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=120000000&DirectPlayProtocols=File,Http,Rtp,Rtmp,Rtsp,Ftp&X-Emby-Client=Emby%20Theater&X-Emby-Device-Name=DESKTOP-FTHEMLU&X-Emby-Device-Id=DESKTOP-FTHEMLU&X-Emby-Client-Version=3.0.17-1.6&X-Emby-Token=723f7a69e8d74736aec99d9ccf2af122&reqformat=json&MediaSourceId=1b2c2bee19d35de7c90f43e4c6ec8eaf&PlaySessionId=be4bfd4d825a4f75a8a10a3eacd53bc8&Static=true HTTP/1.1", upstream: "http://192.168.0.5:8096/emby/videos/94017/%E5%93%A5%E6%96%AF%E6%8B%89%E5%A4%A7%E6%88%98%E9%87%91%E5%88%9A2%EF%BC%9A%E5%B8%9D%E5%9B%BD%E5%B4%9B%E8%B5%B7%20(2024)%20-%202160p.mp4?UserId=cc1edabed16b4fa0b58a26da8658e30b&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=120000000&DirectPlayProtocols=File,Http,Rtp,Rtmp,Rtsp,Ftp&X-Emby-Client=Emby%20Theater&X-Emby-Device-Name=DESKTOP-FTHEMLU&X-Emby-Device-Id=DESKTOP-FTHEMLU&X-Emby-Client-Version=3.0.17-1.6&X-Emby-Token=723f7a69e8d74736aec99d9ccf2af122&reqformat=json&MediaSourceId=1b2c2bee19d35de7c90f43e4c6ec8eaf&PlaySessionId=be4bfd4d825a4f75a8a10a3eacd53bc8&Static=true", host: "nginx.shanhe.ink"
2024/05/18 16:36:28 [warn] 22#22: *61 js: redirect2Pan, UA: libmpv
2024/05/18 16:36:28 [warn] 22#22: *61 js: hit routeCache L1: @root
2024/05/18 16:36:28 [warn] 22#22: *61 js: === /emby/videos/94017/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4, the NJS VM is destroyed ===
2024/05/18 16:36:28 [warn] 22#22: *55 js: === /emby/videos/94017/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4, the NJS VM is destroyed ===
2024/05/18 16:36:29 [warn] 21#21: *63 js: redirect2Pan, UA: libmpv
2024/05/18 16:36:29 [warn] 21#21: *63 js: hit routeCache L1: @root
2024/05/18 16:36:29 [warn] 21#21: *63 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/3/00/0000000003 while reading upstream, client: 172.17.0.12, server: default, request: "GET /emby/videos/94017/stream/%E5%93%A5%E6%96%AF%E6%8B%89%E5%A4%A7%E6%88%98%E9%87%91%E5%88%9A2%EF%BC%9A%E5%B8%9D%E5%9B%BD%E5%B4%9B%E8%B5%B7%20(2024)%20-%202160p.mp4?UserId=cc1edabed16b4fa0b58a26da8658e30b&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=120000000&DirectPlayProtocols=File,Http,Rtp,Rtmp,Rtsp,Ftp&X-Emby-Client=Emby%20Theater&X-Emby-Device-Name=DESKTOP-FTHEMLU&X-Emby-Device-Id=DESKTOP-FTHEMLU&X-Emby-Client-Version=3.0.17-1.6&X-Emby-Token=723f7a69e8d74736aec99d9ccf2af122&reqformat=json&MediaSourceId=1b2c2bee19d35de7c90f43e4c6ec8eaf&PlaySessionId=be4bfd4d825a4f75a8a10a3eacd53bc8&Static=true HTTP/1.1", upstream: "http://192.168.0.5:8096/emby/videos/94017/%E5%93%A5%E6%96%AF%E6%8B%89%E5%A4%A7%E6%88%98%E9%87%91%E5%88%9A2%EF%BC%9A%E5%B8%9D%E5%9B%BD%E5%B4%9B%E8%B5%B7%20(2024)%20-%202160p.mp4?UserId=cc1edabed16b4fa0b58a26da8658e30b&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=120000000&DirectPlayProtocols=File,Http,Rtp,Rtmp,Rtsp,Ftp&X-Emby-Client=Emby%20Theater&X-Emby-Device-Name=DESKTOP-FTHEMLU&X-Emby-Device-Id=DESKTOP-FTHEMLU&X-Emby-Client-Version=3.0.17-1.6&X-Emby-Token=723f7a69e8d74736aec99d9ccf2af122&reqformat=json&MediaSourceId=1b2c2bee19d35de7c90f43e4c6ec8eaf&PlaySessionId=be4bfd4d825a4f75a8a10a3eacd53bc8&Static=true", host: "nginx.shanhe.ink"
2024/05/18 16:38:10 [warn] 21#21: *63 js: === /emby/videos/94017/哥斯拉大战金刚2：帝国崛起 (2024) - 2160p.mp4, the NJS VM is destroyed ===

[access (2).log](https://github.com/bpking1/embyExternalUrl/files/15367198/access.2.log)
[error (2).log](https://github.com/bpking1/embyExternalUrl/files/15367199/error.2.log)

**Comment by chen3861229** [comment]
路径不太常规，经过太多层转换，替换错误了，可以用路径映射参数来解决，保证 emby => 替换为 alist 中相对应的路径就行了
````
const embyPathMapping = [
  [0, 0, "/volume2/disk/115-电影", "/115"],
]
````
不清楚你这个，"/A-电影", "/电影" ,是不是也是 CD2 和 alist 路径不同，如果不同，用下面的
````
const embyPathMapping = [
  [0, 0, "/volume2/disk/115-电影/电影", "/115/A-电影"],
]
````
两种都留空 embyMountPath  变量，但是得为空数组
````
embyMountPath = [""];
````
以上只是示例，你要是这样填也是可以的，embyMountPath 的优先级在 embyPathMapping 之前
````
embyMountPath = ["/volume2/disk"];
const embyPathMapping = [
  [0, 0, "/115-电影", "/115"],
]
````

**Comment by cyay10** [comment]
/volume1/CloudNAS/CloudDrive2/115/A-电影/浪客剑心最终章：追忆篇.mp4
这是我cd2中的视频路径，文件名叫 浪客剑心最终章：追忆篇.mp4

创建软链接到/volume2/disk/115-电影/电影【这是我本地的路径】

刮削整理之后  软链接文件名叫 
/volume2/disk/115-电影/电影/浪客剑心最终章：追忆篇 (2021)/浪客剑心最终章：追忆篇 (2021).mp4

请问大佬，重命名之后的软链接 和  cd2中的 也就是 115的文件名 是不同了。  这个是否影响。

**Comment by chen3861229** [comment]
会影响，这样去查 alist 会找不到对应的文件。。。因为不管软硬链接改了文件名，对于其他软件来说本质上已经是一个新的文件了，只是里边的内容是相同的

**Comment by cyay10** [comment]
我问了一下 gpt  

/volume2/disk/115-电影/电影/浪客剑心最终章：追忆篇 (2021)/浪客剑心最终章：追忆篇 (2021).mp4
这是我的软链接文件

增加一条指令 读取 软链接对应的 源文件
readlink /volume2/disk/115-电影/电影/浪客剑心最终章：追忆篇 (2021)/浪客剑心最终章：追忆篇 (2021).mp4

可以读取到/volume1/CloudNAS/CloudDrive2/115/A-电影/浪客剑心最终章：追忆篇.mp4

把读取到的源文件路径 替换进去  这样是否可行呢。

**Comment by cyay10** [comment]
但是 程序 貌似 没有这样的功能

**Comment by cyay10** [comment]
我刮削完毕之后 ，nfo  jpg这些数据 是本地的， 只有 视频文件是 在网盘中， 不会裂图

**Comment by chen3861229** [comment]
nginx 只是反代接口了，读取文件的权限还是在 emby 服务端那里的，其实最好的方式还是重命名网盘上的文件名，保持一致，也不用把元数据上传到网盘上，只是通过 emby 给的文件名去匹配 alist 上的文件而已，nginx 去做磁盘的 IO 操作还是比较别扭的

**Comment by cyay10** [comment]
完蛋 我这好几万的视频  也改不过来呀。。。

**Comment by chen3861229** [comment]
我这边的处理使用不是很优雅，你可以参考一下，我是 115 空间有多余的，所以存了两份文件，硬链接后的文件做了云同步，传到网盘上已经是单独的两份文件和大小了，也是直接入库的刮削后的，包括图片和 NFO 之类的，如果想优化可以做下边的，
然后用 alist 的元信息屏蔽掉 nfo 和 图片 和 字幕的返回，然后再用 alias 聚合本地的只有元信息和字幕的根文件夹，当然这样有些麻烦且emby的重新扫库，仅供参考

**Comment by cyay10** [comment]
好的 谢谢大佬 耐心解答

**Comment by chen3861229** [comment]
看了下 API 好像很简单，我只能尝试一下了，我这边测试只能用几个文件试，所以覆盖情况可能不足

**Comment by cyay10** [comment]
应该加一条   读取在播放的软链接的 源文件 路径 在替换一下可以  我是菜鸟 只能有思路  改不了 您的代码 哈哈哈

**Comment by chen3861229** [comment]
嗯，没事，因为细节估计比较多，这样 nginx 必须要具有对应文件夹的权限了，容器环境的自己映射且必须得有读取权限，而且为了不消耗大量的 IO 性能，到时候配置项里估计会限得很死，只有指定的路径才会去检查了，代码里再写死超过 1 Kb 的文件跳过读取

**Comment by chen3861229** [comment]
个人测试条件有限，只建了一个软链接测试貌似没啥问题，其余需要自行摸索一下了
13263d6561ffc594b464621981ffa495e9737350

**Comment by cyay10** [comment]
大佬牛逼

**Comment by cyay10** [comment]
我试试看

**Comment by cyay10** [comment]
> 个人测试条件有限，只建了一个软链接测试貌似没啥问题，其余需要自行摸索一下了 [13263d6](https://github.com/bpking1/embyExternalUrl/commit/13263d6561ffc594b464621981ffa495e9737350)

成功了  谢谢大佬
