### ISSUE TITLE
fileball客户端出现了无法播放的情况，而其他客户端和网页均正常

### ISSUE THREAD

**Issue by Putarku** [bpking1/embyExternalUrl#166]
观察日志发现fileball播放时，请求的视频流返回的是404
`2024/05/19 07:58:51 [warn] 28#28: *1 js: === /Items/780032/PlaybackInfo, the NJS VM is destroyed ===

192.168.31.237 - - [19/May/2024:07:58:51 +0000] "GET /Items/780032/stream.mkv?AutoOpenLiveStream=true&IsPlayback=true&MaxStreamingBitrate=42000000&StartTimeTicks=0&UserId=42834cb8b24c4d54a4079f586afbb61a&api_key=f0e74379b1a04aafa1d33423f48ce4ba&MediaSourceId=95cd2d7aa43e46ef7ebfe0e9d03df88e&PlaySessionId=93f022dda2624c1baf7894ecace7bbb3&Static=true HTTP/1.1" 404 54 "-" "libmpv" "-"`
[error.txt](https://github.com/bpking1/embyExternalUrl/files/15368657/error.txt)

**Comment by chen3861229** [comment]
尝试把 emby.js 第260 行的 
````
.replace("/emby/Items", "/videos")
````
改为这样，看下能行吗
````
// only fileball not hava /emby path
.replace(/^.*\/items/i, "/videos")
````
定位参考
````
...
source.DirectStreamUrl = util.addDefaultApiKey(
        r,
        util
          .generateUrl(r, "", r.uri, ["StartTimeTicks"])
          .replace("/emby/Items", "/videos")
          .replace("PlaybackInfo", streamPart)
      );
....
````

**Comment by Putarku** [comment]
尝试修改后已经没问题了
