### ISSUE TITLE
播放本地视频时，ass的外挂字幕不会被加载

### ISSUE THREAD

**Issue by Putarku** [bpking1/embyExternalUrl#170]
使用的设备同样是fileball和fileball的atv版本。在播放本地视频，并请求ass外挂字幕时出现了204的报错。

而如果是使用strm文件时，就可以正常加载strm旁边放着的ass字幕。

但除了fileball这个播放器，其他诸如infuse、网页、vidhub就没有类似的问题
192.168.31.237 - - [21/May/2024:05:52:36 +0000] "GET /Videos/28843/15a32bd418bc928b2db69be397b7967d/Subtitles/3/0/Stream.ass?api_key=xxxx HTTP/1.1" 307 164 "-" "Filebox/1.3.20 (me.shuifeng.Filebox; build:235; iOS 17.2.0) Alamofire/5.8.0" "-"

192.168.31.237 - - [21/May/2024:05:52:38 +0000] "POST /Sessions/Playing/Progress HTTP/1.1" 307 164 "-" "Fileball/235 CFNetwork/1490.0.4 Darwin/23.2.0" "-"

192.168.31.237 - - [21/May/2024:05:52:38 +0000] "POST /Sessions/Playing/Progress HTTP/2.0" 204 0 "-" "Fileball/235 CFNetwor
k/1490.0.4 Darwin/23.2.0" "-"
[error.txt](https://github.com/bpking1/embyExternalUrl/files/15385151/error.txt)

**Comment by chen3861229** [comment]
http 204 只是原始服务端返回的，无需返回内容的提示而已，不是报错哦，我看这行才是关键信息，试下直接用 https 访问服务，服务器信息那里加上 https:// 的前缀，不要用默认的 http:// 试下呢，nginx 上虽然做了 http 307 重定向到 https 上，但是可能部分客户端没有遵守这个状态码的规范
````
192.168.31.237 - - [21/May/2024:05:52:36 +0000] "GET /Videos/28843/15a32bd418bc928b2db69be397b7967d/Subtitles/3/0/Stream.ass?api_key=xxx HTTP/1.1" 307 164 "-" "Filebox/1.3.20 (me.shuifeng.Filebox; build:235; iOS 17.2.0) Alamofire/5.8.0" "-"
````
