### ISSUE TITLE
新版的这么复杂吗，都要改啥东西啊

### ISSUE THREAD

**Issue by chaomarks** [bpking1/embyExternalUrl#171]
上来看了一下有没有跟新，好家伙，功能是越来越完善了，但是都要改哪个文件啊，望优化一下，我把新版脚本复制进去，nginx直接起不来了

**Comment by chen3861229** [comment]
还是只需要改 constant 中的必填项，稍微留意下 【includes // 拆分的 conf 文件夹,http 和 https 端口在这改】中的端口就行了 
此时大致文件结构如下:
````
~/emby2Alist
├── docker // 创建容器脚本文件夹
|   ├── docker-compose.yml // docker-compose 脚本,根据自身情况修改
|   ├── nginx-emby.syno.json // 群晖 docker 脚本,根据自身情况修改
|   └── nginx-jellyfin.syno.json  // 群晖 docker 脚本,根据自身情况修改
└── nginx // nginx 配置文件夹
    ├── conf.d // nginx 配置文件夹
    |   ├── api // JS 脚本文件夹,完全不用改
    |   ├── cert // SSL 证书文件夹,根据自身情况修改
    |   ├── common // 通用工具类文件夹,完全不用改
    |   ├── exampleConfig // 示例 constant 配置文件夹
    |   ├── includes // 拆分的 conf 文件夹,http 和 https 端口在这改
    |   ├── constant.js // 常量主配置文件,根据自身情况修改
    │   ├── emby-live.js // 直播相关脚本,完全不用改
    │   ├── emby-transcode.js // 转码相关脚本,完全不用改
    │   ├── emby.conf // emby 配置文件,根据自身情况修改,注意 https 默认被注释掉了
    │   └── emby.js // 主脚本,完全不用改
    └── nginx.conf // nginx 配置文件,一般不用改
````

**Comment by chaomarks** [comment]
nginx将emby的8096端口反代为8097
然后再用反代将nginx的8097代理到443，为了免端口访问，
是不是这个设置includes // 拆分的 conf 文件夹里,http 就填8096和 https填443

**Comment by chaomarks** [comment]
还有一个问题，我用旧版脚本
![image](https://github.com/bpking1/embyExternalUrl/assets/93130581/1516efa5-7411-4345-a553-444c3c15a732)
网页不能播放TS格式文件，但是emby自己的端口可以播放，手机可以播放，不知道什么原因

**Comment by NASA0719** [comment]
> 还是只需要改 constant 中的必填项，稍微留意下 【includes // 拆分的 conf 文件夹,http 和 https 端口在这改】中的端口就行了 
> 此时大致文件结构如下:
> ````
> ~/emby2Alist
> ├── docker // 创建容器脚本文件夹
> |   ├── docker-compose.yml // docker-compose 脚本,根据自身情况修改
> |   ├── nginx-emby.syno.json // 群晖 docker 脚本,根据自身情况修改
> |   └── nginx-jellyfin.syno.json  // 群晖 docker 脚本,根据自身情况修改
> └── nginx // nginx 配置文件夹
>     ├── conf.d // nginx 配置文件夹
>     |   ├── api // JS 脚本文件夹,完全不用改
>     |   ├── cert // SSL 证书文件夹,根据自身情况修改
>     |   ├── common // 通用工具类文件夹,完全不用改
>     |   ├── exampleConfig // 示例 constant 配置文件夹
>     |   ├── includes // 拆分的 conf 文件夹,http 和 https 端口在这改
>     |   ├── constant.js // 常量主配置文件,根据自身情况修改
>     │   ├── emby-live.js // 直播相关脚本,完全不用改
>     │   ├── emby-transcode.js // 转码相关脚本,完全不用改
>     │   ├── emby.conf // emby 配置文件,根据自身情况修改,注意 https 默认被注释掉了
>     │   └── emby.js // 主脚本,完全不用改
>     └── nginx.conf // nginx 配置文件,一般不用改
> ````

conf.d下应该还有个config文件夹，里面的内容也是按需修改是吧？另外这个最新版似乎修复了一个问题，图片缓存策略imageCachepolicy这个参数在之前的版本中设置为2（其他模式没测试过），在embyCache文件夹下只会有两个空文件夹，用这次新版本就会有一些子文件夹及文件。

**Comment by chen3861229** [comment]
> conf.d下应该还有个config文件夹，里面的内容也是按需修改是吧？

是的，昨晚做了拆分，用到对应功能的 conf 下的需要配置

**Comment by chaomarks** [comment]
> 1.嗯？还有上级反代吗？这个主要看你 SSL 是变动谁做的，如果给 nginx 的话，直接 https 用 8097 ，注释掉 emby.conf 里的 http 那个 include ，打开 https 的，如果变动前置的其他反代处理 https ，nginx 内网只用 http 就行了 2.原始服务播放部分不兼容的ts内部的媒体编码格式会走转容器(搬运转码)，可以参照#126

大佬，建一个TG群或者企鹅群吧，这里回复太麻烦了

**Comment by chen3861229** [comment]
个人暂时没那么多精力，没办法，还是 issus 上有个留档可以方便后来者吧，其实 github 默认是同步邮件发送的，邮件里回复也是同步到这里的

**Comment by chaomarks** [comment]
> 个人暂时没那么多精力，没办法，还是 issus 上有个留档可以方便后来者吧，其实 github 默认是同步邮件发送的，邮件里回复也是同步到这里的

大佬我用最新的脚本，改了这些，还是无法打开代理后的端口网页，不知道哪里的问题
~/emby2Alist
├── docker // （没加这个目录以及里面的文件删除了）
|   ├── docker-compose.yml //（没加文件删除了）
|   ├── nginx-emby.syno.json //（ 没加文件删除了）
|   └── nginx-jellyfin.syno.json  // （没加文件删除了）
└── nginx // （nginx 配置文件夹）
    ├── conf.d // （nginx 配置文件夹）
    |   ├── api // （没有改）
    |   ├── cert // （没有这个文件夹，没改）
    |   ├── common // （没改）
    |   ├── exampleConfig // （没加这个目录以及里面的文件删除了）
    |   ├── includes // （改了里面的http配置，改为nginx容器创建时的映射端口）
    |   ├── constant.js // （改了embyHost为emby的映射端口，embyApiKey改为空，embyMountPath改为空数组）
    │   ├── emby-live.js // （没改）
    │   ├── emby-transcode.js //（ 没改）
    │   ├── emby.conf //（没改，还是使用http）
    │   └── emby.js // （没改）
          ├── config //拆分配置文件夹）
            ├──constant-mount.js  //（改了alist的地址以及token）
             其他文件没改
    └── nginx.conf // 没改

**Comment by chen3861229** [comment]
docker 用的桥接网络吗？容器内部改了端口，映射也需要改的
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/044d743a-244b-4f18-a44f-73821fd49e9a)

**Comment by chaomarks** [comment]
容器emby用的amilays的8088::8096，nginx用的官方最新版8090:80，以前是访问8090就能看到emby了，现在是访问不了，算了，不搞了实在搞不明白了
