### ISSUE TITLE
[discussion] emby直链能实现多线程吗？

### ISSUE THREAD

**Issue by yubanmeiqin9048** [bpking1/embyExternalUrl#18]

**Comment by djniche** [comment]
直链多线程看你播放器支持情况..据我所知 potplayer好像带url复用功能..缺点就是写盘

**Comment by yubanmeiqin9048** [comment]
> 直链多线程看你播放器支持情况..据我所知 potplayer好像带url复用功能..缺点就是写盘

potplayer实现的话是开箱即用？MPV有办法实现吗？

**Comment by djniche** [comment]
> 

MPV应该也有写盘模式吧,但是是不是复用我就不了解了.我是gd盘,走CF后pot刚播放可能就10 20MB/S,十几 二十秒后就能到50-90MB/S的缓冲速度. 感觉是检测到了整个的MP4链接直接复用加速缓冲了
