### ISSUE TITLE
JP VPS部署，115每次都要开梯 才能走302 正常播放

### ISSUE THREAD

**Issue by baiguke2019** [bpking1/embyExternalUrl#184]
CD2挂载扫库 国内IP能正常播放 走的302

创建的strm文件 国内IP播放 提示无兼容的流， 需要开梯才能正常播放。

`2024/05/28 17:21:51 [warn] 20#20: *83 js: === systemInfoHandler: /emby/System/Info, the NJS VM is destroyed ===
2024/05/28 17:22:00 [notice] 20#20: *78 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000008, client: 39.158.37.242, server: default, request: "POST /emby/Items/90/PlaybackInfo?UserId=1fd2e5f826934ac4be52110ed3c265de&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=30281299&X-Emby-Client=Emby+for+Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1", host: "公网ip:8091"
2024/05/28 17:22:00 [warn] 20#20: *78 js: playbackinfo proxy uri: /proxy/emby/Items/90/PlaybackInfo
2024/05/28 17:22:00 [warn] 20#20: *78 js: playbackinfo proxy query string: UserId=1fd2e5f826934ac4be52110ed3c265de&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=30281299&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json
2024/05/28 17:22:00 [warn] 20#20: *78 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"1b7d504509c9e165a12a3997dd41f420","Path":"/Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4","Type":"Default","Container":"strm","Size":0,"Name":"The.Mystic.Nine.S01E03","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/90/original.strm?DeviceId=347d4cf3814cc23c&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=29cc4ea05aec43b88991de5592fcab0a&api_key=6273445035074c0b9d8f9db9c4257676","AddApiKeyToDirectStreamUrl":false,"ReadAtNativeFramerate":false,"ItemId":"90"}],"PlaySessionId":"29cc4ea05aec43b88991de5592fcab0a"}
2024/05/28 17:22:00 [warn] 20#20: *78 js: modify direct play supports all true
2024/05/28 17:22:00 [warn] 20#20: *78 js: modify direct play info
2024/05/28 17:22:00 [warn] 20#20: *78 js: 11ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"1b7d504509c9e165a12a3997dd41f420","Path":"/Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4","Type":"Default","Container":"strm","Size":0,"Name":"The.Mystic.Nine.S01E03","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/90/stream.strm?UserId=1fd2e5f826934ac4be52110ed3c265de&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=30281299&X-Emby-Client=Emby%20for%20Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=29cc4ea05aec43b88991de5592fcab0a&Static=true","AddApiKeyToDirectStreamUrl":false,"ReadAtNativeFramerate":false,"ItemId":"90","XRouteMode":"redirect","XOriginDirectStreamUrl":"/videos/90/original.strm?DeviceId=347d4cf3814cc23c&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=29cc4ea05aec43b88991de5592fcab0a&api_key=6273445035074c0b9d8f9db9c4257676","XModifyDirectStreamUrlSuccess":true}],"PlaySessionId":"29cc4ea05aec43b88991de5592fcab0a"}
2024/05/28 17:22:00 [warn] 20#20: *78 js: === transferPlaybackInfo: /emby/Items/90/PlaybackInfo, the NJS VM is destroyed ===
2024/05/28 17:22:02 [notice] 20#20: *78 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000010, client: 39.158.37.242, server: default, request: "POST /emby/Items/90/PlaybackInfo?UserId=1fd2e5f826934ac4be52110ed3c265de&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&MaxStreamingBitrate=24227000&X-Emby-Client=Emby+for+Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1", host: "公网ip:8091"
2024/05/28 17:22:02 [warn] 20#20: *78 js: playbackinfo proxy uri: /proxy/emby/Items/90/PlaybackInfo
2024/05/28 17:22:02 [warn] 20#20: *78 js: playbackinfo proxy query string: UserId=1fd2e5f826934ac4be52110ed3c265de&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&MaxStreamingBitrate=24227000&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json
2024/05/28 17:22:02 [notice] 20#20: *101 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000011, client: 39.158.37.242, server: default, request: "POST /emby/Items/90/PlaybackInfo?UserId=1fd2e5f826934ac4be52110ed3c265de&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=24227000&X-Emby-Client=Emby+for+Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1", host: "公网ip:8091"
2024/05/28 17:22:02 [warn] 20#20: *101 js: playbackinfo proxy uri: /proxy/emby/Items/90/PlaybackInfo
2024/05/28 17:22:02 [warn] 20#20: *101 js: playbackinfo proxy query string: UserId=1fd2e5f826934ac4be52110ed3c265de&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=24227000&X-Emby-Client=Emby for Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json
2024/05/28 17:22:02 [warn] 20#20: *101 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"1b7d504509c9e165a12a3997dd41f420","Path":"/Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4","Type":"Default","Container":"strm","Size":0,"Name":"The.Mystic.Nine.S01E03","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/90/original.strm?DeviceId=347d4cf3814cc23c&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=0b8287d8fb6a472fa069b2133f21a9f7&api_key=6273445035074c0b9d8f9db9c4257676","AddApiKeyToDirectStreamUrl":false,"ReadAtNativeFramerate":false,"ItemId":"90"}],"PlaySessionId":"0b8287d8fb6a472fa069b2133f21a9f7"}
2024/05/28 17:22:02 [warn] 20#20: *101 js: modify direct play supports all true
2024/05/28 17:22:02 [warn] 20#20: *101 js: modify direct play info
2024/05/28 17:22:02 [warn] 20#20: *101 js: 12ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"1b7d504509c9e165a12a3997dd41f420","Path":"/Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4","Type":"Default","Container":"strm","Size":0,"Name":"The.Mystic.Nine.S01E03","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/90/stream.strm?UserId=1fd2e5f826934ac4be52110ed3c265de&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=24227000&X-Emby-Client=Emby%20for%20Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=0b8287d8fb6a472fa069b2133f21a9f7&Static=true","AddApiKeyToDirectStreamUrl":false,"ReadAtNativeFramerate":false,"ItemId":"90","XRouteMode":"redirect","XOriginDirectStreamUrl":"/videos/90/original.strm?DeviceId=347d4cf3814cc23c&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=0b8287d8fb6a472fa069b2133f21a9f7&api_key=6273445035074c0b9d8f9db9c4257676","XModifyDirectStreamUrlSuccess":true}],"PlaySessionId":"0b8287d8fb6a472fa069b2133f21a9f7"}
2024/05/28 17:22:02 [warn] 20#20: *101 js: === transferPlaybackInfo: /emby/Items/90/PlaybackInfo, the NJS VM is destroyed ===
2024/05/28 17:22:02 [warn] 20#20: *78 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"1b7d504509c9e165a12a3997dd41f420","Path":"/Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4","Type":"Default","Container":"strm","Size":0,"Name":"The.Mystic.Nine.S01E03","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/90/original.strm?DeviceId=347d4cf3814cc23c&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=98c8a3dfbf7b49e0af56eafbdf8adb49&api_key=6273445035074c0b9d8f9db9c4257676","AddApiKeyToDirectStreamUrl":false,"ReadAtNativeFramerate":false,"ItemId":"90"}],"PlaySessionId":"98c8a3dfbf7b49e0af56eafbdf8adb49"}
2024/05/28 17:22:02 [warn] 20#20: *78 js: modify direct play supports all true
2024/05/28 17:22:02 [warn] 20#20: *78 js: modify direct play info
2024/05/28 17:22:02 [warn] 20#20: *78 js: 62ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"1b7d504509c9e165a12a3997dd41f420","Path":"/Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4","Type":"Default","Container":"strm","Size":0,"Name":"The.Mystic.Nine.S01E03","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/90/stream.strm?UserId=1fd2e5f826934ac4be52110ed3c265de&IsPlayback=true&AutoOpenLiveStream=true&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&MaxStreamingBitrate=24227000&X-Emby-Client=Emby%20for%20Android&X-Emby-Device-Name=23113RKC6C&X-Emby-Device-Id=347d4cf3814cc23c&X-Emby-Client-Version=3.3.94&X-Emby-Token=6273445035074c0b9d8f9db9c4257676&X-Emby-Language=zh-cn&reqformat=json&PlaySessionId=98c8a3dfbf7b49e0af56eafbdf8adb49&Static=true","AddApiKeyToDirectStreamUrl":false,"ReadAtNativeFramerate":false,"ItemId":"90","XRouteMode":"redirect","XOriginDirectStreamUrl":"/videos/90/original.strm?DeviceId=347d4cf3814cc23c&MediaSourceId=1b7d504509c9e165a12a3997dd41f420&PlaySessionId=98c8a3dfbf7b49e0af56eafbdf8adb49&api_key=6273445035074c0b9d8f9db9c4257676","XModifyDirectStreamUrlSuccess":true}],"PlaySessionId":"98c8a3dfbf7b49e0af56eafbdf8adb49"}
2024/05/28 17:22:02 [warn] 20#20: *78 js: === transferPlaybackInfo: /emby/Items/90/PlaybackInfo, the NJS VM is destroyed ===
2024/05/28 17:22:02 [warn] 20#20: *71 js: redirect2Pan, UA: Emby/3.3.94 (Linux;Android 14) AndroidXMedia3/1.1.1
2024/05/28 17:22:02 [warn] 20#20: *71 js: itemInfoUri: http://172.17.0.2:8096/Items?Ids=1b7d504509c9e165a12a3997dd41f420&Fields=Path,MediaSources&Limit=1&api_key=6273445035074c0b9d8f9db9c4257676
2024/05/28 17:22:02 [warn] 20#20: *71 js: 3ms, fetchEmbyFilePath async function cost
2024/05/28 17:22:02 [warn] 20#20: *71 js: notLocal: true
2024/05/28 17:22:02 [warn] 20#20: *71 js: notLocal decodeURIComponent embyRes.path
2024/05/28 17:22:02 [warn] 20#20: *71 js: mount emby file path: /Movies/vod/115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4
2024/05/28 17:22:02 [warn] 20#20: *71 js: embyPathMapping: [[0,1,"/Movies/vod",""]]
2024/05/28 17:22:02 [warn] 20#20: *71 js: strMapping replace: /Movies/vod => 
2024/05/28 17:22:02 [warn] 20#20: *71 js: mapped emby file path: /115/剧集/国港台/老九门[全48集][国语配音+中文字幕].The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4
2024/05/28 17:22:03 [warn] 20#20: *71 js: hit cilentSelfAlistRule: [2,"115.com","http://公网ip:5244"]
2024/05/28 17:22:03 [warn] 20#20: *71 js: 913ms, fetchAlistPathApi async function cost
2024/05/28 17:22:03 [warn] 20#20: *71 js: fetchAlistPathApi, UA: Emby/3.3.94 (Linux;Android 14) AndroidXMedia3/1.1.1
2024/05/28 17:22:03 [warn] 20#20: *71 js: redirect to: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:03 [warn] 20#20: *71 js: routeL1Dict add: [/emby/videos/90/stream.strm:1b7d504509c9e165a12a3997dd41f420] : [http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0]
2024/05/28 17:22:03 [warn] 20#20: *71 js: === redirect2Pan: /emby/videos/90/stream.strm, the NJS VM is destroyed ===
2024/05/28 17:22:03 [warn] 20#20: *71 js: redirect2Pan, UA: Emby/3.3.94 (Linux;Android 14) AndroidXMedia3/1.1.1
2024/05/28 17:22:03 [warn] 20#20: *71 js: hit routeCache L1: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:03 [warn] 20#20: *71 js: redirect to: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:03 [warn] 20#20: *71 js: === redirect2Pan: /emby/videos/90/stream.strm, the NJS VM is destroyed ===
2024/05/28 17:22:04 [warn] 20#20: *71 js: redirect2Pan, UA: Emby/3.3.94 (Linux;Android 14) AndroidXMedia3/1.1.1
2024/05/28 17:22:04 [warn] 20#20: *71 js: hit routeCache L1: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:04 [warn] 20#20: *71 js: redirect to: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:04 [warn] 20#20: *71 js: === redirect2Pan: /emby/videos/90/stream.strm, the NJS VM is destroyed ===
2024/05/28 17:22:06 [warn] 20#20: *71 js: redirect2Pan, UA: Emby/3.3.94 (Linux;Android 14) AndroidXMedia3/1.1.1
2024/05/28 17:22:06 [warn] 20#20: *71 js: hit routeCache L1: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:06 [warn] 20#20: *71 js: redirect to: http://公网ip:5244/d/115/%E5%89%A7%E9%9B%86/%E5%9B%BD%E6%B8%AF%E5%8F%B0/%E8%80%81%E4%B9%9D%E9%97%A8%5B%E5%85%A848%E9%9B%86%5D%5B%E5%9B%BD%E8%AF%AD%E9%85%8D%E9%9F%B3+%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95%5D.The.Mystic.Nine.2016.Complete.2160P.WEB-DL.H265.AAC-Huawei/The.Mystic.Nine.S01E03.mp4?sign=MDCvrAo68nmJfQEtMXwyyetonVU3bIZOZx7ACJph9mQ=:0
2024/05/28 17:22:06 [warn] 20#20: *71 js: === redirect2Pan: /emby/videos/90/stream.strm, the NJS VM is destroyed ===
`

**Comment by chen3861229** [comment]
多谢提供日志方便定位，115 处理得比较特殊，因为部分客户端("Emby for iOS"和"Infuse")连 115 直链会有些 bug, 所以默认是让播放的客户端自身请求的 alist ，这个【http://公网ip:5244】搭的国内不知道是墙了你 VPS 端口还是 ip 了，有几个解决方法，多选一
1.尝试更改 alist 默认的端口，如果能通说明 VPS 只是被墙了 5244 端口，或者尝试给 alist 套上 https 以提升稳定性
/alist/data/config.json
```json
{
  "scheme": {
      "address": "0.0.0.0",
      "http_port": -1,
      "https_port": 5244,
      "force_https": true,
      "cert_file": "data/cert/fullchain.pem", // 自己的证书文件
      "key_file": "data/cert/privkey.key", // 自己的证书私钥文件
      "unix_file": "",
      "unix_file_perm": ""
    },
}
```
2.让客户端直接请求 115 直链(查询 alist 在 VPS 局域网内完成)，假如使用的是拆分后的配置文件，改下这个参数 cilentSelfAlistRule , 将 [2, strHead["115"], alistPublicAddr], 注释掉
emby2Alist\nginx\conf.d\config\constant-mount.js
```js
const cilentSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  // [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
];
```
3.国内有公网条件的话，可以重新搭建一个 alist 以供特殊情况的客户端访问

**Comment by baiguke2019** [comment]
👌感谢佬的解答, 我测试下

**Comment by baiguke2019** [comment]
感谢佬的解答 方法2得到解决
const cilentSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  // [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
];

佬还有个问题 
每次第一次播放的时候 要1分钟 才能播放出来 这个能解决吗？

**Comment by chen3861229** [comment]
>每次第一次播放的时候 要1分钟 才能播放出来 这个能解决吗？

这个是 emby 针对 strm 的特性，入库的时候是没有进行媒体编码信息扫描的，表现形式为详情页最下边没有编码信息，只有在第一次播放的同时，才会用客户端解码的媒体信息进行补充入库，第一次播放后详情页最下边就会有编码信息了，所以第一次播放比较慢，我这边是没法干预这个过程的，不过 emby 插件库里有个貌似可以定时处理 strm 媒体信息的，设置-高级-插件-Catalog-元数据-StrmExtract，我这边只是看到了，没有尝试过这个插件，需要自行摸索了，但是这样其实 strm 又扫库了，虽然可能是定时可控可手动取消的，这点也需要自行权衡下

**Comment by baiguke2019** [comment]
再次感谢佬的解答
我觉得既然strm入库, 没必要StrmExtract处理了
看了下日志 是这个这个问题 
2024/06/02 02:43:09 [warn] 20#20: *155 js: playbackinfo subrequest failed
2024/06/02 02:43:09 [warn] 20#20: *155 js: use original link
2024/06/02 02:43:09 [warn] 20#20: *155 js: routeL1Dict add: [/emby/Items/39721/PlaybackInfo:d4bb9153c739ae8bd5c39ce1d38221ce] : [@root]
2024/06/02 02:43:09 [error] 20#20: *167 js: error: preload: Error: read timed out
2024/06/02 02:43:09 [warn] 20#20: *167 js: === preload, the NJS VM is destroyed ===
2024/06/02 02:43:09 [warn] 20#20: *201 js: 60000ms, fetchAlistPathApi async function cost
2024/06/02 02:43:09 [warn] 20#20: *201 js: fetchAlistPathApi, UA: Mozilla/5.0 (Linux; Android 14; 23113RKC6C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36
2024/06/02 02:43:09 [warn] 20#20: *201 js: alistRes: error: alist_path_api fetchAlistFiled Error: read timed out
2024/06/02 02:43:09 [error] 20#20: *201 js: fail to fetch fetchAlistPathApi: error: alist_path_api fetchAlistFiled Error: read timed out,fallback use original link
2024/06/02 02:43:09 [warn] 20#20: *201 js: use original link
2024/06/02 02:43:09 [warn] 20#20: *201 js: === redirect2Pan: /emby/videos/39721/stream.strm, the NJS VM is destroyed ===
2024/06/02 02:44:09 [error] 20#20: *155 upstream timed out (110: Connection timed out) while reading response header from upstream, client:
这个问题是不是单目录下 子目录太多的原因？  （子目录有1W多个）
尝试打开alist那边也慢☺

**Comment by chen3861229** [comment]
啊，你这个，日志中两个方向的查询都失败了，所以走了原始 emby 处理了(中转流量)
1. nginx => emby 它俩不在同一局域网下吗？这条路径正常情况下不会超时失败的，在 2 也失败的情况下，这个暂时不重要了，优先保证 2 的路径是通的，再有问题可以尝试解决这个
2. nginx => alist 这个也可以搭在同局域网下优化查询速度，不过你提到的子目录太多的问题，这个是有关的，alist 可能是一级一级打开目录的，可以尝试精简目录层级，或使用 alist 的 alias 聚合进行目录映射，这个的缺点是变只读，虽然最新版支持了重命名和删除，但不支持其他操作了，可以自己权衡下
3. 还有种方案是开启 alist 的分页参数，这样单级目录超多文件应该会快一些
4. 如果 2 实在无法优化，那只能退而求其次了，使用原始 emby 中转流量处理，可以用路由规则指定这个查询一分钟的目录直接走"proxy"规则，针对这个目录放弃直链功能

**Comment by baiguke2019** [comment]
> 再次感谢佬的解答 我觉得既然strm入库, 没必要StrmExtract处理了 看了下日志 是这个这个问题 2024/06/02 02:43:09 [warn] 20#20: *155 js: playbackinfo subrequest failed 2024/06/02 02:43:09 [warn] 20#20: *155 js: use original link 2024/06/02 02:43:09 [warn] 20#20: *155 js: routeL1Dict add: [/emby/Items/39721/PlaybackInfo:d4bb9153c739ae8bd5c39ce1d38221ce] : [@root] 2024/06/02 02:43:09 [error] 20#20: *167 js: error: preload: Error: read timed out 2024/06/02 02:43:09 [warn] 20#20: *167 js: === preload, the NJS VM is destroyed === 2024/06/02 02:43:09 [warn] 20#20: *201 js: 60000ms, fetchAlistPathApi async function cost 2024/06/02 02:43:09 [warn] 20#20: *201 js: fetchAlistPathApi, UA: Mozilla/5.0 (Linux; Android 14; 23113RKC6C Build/UKQ1.230804.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36 2024/06/02 02:43:09 [warn] 20#20: *201 js: alistRes: error: alist_path_api fetchAlistFiled Error: read timed out 2024/06/02 02:43:09 [error] 20#20: *201 js: fail to fetch fetchAlistPathApi: error: alist_path_api fetchAlistFiled Error: read timed out,fallback use original link 2024/06/02 02:43:09 [warn] 20#20: *201 js: use original link 2024/06/02 02:43:09 [warn] 20#20: *201 js: === redirect2Pan: /emby/videos/39721/stream.strm, the NJS VM is destroyed === 2024/06/02 02:44:09 [error] 20#20: *155 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 这个问题是不是单目录下 子目录太多的原因？ （子目录有1W多个） 尝试打开alist那边也慢☺

nginx emby alist 这个都是在同一局域网部署的,   已上错误 就是间隔一会 第一次播放偶尔会有这个错误, 第2 次3次 都是正常秒播的
我尝试115内 精简分类下 试下看

**Comment by chen3861229** [comment]
可以先试下 3 开下分页试下，如果能解决是最简单的了，不用重新入库了，这个是基于你 strm 得出的，因为如果是挂载情况开了 alist 的分页，可能挂载程序没有兼容 alist 分页就找不到第二页的内容，你可能不存在这种情况，不行再精简分类吧

**Comment by baiguke2019** [comment]
好的了解，
修改了下， alist 那边的， 目录结构的缓存时间 问题暂时得到解决。
再次感谢佬的耐心指导和解答 谢谢！
