### ISSUE TITLE
[bug] embyLaunchPotplayer 报错`response.MediaSources` undefined

### ISSUE THREAD

**Issue by jqtmviyu** [bpking1/embyExternalUrl#185]
## 环境

embyweb+embyLaunchPotplayer

## 描述

在`Series`页, 当没有下一集, 报错`response.MediaSources` undefined

## fix

使用可选链`response.MediaSources?.length`

[        if (response.MediaSources.length > 0) {](https://github.com/bpking1/embyExternalUrl/blob/dea21a5b5351753a72bc4c8c74ac965a76964f98/embyWebAddExternalUrl/embyLaunchPotplayer.js#L181)

**Comment by chen3861229** [comment]
好的，多谢指正，ES 11 小知识 + 1
