### ISSUE TITLE
直链不成功，而且用户已经关闭转码网页端打开视频依然能够出现下载的流量访问

### ISSUE THREAD

**Issue by ethuh** [bpking1/embyExternalUrl#187]
设备情况，使用rclone挂载OneDrive为虚拟目录到VPS上（VPS本身已经有了一个Nginx），然后emby直接把虚拟目录设置为影视库
为了排错，我列出来用到的路径
挂载路径，有两个盘：
`/savezoom/one_nt/`
`/savezoom/one_nm`
alist中也同样有两个盘，盘名分别为one_nt,one_nm,alist中的路径为/ont_nt,/one_nm
emby的docker映射里，填写的两个库路径为：
`- /savezoom/one_nm:/one_nm`
` - /savezoom/one_nt:/media2`

之前用的未做分离配置的版本的时候，是可以正常使用的，clash这边能看到播放视频带宽占用的地址是SharePoint的，现在的话emby网页端设置关闭转码，打开视频居然可以正常播放，查看clash，流量走的是IP：8131端口

下载的仓库的源码，然后把emby2alist的内容复制到VPS后，改了以下几个内容：

1. alistToken
2. alistPublicAddr
3. embyApiKey
4. embyMountPath `const embyMountPath = ["/savezoom"];`
5. http端口改成了8131
`server_name default;
listen 8131; ## Listens on port IPv4
listen [::]:8131; # Listens on port IPv6`

使用docker log命令无输出，进入nginx容器内部看实时日志内容在下面的error.log文件里有,也做了截图

总之：现在不懂为什么没有直链了，是哪里出了问题？为什么转码和互联网质量都做了设置，依然可以走下载的流量（IP：8131端口）的形式看到视频，求教求教，目前VPS里装的是dev版本的，看到图里有说到notLocal: false，然后是hit proxy， not mountPath first: ["/savezoom"]，接着就use original link了，是不是这一块的的问题呢？

<img width="1448" alt="image" src="https://github.com/bpking1/embyExternalUrl/assets/23073985/5d085221-1414-468e-9caa-4dfca66dc78b">

[error.log](https://github.com/bpking1/embyExternalUrl/files/15488484/error.log)

**Comment by chen3861229** [comment]
1.配置文件拆分和不拆分只是两种风格，其实可以直接把原始的配置放到 /conf.d 下替换掉默认的拆分配置就行了，这样可以忽略 /conf.d/conf 下的拆分文件
2.日志关键字抓得确实没错，问题出在 embyMountPath 这个变量配得有问题，这个指的是媒体入库的路径和 alist 的根目录 / 取差集,多出来的那部分就是挂载工具的挂载路径
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#1%E5%A6%82%E4%BD%95%E7%A1%AE%E5%AE%9A-embymountpath-%E7%9A%84%E8%B7%AF%E5%BE%84%E5%A1%AB%E5%86%99

3.这个转发到原始服务上处理是给服务器本地媒体或者查询出错回退使用的，和【转码和互联网质量都做了设置】这个暂无关系

**Comment by ethuh** [comment]
> 1.配置文件拆分和不拆分只是两种风格，其实可以直接把原始的配置放到 /conf.d 下替换掉默认的拆分配置就行了，这样可以忽略 /conf.d/conf 下的拆分文件
> 
> 2.日志关键字抓得确实没错，问题出在 embyMountPath 这个变量配得有问题，这个指的是媒体入库的路径和 alist 的根目录 / 取差集,多出来的那部分就是挂载工具的挂载路径
> 
> https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#1%E5%A6%82%E4%BD%95%E7%A1%AE%E5%AE%9A-embymountpath-%E7%9A%84%E8%B7%AF%E5%BE%84%E5%A1%AB%E5%86%99
> 
> 3.这个转发到原始服务上处理是给服务器本地媒体或者查询出错回退使用的，和【转码和互联网质量都做了设置】这个暂无关系
> 
> 4.看到提供的 one_nm 路径是相同的，把 embyMountPath 置空 emby2Alist\nginx\conf.d\constant.js
> 
> ```js
> // 如果没有挂载,全部使用 strm 文件，忽略这个注释
> // 此项填[""],必须要是数组
> const embyMountPath = [""];
> ```
> 
> 然后 one_nt 这个需要用到路径映射参数 emby2Alist\nginx\conf.d\config\constant-pro.js
> 
> ```js
> // 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠
> // 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const embyPathMapping = [
>   [0, 0, "/media2", "/ont_nt"],
> ];
> ```

十分感谢大佬的帮助，解释的十分清晰明白，目前已经可以用了，再次感谢大佬的开发工作，实在是太好用、太方便了
