### ISSUE TITLE
客户端已经实现115直链播放了，emby网页端怎么单独配置成不走直链，而是回退走本地路径播放？

### ISSUE THREAD

**Issue by LunaticXJ** [bpking1/embyExternalUrl#188]
客户端已经实现115直链播放了，emby网页端不支持直链播放，那怎么单独配置成emby网页端不走直链，也不由网页侧请求alist直链，而是回退成走原始本地路径播放呢？需要怎么配置，请大佬指点

**Comment by chen3861229** [comment]
#130

**Comment by LunaticXJ** [comment]
你好，按FAQ修改了配置文件还是不行，配置文件和日志如下，麻烦帮忙看下哈
[constant.js.txt](https://github.com/bpking1/embyExternalUrl/files/15500737/constant.js.txt)
[MediaLinker.log](https://github.com/bpking1/embyExternalUrl/files/15500739/MediaLinker.log)

**Comment by chen3861229** [comment]
1.日志注意匿名化敏感信息哦，看日志中出现了 embyPathMapping 这个不正常，路由参数判断成功的情况下不会走到这里，会直接走 nginx proxy 使用 emby 原始链接了
2.尝试更新下代码，历史的 constant.js 还是可以用的，覆盖掉 conf.d 下默认的拆分的就行

**Comment by LunaticXJ** [comment]
检查了一下设备的类型没问题，是 Emby Web 开头的。
我用的是Docker版的MediaLinker，直接拉latest版本可以吗，我看docker hub上面是更新时间是2小时前，或者怎么看版本号？

**Comment by LunaticXJ** [comment]
更新到了最新版Docker版，播放还是一样失败。我当前的部署是播放strm文件，文件里面放本地绝对路径，因此notLocal是true，不知道跟这个有没关系

**Comment by LunaticXJ** [comment]
function isProxy(r, proxyRules, filePath, isAlistRes, notLocal) {
  const disableRedirectRule = proxyRules;
  const mountPath = config.embyMountPath;
  if (!isAlistRes) {
    // local file not xxxMountPath first
    if (mountPath.every(path => path && !filePath.startsWith(path) && !notLocal)) {
      ngx.log(ngx.WARN, `hit proxy, not mountPath first: ${JSON.stringify(mountPath)}`);
      return true;
    }
  }
应该是这段代码判断为false了，不清楚这里面的逻辑，对于我这种场景notLocal是否应该判断为true呢，这样就能返回true了。

**Comment by chen3861229** [comment]
>我当前的部署是播放strm文件，文件里面放本地绝对路径，因此notLocal是true，getRouteMode返回结果是redirect不知道跟这个有没关系

1.确实是这里判断的原因，但和下面的代码暂无关系，那段是判断本地文件不以 mountPath 开头的，是给本地文件 alist 上没有做处理的

2.我这里用阿里的文件模拟规则测试了下，也是没复现出来，能再提供下新的日志内容吗？记得替换掉隐私信息

**Comment by LunaticXJ** [comment]
好的，感谢大佬，等Docker发布后我测试一下~

**Comment by chen3861229** [comment]
目前有一个新的解决方案，可以参照
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#6115-%E5%86%85%E5%AE%B9%E6%97%A0%E6%B3%95-web-%E7%AB%AF%E6%92%AD%E6%94%BEhtmlvideoplayer-%E8%B7%A8%E5%9F%9F

**Comment by LunaticXJ** [comment]
感谢大佬，新的方案后面测试一下。
现在我更新到最新的版本，想说测试一下先前115 Web端不走302走直链的解决方案，可是发现现在非Web端反而都走不了302重定向了，配置还是跟原来的一模一样，麻烦帮忙看一下哈~
[MediaLinker.log](https://github.com/user-attachments/files/16118074/MediaLinker.log)
