### ISSUE TITLE
将iptv直链播放改成中转播放应如何操作

### ISSUE THREAD

**Issue by erbukuawu** [bpking1/embyExternalUrl#193]
如题，自己宽带有公网ipv6和ipv4，因为现在高清稳定的直播源基本上都是ipv6的，在家正常播放，但是在单位由于没有Ipv6，采用直链播放的话是不支持的，如果能够利用Emby中转一下就能实现IPv4观看v6直播源了。
        求助大佬如果仅想直播功能采用中转播放，其他不变的话是不是可以通过改emby-live.js里面的代码实现？具体改的话应该怎么改呢？

**Comment by chen3861229** [comment]
不用改代码进行特殊实现的，配置项中的路由规则可以间接实现(不是直接是因为判断条件比较复杂)

假如是用的默认拆分后的配置文件，改这里，emby2Alist\nginx\conf.d\config\constant-pro.js，如果是 conf.d 下 constant.js 为单体全量配置文件，直接找 routeRule 配置项
1.我这里示例规则是把该指定的直播链接一刀切了，所有客户端全部走"proxy"的原始 emby 中转流量处理，如果需要更灵活的判断需要自己尝试下

```js
// 路由规则,注意有先后顺序,"proxy"规则优先级最高,其余依次,千万注意规则不要重叠,不然排错十分困难,字幕和图片走了缓存,不在此规则内
// 参数1: 指定处理模式,单规则的默认值为"proxy",但是注意整体规则都不匹配默认值为"redirect",然后下面参数序号-1
// "proxy": 原始媒体服务器处理(中转流量), "redirect": 直链302, "transcode": 转码, "block": 只是屏蔽播放
// "transcode",稍微有些歧义,大部分情况等同于"proxy",这里只是不做转码参数修改,具体是否转码由 emby 客户端自己判断上报或客户端手动切换码率控制
// 参数2: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数3: 匹配类型或来源(字符串参数类型) "filePath": 文件路径(Item.Path), "alistRes": alist返回的链接
// 参数4: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数5: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
const routeRule = [
  ["proxy", "filePath", 0, "https://node1.xxx.com"],
];
```
2.以下是带上特定 emby 用户 ID 的判断，因为判断不了网络状况，所以折中处理，可以新建一个 emby 用户专用在你提到的场景下

```js
const routeRule = [
  // 注意这里省略了参数1,默认值为"proxy",参数2: 分组名,只是做标识的,可以理解为备注,可以随意填写
  ["iptv-user-proxy", "r.args.UserId", 0, "ac0d220d548f43bbb73cf9b44b2ddf0e"], // 链接入参,用户 ID，这里填自身实际情况
  ["iptv-user-proxy", "filePath", 0, "https://node1.xxx.com"], // 这里填自身实际情况
];
```

3.还可以尝试使用远程客户端真实 IP 进行判断，但是前提是 nginx 必须为 host 网络，如果还存在上级反代，需要传递客户端真实 IP 的标头，还有个前提是你们公司的出口 IP 是有规则的，不过大概率是 NAT 后动态的 IP ，我也不是很清楚同一个城市分配的 IP 是不是严格固定开头的，我猜是的，不过不确定有没有特殊情况，需要自己尝试下了

```js
const routeRule = [
  // docker 注意必须为 host 模式,不然此变量全部为内网ip,判断无效,nginx 内置变量不带$,客户端地址($remote_addr)
  ["r.variables.remote_addr", 0, "192."], // 可为单字符串或数组内字符串，填自身实际情况，可以参照 strHead.lanIp，emby2Alist\nginx\conf.d\config\constant-common.js
];
```

直播的 filePath 在 emby 中是远程链接形式，需要自己找下该直播链接的通用匹配判断字符串
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/78f9c08b-5523-44c2-ac8d-08a8e7dc2d36)

这里只是示例，X-Emby-xxx 这些链接入参大部分 emby 接口都带上了，实际应该看 /emby/videos/422953/xxx.xxx 这个才是播放接口，+ 号会被 nginx 自身强制替换为一个空格
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/41d71312-a8bf-4967-b4e2-24ba7ea0d6ed)

**Comment by chen3861229** [comment]
不是很建议改代码层面的，处理比较复杂，改那个 js 确实可以还原回 emby 自己的处理，原本 emby 都是中转流量处理的，但是这个其实是直播和部分情况的转码都会进到这里，如果确实要改，有两种

1.直接改 emby2Alist\nginx\conf.d\emby-live.js
方法第一行直接加 return Emby.internalRedirect(r); 转回 emby 原始链接处理

2.直接从 nginx 源头上不放代直播和部分转码的使用到的接口，注释这两段即可
emby2Alist\nginx\conf.d\emby.conf
```conf
    # Redirect the live to njs
    # location ~* /videos/(.*)/live {
    #     # Disable buffering when the nginx proxy gets very resource heavy upon streaming
    #     proxy_buffering off;
    #     # useProxy mark
    #     if ($args ~* "useProxy=1") {
    #         proxy_pass $emby;
    #         break;
    #     }
    #     js_content embyLive.directLive;
    # }
    # location ~* /videos/(.*)/master {
    #     # Disable buffering when the nginx proxy gets very resource heavy upon streaming
    #     proxy_buffering off;
    #     # useProxy mark
    # 	if ($args ~* "useProxy=1") {
    #         proxy_pass $emby;
    #         break;
    #     }
    #     # transcodeConfig
    #     set $flag "";
    # 	if ($transcodeEnable = true) {
    #         set $flag "${flag}1";
    # 	}
    #     if ($transcodeType = nginx) {
    #     	set $flag "${flag}1";
	# 	}
    #     if ($flag = "11") {
    #         add_header X-Upstream-Addr $upstream_addr; # for debug
    #     	proxy_pass http://transcode_group;
    #         break;
    #     }
    #     if ($flag = "1") {
    #         js_content transcode.transcodeBalance;
    #         break;
    #     }
    #     js_content embyLive.directLive;
    # }
```

**Comment by erbukuawu** [comment]
> 不是很建议改代码层面的，处理比较复杂，而且会影响该脚本的其他功能，改那个 js 确实可以还原回 emby 自己的处理，原本 emby 都是中转流量处理的，但是这个其实是直播和部分情况的转码都会进到这里，如果确实要改，有两种
> 
> 1.直接改 emby2Alist\nginx\conf.d\emby-live.js 方法第一行直接加 return Emby.internalRedirect(r); 转回 emby 原始链接处理
> 
> 2.直接从 nginx 源头上不反代直播和部分转码的使用到的接口，注释这两段即可 emby2Alist\nginx\conf.d\emby.conf
> 
> ```
>     # Redirect the live to njs
>     # location ~* /videos/(.*)/live {
>     #     # Disable buffering when the nginx proxy gets very resource heavy upon streaming
>     #     proxy_buffering off;
>     #     # useProxy mark
>     #     if ($args ~* "useProxy=1") {
>     #         proxy_pass $emby;
>     #         break;
>     #     }
>     #     js_content embyLive.directLive;
>     # }
>     # location ~* /videos/(.*)/master {
>     #     # Disable buffering when the nginx proxy gets very resource heavy upon streaming
>     #     proxy_buffering off;
>     #     # useProxy mark
>     # 	if ($args ~* "useProxy=1") {
>     #         proxy_pass $emby;
>     #         break;
>     #     }
>     #     # transcodeConfig
>     #     set $flag "";
>     # 	if ($transcodeEnable = true) {
>     #         set $flag "${flag}1";
>     # 	}
>     #     if ($transcodeType = nginx) {
>     #     	set $flag "${flag}1";
> 	# 	}
>     #     if ($flag = "11") {
>     #         add_header X-Upstream-Addr $upstream_addr; # for debug
>     #     	proxy_pass http://transcode_group;
>     #         break;
>     #     }
>     #     if ($flag = "1") {
>     #         js_content transcode.transcodeBalance;
>     #         break;
>     #     }
>     #     js_content embyLive.directLive;
>     # }
> ```

好的谢谢大佬，我先试试看
