### ISSUE TITLE
emby用strm,到底在哪里改配置才能反代啊。

### ISSUE THREAD

**Issue by xiewenxuan** [bpking1/embyExternalUrl#200]
不用strm,现在是走直链了，但是因为我库太大了，想用strm文件，配置了半天也搞不对，生成的strm文件就是alist的远程地址，在哪里去修改参数啊，怎么修改啊。

**Comment by chen3861229** [comment]
strm 入库后默认就是支持的

eg 01 : strm 内部文本，这个是 emby 官方支持和建议的格式，区别是这个默认会转发给远程客户端访问，所以需要公网畅通，5244 能访问到
```
https://mydomain:5244/d/文件路径
```
eg 02 : strm 内部文本，这个是自定义实现的，目前不太建议用这种了，因为 emby 不会补充媒体编码信息，这个是需要查询当前 alist 信息的
```
/文件路径
```

eg 02 : strm 内部文本，这个是自定义实现的，局域网开头的 alist 地址这边 nginx 中会访问获取这个 alist 的直链信息转发给客户端，鉴于新版本 alist 都默认开启了 sign 所有，如果此 alist 和主 alist 不是同一个服务，需要注意配置下 sign 信息，
emby2Alist\nginx\conf.d\config\constant-strm.js 中 redirectStrmLastLinkRule
```
http://192.168.1.100:5244/d/文件路径
```

其实需要看你的 strm 生成工具生成的是哪一种
