### ISSUE TITLE
请教下transferPlaybackInfo时间过长问题

### ISSUE THREAD

**Issue by NickLuo21** [bpking1/embyExternalUrl#204]
![CleanShot 2024-06-06 at 16 46 21@2x](https://github.com/bpking1/embyExternalUrl/assets/17668622/b23a6728-f6dc-4a5b-a80d-aa756ee21463)

每次执行transferPlaybackInfo基本需要7,8秒，请问下这个时间可以怎么优化下
目前emby和nginx都是在一个vps上面，都是用的docker部署，开了host模式

**Comment by chen3861229** [comment]
这个时间确实太长了，正常只在 20-200 ms 间，看到是 strm 格式，不确定是不是内部的远程链接比较费时 ?
排查方式，先直接访问源服务试试，对比下耗时，以下是可能的几种原因，不一定对

1.strm 内部文本用了自定义的 / 开头的路径，这种 emby 第一次播放后不会补充入库媒体编码信息，所以每次播放都会比较慢，7-8 s 左右，播放同时也是会调 transferPlaybackInfo 的，如果是这种，目前建议改为 strm 内部文本为 emby 官方文档的形式，即 http 协议的直链

2.如果对比源服务包括首页展现也很慢，超过 10 s 的这种，同时媒体库内容太多，可以尝试优化 emby 的数据库性能，具体参照
https://github.com/bpking1/embyExternalUrl/blob/main/emby2Alist/README.md#2024-04-11

**Comment by NickLuo21** [comment]
> 这个时间确实太长了，正常只在 20-200 ms 间，看到是 strm 格式，不确定是不是内部的远程链接比较费时 ? 排查方式，先直接访问源服务试试，对比下耗时，以下是可能的几种原因，不一定对
> 
> 1.strm 内部文本用了自定义的 / 开头的路径，这种 emby 第一次播放后不会补充入库媒体编码信息，所以每次播放都会比较慢，7-8 s 左右，播放同时也是会调 transferPlaybackInfo 的，如果是这种，目前建议改为 strm 内部文本为 emby 官方文档的形式，即 http 协议的直链
> 
> 2.如果对比源服务包括首页展现也很慢，超过 10 s 的这种，同时媒体库内容太多，可以尝试优化 emby 的数据库性能，具体参照 https://github.com/bpking1/embyExternalUrl/blob/main/emby2Alist/README.md#2024-04-11

感谢大佬解答，我这边确实是生成的本地路径的strm，strm文件里面是一个文件路径不是http开头的直链，我换成http直链试试看
