### ISSUE TITLE
Plex直链成功，但播放内容串了

### ISSUE THREAD

**Issue by mymoonyue** [bpking1/embyExternalUrl#205]
播放一个视频1后，再播放其他视频2实际上还是之前的视频1。要过一段时间后重新播放才是视频2，然后再播放视频3 也还是视频2。

是缓存的原因还是啥呀

**Comment by chen3861229** [comment]
抱歉，漏掉了播放还有个一样 URL 的路径 location ~* /video/:/transcode/universal/start
确实脚本中的缓存直链原因，暂时可以先关闭一下，我这边之后修复一下,
假如是默认的拆分后配置文件，改 plex2Alist\nginx\conf.d\config\constant-pro.js，
改完重启下 nginx
```js
// 路由缓存配置
const routeCacheConfig = {
  // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
  // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
  enable: false,
  // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
  enableL2: false,
  // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
  // plex uri 唯一
  keyExpression: "r.uri", // "r.uri:r.args.X-Plex-Client-Identifier"
};
```

**Comment by mymoonyue** [comment]
> 抱歉，漏掉了播放还有个一样 URL 的路径 location ~* /video/:/transcode/universal/start 确实脚本中的缓存直链原因，暂时可以先关闭一下，我这边之后修复一下, 假如是默认的拆分后配置文件，改 plex2Alist\nginx\conf.d\config\constant-pro.js， 改完重启下 nginx
> 
> ```js
> // 路由缓存配置
> const routeCacheConfig = {
>   // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
>   // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
>   enable: false,
>   // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
>   enableL2: false,
>   // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
>   // plex uri 唯一
>   keyExpression: "r.uri", // "r.uri:r.args.X-Plex-Client-Identifier"
> };
> ```

感谢回复，另外想问下后面要怎么更新呢，直接全部替换然后重新配置嘛

**Comment by mymoonyue** [comment]
> 这个主要看代码改动大不大了，如果不是很大，单独替换变化的文件就行了，配置项之类的不用动， 现阶段应该不会有太大变化了，假如变动太大，contans 之类的可以直接覆盖新代码的空配置，不过还是一定注意备份下之前的文件，还有一种是使用合作者构建的 docker 容器，可能会简单点儿 https://github.com/thsrite/MediaLinker?tab=readme-ov-file

好嘞感谢！

**Comment by chen3861229** [comment]
已做修复
a9fb3076ae72ebb2684e546f6271d9eed47b1ef1

1.替换下
plex2Alist\nginx\conf.d\common\util.js

2.更改下 routeCacheConfig 的 keyExpression
```js
// 路由缓存配置
const routeCacheConfig = {
  // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
  // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
  enable: true,
  // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
  enableL2: false,
  // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
  keyExpression: "r.uri:r.args.path:r.args.mediaIndex:r.args.partIndex", //"xxx:r.args.X-Plex-Client-Identifier"
};
```

**Comment by mymoonyue** [comment]
> 已做修复 [a9fb307](https://github.com/bpking1/embyExternalUrl/commit/a9fb3076ae72ebb2684e546f6271d9eed47b1ef1)
> 
> 1.替换下 plex2Alist\nginx\conf.d\common\util.js
> 
> 2.更改下 routeCacheConfig 的 keyExpression
> 
> ```js
> // 路由缓存配置
> const routeCacheConfig = {
>   // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
>   // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
>   enable: true,
>   // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
>   enableL2: false,
>   // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
>   keyExpression: "r.uri:r.args.path:r.args.mediaIndex:r.args.partIndex", //"xxx:r.args.X-Plex-Client-Identifier"
> };
> ```

好的，老哥效率杠杠的
