### ISSUE TITLE
请教一下关于PlaybackInfo直链播放IPTV的原理

### ISSUE THREAD

**Issue by yugoai** [bpking1/embyExternalUrl#209]
我想要实现客户端直接播放IPTV源，然而当点击IPTV播放的时候，客户端只请求了一条PlaybackInfo 然后就一直等待Emby服务器了，服务器内部在和IPTV的源在通讯。并没有触发客户端走location ~* /videos/(.*)/live {和 location ~* /videos/(.*)/master { 块处理。看到代码里面处理了PlaybackInfo相关操作，不太理解是什么原理，求教大佬！！

**Comment by chen3861229** [comment]
> 服务器内部在和IPTV的源在通讯
1.这个是正常的，查询源服务的 PlaybackInfo 接口才能拿到一些信息，源服务这个过程中会去获取 IPTV 的源信息，感觉是这个 IPTV 源响应太慢或者失效了，有用源媒体服务试过播放吗？

> 并没有触发客户端走location
2.这个就是 1 中问题卡住了，导致没有走后续接口了

> 不太理解是什么原理
3.PlaybackInfo 这个里边的处理更多还是强制修改直接播放的服务端判断结果的，不过确实少量有一段直播的 location 路由处理,
完整流程是客户端发出 PlaybackInfo 请求到达 nginx 的 location ~* /Items/(.*)/PlaybackInfo 上，js 中的 transferPlaybackInfo 发送子请求到源服务(也就是实现反代，只请求了一次，没有多余请求，因为没走 nginx.conf 的 proxy_pass 反代实现)，然后 PlaybackInfo 请求到达源媒体服务内部处理，NJS 实例等待返回结果(nginx 整体的超时时间这边并没有进行配置，从其他人 issus 中得知 nginx 全局默认 60s 超时)，所以你的情况大概率是卡在这一步了，响应等待失败会回退到源服务处理，其实这种失败情况还是把 PlaybackInfo 到源服务走了一遍，也同样会卡住，根本原因还是源服务对这个 IPTV 地址的有效性不行，还有一种失败是源服务响应回的非 200 状态失败，这种 NJS 会传递源服务的失败结果给客户端，源服务影响成功的状态后，才会走 transferPlaybackInfo => modifyDirecPlayInfo 中 source.IsInfiniteStream 判断编辑播放链接以匹配 location ~* /videos/(.*)/master 块，然后就是 embyLive.directLive 中 302 到直播 IPTV 源地址的处理了

**Comment by yugoai** [comment]
> > 服务器内部在和IPTV的源在通讯
> 
> 1.这个是正常的，查询源服务的 PlaybackInfo 接口才能拿到一些信息，源服务这个过程中会去获取 IPTV 的源信息，感觉是这个 IPTV 源响应太慢或者失效了，有用源媒体服务试过播放吗？
> 
> > 并没有触发客户端走location
> 
> 2.这个就是 1 中问题卡住了，导致没有走后续接口了
> 
> > 不太理解是什么原理
> 
> 3.PlaybackInfo 这个里边的处理更多还是强制修改直接播放的服务端判断结果的，不过确实少量有一段直播的 location 路由处理, 完整流程是客户端发出 PlaybackInfo 请求到达 nginx 的 location ~* /Items/(._)/PlaybackInfo 上，js 中的 transferPlaybackInfo 发送子请求到源服务(也就是实现反代，只请求了一次，没有多余请求，因为没走 nginx.conf 的 proxy_pass 反代实现)，然后 PlaybackInfo 请求到达源媒体服务内部处理，NJS 实例等待返回结果(nginx 整体的超时时间这边并没有进行配置，从其他人 issus 中得知 nginx 全局默认 60s 超时)，所以你的情况大概率是卡在这一步了，响应等待失败会回退到源服务处理，其实这种失败情况还是把 PlaybackInfo 到源服务走了一遍，也同样会卡住，根本原因还是源服务对这个 IPTV 地址的有效性不行，还有一种失败是源服务响应回的非 200 状态失败，这种 NJS 会传递源服务的失败结果给客户端，源服务响应成功的状态后，才会走 transferPlaybackInfo => modifyDirecPlayInfo 中 source.IsInfiniteStream 判断编辑播放链接以匹配 location ~* /videos/(._)/master 块，然后就是 embyLive.directLive 中 302 到直播 IPTV 源地址的处理了
> 
> 更新了 FAQ 文档，大致内容相同 https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#23%E6%92%AD%E6%94%BE%E6%B5%81%E7%A8%8B%E8%A7%A3%E6%9E%90

感谢回复，的确是我的IPTV源在Emby服务器无法访问造成的，IPTV是我内网搭建的一个源，我原本是想测试直接让Emby服务器返回源的Path（内网IP）给播放器直接播放IPTV源，看来Emby服务器要先自己访问成功才能继续后面的操作。现在我映射到外网可以用了。
