### ISSUE TITLE
请问大佬如何设置图片缓存

### ISSUE THREAD

**Issue by bjzhili** [bpking1/embyExternalUrl#211]
我在映射目录embyCache下看不到任何图片缓存文件，文件夹目录为空。这样每次在新设备上访问emby就造成硬盘炒豆子声。我的docker是用固态部署的，如果能将图片缓存到embyCache目录下我的hc550硬盘就不会炒豆子了？希望大佬指导！

**Comment by chen3861229** [comment]
很有可能是目录权限不够，试下
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

**Comment by chen3861229** [comment]
很有可能是目录权限不够，试下
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

**Comment by bjzhili** [comment]
容器是用root运行的。谢谢我仔细阅读下。
