### ISSUE TITLE
有没有可能搞一个青春版

### ISSUE THREAD

**Issue by intheshell2077** [bpking1/embyExternalUrl#214]
冒昧问一句，未来可不可以搞一个仅包含实现直链相关功能的独立的配置哦，类似青春版。其实原始需求就是通过njs+alist的使用，让Plex/Emby支持直链播放。这怎么还越搞越复杂了呢。譬如我现在遇到的难题是：我已经有了自己的nginx配置，我不想要其他的配置，只想单独把直链这部分实现搞到我自己的配置中，这就变得难上加难了...

感谢你的分享。

**Comment by chen3861229** [comment]
这个其实分支开起来不难，但是维护起来比较麻烦，而且稍微有些没必要，其实相较于 bpking1 大佬的最初版本，只是加了些细节上的修复，总体变化不算太大，全部默认配置的情况下也还是走直链的，不会有转码的情况，后边加的所有配置基本都是可选项，根据你的需求，其实只用关注这两个配置文件就行了，和之前的是一样的，其余的复制过去不用改它们
```
emby2Alist\nginx\conf.d\constant.js
emby2Alist\nginx\conf.d\config\constant-mount.js
```

**Comment by intheshell2077** [comment]
我尝试把这个融合到我的nginx配置中，出现了一些报错，集中在这里：plex2Pan.plexApiHandler，请问这个plexApiHandler是做啥的，我看大部分请求都被这个拦截了

**Comment by intheshell2077** [comment]
页面都出不来了，nginx log一直出现如下错误：


2024/06/18 11:05:59 [error] 38#38: *16 too big subrequest response: 72481 while sending to client, client: 172.71.210.16, server: plex.org, request: "GET /library/sections/14/all?type=2&sort=episode.addedAt%3Adesc&includeCollections=1&includeExternalMedia=1&includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.129.1&X-Plex-Client-Identifier=u6m0a4og7ckrxx15vrk0nq6p&X-Plex-Platform=Safari&X-Plex-Platform-Version=16.6&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Name=Safari&X-Plex-Device-Screen-Resolution=1440x795%2C1440x900&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=uuyRrQZTyovwDfhULsG3&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=fairplay&X-Plex-Language=en HTTP/2.0", subrequest: "/library/sections/14/all", upstream: "http://127.0.0.1:32400/library/sections/14/all?type=2&sort=episode.addedAt%3Adesc&includeCollections=1&includeExternalMedia=1&includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.129.1&X-Plex-Client-Identifier=u6m0a4og7ckrxx15vrk0nq6p&X-Plex-Platform=Safari&X-Plex-Platform-Version=16.6&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Name=Safari&X-Plex-Device-Screen-Resolution=1440x795%2C1440x900&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=xxx&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=fairplay&X-Plex-Language=en", host: "plex.org", referrer: "https://plex.org/web/index.html"

2024/06/18 11:05:59 [error] 38#38: *16 pending events while closing request, client: 172.71.210.16, server: 0.0.0.0:4432024/06/18 11:05:59 [error] 38#38: *16 too big subrequest response: 72481 while sending to client, client: 172.71.210.16, server: plex.org, request: "GET /library/sections/14/all?type=2&sort=episode.addedAt%3Adesc&includeCollections=1&includeExternalMedia=1&includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.129.1&X-Plex-Client-Identifier=u6m0a4og7ckrxx15vrk0nq6p&X-Plex-Platform=Safari&X-Plex-Platform-Version=16.6&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Name=Safari&X-Plex-Device-Screen-Resolution=1440x795%2C1440x900&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=uuyRrQZTyovwDfhULsG3&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=fairplay&X-Plex-Language=en HTTP/2.0", subrequest: "/library/sections/14/all", upstream: "http://127.0.0.1:32400/library/sections/14/all?type=2&sort=episode.addedAt%3Adesc&includeCollections=1&includeExternalMedia=1&includeAdvanced=1&includeMeta=1&X-Plex-Product=Plex%20Web&X-Plex-Version=4.129.1&X-Plex-Client-Identifier=u6m0a4og7ckrxx15vrk0nq6p&X-Plex-Platform=Safari&X-Plex-Platform-Version=16.6&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=bundled&X-Plex-Device=OSX&X-Plex-Device-Name=Safari&X-Plex-Device-Screen-Resolution=1440x795%2C1440x900&X-Plex-Container-Start=0&X-Plex-Container-Size=50&X-Plex-Token=xxx&X-Plex-Provider-Version=6.5&X-Plex-Text-Format=plain&X-Plex-Drm=fairplay&X-Plex-Language=en", host: "plex.org", referrer: "https://plex.org/web/index.html"

2024/06/18 11:05:59 [error] 38#38: *16 pending events while closing request, client: 172.71.210.16, server: 0.0.0.0:443

**Comment by chen3861229** [comment]
> 2024/06/18 11:05:59 [error] 38#38: *16 too big subrequest response: 72481 while sending to client, client: 172.71.210.16, server: plex.org, request: "GET /library/sections/14/all?

这行日志已经很清晰了，确认下 plex.conf 中这个参数的大小，nginx 的默认值是很小的，只有 4KB / 8KB
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/6ce52b7e-ed99-4087-86b6-ec71fedbc118)

**Comment by intheshell2077** [comment]
修改了这个，页面可以载入了，但是无法播放。log里面频繁见到如下错误：

js: plexApiHandler subrequest failed, status: 404
js exception: Error: unhandled promise rejection: TypeError: cannot get property "get" of undefined
    at redirect2Pan (/etc/nginx/njs-script/plex.js:35)

plex.js 35行这里是这句：cachedLink = ngx.shared[routeDictKey].get(cacheKey);

另外，我其实不太理解为什么要发起那么多的子请求，这样真的不会影响nginx的性能和效率吗，还有，你之前说的，part对象，/metadata/这个请求里面，不是可以直接拿到具体的视频挂在路径么。

**Comment by intheshell2077** [comment]
顺便说一下我的使用方式，不确定是否使用正确，引用如下：

njs文件
constant-all.js （只修改这里面的参数）
events.js
periodics.js
util.js
plex.js

conf文件
plex.conf
我将PlexMediaServer从Start到End之间的配置，加到我自己的conf中，同时增加了subrequest_output_buffer_size设置
