### ISSUE TITLE
播放记录没有记具体的时间问，一个视频只要点开后关闭下次就直接显示已观看了

### ISSUE THREAD

**Issue by NickLuo21** [bpking1/embyExternalUrl#216]
如题，不知道你们有没有碰到过这个问题；走nginx代理的时候任何视频只要点开后，不管看了多久关闭后就显示已观看完了，不会记录到这个视频的具体观看到的时间点。
但是如果不走nginx代理，直接连emby端口的话是可以记录到这个视频的观看时间点

**Comment by NickLuo21** [comment]
视频信息是用是strm文件记录，测试使用8096端口可以记录到具体的播放时间点

**Comment by NickLuo21** [comment]
strm文件里记录的是本地文件路径，以"/"开头

**Comment by wjt0321** [comment]
您解决这个问题了么？我也遇到了，同样是strm文件
