### ISSUE TITLE
怎么把strm文件内部地址转为cd2地址播放

### ISSUE THREAD

**Issue by NASA0719** [bpking1/embyExternalUrl#225]
感谢大佬的项目，有个问题咨询下，
  strm地址为`http://10.0.0.2:5678/d/`播放正常，现在想转为`http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/`开头的cd2地址播放，emby-nginx可以完成这个过程吗？如果不行就不用看后边的了。
尝试修改constant-pro.js的路径映射，修改后达到预期效果（复制修改后的地址到浏览器可以正常下载文件），但是路由规则不知道应该怎么配置，尝试配置为proxy时播放会直接使用`http://10.0.0.2:5678/d/`导致路径映射完全没生效，如果配置为redirect猜测应该是cd2不支持302所以emby直接报错`不兼容的流`，请教应该如何配置？

以下是constant-pro.js配置及分别使用proxy和redirect播放时的日志
```
const routeCacheConfig = {
  // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
  // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
  enable: false,
  // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
  enableL2: false,
  // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
  // 注意 jellyfin 是小写开头 mediaSourceId
  keyExpression: "r.uri:r.args.MediaSourceId", // "r.uri:r.args.MediaSourceId:r.args.X-Emby-Device-Id"
};
const routeRule = [
  ["redirect", "filePath", 0, "http://10.0.0.2"],
];
const embyPathMapping = [
  // [0, 2, "xiaoya.host", "10.0.0.2"],
  [0, 2, "http://10.0.0.2:5678/d", ""],
  [0, 2, /\//g, "%2F"], // 正则替换/为%2F
  [1, 2, "http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/%2FWebDAV"],
  [0, 2, / /g, "%20"], // 正则替换空格为%20
];
```
[error.log](https://github.com/user-attachments/files/15856425/error.log)

**Comment by chen3861229** [comment]
> strm地址为http://10.0.0.2:5678/d/播放正常，现在想转为http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/开头的cd2

1.假如 http://10.0.0.2:5678/d/xxx 为 strm 内部文本，可以用 embyPathMapping 来替换路径，以下需要和你已配置的合并下
emby2Alist\nginx\conf.d\config\constant-pro.js

```js
// 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const embyPathMapping = [
  [0, 2, "http://10.0.0.2:5678/d/", "http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/"], 
];
```

2.根据日志后半段来看写得没问题，strm 可以不用写 routeRule，判断是 notLocal 非本地的文件默认就是 redirect 的
```js
notLocal: true
notLocal decodeURIComponent embyRes.path
hit redirect: ["filePath",0,"http://10.0.0.2"]
getRouteMode: redirect
```

> 如果配置为redirect猜测应该是cd2不支持302所以emby直接报错不兼容的流

3.这个理解错了，此处的 redirect 是相对本脚本的 nginx 来说的，也就是响应一个 302 重定向到目标地址去，和 CD2 的网盘直链 302 稍微有些区别，和这个无关

4.根据日志后半段，其实已经按你的预期结果成功了，这个看起来这个是一个局域网地址，该客户端测试时是处于同局域网下吗？虽然你的描述好像是同局域网下且链接畅通，还有可能是浏览器不支持这个媒体编码格式的播放，可以换用局域网下的客户端试一下
> 修改后达到预期效果（复制修改后的地址到浏览器可以正常下载文件）

```js
redirect to: http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/%2FWebDAV%2F🈴我的阿里分享%2F电影%2F坚如磐石（2023）%2FUnder.The.Light.2023.1080p.BluRay.REMUX.AVC.DTS-HD.MA.TrueHD.5.1.mkv
```

**Comment by NASA0719** [comment]
> > strm地址为[http://10.0.0.2:5678/d/播放正常，现在想转为http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/开头的cd2](http://10.0.0.2:5678/d/%E6%92%AD%E6%94%BE%E6%AD%A3%E5%B8%B8%EF%BC%8C%E7%8E%B0%E5%9C%A8%E6%83%B3%E8%BD%AC%E4%B8%BAhttp://10.0.0.2:19798/static/http/10.0.0.2:19798/False/%E5%BC%80%E5%A4%B4%E7%9A%84cd2)
> 
> 1.假如 http://10.0.0.2:5678/d/xxx 为 strm 内部文本，可以用 embyPathMapping 来替换路径，以下需要和你已配置的合并下 emby2Alist\nginx\conf.d\config\constant-pro.js
> 
> ```js
> // 路径映射,会在 xxxMountPath 之后从上到下依次全部替换一遍,不要有重叠
> // 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const embyPathMapping = [
>   [0, 2, "http://10.0.0.2:5678/d/", "http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/"], 
> ];
> ```
> 
> 2.根据日志后半段来看写得没问题，strm 可以不用写 routeRule，判断是 notLocal 非本地的文件默认就是 redirect 的
> 
> ```js
> notLocal: true
> notLocal decodeURIComponent embyRes.path
> hit redirect: ["filePath",0,"http://10.0.0.2"]
> getRouteMode: redirect
> ```
> 
> > 如果配置为redirect猜测应该是cd2不支持302所以emby直接报错不兼容的流
> 
> 3.这个理解错了，此处的 redirect 是相对本脚本的 nginx 来说的，也就是响应一个 302 重定向到目标地址去，和 CD2 的网盘直链 302 稍微有些区别，和这个无关
> 
> 4.根据日志后半段，其实已经按你的预期结果成功了， ~这个看起来这个是一个局域网地址，该客户端测试时是处于同局域网下吗？虽然你的描述好像是同局域网下且链接畅通，还有可能是浏览器不支持这个媒体编码格式的播放，可以换用局域网下的客户端试一下~
> 
> > 修改后达到预期效果（复制修改后的地址到浏览器可以正常下载文件）
> 
> ```js
> redirect to: http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/%2FWebDAV%2F🈴我的阿里分享%2F电影%2F坚如磐石（2023）%2FUnder.The.Light.2023.1080p.BluRay.REMUX.AVC.DTS-HD.MA.TrueHD.5.1.mkv
> ```
> 
> 5.已确认是我这边代码问题，中文编码问题，正在修复中

感谢回复
1.路径映射这块可能是cd2比较特殊，不能像你给的这样直接替换开头，无需关注
2.又测试了下，把这段中的10.去掉然后用客户端播放正常，
```
const strHead = {
  lanIp: ["172.", "10.", "192.", "xiaoya.host", "[fd00:"], // 局域网ip头
  "115": "115.com",
  ali: "aliyundrive.net",
};
```
如果不去掉日志报错如下
```
2024/06/16 21:43:35 [warn] 319#319: *8519 js: mapped emby file path: http://10.0.0.2:19798/static/http/10.0.0.2:19798/False/%2FWebDAV%2F🈴我的阿里分享%2F电影%2F坚如磐石（2023）%2FUnder.The.Light.2023.1080p.BluRay.REMUX.AVC.DTS-HD.MA.TrueHD.5.1.mkv
2024/06/16 21:43:35 [warn] 319#319: *8519 js: filePath hit redirectStrmLastLinkRule: [[0,["http://172.","http://10.","http://192.","http://xiaoya.host","http://[fd00:"]]]
2024/06/16 21:43:35 [warn] 319#319: *8519 js: fetchStrmLastLink response.status: 404, contentType: undefined
2024/06/16 21:43:35 [error] 319#319: *8519 js: error: fetchStrmLastLink: 404 Not Found
2024/06/16 21:43:35 [warn] 319#319: *8519 js: warn: fetchStrmLastLink, not expected result, failback once
2024/06/16 21:43:35 [warn] 319#319: *8519 js: === redirect2Pan: /emby/videos/423439/stream.mkv, the NJS VM is destroyed ===
```
（有一点比较奇怪，当strm链接为alist地址时浏览器播放正常，但是如果地址映射成cd2地址时浏览器播放不了，客户端可以）

**Comment by chen3861229** [comment]
新提交应该是修复了，不要用路径映射处理 URL 的编码问题了
8da7b675c1538975ed4ee8dc08c86407417a2ac2

**Comment by chen3861229** [comment]
> 2.又测试了下，把这段中的10.去掉然后用客户端播放正常

这边变量在两个地方用到了，
emby2Alist\nginx\conf.d\config\constant-pro.js
1.这里默认是注释的，可以不用管
```js
const routeRule = [
  // docker 注意必须为 host 模式,不然此变量全部为内网ip,判断无效,nginx 内置变量不带$,客户端地址($remote_addr)
  // ["r.variables.remote_addr", 0, strHead.lanIp],
];
```
emby2Alist\nginx\conf.d\config\constant-strm.js
2.第二处确实和 strm 有关，注释这个就可以了
```js
// 指定是否转发由 njs 获取 strm 重定向后直链地址的规则,例如 strm 内部为局域网 ip 或链接需要验证
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为 xxxPathMapping 映射后的 strm 内部链接
const redirectStrmLastLinkRule = [
  // [0, strHead.lanIp.map(s => "http://" + s)],
];
```

**Comment by chen3861229** [comment]
> （有一点比较奇怪，当strm链接为alist地址时浏览器播放正常，但是如果地址映射成cd2地址时浏览器播放不了，客户端可以）

这个其实就是 URL 里有中文等特殊字符没编码导致的，alist 获取的直接是网盘商的公网直链，里边本身是没有特殊字符的，自己拼接路径的话就需要考虑和处理下了，客户端可以这个就不太清楚了，可能客户端自己做了编码的兼容吧

**Comment by NASA0719** [comment]
> 新提交应该是修复了，不要用路径映射处理 URL 的编码问题了 [8da7b67](https://github.com/bpking1/embyExternalUrl/commit/8da7b675c1538975ed4ee8dc08c86407417a2ac2)
> 
> 现在默认已经对远程链接中(notLocal: true)包含 /False/ 和 /d/ 之后的文件路径字符串进行统一的 encodeURIComponent 处理
> 
> ```js
> // 这两个应该可以去掉了
> [0, 2, /\//g, "%2F"], // 正则替换/为%2F
> [0, 2, / /g, "%20"], // 正则替换空格为%20
> // 然后这个改成
> [1, 2, "http://10.0.0.2:19798/static/http/10.0.0.2:19798/False//WebDAV"],
> ```

感谢大佬，已经正常了

**Comment by chen3861229** [comment]
是的，已经对路径部分做了编码，浏览器不行的话换个普通 h264 的 mp4 测试呢？有可能是 web 客户端的编码支持太少的问题

**Comment by NASA0719** [comment]
> 是的，已经对路径部分做了编码，浏览器不行的话换个普通 h264 的 mp4 测试呢？有可能是 web 客户端的编码支持太少的问题

试过了，也不行，还是老老实实用客户端吧
