### ISSUE TITLE
yamby无法进行302

### ISSUE THREAD

**Issue by yating1022** [bpking1/embyExternalUrl#231]
yamby的wiki原文是

如果你的服务器对播放流使用了重定向，必须要代理 emby/videos/{id}/original.xxx 路径。
在 Emby 4.8 及以上版本，Server 端会默认使用这个播放路径。

应该怎么去修改呢

**Comment by chaomarks** [comment]
可以啊，我用的旧版本的新脚本不会设置一直没换

**Comment by Katou-Kouseki** [comment]
我的新版本脚本也是正常使用的

**Comment by chen3861229** [comment]
这个很久之前我记得有 issus 提到过，确认下 emby.conf 中已经是最新版本的写法了，

# Redirect the stream to njs
location ~* /videos/(.*)/(stream|original)

**Comment by yating1022** [comment]
> 这个两个月前有 issus 提过并修复过了，确认下 emby.conf 中已经是最新版本的写法了，
> 
> ```
> # Redirect the stream to njs
> location ~* /videos/(.*)/(stream|original)
> ```
> 
> [chen3861229#23 (comment)](https://github.com/chen3861229/embyExternalUrl/issues/23#issuecomment-2049619666)

感谢大佬的指导，解决了
