### ISSUE TITLE
夸克网盘挂载到alist，反代之后不能播放，该怎么设置

### ISSUE THREAD

**Issue by 907739769** [bpking1/embyExternalUrl#232]
夸克网盘挂载到alist，反代之后不能播放，该怎么设置。115网盘的没问题。该怎么分开设置

**Comment by chen3861229** [comment]
假如使用的是拆分后的配置文件
emby2Alist\nginx\conf.d\config\constant-pro.js

填写 routeRule 路由规则来强制走 nginx 的代理中转
```js
const routeRule = [
  // 以下三选一等价，只是填写风格不同，/mnt/夸克网盘 这个需要按照自身实际情况填写入库文件的路径
  ["filePath", 0, "/mnt/夸克网盘"], 
  ["proxy", "filePath", 0, "/mnt/夸克网盘"],
  ["proxy", "走代理", "filePath", 0, "/mnt/夸克网盘"],
];
```

**Comment by 907739769** [comment]
> 假如使用的是拆分后的配置文件 emby2Alist\nginx\conf.d\config\constant-pro.js
> 
> 填写 routeRule 路由规则来强制走 nginx 的代理中转
> 
> ```js
> const routeRule = [
>   // 以下三选一等价，只是填写风格不同，/mnt/夸克网盘 这个需要按照自身实际情况填写入库文件的路径
>   ["filePath", 0, "/mnt/夸克网盘"], 
>   ["proxy", "filePath", 0, "/mnt/夸克网盘"],
>   ["proxy", "走 nginx 代理中转,这只是个进行分组的键值,类似于备注,可以随意填写", "filePath", 0, "/mnt/夸克网盘"],
> ];
> ```

我是用的生成strm文件的方式访问alist网盘的

**Comment by chen3861229** [comment]
是一样的，"filePath" 这个可能存在一定混淆，其实指的就是 emby 的入库路径，它包含文件路径和远程链接两种情况，/mnt/夸克网盘 这个你按实际情况改为 https://alist.com:5244/d/夸克网盘 类似这种就行了
