### ISSUE TITLE
115+strm+alist签名

### ISSUE THREAD

**Issue by qsd4014** [bpking1/embyExternalUrl#233]
请问一下使用115+strm+alist签名这样的组合的时候strm的直链是不带签名的。播放会出错。请问一下在不关闭alist全局签名的情况下应该怎么请求签名呢？

**Comment by hfoi589** [comment]
全局签名也关掉呗

**Comment by chen3861229** [comment]
假如是使用的拆分后的配置文件
emby2Alist\nginx\conf.d\config\constant-mount.js

alistToken 和 alistSignExpireTime 这两个需要按 alist 中的设置的进行填写
```js
// alist token, 在 alist 后台查看
const alistToken = "alsit-123456";

// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 0;
```

**Comment by qsd4014** [comment]
感谢回复，已解决，但还有一个问题是
