### ISSUE TITLE
字幕缓存疑似失效

### ISSUE THREAD

**Issue by Katou-Kouseki** [bpking1/embyExternalUrl#240]
脚本和服务端均更新至最新版本，字幕缓存疑似失效，subtitles文件夹下没有任何内容

emby版本：4.9.0.25

**Comment by Katou-Kouseki** [comment]
今天尝试重启了一轮机器就正常了（尴尬），昨天开发者工具看网络标签中stream.ass一直卡在挂起

**Comment by chen3861229** [comment]
测试了下，字幕这块和之前是一样的，没变化，location ~* /videos/(.*)/Subtitles 也是可以命中新 API 样式匹配的，
建议排查下缓存目录的权限设置，当然如果图片缓存正常就不用排查了，

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

![1719149797522](https://github.com/bpking1/embyExternalUrl/assets/42368856/2450f3f5-990c-4df6-898c-b349c5e6a192)
![1719149973574](https://github.com/bpking1/embyExternalUrl/assets/42368856/8720bcb7-2d85-4f92-aab8-6034de07d45f)
![1719150019604](https://github.com/bpking1/embyExternalUrl/assets/42368856/41b8508b-06aa-4936-8157-d938016e456b)

这块缓存因为是之前合作者添加的，暂时不太清楚细分情况下的工作逻辑，从当前这个 beta 版的测试情况来说，其实和之前 4.8 的逻辑一致

1.内封(内挂)的软字幕，从浏览器控制台看到是偶尔会请求失败，这个 4.8 之前的稳定版也是这样的，内封字幕的 emby 提取和服务端转码设置中的 允许实时提起字幕 这个选项有关，暂不清楚是什么原因，但是浏览器播放字幕是正常的，猜测有可能是 emby 自身代码的问题

2.上图中的是，外挂软字幕，这个是正常缓存工作的

**Comment by chen3861229** [comment]
> 今天尝试重启了一轮机器就正常了（尴尬）

这种是正常情况，不是误判，我之前也遇到过，是挂载工具挂了，导致 emby 读取不到 alist 上的字幕文件，所以播放起来就是没字幕加载了，需要先重启挂载工具(CD2)，等确认目录挂载没问题了，再重启 emby 服务端就是正常的了，其实不用重启机器，虽然我之前不清楚原因也是直接重启 NAS 的

**Comment by Katou-Kouseki** [comment]
> > 今天尝试重启了一轮机器就正常了（尴尬）
> 
> 这种是正常情况，不是误判，我之前也遇到过，是挂载工具挂了，导致 emby 读取不到 alist 上的字幕文件，所以播放起来就是没字幕加载了，需要先重启挂载工具(CD2)，等确认目录挂载没问题了，再重启 emby 服务端就是正常的了，其实不用重启机器，虽然我之前不清楚原因也是直接重启 NAS 的

感谢大佬的解答。我这边是通过rclone挂载的，下次再遇到尝试重启rclone试试。另外我这边播放时外挂字幕似乎会存在一定的延迟，这个现象普遍存在吗。

**Comment by chen3861229** [comment]
1.重启rclone后一定注意需要再重启 emby 才会正常的
2.外挂字幕延迟这个是 emby 官方客户端是这样设计的延迟加载，是正常的，播放成功后才会发起字幕的异步请求，所以存在延迟，因为 emby 没考虑过挂载的这个情况，它只支持本地文件系统的，正常本地文件系统也就 1s 的延迟可以忽略不记

**Comment by Katou-Kouseki** [comment]
> 1.重启rclone后一定注意需要再重启 emby 才会正常的 2.外挂字幕延迟这个是 emby 官方客户端是这样设计的延迟加载，是正常的，播放成功后才会发起字幕的异步请求，所以存在延迟，因为 emby 没考虑过挂载的这个情况，它只支持本地文件系统的，正常本地文件系统也就 1s 的延迟可以忽略不记

原来如此，了解了😂
