### ISSUE TITLE
请问，使用音流这软件播放音乐，无法实现直链播放，是这个软件的问题还是我少操作了哪一步？

### ISSUE THREAD

**Issue by xinxuxu** [bpking1/embyExternalUrl#241]
emby客户端都没问题，就是和音乐有关的第三方都强行走服务器流量

**Comment by chen3861229** [comment]
这里记录下 ，棉花音乐的调用日志
<details> 
    <summary>access.log</summary>
    ```
    "GET /emby/Audio/311791/universal?EnableRedirection=true&PlaySessionId=1719146819159&api_key=xxx&UserId=ac0d220d548f43bbb73cf9b44b2ddf0e&DeviceId=3b2bbf9e7582a461&MaxStreamingBitrate=944999 HTTP/1.1" 302 138 "-" "okhttp/4.12.0" "-"
"GET /emby/Audio/311791/universal?EnableRedirection=true&PlaySessionId=1719146824194&api_key=xxx&UserId=ac0d220d548f43bbb73cf9b44b2ddf0e&DeviceId=3b2bbf9e7582a461&MaxStreamingBitrate=944999 HTTP/1.1" 302 138 "-" "okhttp/4.12.0" "-"
"GET /emby/Audio/310077/universal?EnableRedirection=true&PlaySessionId=1719146818174&api_key=xxx&UserId=ac0d220d548f43bbb73cf9b44b2ddf0e&DeviceId=3b2bbf9e7582a461&MaxStreamingBitrate=944999 HTTP/1.1" 302 138 "-" "Lavf/58.12.100" "-"
"GET /Items/310077/66b6a4c443d77ec686738f657bdf67fa/Subtitles/2/Stream.lrc HTTP/1.1" 200 0 "-" "Ktor client" "-"
"GET /emby/Audio/310077/universal?EnableRedirection=true&PlaySessionId=1719146828192&api_key=xxx&UserId=ac0d220d548f43bbb73cf9b44b2ddf0e&DeviceId=3b2bbf9e7582a461&MaxStreamingBitrate=944999 HTTP/1.1" 302 138 "-" "okhttp/4.12.0" "-"

    ```
</details>

**Comment by xinxuxu** [comment]
大佬，感谢及时修复，不过更新后，音流大部分歌曲都播不了，只剩下寥寥几首可以播（看流量走直链了），都是alist挂的天翼

**Comment by xinxuxu** [comment]
应该还是音流这个软件的问题，我用了另外一个支持emby音乐的app，symfonium这软件，一切正常

**Comment by chen3861229** [comment]
音流 安卓APP 我这边用的最新版 1.2.9，网盘是微软 OneDrive , 音流的两个连接模式(默认/直连，不清楚有啥区别，我看 emby API 的调用是一样的)都试了，没啥问题，唯一的问题是它默认播放的时候会获取下一首歌的数据，也就是会同时加载两首歌，所以会分别走两首歌的 alist 直链查询，不知道是不是两首加起来的查询时间过慢了，导致偶发性(我这边概率较小)的播放失败，也就是 UI 界面的歌曲时长是 0，点击另外一首再且切换点击回来就偶尔会正常，极大概率是 音流 内部有请求超时的限制，我是 OneDrive，alist  
 第一首，1580ms，第二首，399ms， 我这边基本都是 200ms - 2000ms 之间

**Comment by gitbobobo** [comment]
默认和直连不会影响播放功能。

刚才又验证了一次，开始缓存下一首歌的时机是当前歌曲缓存完成之后，并不会说同时请求两首歌的数据。

<img width="911" alt="image" src="https://github.com/user-attachments/assets/2e100ab3-7700-4791-8dee-05faf85defed">

> 调试模式，限制了网速（没有走直链，nas里的歌曲）

**Comment by gitbobobo** [comment]
目前我也不能肯定一定不是音流的问题，毕竟其他客户端都可以正常播放。

这个直链环境好搞吗，我想在本地搞一个测测看？我目前是docker装的emby，如果用你的插件的话，怎样会比较简单一点？

**Comment by chen3861229** [comment]
多谢作者了，最简单我感觉应该是合作者构建的 docker 容器，https://github.com/thsrite/MediaLinker?tab=readme-ov-file

不过都是有两个依赖项，
1.alist , 这个对接不同的网盘商，nginx 劫持播放请求重定向到直链上查询过程需要，可以和 emby server 不在同一台机器上

2.挂载工具，rclone / cd2 ,建议 CloudDrive2 免费版挂载一个 alist 的 webDAV 够用了，好处有 web 控制台，任务面板，这个是给 emby / jellyfin / plex 等不支持 webDAV 路径入库方式的服务做的本地文件系统兼容层，需要和 emby server 在同一个机器上，rclone / cd2 都有对应的 docker 容器版本

然后下面就是此脚本的配置项了，
3.rclone / cd2 + alist 的情况下，默认仅需配置两个拆分后的配置文件就够了，其它拆分后的配置文件可以保持默认，
以下是个人日常使用的最小配置集合

emby2Alist\nginx\conf.d\constant.js
```js
// 必填项,根据实际情况修改下面的设置

// 这里默认 emby/jellyfin 的地址是宿主机,要注意 iptables 给容器放行端口
const embyHost = "http://192.168.31.200:8096";

// emby/jellyfin api key, 在 emby/jellyfin 后台设置
const embyApiKey = "f839390f50a648fd92108bc11ca6730a";

// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = ["/AList"];
```
emby2Alist\nginx\conf.d\config\constant-mount.js
```js
// 选填项,用不到保持默认即可

// rclone/CD2 挂载的 alist 文件配置,根据实际情况修改下面的设置
// 访问宿主机上 5244 端口的 alist 地址, 要注意 iptables 给容器放行端口
const alistAddr = "http://mydomain:5244";

// alist token, 在 alist 后台查看
const alistToken = "alsit-123456";

// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 0;

// alist 公网地址,用于需要 alist server 代理流量的情况,按需填写
const alistPublicAddr = "http://mydomain:5244";

// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
// ,有分组时不可省略填写,可为表达式
// 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
// 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const clientSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
  // 优先使用 filePath,可省去一次查询 alist,如驱动为 alias,则应使用 alistRes
  // ["115-local", "filePath", 0, "/mnt/115", alistPublicAddr],
  // ["115-local", "r.args.X-Emby-Client", 0, strHead.xEmbyClients.seekBug], // 链接入参,客户端类型
  // ["115-alist", "alistRes", 2, strHead["115"], alistPublicAddr],
  // ["115-alist", "r.args.X-Emby-Client", 0, strHead.xEmbyClients.seekBug],
];
```

**Comment by gitbobobo** [comment]
感谢指导，看起来好麻烦的样子，我有空试试

最近有两个用户为我提供了直链的测试账号，不过都是navidrome的，感觉原理应该是一样的。

之前音流对302响应的处理确实有些问题，不过测试版已经处理了，只剩下一种非标准的302响应我这里暂时无法处理，就是 302 响应头的 Location 地址，值如果是中文的，会导致重定向时URL乱码，这里只能服务端返回值时先把 location 的值用 URL Encode 一下，这是对应的 [issue](https://github.com/gitbobobo/StreamMusic/issues/495)

这个问题是由于 [dart 中的网络请求遵循标准的http协议](https://github.com/dart-lang/http/issues/227)，并未对历史遗留的非标准行为做兼容导致的问题，我这里无法接管解码响应头的逻辑，所以目前只能由服务端处理一下。

不确定你这里是否是因为偶然播放到携带中文路径的歌曲才导致无法播放的

**Comment by chen3861229** [comment]
1.多谢开发者积极适配，看到新支持了安卓 TV 模式，很不错，已经下载安卓和 windows 1.3.1 测试版进行了验证，确认没问题了

> 不过都是navidrome的，感觉原理应该是一样的

2.302 重定向的原理确实是一样的

> 只剩下一种非标准的302响应我这里暂时无法处理，就是 302 响应头的 Location 地址，值如果是中文的，会导致重定向时URL乱码，这里只能服务端返回值时先把 location 的值用 URL Encode 一下

3.个人建议不要兼容这种非标准的了，会产生一些规范误解之类的，假如是返回的一段文本或 json 中的字段倒是可以 URL Encode 一下，网址和 302 响应头的 Location 地址，确实是让服务端返回编码后的处理最合适的

> 不确定你这里是否是因为偶然播放到携带中文路径的歌曲才导致无法播放的

4.这边默认的话应该不会出现这种带中文的情况，不过也如 3 中提到的，不知道是不是用户开启了 `useRealFileName` 导致的，开启这个确实会把真实文件名中的中文带进去，无 URL Encode 当初是为了方便播放器显示标题用的，这个配置项确实加得很没必要且破坏了网址的规范性，之后将在 FAQ 中强调一下

```js
// 串流配置
const streamConfig = {
  // 启用后将修改直接串流链接为真实文件名,方便第三方播放器友好显示和匹配,
  // 默认不启用,可能存在兼容问题,如发现原始链接代理失败,请关闭此选项,
  // 该选项只对 emby 有用, jellyfin 为前端自行拼接的
  useRealFileName: false,
};
```

**Comment by icezxf** [comment]
大佬 针对navidrome能不能也出一个配置啊 我的音乐都是刮削好的 emby直接读取也读不出来
