### ISSUE TITLE
如何防止局域网环境下，使用官方app时，服务器地址变回直连地址呢？

### ISSUE THREAD

**Issue by Putarku** [bpking1/embyExternalUrl#243]
例如我的直链端口是8095，在局域网内连接上以后，是可以正常获取直链播放的。但重启app以后，服务器地址的端口又会自动变回8096，导致播放网盘文件都需要emby上走一圈。直接的影响就是局域网内播放直链的影视，启播速度会明显比用直链接口的速度慢。

而其他第三方客户端例如infuse、fileball、yamby均不会自动改变服务端地址，可以一直用直链端口8095

**Comment by chen3861229** [comment]
可以参照文档试一下，原理是掐断官方客户端默认且强制的局域网发现(UDP广播)功能

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#19%E5%B1%80%E5%9F%9F%E7%BD%91%E4%B8%8B%E5%8F%AF%E8%83%BD%E5%AD%98%E5%9C%A8%E7%BB%95%E8%BF%87-nginx-%E5%A4%84%E7%90%86%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by Putarku** [comment]
测试了一下，只需要在服务端-网络里面，将`本地IP地址`改成随便一个别的IP就可以避免该问题了。
![image](https://github.com/bpking1/embyExternalUrl/assets/66679443/fa2a5a51-93d7-45b2-9c1f-d757d8ef2055)
