### ISSUE TITLE
emby走直链播视频成功但有2个问题，“家庭视频与照片”类型媒体库中图片都无法打开，“书籍”类媒体库的pdf文件无法下载

### ISSUE THREAD

**Issue by LiYefei** [bpking1/embyExternalUrl#244]
【“家庭视频与照片”类型媒体库中图片都无法打开】
就是放一大堆图片的目录，全部是裂开的小图标，其中个别是视频文件是能打开的

【“书籍”类媒体库的pdf文件无法下载】
这个估计没什么人用，emby对书籍暂时只提供下载能力，但按教程配置直链后这块下载失败了

**Comment by LiYefei** [comment]
对了，我alist挂的115网盘，试的安卓手机，用官方emby客户端或者chrome浏览器都有问题

**Comment by chen3861229** [comment]
1.这个是 nginx 缓存的目录权限不够，图片和部分的字幕是走了缓存的，二选一方案，如果图片大多在网盘中，建议方案 1.1 

1.1 给缓存目录相应的权限https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

1.2 单独禁用掉图片缓存
#226

2.这个需要我找个 pdf 先测试下了，确实没人入库这个类型的

**Comment by LiYefei** [comment]
2.2问题解决了
1问题还在，目前确定error日志没有权限问题的打印，我也按1.2操作，重启nginx，清安卓APP数据后问题依旧，我再看看

**Comment by LiYefei** [comment]
1问题在关闭缓存后也解决了，刚才看着好像没解决是因为CD2的挂载不知道怎么挂了，重新挂上就好了
