### ISSUE TITLE
有些视频为什么不能播放呢？

### ISSUE THREAD

**Issue by lw6644700** [bpking1/embyExternalUrl#246]
有些视频打开一直转圈圈不会播放，但是视频确定是好的，不直链的话是可以播放的，比如下面日志的两个文件，第一个文件是能播放的，第二个是不能播放转圈的，我看有个提示Property "MediaSourceId" not found in object,will ignore，是这个的问题吗？要怎么处理啊？

/PlaybackInfo, the NJS VM is destroyed ===
2024/06/27 13:49:05 [warn] 19#19: *2880 js: redirect2Pan, UA: Infuse-Direct/7.8
2024/06/27 13:49:05 [warn] 19#19: *2880 js: itemInfoUri: http://172.17.0.2:8096/Items?Ids=ba1228a4bd9f3abc1521a1afbe1ab40a&Fields=Path,MediaSources&Limit=1&api_key=a207b7ce7fa3478985d64254d9c784a7
2024/06/27 13:49:05 [warn] 19#19: *2880 js: 4ms, fetchEmbyFilePath async function cost
2024/06/27 13:49:05 [warn] 19#19: *2880 js: notLocal: false
2024/06/27 13:49:05 [warn] 19#19: *2880 js: mount emby file path: /mnt/cd2/115/璧勬簮/鍔ㄦ极/涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016)/Season 3/涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016) - S03E01 - 绗?闆?mkv
2024/06/27 13:49:05 [warn] 19#19: *2880 js: getRouteMode: redirect
2024/06/27 13:49:05 [warn] 19#19: *2880 js: embyPathMapping: [[0,0,"/mnt/cd2",""]]
2024/06/27 13:49:05 [warn] 19#19: *2880 js: strMapping replace: /mnt/cd2 => 
2024/06/27 13:49:05 [warn] 19#19: *2880 js: mapped emby file path: /115/璧勬簮/鍔ㄦ极/涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016)/Season 3/涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016) - S03E01 - 绗?闆?mkv
2024/06/27 13:49:05 [warn] 19#19: *2880 js: hit cilentSelfAlistRule: [2,"115.com","http://47.113.96.95:5244"]
2024/06/27 13:49:05 [warn] 19#19: *2880 js: 170ms, fetchAlistPathApi async function cost
2024/06/27 13:49:05 [warn] 19#19: *2880 js: fetchAlistPathApi, UA: Infuse-Direct/7.8
2024/06/27 13:49:05 [warn] 19#19: *2880 js: redirect to: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)/Season%203/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)%20-%20S03E01%20-%20%E7%AC%AC1%E9%9B%86.mkv?sign=XsEIrcoD25dY1xPtyBZbod2LKsMGk7zMOmyb7Y-aYsA=:0
2024/06/27 13:49:05 [warn] 19#19: *2880 js: routeL1Dict add: [/Videos/ba1228a4bd9f3abc1521a1afbe1ab40a/stream:ba1228a4bd9f3abc1521a1afbe1ab40a] : [http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)/Season%203/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)%20-%20S03E01%20-%20%E7%AC%AC1%E9%9B%86.mkv?sign=XsEIrcoD25dY1xPtyBZbod2LKsMGk7zMOmyb7Y-aYsA=:0]
2024/06/27 13:49:05 [warn] 19#19: *2880 js: === redirect2Pan: /Videos/ba1228a4bd9f3abc1521a1afbe1ab40a/stream, the NJS VM is destroyed ===
2024/06/27 13:49:06 [warn] 19#19: *2880 js: redirect2Pan, UA: Infuse-Direct/7.8
2024/06/27 13:49:06 [warn] 19#19: *2880 js: hit cache routeL1Dict: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)/Season%203/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)%20-%20S03E01%20-%20%E7%AC%AC1%E9%9B%86.mkv?sign=XsEIrcoD25dY1xPtyBZbod2LKsMGk7zMOmyb7Y-aYsA=:0
2024/06/27 13:49:06 [warn] 19#19: *2880 js: redirect to: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)/Season%203/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%A5%9D%E7%A6%8F%EF%BC%81%20(2016)%20-%20S03E01%20-%20%E7%AC%AC1%E9%9B%86.mkv?sign=XsEIrcoD25dY1xPtyBZbod2LKsMGk7zMOmyb7Y-aYsA=:0
2024/06/27 13:49:06 [warn] 19#19: *2880 js: === redirect2Pan: /Videos/ba1228a4bd9f3abc1521a1afbe1ab40a/stream, the NJS VM is destroyed ===
2024/06/27 13:49:08 [warn] 19#19: *2850 js: playbackinfo proxy uri: /proxy/Items/ba1228a4bd9f3abc1521a1afbe1ab40a/PlaybackInfo
2024/06/27 13:49:08 [warn] 19#19: *2850 js: playbackinfo proxy query string: UserId=53c7b5b0d4b6423bbfca20f2c375ad3d
2024/06/27 13:49:08 [warn] 19#19: *2850 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"ba1228a4bd9f3abc1521a1afbe1ab40a","Path":"/mnt/cd2/115/\u8D44\u6E90/\u52A8\u6F2B/\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u795D\u798F\uFF01 (2016)/Season 3/\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u795D\u798F\uFF01 (2016) - S03E01 - \u7B2C1\u96C6.mkv","Type":"Default","Container":"mkv","Size":1441890140,"Name":"\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u795D\u798F\uFF01 (2016) - S03E01 - \u7B2C1\u96C6","IsRemote":false,"ETag":"35e8c35e2bc5d5a4779d1af4b0fc4d9c","RunTimeTicks":14204500000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","TimeBase":"1/1000","VideoRange":"SDR","VideoRangeType":"SDR","AudioSpatialFormat":"None","DisplayTitle":"1080p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":8120751,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976,"RealFrameRate":23.976,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false},{"Codec":"aac","Language":"jpn","TimeBase":"1/1000","Title":"Japanese","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","DisplayTitle":"Japanese - AAC - Stereo - Default","IsInterlaced":false,"IsAVC":false,"ChannelLayout":"stereo","BitRate":128002,"Channels":2,"SampleRate":44100,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":fal
2024/06/27 13:49:08 [warn] 19#19: *2850 js: modify direct play supports all true
2024/06/27 13:49:08 [warn] 19#19: *2850 js: modify direct play info
2024/06/27 13:49:08 [warn] 19#19: *2850 js: 5ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"ba1228a4bd9f3abc1521a1afbe1ab40a","Path":"/mnt/cd2/115/璧勬簮/鍔ㄦ极/涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016)/Season 3/涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016) - S03E01 - 绗?闆?mkv","Type":"Default","Container":"mkv","Size":1441890140,"Name":"涓虹編濂界殑涓栫晫鐚笂绁濈锛?(2016) - S03E01 - 绗?闆?,"IsRemote":false,"ETag":"35e8c35e2bc5d5a4779d1af4b0fc4d9c","RunTimeTicks":14204500000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","ColorSpace":"bt709","ColorTransfer":"bt709","ColorPrimaries":"bt709","TimeBase":"1/1000","VideoRange":"SDR","VideoRangeType":"SDR","AudioSpatialFormat":"None","DisplayTitle":"1080p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":8120751,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976,"RealFrameRate":23.976,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false},{"Codec":"aac","Language":"jpn","TimeBase":"1/1000","Title":"Japanese","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","DisplayTitle":"Japanese - AAC - Stereo - Default","IsInterlaced":false,"IsAVC":false,"ChannelLayout":"stereo","BitRate":128002,"Channels":2,"SampleRate":44100,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Level":0},{"Codec":"subrip","Language":"chi","TimeBase":"1/1000","Title":"绠€浣?2024/06/27 13:49:08 [warn] 19#19: *2850 js: === transferPlaybackInfo: /Items/ba1228a4bd9f3abc1521a1afbe1ab40a/PlaybackInfo, the NJS VM is destroyed ===
2024/06/27 13:49:17 [warn] 19#19: *2850 js: playbackinfo proxy uri: /proxy/Items/f46f5f643e4fd73d5dc578b59622ab7d/PlaybackInfo
2024/06/27 13:49:17 [warn] 19#19: *2850 js: playbackinfo proxy query string: UserId=53c7b5b0d4b6423bbfca20f2c375ad3d
2024/06/27 13:49:17 [warn] 19#19: *2850 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"f46f5f643e4fd73d5dc578b59622ab7d","Path":"/mnt/cd2/115/\u8D44\u6E90/\u52A8\u6F2B/\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u7206\u7130\uFF01 (2023)/Season 1/\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u7206\u7130\uFF01 (2023) - S01E02 - \u7B2C2\u96C6.mkv","Type":"Default","Container":"mkv","Size":1258515588,"Name":"\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u7206\u7130\uFF01 (2023) - S01E02 - \u7B2C2\u96C6","IsRemote":false,"ETag":"653c0790d8e47822c2e1d72f06f7f2ed","RunTimeTicks":14210980000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":true,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"ass","Language":"chi","TimeBase":"1/100","Title":"zh-cn","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","LocalizedUndefined":"\u672A\u5B9A\u4E49","LocalizedDefault":"\u9ED8\u8BA4","LocalizedForced":"\u5F3A\u5236\u7684","LocalizedExternal":"\u5916\u90E8","LocalizedHearingImpaired":"\u542C\u529B\u969C\u788D","DisplayTitle":"zh-cn - Chi - ASS - \u5916\u90E8","IsInterlaced":false,"IsAVC":false,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"Type":"Subtitle","Index":0,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/mnt/cd2/115/\u8D44\u6E90/\u52A8\u6F2B/\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u7206\u7130\uFF01 (2023)/Season 1/\u4E3A\u7F8E\u597D\u7684\u4E16\u754C\u732E\u4E0A\u7206\u7130\uFF01 (2023) - S01E02 - \u7B2C2\u96C6.chi.zh-cn.ass","Level":0},{"Codec":"ass","Language":"chi","TimeBase":"1/100","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","LocalizedUndefined":"\u672A\u5B9A\u4E49","LocalizedDefault":"\u9ED8\u8BA4","LocalizedForced
2024/06/27 13:49:17 [warn] 19#19: *2850 js: modify direct play supports all true
2024/06/27 13:49:17 [warn] 19#19: *2850 js: modify direct play info
2024/06/27 13:49:17 [warn] 19#19: *2850 js: 4ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"f46f5f643e4fd73d5dc578b59622ab7d","Path":"/mnt/cd2/115/璧勬簮/鍔ㄦ极/涓虹編濂界殑涓栫晫鐚笂鐖嗙劙锛?(2023)/Season 1/涓虹編濂界殑涓栫晫鐚笂鐖嗙劙锛?(2023) - S01E02 - 绗?闆?mkv","Type":"Default","Container":"mkv","Size":1258515588,"Name":"涓虹編濂界殑涓栫晫鐚笂鐖嗙劙锛?(2023) - S01E02 - 绗?闆?,"IsRemote":false,"ETag":"653c0790d8e47822c2e1d72f06f7f2ed","RunTimeTicks":14210980000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"ass","Language":"chi","TimeBase":"1/100","Title":"zh-cn","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","LocalizedUndefined":"鏈畾涔?,"LocalizedDefault":"榛樿","LocalizedForced":"寮哄埗鐨?,"LocalizedExternal":"澶栭儴","LocalizedHearingImpaired":"鍚姏闅滅","DisplayTitle":"zh-cn - Chi - ASS - 澶栭儴","IsInterlaced":false,"IsAVC":false,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"Type":"Subtitle","Index":0,"IsExternal":true,"IsTextSubtitleStream":true,"SupportsExternalStream":true,"Path":"/mnt/cd2/115/璧勬簮/鍔ㄦ极/涓虹編濂界殑涓栫晫鐚笂鐖嗙劙锛?(2023)/Season 1/涓虹編濂界殑涓栫晫鐚笂鐖嗙劙锛?(2023) - S01E02 - 绗?闆?chi.zh-cn.ass","Level":0},{"Codec":"ass","Language":"chi","TimeBase":"1/100","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","LocalizedUndefined":"鏈畾涔?,"LocalizedDefault":"榛樿","LocalizedForced":"寮哄埗鐨?,"LocalizedExternal":"澶栭儴","LocalizedHearingImpaired":"鍚姏闅滅","DisplayTitle":"Chi - ASS - 澶栭儴","IsInterlaced":false,"IsAVC":false,"IsDefault":false,"IsForced":false,"IsHearingImpaired":false,"Height":0,"Width":0,"Type":"Subtitle","Index
2024/06/27 13:49:17 [warn] 19#19: *2850 js: === transferPlaybackInfo: /Items/f46f5f643e4fd73d5dc578b59622ab7d/PlaybackInfo, the NJS VM is destroyed ===
2024/06/27 13:49:17 [warn] 19#19: *2880 js: redirect2Pan, UA: Infuse-Direct/7.8
2024/06/27 13:49:17 [warn] 19#19: *2880 js: hit cache routeL1Dict: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)/Season%201/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv?sign=1BJwbU7mSCgihUAd4PTf0RACoI3YXougLq3oboQU2FY=:0
2024/06/27 13:49:17 [warn] 19#19: *2880 js: redirect to: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)/Season%201/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv?sign=1BJwbU7mSCgihUAd4PTf0RACoI3YXougLq3oboQU2FY=:0
2024/06/27 13:49:17 [warn] 19#19: *2880 js: === redirect2Pan: /Videos/f46f5f643e4fd73d5dc578b59622ab7d/stream, the NJS VM is destroyed ===
2024/06/27 13:49:18 [warn] 19#19: *2880 js: redirect2Pan, UA: Infuse-Direct/7.8
2024/06/27 13:49:18 [warn] 19#19: *2880 js: hit cache routeL1Dict: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)/Season%201/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv?sign=1BJwbU7mSCgihUAd4PTf0RACoI3YXougLq3oboQU2FY=:0
2024/06/27 13:49:18 [warn] 19#19: *2880 js: redirect to: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)/Season%201/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv?sign=1BJwbU7mSCgihUAd4PTf0RACoI3YXougLq3oboQU2FY=:0
2024/06/27 13:49:18 [warn] 19#19: *2880 js: === redirect2Pan: /Videos/f46f5f643e4fd73d5dc578b59622ab7d/stream, the NJS VM is destroyed ===
2024/06/27 13:49:20 [warn] 19#19: *2880 js: redirect2Pan, UA: Infuse-Direct/7.8
2024/06/27 13:49:20 [warn] 19#19: *2880 js: Property "MediaSourceId" not found in object,will ignore
2024/06/27 13:49:20 [warn] 19#19: *2880 js: hit cache routeL1Dict: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)/Season%201/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv?sign=1BJwbU7mSCgihUAd4PTf0RACoI3YXougLq3oboQU2FY=:0
2024/06/27 13:49:20 [warn] 19#19: *2880 js: redirect to: http://47.113.96.95:5244/d/115/%E8%B5%84%E6%BA%90/%E5%8A%A8%E6%BC%AB/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)/Season%201/%E4%B8%BA%E7%BE%8E%E5%A5%BD%E7%9A%84%E4%B8%96%E7%95%8C%E7%8C%AE%E4%B8%8A%E7%88%86%E7%84%B0%EF%BC%81%20(2023)%20-%20S01E02%20-%20%E7%AC%AC2%E9%9B%86.mkv?sign=1BJwbU7mSCgihUAd4PTf0RACoI3YXougLq3oboQU2FY=:0
2024/06/27 13:49:20 [warn] 19#19: *2880 js: Property "MediaSourceId" not found in object,will ignore
2024/06/27 13:49:20 [warn] 19#19: *2880 js: === redirect2Pan: /Videos/f46f5f643e4fd73d5dc578b59622ab7d/f46f5f643e4fd73d5dc578b59622ab7d/Subtitles/0/0/Stream.ass, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
>MediaSourceId" not found in object,will ignore

1.和这个无关，这行日志是预期的正确行为

2.1 可以尝试关闭路由缓存试下，或者尝试关闭下 alist 设置 -> 全局 -> 签名所有，测试完毕后记得改回去

emby2Alist\nginx\conf.d\config\constant-pro.js

```js
// 路由缓存配置
const routeCacheConfig = {
  // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
  // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
  enable: false,
  // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,cilentSelfAlistRule 中的和首页直接播放的不生效
  enableL2: false,
  // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
  // 注意 jellyfin 是小写开头 mediaSourceId
  keyExpression: "r.uri:r.args.MediaSourceId", // "r.uri:r.args.MediaSourceId:r.args.X-Emby-Device-Id"
};
```

**Comment by chen3861229** [comment]
3.也有可能遇到了客户端不支持的媒体格式，可以参照开启 允许转码 参数

https://github.com/chen3861229/embyExternalUrl/issues/51
