### ISSUE TITLE
请教关于IPV6错误的问题

### ISSUE THREAD

**Issue by Moe8383** [bpking1/embyExternalUrl#258]
启动后显示：
10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
其他功能似乎正常，但EMBY搜刮的时候（STRM模式）无法使用image capture，请问是哪里配置错了吗？

**Comment by Moe8383** [comment]
另外，在日志中，看不到任何登陆或重定向的信息，是否正常？

**Comment by NASA0719** [comment]
> 启动后显示： 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist 其他功能似乎正常，但EMBY搜刮的时候（STRM模式）无法使用image capture，请问是哪里配置错了吗？

好歹先看看FAQ再问吧，[https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#5docker-compose-%E5%90%8E%E6%8F%90%E7%A4%BA%E6%89%BE%E4%B8%8D%E5%88%B0-defaultconf](url)
image capture没用过不懂

**Comment by NASA0719** [comment]
> 另外，在日志中，看不到任何登陆或重定向的信息，是否正常？

你说的日志是docker日志？nginx日志早就修改到文件而不显示在docker日志了，`- ../nginx/log:/var/log/nginx`查看这个对应的的映射目录就能看到

**Comment by chen3861229** [comment]
1.上面补充的是对的，如果功能正常的话不用关注，10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist

2.我也没看懂 image capture 这个指的是？

2.1 假如说的是图片缓存功能不正常，可参照

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

2.2 假如说的是 emby 等之类的媒体同目录下没有 poster.xxx 之类的海报，服务端提取视频第一帧作为封面的这个功能，这个是 emby 源服务端那边功能，需要查找下 emby 官方文档了，据我的使用体验，只有在媒体命名不规范刮削不到的时候才会走这个过程，所以有三种解决方案

2.2.1 最简单的还是 strm 生成为符合 emby 官方文档规范的命名风格，这样同目录下不需要 poster.xxx 的海报图片

2.2.2 用工具刮削一遍，在同目录生成 poser.xxx 海报图片

2.2.3 strm 内部的链接风格符合 emby 官方支持的格式，即 http 开头之类的直链，不要使用脚本强行兼容的 / 开头的写法，这种只支持播放，其他很多方面有 bug，例如 emby 服务端是读取不到 strm 指向的文件的，所以也就无法提取封面图，章节，转码这些操作了

**Comment by mymoonyue** [comment]
> 启动后显示：
> 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist
> 其他功能似乎正常，但EMBY搜刮的时候（STRM模式）无法使用image capture，请问是哪里配置错了吗？

我用的plex，之前（大约两周前更新的）正常，今天下午更新完也有类似的报错，8091反代端口能正常访问，元数据也正常显示，但是无法播放，也没有报错，就是0kb一直加载中

**Comment by Moe8383** [comment]
> 1.上面补充的是对的，如果功能正常的话不用关注，10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf is not a file or does not exist

谢谢提醒，之前一直用dev的老板本，没注意，后来看了FAQ明白了。

> 2.2.3 strm 内部的链接风格符合 emby 官方支持的格式，即 http 开头之类的直链，不要使用脚本强行兼容的 / 开头的写法，这种只支持播放，其他很多方面有 bug，例如 emby 服务端是读取不到 strm 指向的文件的，所以也就无法提取封面图，章节，转码这些操作了

Image capture指媒体库设置里面的“图像获取器”。
![image](https://github.com/bpking1/embyExternalUrl/assets/104888281/25aa02ab-2e0a-463d-9424-3fd9cf7ab83c)
我是用auto_symlink项目生成https开头的直链，用alist挂在115网盘，alist使用别名整合了内容，cd2挂载在本地。

**Comment by chen3861229** [comment]
> 我用的plex，之前（大约两周前更新的）正常

已修复

https://github.com/bpking1/embyExternalUrl/pull/260

**Comment by chen3861229** [comment]
> 因为有些自己的视频素材，需要截取首帧作为封面。直接搜刮cd2挂载文件是可以正常获取封面的，但strm就不行。

1.可以尝试使用下这个插件，虽然我没用过，StrmExtract，不清楚它能不能补充提取封面图
```
2.emby 插件库里有个貌似可以定时处理 strm 媒体信息的,设置-高级-插件-Catalog-元数据-StrmExtract, 我这边只是看到了,没有尝试过这个插件,需要自行摸索,但是这样其实 strm 又扫库了,虽然可能是定时可控可手动取消的,这点也需要自行权衡下
```
引用来源，

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#22%E6%94%AF%E6%8C%81-emby-api-%E7%9A%84%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%92%AD%E6%94%BE-strm-%E6%97%A0%E6%B3%95%E8%AE%B0%E5%BD%95%E6%92%AD%E6%94%BE%E8%BF%9B%E5%BA%A6

**Comment by mymoonyue** [comment]
> > 我用的plex，之前（大约两周前更新的）正常
> 
> 已修复
> 
> #260

大佬流批

**Comment by mymoonyue** [comment]
> > 我用的plex，之前（大约两周前更新的）正常
> 
> 已修复
> 
> #260

可以播放但不是直链了哎，网页（用的劫持后的8091端口）和app播放都是走的本地。之前直链成功网页端8091其实播放不了的。

**Comment by Moe8383** [comment]
> 1.可以尝试使用下这个插件，虽然我没用过，StrmExtract，不清楚它能不能补充提取封面图，如果同样无法满足需求，那就是 emby 源服务端对 strm 的处理就是如此的，只能等待官方支持了
> 
> 
> 
> > 2.emby 插件库里有个貌似可以定时处理 strm 媒体信息的,设置-高级-插件-Catalog-元数据-StrmExtract, 我这边只是看到了,没有尝试过这个插件,需要自行摸索,但是这样其实 strm 又扫库了,虽然可能是定时可控可手动取消的,这点也需要自行权衡下

之前试过了这个插件，没效果，怀疑是不是我路径映射的问题，我再琢磨一下，谢谢大佬答疑！

**Comment by chen3861229** [comment]
> 可以播放但不是直链了哎，网页（用的劫持后的8091端口）和app播放都是走的本地

1.constant.js 新代码统一改了两个变量名，这边有手动修改下吗？情况特殊，统一变量名以后不会再随意更改这块内容了，我这边简单测试了下是没问题的，有转发直链

plex2Alist\nginx\conf.d\constant.js
或者位于拆分后的配置文件
plex2Alist\nginx\conf.d\config\constant-pro.js
```js
const plexMountPath = ["/AList"];
const plexPathMapping = [];
=>
const mediaMountPath = ["/AList"];
const mediaPathMapping = [];
```

**Comment by mymoonyue** [comment]
> > 可以播放但不是直链了哎，网页（用的劫持后的8091端口）和app播放都是走的本地
> 
> 1.constant.js 新代码统一改了两个变量名，这边有手动修改下吗？情况特殊，统一变量名以后不会再随意更改这块内容了，我这边简单测试了下是没问题的，有转发直链
> 
> plex2Alist\nginx\conf.d\constant.js 或者位于拆分后的配置文件 plex2Alist\nginx\conf.d\config\constant-pro.js
> 
> ```js
> const plexMountPath = ["/AList"];
> const plexPathMapping = [];
> =>
> const mediaMountPath = ["/AList"];
> const mediaPathMapping = [];
> ```

感谢，已经解决！

**Comment by Moe8383** [comment]
> 1.可以尝试使用下这个插件，虽然我没用过，StrmExtract，不清楚它能不能补充提取封面图，如果同样无法满足需求，那就是 emby 源服务端对 strm 的处理就是如此的，只能等待官方支持了

应该是Emby不支持直接通过strm截取帧……
再请教，如果使用symlink软连的方式，应该怎么设置获取直链？我是用CD2挂载alist，alist用alias整合资源。直接导入软连，可以获取首帧，但走的本地。
设置里面有“symlinkRule”，具体应该填哪个路径？例如，我的挂载目录为：/mnt/cloudnas/CloudDrive/alist/alias，软连目录为/mnt/cdlink

**Comment by chen3861229** [comment]
1.symlinkRule 此参数仅在软连接后的文件名和原始文件名不一致或路径差异较大时使用，如果你的差异不大，建议用 mediaPathMapping 来进行路径映射来得简单，而且不经过文件系统查询，性能会稍微好一些，以下二选一，
这里假设，/mnt/cloudnas/CloudDrive/alist/alias 和 /mnt/cdlink 为同目录级别
，存在 /mnt/cloudnas/CloudDrive/alist/alias/file.xxx 和 /mnt/cdlink/file.xxx，且 alist 根目录下存在 /alias 文件夹

1.1 这种会简单一点，但是存在一定局限性，如上
```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数1: 0: 默认做字符串替换, 1: 前插, 2: 尾插
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  [0, 0, "/mnt/cdlink", "/alias"],
];
// 上述前提是，注意 /mnt 会先被移除掉了
const mediaMountPath = ["/mnt"];
// 假如 mediaMountPath 为空数组
const mediaPathMapping = [
  [0, 0, "/cdlink", "/alias"],
];
```
即 /mnt/cdlink/file.xxx 入库的文件会被转换为 /alias/file.xxx 这个路径去 alist 中取直链

1.2 这种稍微复杂些了，需要先保证将 /mnt/cdlink 这个宿主机目录以同路径映射到 docker 中 /mnt/cdlink ，且 nginx 确保具有此目录的读取权限
```js
// 指定需要获取符号链接真实路径的规则,优先级在 mediaMountPath 和 routeRule 之间
// 注意前提条件是此程序或容器必须挂载或具有对应目录的读取权限,否则将跳过处理,不生效
// 此参数仅在软连接后的文件名和原始文件名不一致或路径差异较大时使用,其余情况建议用 mediaPathMapping
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为媒体服务入库的文件路径(Item.Path)
const symlinkRule = [
  // [0, "/mnt/cdlink"],
];
```
