### ISSUE TITLE
您好 关于docker-NGINX 需要单独编译模块么

### ISSUE THREAD

**Issue by Ccnavi** [bpking1/embyExternalUrl#262]
运行 docker compose NGINX 日志输出提示 找不到 http_js 模块
这个需要单独编译吗

**Comment by Ccnavi** [comment]
还是说 只能宿主机本地模式安装NGINX 然后在编译

**Comment by Ccnavi** [comment]
已经配置好了 也感谢楼主解答 
如何观察plexalist是否走了直连呢

**Comment by chen3861229** [comment]
1.在 nginx 的 error.log 业务日志中搜索 redirect to 关键字可以严格确认，/docker/nginx-plex2alist/log

2.或者暂时需要凭感觉，在非局域网下加载速度大于 nginx 所在网络的上传带宽也可以快速判断

3.这条仅仅是调试判断，无法日常判断，如果浏览器端可以打开控制台网络选项卡查看是否 302 ，移动端的话抓包了
