### ISSUE TITLE
用embyLaunchPotplayer拉起potplayer播放无法加载外挂字幕

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [bpking1/embyExternalUrl#263]
拉起potplayer后没有外挂字幕但是我看了下pot确实收到了ass，以前脚本可以正常用，不知道是不是emby新版本更新了数据库的问题，都是本地文件不是网盘
![image](https://github.com/bpking1/embyExternalUrl/assets/78670748/08ee7501-23ea-40e4-b833-648a21db01b6)

**Comment by chen3861229** [comment]
1.试了下，是特效字幕或字幕字体的兼容问题，potplayer，我这边只测了一个文件，ass 的字幕从 emby 详情页手动下载并加载进 pot 都没用，也尝试查看了 ass 中的字体为，微软雅黑，并设置了 pot 也没用，字幕样式这块我也不是很熟，但是脚本调用的外挂字幕 srt 格式是支持的，因为该字幕格式内部没有复杂的样式

![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/0842a527-af05-4c8f-939e-47cb52da9f37)

![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/ea08d7b5-b6e6-4ff0-9f72-d3fe0679e730)

![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/e00c3e61-0913-446a-9960-af484f95aa47)

![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/c3d4343e-585a-41d8-8917-bdd1c1eed042)

**Comment by SchrodingerBarbatos** [comment]
> 1.试了下，是特效字幕或字幕字体的兼容问题，potplayer，我这边只测了一个文件，ass 的字幕从 emby 详情页手动下载并加载进 pot 都没用，也尝试查看了 ass 中的字体为，微软雅黑，并设置了 pot 也没用，字幕样式这块我也不是很熟，但是脚本调用的外挂字幕 srt 格式是支持的，因为该字幕格式内部没有复杂的样式
> 
> ![image](https://private-user-images.githubusercontent.com/42368856/345061896-0842a527-af05-4c8f-939e-47cb52da9f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mjk3NDYsIm5iZiI6MTcxOTkyOTQ0NiwicGF0aCI6Ii80MjM2ODg1Ni8zNDUwNjE4OTYtMDg0MmE1MjctYWYwNS00YzhmLTkzOWUtNDdjYjUyZGE5ZjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmZmVlNmVjNGUzZWQ4M2VmYjljNDI1NzQ0NzYzYmYyMTNkMGJkMTc5ZjY1Njk3MWRiOWE5ZDdhZGU0NzZkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2gio7IK1hN8c-K2czFxoBnWMkSOLOTKk6K0ZIvDH4DM)
> 
> ![image](https://private-user-images.githubusercontent.com/42368856/345063775-ea08d7b5-b6e6-4ff0-9f72-d3fe0679e730.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mjk3NDYsIm5iZiI6MTcxOTkyOTQ0NiwicGF0aCI6Ii80MjM2ODg1Ni8zNDUwNjM3NzUtZWEwOGQ3YjUtYjZlNi00ZmYwLTlmNzItZDNmZTA2NzllNzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiNzRiYmUwZGEzNGRmOTBhZjUxZDM1ZWU4NDg5ZThlZmEwM2M1MGQyNGU2NmJlMTA5ZTBjNTkxOTlhOGNlMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hNXZr51-syH6VK0LDfA-CNbnV87jA9FiaY5isvpYQ8M)
> 
> ![image](https://private-user-images.githubusercontent.com/42368856/345064309-e00c3e61-0913-446a-9960-af484f95aa47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mjk3NDYsIm5iZiI6MTcxOTkyOTQ0NiwicGF0aCI6Ii80MjM2ODg1Ni8zNDUwNjQzMDktZTAwYzNlNjEtMDkxMy00NDZhLTk5NjAtYWY0ODRmOTVhYTQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZWU0ODZlZDQxMjNiNmViZTk0N2EyZjYyNzU5MTEwMWNjNzIzZDFiZjY1NDQwZjkxMTUyYzVhODU2MDAyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iPMJ_tKfa9wdkW9CMyhTE0pPokTQ722vbrN0DuKdt5Y)
> 
> ![image](https://private-user-images.githubusercontent.com/42368856/345064417-c3d4343e-585a-41d8-8917-bdd1c1eed042.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mjk3NDYsIm5iZiI6MTcxOTkyOTQ0NiwicGF0aCI6Ii80MjM2ODg1Ni8zNDUwNjQ0MTctYzNkNDM0M2UtNTg1YS00MWQ4LTg5MTctYmRkMWMxZWVkMDQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE0MTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2YWEzOTJkMzRlNDk2Y2NmNGFlMTM3ZTA2ZjUxNzc4OTgyYzMyOWI1NDExZGYwNjhiYjRkMzUyODE2MzM2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2WXE5aRh5gzYzwdgEkTDDKwPQIgkY0eMPyT8uBYRjHw)

我用的确实是ass字幕，但是本地播没问题，如果把字幕下通过emby下来我这边用也没有问题，不太确定什么问题

**Comment by chen3861229** [comment]
这个就是 potplayer 本身的字幕样式兼容性问题了，可以尝试调整下 potplayer  字幕字体或一些样式设置

**Comment by SchrodingerBarbatos** [comment]
> 这个就是 potplayer 本身的字幕样式兼容性问题了，可以尝试调整下 potplayer 字幕字体或一些样式设置

我用客户端拉pot字幕是可以播放的，链接如下：http://10.10.10.8:8096/emby/videos/224085/original.mkv?DeviceId=Barabtos&MediaSourceId=0300cb9f988f93d149904e9a97cd176e&PlaySessionId=9e5a9b2ef34543db87c488fe4ac09544&api_key=1bab61e57877442fb0696e57edc81a1a
脚本的链接是：http://10.10.10.8:8096/emby/videos/224085/stream.mkv?api_key=1bab61e57877442fb0696e57edc81a1a&Static=true&MediaSourceId=0300cb9f988f93d149904e9a97cd176e
应该不是pot的字幕样式兼容性问题吧

**Comment by SchrodingerBarbatos** [comment]
> > 这个就是 potplayer 本身的字幕样式兼容性问题了，可以尝试调整下 potplayer 字幕字体或一些样式设置
> 
> 我用客户端拉pot字幕是可以播放的，链接如下：http://10.10.10.8:8096/emby/videos/224085/original.mkv?DeviceId=Barabtos&MediaSourceId=0300cb9f988f93d149904e9a97cd176e&PlaySessionId=9e5a9b2ef34543db87c488fe4ac09544&api_key=1bab61e57877442fb0696e57edc81a1a 脚本的链接是：http://10.10.10.8:8096/emby/videos/224085/stream.mkv?api_key=1bab61e57877442fb0696e57edc81a1a&Static=true&MediaSourceId=0300cb9f988f93d149904e9a97cd176e 应该不是pot的字幕样式兼容性问题吧

试了下，客户端拉pot的话字幕好像是另外传进去的
