### ISSUE TITLE
纠结是symlink还是strm模式

### ISSUE THREAD

**Issue by Moe8383** [bpking1/embyExternalUrl#266]
最近很纠结到底用symlink还是strm好。
个人觉得，strm方便批量修改，对目录结构要求没那么严格，但媒体信息搜刮不是很完善，例如：
1.媒体音频信息时有缺失
2.视频（非电影）无法获取首帧做封面
3.plex不原生支持
而用symlink软连，好像就没有上述不足；缺点是目录结构尽量要一致，依赖源文件，但现在很多工具都是自动批量更新软连接的；扫库慢？不知道我理解的对不对。
请教各位大佬，哪种方式更优呢？我需求是家庭自用的媒体库，数量目前大概一两万，都是通过alist、CD2挂载，远程访问的多，Emby和Plex。

**Comment by chen3861229** [comment]
个人建议还是 symlink 软链接，毕竟这样符合媒体服务器的本地文件系统倾向，兼容性也好，扫库慢和频繁其实不是缺点，是媒体服务器很多功能依赖于这个行为，你提到的，再加上，播放时长/播放次数统计，实时转码的兼容性，转换任务的支持性...
这个取决于你对这些功能的依赖度了，如果都不重要，再考虑 strm 方式

**Comment by YnSen** [comment]
> 个人建议还是 symlink 软链接，毕竟这样符合媒体服务器的本地文件系统倾向，兼容性也好，扫库慢和频繁其实不是缺点，是媒体服务器很多功能依赖于这个行为，你提到的，再加上，播放时长/播放次数统计，实时转码的兼容性，转换任务的支持性... 这个取决于你对这些功能的依赖度了，如果都不重要，再考虑 strm 方式

用symlink 软链接后是不是不能302直链播放了，我用symlink软连接后，发现跑的是服务器流量了，strm格式就是直链播放，不知道是我没弄对还是symlink软连接后不能直链播放了，希望得到大佬回复。

**Comment by chen3861229** [comment]
https://github.com/chen3861229/embyExternalUrl/issues/53#issuecomment-2217925061

1.脚本对于 symlink 支持 302 播放，symlink 软链接如果和源文件路径差异太大，假如是 docker 环境，需要挂载同路径到容器中，且具有读取权限，听描述，大概率是没有找到这个软链接的文件地址或没有读取权限，所以默认走了回退到源服务中转的逻辑，这个具体需要排查下 error.log 中的一些信息

**Comment by Moe8383** [comment]
> 个人建议还是 symlink 软链接，毕竟这样符合媒体服务器的本地文件系统倾向，兼容性也好，扫库慢和频繁其实不是缺点，是媒体服务器很多功能依赖于这个行为，你提到的，再加上，播放时长/播放次数统计，实时转码的兼容性，转换任务的支持性...
> 
> 这个取决于你对这些功能的依赖度了，如果都不重要，再考虑 strm 方式

确实，strm的依赖条件很少，但信息缺失。想问一下，Emby 怎么设置优先读取本地元数据，没有再刮削？

**Comment by YnSen** [comment]
> [chen3861229#53 (comment)](https://github.com/chen3861229/embyExternalUrl/issues/53#issuecomment-2217925061)
> 
> 1.脚本对于 symlink 支持 302 播放，symlink 软链接如果和源文件路径差异太大，假如是 docker 环境，需要挂载同路径到容器中，且具有读取权限，听描述，大概率是没有找到这个软链接的文件地址或没有读取权限，所以默认走了回退到源服务中转的逻辑，这个具体需要排查下 error.log 中的一些信息

已解决，感谢大佬

**Comment by szyevan** [comment]
用了strm，本地NFO会被emby修改有时候，而且演员会错乱，全部变成同一个演员，但是不用做cd2 ，直接可以连接alist账户，找个有的解决吗

**Comment by chen3861229** [comment]
> 用了strm，本地NFO会被emby修改有时候

1.这个的话可以把目录改为只读试试，或让 AI 写的脚本批量将 NFO 后缀文件改成只读，但是这样会产生新的问题，也就是数据不能实时变更了，我这边因为是用的 alist 的 alias 别名，所以媒体目录都是只读的，删除媒体比较麻烦，需要自己去 alist 对应的驱动下手动删除并刷新，以上只是参考，具体使用需要自己尝试下，看能否接受这些缺点

> 但是不用做cd2 ，直接可以连接alist账户

2.这个的话应该和 1 中我的情况类似，补充下看漏掉 cd2 了，1 中设置只读也可用挂载工具挂载为只读的，strm 直接指向 alist 文件地址的话，建议刮削为规范命名，strm 文件周围不要存 nfo 文件，直接让 emby 内部去管理(会存在 metadata 文件夹内)，但是这种也有缺点，可能对剧集之类的嵌套 season 的结构识别有些问题，各种方案也是各有优缺点，需要权衡下了

**Comment by szyevan** [comment]
> > 用了strm，本地NFO会被emby修改有时候
> 
> 1.这个话可以把目录改为只读试试，或者让AI写的脚本批量将NFO后缀文件改成只读，但是这样会产生新的问题，也就是数据不能实时变更了，我这边因为是用的alist的别名别名，所以媒体目录都是只读的，删除媒体比较麻烦，需要自己去alist对应的驱动下手动删除并刷新，以上只是参考，具体使用需要自己尝试下，看能否接受这些缺点
> 
> > 但是不用做cd2，直接可以连接alist账户
> 
> 2.这个话应该和1 中我情况类似，补充下看漏掉cd2了，1 中设置只读也可用挂载工具挂载为只读的，strm直接指向alist文件地址的话，建议刮削为规范命名，strm文件周围不要存nfo文件，直接让emby内部去管理(会存在元数据文件夹内)，但是这种也有缺点，可能对剧集就像嵌套结构识别有些问题，各种方案也是各有优缺点，需要权衡一下
> 
> #283

“直接让 emby 内部去管理(会存在 metadata 文件夹内”这步怎么操作

**Comment by chen3861229** [comment]
> 直接让 emby 内部去管理(会存在 metadata 文件夹内)

稍微有点歧义，其实是这步的结果

> 建议刮削为规范命名，strm 文件周围不要存 nfo 文件
> 但是这种也有缺点，可能对剧集之类的嵌套 season 的结构识别有些问题

**Comment by Moe8383** [comment]
> > 用了strm，本地NFO会被emby修改有时候
> 
> 
> 
> 1.这个的话可以把目录改为只读试试，或让 AI 写的脚本批量将 NFO 后缀文件改成只读，但是这样会产生新的问题，也就是数据不能实时变更了，我这边因为是用的 alist 的 alias 别名，所以媒体目录都是只读的，删除媒体比较麻烦，需要自己去 alist 对应的驱动下手动删除并刷新，以上只是参考，具体使用需要自己尝试下，看能否接受这些缺点

目前有个strm的方案，就是用MP里面的云盘strm同步删除插件，可以直接在Emby把strm删了，同步删除源文件。不过有点风险，前几天试过像批量整理strm，结果同步把源文件都删了……
另外，如果用symlink的话，怎么实现在Emby删除软连同步删除源视频？

**Comment by chen3861229** [comment]
> 另外，如果用symlink的话，怎么实现在Emby删除软连同步删除源视频？

我觉得最好不要这样做。。。因为这个过程有风险且可能无法还原，目前貌似没这样工具，因为误操作风险太大了吧，之前 NT 看到过 Emby同步删除 这个插件，但是我没尝试过，基于 emby 插件中的 Emby Scripter-X 实现的

**Comment by Moe8383** [comment]
> > 另外，如果用symlink的话，怎么实现在Emby删除软连同步删除源视频？
> 
> 
> 
> 我觉得最好不要这样做。。。因为这个过程有风险且可能无法还原，目前貌似没这样工具，因为误操作风险太大了吧，之前 NT 看到过 Emby同步删除 这个插件，但是我没尝试过，基于 emby 插件中的 Emby Scripter-X 实现的

是风险有点大，只是从源文件删除不太直观。
另外，是不是symlink直连只能是alist挂载？CD2好像不行？

**Comment by chen3861229** [comment]
> 是不是symlink直连只能是alist挂载？CD2好像不行？

和挂载工具没关系了，软链接属于文件系统层面的东西了，遵循文件系统上的软链接规范就行，只需要注意下不要跨不同的路径风格

https://github.com/chen3861229/embyExternalUrl/issues/53

**Comment by Moe8383** [comment]
> > 是不是symlink直连只能是alist挂载？CD2好像不行？
> 
> 
> 
> 和挂载工具没关系了，软链接属于文件系统层面的东西了，遵循文件系统上的软链接规范就行，只需要注意下不要跨不同的路径风格
> 
> 
> 
> https://github.com/chen3861229/embyExternalUrl/issues/53

我直接用CD2挂载115，symlink走的本地。而用CD2挂载alist，就可以302，是这样的吗？

**Comment by chen3861229** [comment]
> 我直接用CD2挂载115，symlink走的本地。而用CD2挂载alist，就可以302，是这样的吗？

是的，更精确的讲，是依赖这两个 
1. CD2挂载115，
2. symlink走的本地，
3. CD2挂载 alist 纯粹是给 emby 服务入库文件用的，注意到你的特定情况好像并不需要这步，步骤 1 中已经等价
4. nginx 脚本是通过 http 进行请求查询 alist 的

**Comment by Moe8383** [comment]
> > 我直接用CD2挂载115，symlink走的本地。而用CD2挂载alist，就可以302，是这样的吗？
> 
> 
> 
> 是的，更精确的讲，是依赖 1 和 2
> 
> 1.CD2挂载115，
> 
> 2.symlink走的本地，
> 
> 3.CD2挂载 alist 纯粹是给 emby 服务入库文件用的，注意到你的特定情况好像并不需要这步，步骤 1 中已经等价
> 
> 4.nginx 脚本是通过 http 进行请求查询 alist 的

我的需求是远程302直连，是不是意味着用symlink方案的话，一定要用CD2挂载alist生成软连，才能302？CD2挂alist感觉实时监控有问题，MP刮削的元数据无法自动转移到alist，但可以自动转移到cd2直接挂载的115，不知道是不是我设置有问题……

**Comment by chen3861229** [comment]
> 一定要用CD2挂载alist生成软连，才能302？

这个是受限于

> 是不是意味着用symlink方案的话

> 需求是远程302直连

这个不强制依赖 symlink 或 strm 方案，默认最简单的方案是直接网络查询 alist 接口即可，也是脚本中默认的行为

**Comment by chaomarks** [comment]
> 最近很纠结到底用symlink还是strm好。 个人觉得，strm方便批量修改，对目录结构要求没那么严格，但媒体信息搜刮不是很完善，例如： 1.媒体音频信息时有缺失 2.视频（非电影）无法获取首帧做封面 3.plex不原生支持 而用symlink软连，好像就没有上述不足；缺点是目录结构尽量要一致，依赖源文件，但现在很多工具都是自动批量更新软连接的；扫库慢？不知道我理解的对不对。 请教各位大佬，哪种方式更优呢？我需求是家庭自用的媒体库，数量目前大概一两万，都是通过alist、CD2挂载，远程访问的多，Emby和Plex。

我用strm，可以继续播放，网页播放，唯一的缺点就是要点了播放才能显示外置播放器

**Comment by chen3861229** [comment]
>

这个之前已经修复过了，需要手动替换下新代码

https://github.com/bpking1/embyExternalUrl/commit/c0ffac66667d455174cd24e3cacca3f45556a55b

**Comment by ei0ch** [comment]
> > > 用了strm，本地NFO会被emby修改有时候
> > 
> > 
> > 1.这个的话可以把目录改为只读试试，或让 AI 写的脚本批量将 NFO 后缀文件改成只读，但是这样会产生新的问题，也就是数据不能实时变更了，我这边因为是用的 alist 的 alias 别名，所以媒体目录都是只读的，删除媒体比较麻烦，需要自己去 alist 对应的驱动下手动删除并刷新，以上只是参考，具体使用需要自己尝试下，看能否接受这些缺点
> 
> 目前有个strm的方案，就是用MP里面的云盘strm同步删除插件，可以直接在Emby把strm删了，同步删除源文件。不过有点风险，前几天试过像批量整理strm，结果同步把源文件都删了…… 另外，如果用symlink的话，怎么实现在Emby删除软连同步删除源视频？



> > > 用了strm，本地NFO会被emby修改有时候
> > 
> > 
> > 1.这个的话可以把目录改为只读试试，或让 AI 写的脚本批量将 NFO 后缀文件改成只读，但是这样会产生新的问题，也就是数据不能实时变更了，我这边因为是用的 alist 的 alias 别名，所以媒体目录都是只读的，删除媒体比较麻烦，需要自己去 alist 对应的驱动下手动删除并刷新，以上只是参考，具体使用需要自己尝试下，看能否接受这些缺点
> 
> 目前有个strm的方案，就是用MP里面的云盘strm同步删除插件，可以直接在Emby把strm删了，同步删除源文件。不过有点风险，前几天试过像批量整理strm，结果同步把源文件都删了…… 另外，如果用symlink的话，怎么实现在Emby删除软连同步删除源视频？

求指路，MP里这个插件是怎么设置的，一直没弄明白
