### ISSUE TITLE
nginx和emby分开部署该如何修改配置

### ISSUE THREAD

**Issue by pattonbina** [bpking1/embyExternalUrl#268]
非常感谢大佬的程序，emby2Alist 所有配置基本都是以默认nginx和emby服务在同一宿主机，如果我是两台vps，一台机器rclone+emby,另一台机器挂alist和nginx,请问我该修改哪些配置呢，因为我使用的是gd，所以只希望通过物理距离近一点的小鸡来提升访问速度，不需要获取直链，但希望使用代理url,或者是直接通过alist下载，再次非常感谢！

**Comment by pattonbina** [comment]
Alist2emby

**Comment by pattonbina** [comment]
非常感谢您的答复，我需要的就是2.3这种方案，（1）我的alist和nginx部署在同一台轻量大带宽vps，网络上能更快的响应我；（2）然后emby部署在远端性能较高的vps上，这样可以尽可能的提高我embyserver的性能，然后尽可能的提高视频的下载速度。从响应上来说，确实客户端和emby的响应交互时间拉长了一些。

我今天在您没有答复我之前测试过，没有改代码，只是改了必要配置选项，网页播放发现nginx返回的视频流地址没有携带服务端口，即应该返回：http://alist-ip:5244/p/.....,而实际返回的视频文件地址为http://alist-ip/p/....，暂时还没有解决。

再次感谢您的耐心解答，我会再尝试以下，自己折腾一下，如果能成功，将在这个issue给您反馈

**Comment by chen3861229** [comment]
alist 响应丢失端口号这个问题之前遇到过，~~不过我忘了具体怎么解决的了。。。尴尬，可能和以下原因有关~~

1.alist 前有挂反代吗？挂了反代需要传递一些约定俗成的代理标头给上游，这个 alist 官方文档中也有，经过测试，确定和此因素有关，没有传递正确的 Host 标头给 alist

![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/3a5084e0-55ae-406d-9844-6f7ee1f91aed)

![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/40a411af-94b4-4c45-aa28-79e6135d79fa)

2.本脚本已经传递了这些标头，位于 emby2Alist\nginx\conf.d\includes\proxy-header.conf 中

3.如果实在没法解决，可以直接改脚本代码解决，在 emby.js 的 164 行 return redirect(r, alistRes); 之前加上

```js
alistRes = alistRes.includes("http://my-alist.com")
          ? alistRes.replace("http://my-alist.com", config.alistPublicAddr)
          : alistRes;
```

**Comment by chen3861229** [comment]
方便留个档吗？alist 响应丢失端口号这个问题，这个有涉及到上述的 2 或 3 吗？如果有涉及到，我这边可以修复提交下

**Comment by pattonbina** [comment]
好的，我更新到你最新的代码后，发现当nginx和emby分离部署，并且emby上rclone挂载网盘，是不转直链的
经过排查，问题出在
  mediaPathMapping.map(arr => {
    if ((arr[1] == 0 && embyRes.notLocal)
      || (arr[1] == 1 && (!embyRes.notLocal || isRemote))
      || (arr[1] == 2 && (!embyRes.notLocal || !isRemote))) {
        return;
    }
    mediaItemPath = util.strMapping(arr[0], mediaItemPath, arr[2], arr[3]);
  });
因为emby不是本地部署，所以导致替换直接跳过
我的规避方法是，在constant.js中加了一个变量：
//如果emby和alist分离部署,并且上面的路径为绝对路径，例如“/mnt/gd”，则此处值为true
const isEmbyAListSepDep = true;
并在emby.js中，加上了判断：
  mediaPathMapping.map(arr => {
    if ((arr[1] == 0 && embyRes.notLocal && !isEmbyAListSepDep)
      || (arr[1] == 1 && (!embyRes.notLocal || isRemote))
      || (arr[1] == 2 && (!embyRes.notLocal || !isRemote))) {
        return;
    }
    mediaItemPath = util.strMapping(arr[0], mediaItemPath, arr[2], arr[3]);
 
问题得以解决！

**Comment by chen3861229** [comment]
> if ((arr[1] == 0 && embyRes.notLocal && !isEmbyAListSepDep)

这里其实不是干这个用的，不过修改后能正常用就行了，之后我这里加下注释，
分离部署代码中没有做限制的，只是没测试过，所以可能出现了这个小 bug，其他方面应该问题不大
