### ISSUE TITLE
请教大佬 直连网盘播放后 如何套证书 访问emby

### ISSUE THREAD

**Issue by gd0772** [bpking1/embyExternalUrl#27]
我在VPS搭建Docker 版的 emby ,然后用Alist转换为Webdav，Rclone挂载，能正常的通过直连网盘的方式观看影片，看着 浏览器地址栏 显示不安全链接 强迫症来了，我尝试修改Nginx 配置文件添加ssl，证书是通过 [https://freessl.cn/](url) 申请的年证书，证书格式是 Nginx 以下是我的emby访问域名配置文件 添加了 ssl 相关，但是并不生效，依然是没有证书 不安全的状态，望大佬指点

# Load the njs script
js_path /etc/nginx/conf.d/;
js_import emby2Pan from emby.js;
#Cache images                            
proxy_cache_path /var/cache/nginx/emby levels=1:2 keys_zone=emby:100m max_size=1g inactive=30d use_temp_path=off;
proxy_cache_path /var/cache/nginx/emby/subs levels=1:2 keys_zone=embysubs:10m max_size=1g inactive=30d use_temp_path=off;
server{
    gzip on;
    listen 80;
    listen [::]:80;
    server_name tycl.cc;
    listen 443;
    listen [::]:443;
    server_name tycl.cc;
    
    ssl_certificate /etc/nginx/ssl/tycl.cc/tycl.cc.cer;
    ssl_certificate_key /etc/nginx/ssl/tycl.cc/tycl.cc.key;
    ssl_session_timeout 5m;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+CHACHA20-draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5"; 
    
    location ~ /{
        return 301 https://$host$request_uri;
    }

    # aliDrive direct stream need no-referrer
    add_header 'Referrer-Policy' 'no-referrer';
    set $emby http://127.0.0.1:10010;  #emby address

    # Proxy sockets traffic for jellyfin-mpv-shim and webClient
    location ~ /(socket|embywebsocket) {
        # Proxy Emby Websockets traffic
        proxy_pass $emby;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
    }

    # Redirect the stream to njs
    location ~* /videos/(\d+)/stream {             
        js_content emby2Pan.redirect2Pan;
    }
    # for webClient download ,android is SyncService api
    location ~* /Items/(\d+)/Download {
        js_content emby2Pan.redirect2Pan;
    }

     #Cache the Subtitles
    location ~* /videos/(.*)/Subtitles {
        proxy_pass $emby;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_cache embysubs;
        proxy_cache_revalidate on;
        proxy_cache_lock_timeout 10s;
        proxy_cache_lock on;
        proxy_cache_valid 200 30d;
        proxy_cache_key $proxy_host$uri;
        #add_header X-Cache-Status $upstream_cache_status; # This is only to check if cache is working
    }
    
    # Cache the images
    location ~ /Items/(.*)/Images {
        proxy_pass $emby;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;

        proxy_cache emby;
        proxy_cache_revalidate on;
        proxy_cache_lock_timeout 10s;  
        proxy_cache_lock on; 
        # add_header X-Cache-Status $upstream_cache_status; # This is only to check if cache is working
    }

    location / {
        # Proxy main Emby traffic
        proxy_pass $emby;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Protocol $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        # Disable buffering when the nginx proxy gets very resource heavy upon streaming
        proxy_buffering off;
    }
}

**Comment by choateyang** [comment]
**emby.conf文件**
`server{
    gzip on;
    listen 443 ssl;
    server_name 域名;
    add_header 'Referrer-Policy' 'no-referrer';
    set $emby http://本地域名:8096;  #emby/jellyfin address
    ssl_certificate /etc/nginx/ssl/ssl.pem;
    ssl_certificate_key /etc/nginx/ssl/ssl.key;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    # Proxy sockets traffic for jellyfin-mpv-shim and webClient
    location ~* /(socket|embywebsocket) {
        # Proxy emby/jellyfin Websockets traffic
        proxy_pass $emby;
        proxy_http_version 1.1;`

**docker-compose.yml文件**
`services:

    service.nginx:
      image: nginx:alpine
      container_name: emby-nginx
      ports:
        - 端口:端口
      volumes:
        - /root/emby2Alist/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /root/emby2Alist/nginx/conf.d:/etc/nginx/conf.d
        - /root/emby2Alist/nginx/ssl:/etc/nginx/ssl //nginx文件夹下增加ssl文件夹，将证书文件放进去
        - /root/emby2Alist/nginx/embyCache:/var/cache/nginx/emby
      restart: always`
