### ISSUE TITLE
客户端字幕和音轨

### ISSUE THREAD

**Issue by yating1022** [bpking1/embyExternalUrl#273]
在最新版本的脚本情况下，windows的学习小秘的emby和安卓 播放302的115直链无法切换音轨和字幕，但是在使用yamby的时候是可以正常切换音轨和字幕的，是学习小秘客户端的版本老了，还是我脚本设置的问题，大佬有时间的话能不能解答一下谢谢。

**Comment by chen3861229** [comment]
1.我平时也是用这个客户端，和版本没啥太大关系，不过基于官方的客户端音轨切换这块有 issus 确实提到过相关问题，大概率是音频的格式高规格了，官方样式的客户端本身不支持

1.1 可以开启允许转码，走音频的转码，脚本配置允许转码
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#8%E5%85%81%E8%AE%B8%E8%BD%AC%E7%A0%81%E5%8A%9F%E8%83%BD%E4%BD%86%E4%B8%8D%E9%9C%80%E8%A6%81%E5%88%86%E7%A6%BB%E8%BD%AC%E7%A0%81%E8%B4%9F%E8%BD%BD%E8%AF%A5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE

1.2 使用对应平台的客户端播放，yamby 也行

2.字幕的话，官方样式的客户端应该是支持的切换显示的，前提是没有调用外部播放器，内挂/外挂的都可以，但我这边不太清楚官方客户端支持的哪些格式和字体兼容性，普通的 ass/srt 应该都没问题，这个和音轨差不多，也是取决于官方样式的客户端自身的兼容性问题

**Comment by yating1022** [comment]
> 1.我平时也是用这个客户端，和版本没啥太大关系，不过基于官方的客户端音轨切换这块有 issus 确实提到过相关问题，大概率是音频的格式高规格了，官方样式的客户端本身不支持
> 
> 1.1 可以开启允许转码，走音频的转码，脚本配置允许转码 https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#8%E5%85%81%E8%AE%B8%E8%BD%AC%E7%A0%81%E5%8A%9F%E8%83%BD%E4%BD%86%E4%B8%8D%E9%9C%80%E8%A6%81%E5%88%86%E7%A6%BB%E8%BD%AC%E7%A0%81%E8%B4%9F%E8%BD%BD%E8%AF%A5%E5%A6%82%E4%BD%95%E9%85%8D%E7%BD%AE
> 
> 1.2 使用对应平台的客户端播放，yamby 也行
> 
> 2.字幕的话，官方样式的客户端应该是支持的切换显示的，前提是没有调用外部播放器，内挂/外挂的都可以，但我这边不太清楚官方客户端支持的哪些格式和字体兼容性，普通的 ass/srt 应该都没问题，这个和音轨差不多，也是取决于官方样式的客户端自身的兼容性问题

直接改调用外部播放器了，af和yamby都行，windows我只能通过调用外部播放器解决了
