### ISSUE TITLE
alistWebLaunchExternalPlayer无法拉起mpv

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [bpking1/embyExternalUrl#275]
embyLaunchPotplayer拉起mpv是正常的，用alistWebLaunchExternalPlayer会提示拉起但是mpv不会被拉起

**Comment by chen3861229** [comment]
已修复 URL 的 BASE64 编码问题，不过我这边 windows edge 浏览器怎么也调用不起来 MPV 也不是很清楚，用命令行是可以播放的，

![QQ_1720535367932](https://github.com/bpking1/embyExternalUrl/assets/42368856/53800b2a-aed9-4085-832c-5553a37cb366)

已经参考了 https://github.com/akiirui/mpv-handler/issues/41 尝试，也是同样不行，可以尝试下更新修复后编码问题后本脚本的代码，看下有没有改善

**Comment by SchrodingerBarbatos** [comment]
用了新的脚本代码就可以拉起了
