### ISSUE TITLE
本地与云端流程逻辑判断

### ISSUE THREAD

**Issue by ershouqingge** [bpking1/embyExternalUrl#276]
我这边emby目前是本地有一个媒体库。我用的项目的旧版，因为更新调试比较麻烦，如果有ui简单配置就好了。

我用gtp简单把之前的改了一下以符合我的需求。

之前好像是全部去alist拿直链，拿不到才返回本地，这样响应时间比较长，而且会造成资源浪费。

我加了一个路径判断，从emby的api拿到链接后，提取一下面前的几级目录跟embyMountPath进行对比判断，如果匹配说明是云盘文件就走alist拿直链，如果不匹配说明是本地文件，直接内部重定向。

我看最近这个项目更新了非常多，感谢

**Comment by chen3861229** [comment]
嗯，新版这块的逻辑被抽取到以下位置了，可以参考下，不过改后能用就行了

emby2Alist\nginx\conf.d\emby.js 第 83 行
const routeMode = util.getRouteMode(r, embyRes.path, false, embyRes.notLocal);
=>
emby2Alist\nginx\conf.d\common\util.js 第 125 行
if (isProxy(r, proxyRules, filePath, isAlistRes, notLocal)) {
=>
emby2Alist\nginx\conf.d\common\util.js 第 173 行
```js
function isProxy(r, proxyRules, filePath, isAlistRes, notLocal) {
  const disableRedirectRule = proxyRules;
  const mountPath = config.mediaMountPath;
  if (!isAlistRes) {
    // exact, local file not mediaMountPath first
    if (mountPath && mountPath.every(path => path && !filePath.startsWith(path) && !notLocal)) {
      ngx.log(ngx.WARN, `hit proxy, not mountPath first: ${JSON.stringify(mountPath)}`);
      return true;
    }
    // indeterminate, regard notLocal and mediaMountPath empty default as local file
    if (mountPath && Array.isArray(mountPath) 
      && (mountPath.length === 0 || mountPath.every(p => p.length === 0)) && !notLocal) {
      ngx.log(ngx.WARN, `hit proxy, maybe is localFile: ${JSON.stringify(mountPath)}`);
      return true;
    }
  }
```
