### ISSUE TITLE
plex,用kodi的plex插件好像直链不成功

### ISSUE THREAD

**Issue by xinxuxu** [bpking1/embyExternalUrl#280]
plex电视端碰到一些音频格式或者字幕就会触发转码，想用kod+plex插件的形式播放，只能走服务器流量
https://github.com/croneter/PlexKodiConnect

**Comment by chen3861229** [comment]
方便提供下 /nginx-plex2alist/log/error.log 日志吗？这样好排查一点，粘贴的时候注意替换自己的域名等隐私内容

**Comment by xinxuxu** [comment]
> 方便提供下 /nginx-plex2alist/log/error.log 日志吗？这样好排查一点，粘贴的时候注意替换自己的域名等隐私内容

费了老大的劲 安装kodi+插件，发现这插件好像直接走32400端口，都不产生log的，不折腾了，还是emby直接拿来用好

**Comment by xinxuxu** [comment]
> 方便提供下 /nginx-plex2alist/log/error.log 日志吗？这样好排查一点，粘贴的时候注意替换自己的域名等隐私内容

2024/07/13 15:19:38 [warn] 24#24: *4099 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/5/42/0000000425 while reading upstream, client: xxx.xxx.xxx.xx, server: default, request: "GET /library/parts/1824/1711109591/?X-Plex-Token=CDyq4KKGL6srTEv4rK7t&X-Plex-Client-Profile-Name=Generic&X-Plex-Client-Identifier=b2088c45-28e1-42d9-9240-0625f8e119bd HTTP/1.1", upstream: "http://192.168.50.150:32400/library/parts/1824/1711109591/?X-Plex-Token=CDyq4KKGL6srTEv4rK7t&X-Plex-Client-Profile-Name=Generic&X-Plex-Client-Identifier=b2088c45-28e1-42d9-9240-0625f8e119bd", host: "域名:32410"
2024/07/13 15:19:43 [warn] 23#23: *4143 js: === plexApiHandler: /library/metadata/4018, the NJS VM is destroyed ===
2024/07/13 15:19:43 [warn] 23#23: *4085 js: === plexApiHandler: /library/sections/7/all, the NJS VM is destroyed ===
2024/07/13 15:19:43 [warn] 22#22: *4146 js: === plexApiHandler: /library/sections/7/all, the NJS VM is destroyed ===
2024/07/13 15:19:43 [warn] 23#23: *4085 js: === plexApiHandler: /library/sections/2/all, the NJS VM is destroyed ===
2024/07/13 15:19:43 [warn] 23#23: *4085 js: === plexApiHandler: /library/metadata/4018, the NJS VM is destroyed ===
2024/07/13 15:19:43 [warn] 23#23: *4085 js: === plexApiHandler: /library/metadata/4018, the NJS VM is destroyed ===



大佬，应该是这部分吧？

**Comment by chen3861229** [comment]
> http://192.168.50.150:32400/library/parts/1824/1711109591

虽然不是很全，但是请求是进入 NJS 中了，这个就是 plex 的串流或下载的链接

**Comment by xinxuxu** [comment]
好的，谢谢 可能是我哪里操作不当
