### ISSUE TITLE
用了strm，本地的nfo信息会被emby修改，很多片子的演员都变同一个人了，这个有的解决吗

### ISSUE THREAD

**Issue by szyevan** [bpking1/embyExternalUrl#283]

**Comment by chen3861229** [comment]
还有个折中方案是 ，不开启，元数保存储方式 NFO 和 将媒体图像保存到媒体文件夹中 ，开启后，这个两个选项给予了 emby server 的文件写入权限，这两个数据已经被 emby server 接管了，所以会进行删除和写入的操作，关闭后用刮削软件一次性维护就行了

出处
https://github.com/bpking1/embyExternalUrl/issues/299#issuecomment-2239110913
