### ISSUE TITLE
emby安卓客户端的下载功能异常

### ISSUE THREAD

**Issue by Katou-Kouseki** [bpking1/embyExternalUrl#284]
如题，尝试下载十部剧集，可能只有一部实际下载成功，大部分都卡在已列队。我看项目中安卓似乎是走的Sync，不知道是否有关联。

**Comment by chen3861229** [comment]
十部大概有多少集？不知道是不是报文太大超出代码中的 8MB 限制了，
emby2Alist\nginx\conf.d\emby.js 第 473 行

```js
async function fetchEmbyFilePath(itemInfoUri, itemId, Etag, mediaSourceId) {
...
max_response_body_size: 8388608, // bytes, default 32KB this is 8MB
```
可改为 16 MB 或 更大试一下
```js
async function fetchEmbyFilePath(itemInfoUri, itemId, Etag, mediaSourceId) {
...
max_response_body_size: 16 * 1024 * 1024, // bytes, default 32KB
```

**Comment by Katou-Kouseki** [comment]
尝试改成了32 MB没有变化，一般播放成功会有触发NJS的日志吧，这个似乎没看到有，但日志中有Sync的相关段落。文件里是一段从打开客户端在首页长按一部剧集点下载后的操作过程中产生的日志，劳烦帮忙看看了。
[emby-nginx-20240713224211.log](https://github.com/user-attachments/files/16202591/emby-nginx-20240713224211.log)

**Comment by chen3861229** [comment]
那和 8MB 没关系，我这边测试了下，单剧集下的 50 集是够用的，安卓客户端的 Sync 下载也会有 NJS 的日志打印，你的日志中有一些 Sync 相关接口的查询信息，但是不知道为什么没有最关键的，GET /emby/Sync/JobItems/57437/File?api_key=xxx HTTP/2.0" 302 138 , 这个是 emby 原始真正的下载请求链接

![QQ_1720885063845](https://github.com/user-attachments/assets/c027b47c-9368-4c52-97ae-f3bc563049a9)
![QQ_1720885567575](https://github.com/user-attachments/assets/3d53f63e-3906-4ffc-a7ca-3888a3620798)
![QQ_1720885642004](https://github.com/user-attachments/assets/b6baebfe-01d9-4dc1-8dec-25a3024972d7)
![image](https://github.com/user-attachments/assets/d7f17dba-1520-46ae-8158-ba2fc3480bf2)

**Comment by chen3861229** [comment]
怀疑是不是客户端设备存储占满了？虽然未下载的文件是 0 KB 在客户端上占位的

**Comment by Katou-Kouseki** [comment]
设备存储是正常的，因为已经用过不止一台设备进行测试了，其实一直以来都受到该问题的困扰了，自己尝试过看日志也没搞懂问题的原因，平均下来可能下载成功率不到10%😭。不知道与安卓客户端是否有关系呢，我这里用了两个客户端进行测试，一个是来自emby小秘的，另一个是kirlif的。
![Screenshot_2024-07-13-23-58-30-421_com miui securitycenter](https://github.com/user-attachments/assets/49d5219d-47d9-4e96-981f-cfb789d35208)
![Screenshot_2024-07-13-23-58-48-679_com miui securitycenter](https://github.com/user-attachments/assets/731dd6d2-1cce-4e8b-9c19-be6ad4a6f08e)

**Comment by chen3861229** [comment]
1.有可能与客户端有关，因为日志中没有发起 GET /emby/Sync/JobItems/57437/File?api_key=xxx HTTP/2.0" 302 138 到服务端上了，我这边都是用的小秘版的

2.这个和服务端的开心版也稍微有些关系，之前用的 lovechen 镜像的某些版本没有开心到位，可以在 emby 服务端启用调试日志中看到被禁用了，因为客户端的 /Sync 下载功能是收费的，目前在用的 amilys/embyserver:latest 是没问题的

**Comment by Katou-Kouseki** [comment]
我目前的镜像是 amilys/embyserver:beta，最近没去更新镜像，应该是 4.9.0.25 的版本。

**Comment by chen3861229** [comment]
amilys/embyserver:beta 换到了 4.9.0.26 ，客户端版本是 Emby for Android_3.2.32_v17.41(Carnival) ，还是复现不出来，日志表现基本和上边一样，貌似没啥排查办法了，应该和客户端版本没啥关系，朋友里客户端有用历史版本小秘的，

![image](https://github.com/user-attachments/assets/c8045dae-b29e-49df-bbd4-eebdf8f68a92)

这个公用用户的设置项应该也没啥不同

![QQ_1720897409823](https://github.com/user-attachments/assets/94149198-33ae-4a4d-ae2a-d2d2c108af41)

![QQ_1720897445535](https://github.com/user-attachments/assets/5a9af48c-b9aa-487e-a44f-e2b317a765d9)

**Comment by Katou-Kouseki** [comment]
辛苦大佬的测试了，昨晚我也多次尝试但都没有结果，日志始终没有打印出 GET /emby/Sync/JobItems/57437/File?api_key=xxx HTTP/2.0" 302 138 的相关字段。但是今早起来看服务端发现昨天“已列队”的两项变成“准备传输”，打开客户端一看下载任务马上就自己开始了，此时查看日志也有 "GET /emby/Sync/JobItems/57437/File"的相关字段😂

**Comment by chen3861229** [comment]
啊，这个很久之前加 SyncApi 重定向的时候提过，我自己也忘了，不过没事，能正常用了就行，emby 的这个 SyncApi 设计得很有问题，如果通知栏没有出现正在下载的通知，需要杀进程重开 app 多触发几次，然后如果单次下载的任务太多，需要等几十秒才会开始，而且移除了单个任务，服务端实时生效，但客户端任务列表里的不会消失，会一个个请求 emby 服务端返回 404 和 500 依次失败弹出通知栏，很烦，推荐单个任务不要添加太多的队列了，即单次下载单季剧集

> 看起来就像是在排队后才执行的任务

其实 emby 的 SyncApi 内部确实就是这样实现的，估计是为了减轻服务端压力吧，可能原始涉及部分转码，只能想出这个优点了，然后其他 bug 一堆

**Comment by Katou-Kouseki** [comment]
但是实际没到能够正常用的阶段。也试过放置在那里数十分钟不会有变化，放一晚上倒是可能进准备传输状态了。另外杀进程重开几次也尝试过的。 

> 而且移除了单个任务，服务端实时生效，但客户端任务列表里的不会消失，会一个个请求 emby 服务端返回 404 和 500 依次失败弹出通知栏

这个深有同感，明明移除掉的下载任务客户端还是会进行

**Comment by chen3861229** [comment]
试下勾选这个全速转换呢？虽然我没对比过，单纯只是我禁用了所有用户的转码权限，且知道这个下载过程并不会走转换任务/转码，所以暂不清楚这个选项是否能加速任务的准备队列

![QQ_1720939124939](https://github.com/user-attachments/assets/3dd8eddc-b8bf-49f3-a97c-644311aa4fd6)

**Comment by Katou-Kouseki** [comment]
辛苦大佬解答和测试了，方法都试过了都不大行，目前判断就是emby的排队导致，只能web端观察下载请求变成“准备传输”时打开安卓客户端会进行下载。
