### ISSUE TITLE
使用alist2emby反代后在web访问无论是strm文件还是本地的mkv文件都提示不兼容的流

### ISSUE THREAD

**Issue by Akimio521** [bpking1/embyExternalUrl#286]
请问这个正常，反代后只能通过客户端播放吗

**Comment by palonnn** [comment]
> 请问这个正常，反代后只能通过客户端播放吗

web播放貌似已经有解决方案了，https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

**Comment by Akimio521** [comment]
看到了`constant-transcode.js`，配置了一下web可以正常播放，但是本地转码失效了....
里面的变量名看着有点懵，我说一下我的情况和配置情况

# 个人情况
## 视频
目前我的影视库有三种视频：
- 本地视频：大部分为内封字幕，少部分为内嵌字幕、外挂字幕和外挂音轨，映射到emby容器内的/media/local
- Strm：
  - 视频源链接：浏览器访问这个链接可以直接下载视频，公网可以直接访问下载，大部分为内嵌字幕、少部分为内封字幕和外挂字幕，映射到emby容器内的/media/strm/url
  - Alist下载链接：通过Alist代理网盘的视频，公网也可也直接访问到这个链接进行下载，映射到emby容器内的/media/strm/alist

## 容器环境
- EmbyServer：host
- Emby-Nginx：bridge
- Nginx-Proxy-Manager：brigde

## 关于网络
1. => NPM提供SSL和统一端口反代NAS上所有的程序，这里反代了Emby-Nginx的8091
2. => Emby-Nginx反代EmbyServer的8096
3. => EmbyServer
- 备注：
  - 如果可以把emby2alist集成到NPM的话更好，但不太懂Nginx
  - NPM使用了自定义的bridge网桥，方便我直接通过容器名直接反代，但似乎这样会丢失访问者的真实IP变成一个B类的私有地址（docker-bridge网桥gateway地址），似乎debian系统可以通过一些操作传递真实的IP，但群晖魔改太多了，无解
  - 所有访问都通过公网URL进行访问，因为最前面的NPM的网络是bridge，所以EmbyServer看到所有的访问都是私有地址

# 需求
- 本地视频可以转码播放
- Strm视频可以直接302重定向
- Web最好能直接播放（大部分Strm都是h264的）

# 当前配置
目前我配置下面几个地方，
```js
const embyHost = "http://172.17.0.1:8096";
const embyApiKey = "ebbcbxxxxxxxxx9e12f";
const mediaMountPath = ["/media/strm"];
```

```js
const transcodeConfig = {
  enable: true,
  enableStrmTranscode: false,
  type: "distributed-media-server", 
  maxNum: 3,
  redirectTransOptEnable: true,
  targetItemMatchFallback: "redirect", 
  server: []
};
```

# 当前效果：
 - 可以正常播放（本地视频正常推流，Strm视频302重定向）
 - 但是本地视频无法转码
