### ISSUE TITLE
反代后可以获取302直链  并且顺利播放 但是播放本地硬盘是就会报错 请大佬帮忙看一下 是bug还是我的问题

### ISSUE THREAD

**Issue by felix-klk** [bpking1/embyExternalUrl#29]
![image](https://github.com/bpking1/embyExternalUrl/assets/52670643/b8410ff0-f28f-45bd-8788-a676493a9e53)

**Comment by felix-klk** [comment]
可以播放的链接如下 
http://192.168.3.99:38096/emby/videos/61894/stream.mkv?api_key=5972849eee2543ddb2cbbf4e834779bc&Static=true&MediaSourceId=a65eebf94413d3f69196accb493003aa

potplayer://http://192.168.3.99:38096/emby/videos/61894/stream.mkv?api_key=5972849eee2543ddb2cbbf4e834779bc&Static=true&MediaSourceId=a65eebf94413d3f69196accb493003aa%20/sub=%20/current%20/title=%22%E7%96%AF%E7%8B%82%E5%85%83%E7%B4%A0%E5%9F%8E%20(2023)%20-%202160p%20WEB-DL%20H265.mkv%22%20/seek=0:00

反代后8095不能播放的链接如下 
http://192.168.3.99:38095/emby/videos/61894/stream.mkv?api_key=4fe0c9c9eff74cc99c3ef8e834917667&Static=true&MediaSourceId=a65eebf94413d3f69196accb493003aa

**Comment by felix-klk** [comment]
打开 报错如下
Not Found
The requested URL /p/mnt/data_sdb1/infuse/%E7%94%B5%E5%BD%B1/%E5%8A%A8%E7%94%BB%E7%94%B5%E5%BD%B1/%E7%96%AF%E7%8B%82%E5%85%83%E7%B4%A0%E5%9F%8E%20%282023%29/%E7%96%AF%E7%8B%82%E5%85%83%E7%B4%A0%E5%9F%8E%20%282023%29%20-%202160p%20WEB-DL%20H265.mkv?sign=dcdee2q5y-ZUHtTbnPG5-jA03HLOydgN9--UQTEZ7JM=:0 was not found on this server.

**Comment by felix-klk** [comment]
![image](https://github.com/bpking1/embyExternalUrl/assets/52670643/8e142ad0-3389-417a-90be-b0720a7c51c6)
本地挂载rclone 的alist路径 在/mnt/alist 
emby 容器安装 媒体文件也是使用/mnt 下的路径
![image](https://github.com/bpking1/embyExternalUrl/assets/52670643/add042ab-1ae6-4aea-afda-23915a5ef993)

我设置参数时只能设置embyMountPath 配置为 /mnt/alist 才能成功获取直连  
但是播放本地视频时候报错

**Comment by AmbitiousJun** [comment]
源码里面，在 Alist 找不到资源就会直接返回 404，我尝试修复了一下，但是没办法测试，你可以到我的仓库下载代码试试：https://github.com/AmbitiousJun/embyExternalUrl

**Comment by felix-klk** [comment]
h

> 源码里面，在 Alist 找不到资源就会直接返回 404，我尝试修复了一下，但是没办法测试，你可以到我的仓库下载代码试试：https://github.com/AmbitiousJun/embyExternalUrl

好的谢谢大佬
