### ISSUE TITLE
今天的更新有什么问题吗？

### ISSUE THREAD

**Issue by lw6644700** [bpking1/embyExternalUrl#291]
按照以前的配置，今天更新版本无法播放，日志提示js exception: Error: unhandled promise rejection: ReferenceError: cannot access variable before initialization
    at redirect2Pan (/etc/nginx/conf.d/emby.js:19)

没有返回直链，要怎么处理啊？

**Comment by chen3861229** [comment]
不好意思，可能是前天晚上更新的代码有个变量大意忘了导出了，昨晚的修复应该已经修复了，可以尝试下更新下代码

**Comment by lw6644700** [comment]
还是不行呀，有返回直链地址，但是infuse播放错误，我复制日志的返回地址在浏览器打开会显示下面的内容，好像从14号的版本开始都是这样，退回之前的就正常，是还有哪里需要配置？以前更新我配置constant.js文件和constant-mount.js文件就行了，现在多了地方需要配置？

{
    "code": 401,
    "message": "sign invalid",
    "data": null
}

**Comment by chen3861229** [comment]
{
"code": 401,
"message": "sign invalid",
"data": null
}
这块应该和 14 后的修改没太大关系，看提示是 alist 接口返回签名过期了，这两个有配置过吗？最近的修改没动这块参数

emby2Alist\nginx\conf.d\config\constant-mount.js

```js
// alist 是否启用了 sign
const alistSignEnable = false;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 12;
```

**Comment by lw6644700** [comment]
这是我constant.js文件的配置
![image](https://github.com/user-attachments/assets/411b068b-97e4-4060-813a-58d9f297fd9c)

这是我constant-mount.js文件的配置
<img width="859" alt="image" src="https://github.com/user-attachments/assets/dbc7bf9a-5d4c-43c2-8d1b-45f31492f9dc">

这是我的日志，返回了直链，但是错误的直链
<img width="1917" alt="image" src="https://github.com/user-attachments/assets/3fd8510a-352b-4c70-8b6b-27537e0ccc70">


我只配置了这两个文件，并且旧版本用这样的配置能使用

**Comment by chen3861229** [comment]
知道原因了，抱歉，之前 emby.js 中有个 handleAlistRawUrl 取值的 alist sign 是从 /fs/get 接口返回值取的 sign ，所以一定是正确的，
https://github.com/bpking1/embyExternalUrl/commit/08f7f85e4f878fd6e3b8c49d5306959c84c728e2

这个修改中做了抽取统一逻辑，所以目前的 alist sign 值必须配置正确的参数以计算正确的 sign 值，所以需要把 alistSignExpireTime 严格改为 alist 服务端中设定的值，

```js
// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 0;
```

![QQ_1721226498126](https://github.com/user-attachments/assets/6671901f-bc18-44dc-84d5-fa149d2e1c1f)

**Comment by lw6644700** [comment]
奇怪了，我alist直链有效时间是0，alistSignExpireTime我也改成0了，返回的直链打开还是显示
{
    "code": 401,
    "message": "sign invalid",
    "data": null
}

我alist关闭签名，alistSignEnable改回默认的false可以播放了，我先关闭签名使用吧😄

**Comment by chen3861229** [comment]
已经修复，为了安全，alist 签名还是建议打开

**Comment by lw6644700** [comment]
> 已经修复，为了安全，alist 签名还是建议打开

最新的开启签名可以了，谢谢
