### ISSUE TITLE
alist路径映射不会根据设置规则替换

### ISSUE THREAD

**Issue by nbazedong** [bpking1/embyExternalUrl#298]
配置了路径替换，但是好像不会替换成功。把alist挂载路径设置成【影音库/volume1/CloudNAS/CloudDrive/阿里云盘0900】就可以获取到。

设置的参数如下：
const mediaMountPath = [""];
const mediaPathMapping = [
  [0, 0, "/volume1/CloudNAS/CloudDrive","/影音库"]
];

日志输出：
[warn] 21#21: *874 js: mount emby file path: /volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4
2024/07/18 16:18:13 [warn] 21#21: *874 js: getRouteMode: redirect
2024/07/18 16:18:13 [warn] 21#21: *874 js: mediaPathMapping: [[0,0,"/volume1/CloudNAS/CloudDrive","/影音库"]]
2024/07/18 16:18:13 [warn] 21#21: *874 js: mapped emby file path: /volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4
2024/07/18 16:18:13 [warn] 21#21: *874 js: sourceStrValue, alistRes = /volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4
2024/07/18 16:18:13 [warn] 21#21: *874 js: 1ms, fetchAlistPathApi async function cost
2024/07/18 16:18:13 [warn] 21#21: *874 js: fetchAlistPathApi, UA: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
2024/07/18 16:18:13 [warn] 21#21: *874 js: alistRes: error500: alist_path_api 500 failed get storage: storage not found; rawPath: /volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4
2024/07/18 16:18:13 [warn] 21#21: *874 js: will req alist /api/fs/list to rerty
2024/07/18 16:18:16 [warn] 21#21: *874 js: try to fetch alist path from /影音库/volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4

**Comment by chen3861229** [comment]
> /volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4

这个文件路径对应的 emby 入库的文件类型是什么样的？是 strm 这种远程链接文件的形式吗

**Comment by nbazedong** [comment]
> > /volume1/CloudNAS/CloudDrive/阿里云盘0900/影音库/Media/电影/外语电影/哥 (2016)/哥 (2016).mp4
> 
> 这个文件路径对应的 emby 入库的文件类型是什么样的？是 strm 这种远程链接文件的形式吗

是的。strm文件

**Comment by chen3861229** [comment]
路径映射 strm 参数需要更改下第二个参数类型为 1 或 2，从日志中路径初步判断应该设置为 1 ，具体需要以实际类型为准

```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  [0, 1, "/volume1/CloudNAS/CloudDrive","/影音库"]
];
```

**Comment by Muggles001** [comment]
> 路径映射 strm 参数需要更改下第二个参数类型为 1 或 2，从日志中路径初步判断应该设置为 1 ，具体需要以实际类型为准
> 
> ```js
> // 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
> // 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const mediaPathMapping = [
>   [0, 1, "/volume1/CloudNAS/CloudDrive","/影音库"]
> ];
> ```

你好本地cd2挂在目录是/volume1/pt/CloudDrive/115  alist上是/115  emby上是/volume1/pt/CloudDrive/115/电影等，应该如何设置，然后图片上设置是否正确，谢谢您解答
<img width="1280" alt="febb4d703ac7b454132e760d39ff8f6" src="https://github.com/user-attachments/assets/3f5897ff-8ce4-423a-860d-8e10a3098100">

**Comment by nbazedong** [comment]
> 路径映射 strm 参数需要更改下第二个参数类型为 1 或 2，从日志中路径初步判断应该设置为 1 ，具体需要以实际类型为准
> 
> ```js
> // 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
> // 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const mediaPathMapping = [
>   [0, 1, "/volume1/CloudNAS/CloudDrive","/影音库"]
> ];
> ```

明白了，原来是第二个参数的原因。按照这样配置已经可以了。顺便问下。我看日志里头mediaPathMapping数组也有两个参数，默认是0,0，配置里头mediaPathMapping参数是否也可以配置这两个参数，和mediaPathMapping一样呢？
mediaPathMapping: [[0,0,"/volume1/CloudNAS",""],[0,0,"/CloudDrive","/影音库"],[0,1,"/volume1/CloudNAS/CloudDrive","/影音库"]]

**Comment by chen3861229** [comment]
mediaPathMapping 中默认被添加加的 0, 0 的那个是兼容之前的参数 mediaMountPath 来的，即最终都是由 mediaPathMapping 按先后顺序进行字符串替换，所以同类型的规则不要重叠了，虽然可以这样写
```js
// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理,不用重复填写至 disableRedirectRule
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = ["/volume1/CloudNAS"];
``

> mediaPathMapping: [[0,0,"/volume1/CloudNAS",""],[0,0,"/CloudDrive","/影音库"],[0,1,"/volume1/CloudNAS/CloudDrive","/影音库"]]

不会出现问题，但是规则可能有些多余，假如存在这样一个本地挂载文件，非 strm 的情况下，

/volume1/CloudNAS/1.xxx
=> [0,0,"/volume1/CloudNAS",""]
/1.xxx
=> [0,0,"/CloudDrive","/影音库"]，对于这个文件路径不会做任何操作了，因为没有命中，但是对于 /CloudDrive/1.xxx 是命中的
/1.xxx

所以具体还是以个人实际情况判断
