### ISSUE TITLE
出现一个EMBY刷新元数据后，本地封面图片文件丢失的问题

### ISSUE THREAD

**Issue by Moe8383** [bpking1/embyExternalUrl#299]
采用STRM的方案，源网盘媒体已经刮削好了，同步到本地盘。导入EMBY后一切正常，但对媒体库“刷新元数据、覆盖图片”后，原来已有的图片文件就被全部删除了，媒体库显示是有图像的，但本地盘里面的图片文件没了。重新删除媒体库再建，再刷新元数据覆盖原图片，又会在本地盘生成图片。请问是什么原因呢？？
EMBY媒体库设置：读取NFO、元数据NFO存储、将媒体图像保存到媒体文件夹中。

**Comment by chen3861229** [comment]
不建议开启，元数保存储方式 NFO 和 将媒体图像保存到媒体文件夹中 ， 这个两个选项给予了 emby server 的文件写入权限，所以导致了描述中的问题，这两个数据已经被 emby server 接管了，所以会进行删除和写入的操作

> 媒体库显示是有图像的

这个是因为 nginx 对图像进行了缓存，以下是默认的配置值，更新代码后可以设置为 3 ，关闭 nginx 这层上的缓存
emby2Alist\nginx\conf.d\config\constant-ext.js
```js
// 图片缓存策略,包括主页、详情页、图片库的原图,路由器 nginx 请手动调小 conf 中 proxy_cache_path 的 max_size
// 0: 不同尺寸设备共用一份缓存,先访问先缓存,空间占用最小但存在小屏先缓存大屏看的图片模糊问题
// 1: 不同尺寸设备分开缓存,空间占用适中,命中率低下,但契合 emby 的图片缩放处理
// 2: 不同尺寸设备共用一份缓存,空间占用最大,移除 emby 的缩放参数,直接原图高清显示
// 3: 关闭 nginx 缓存功能,已缓存文件不做处理
const imageCachePolicy = 0;
```

**Comment by Moe8383** [comment]
> 不建议开启，元数保存储方式 NFO 和 将媒体图像保存到媒体文件夹中 ， 这个两个选项给予了 emby server 的文件写入权限

考虑是有些视频想交给emby刮削

**Comment by chen3861229** [comment]
> 考虑是有些视频想交给emby刮削

这样也可以，如果图片都不是直接存储在网盘上的话，可以关闭 const imageCachePolicy = 3; nginx 图片缓存来更直观的感受到 emby server 图片的修改

**Comment by Moe8383** [comment]
> 这样也可以，如果图片都不是直接存储在网盘上的话

有些图片在网盘，有些不在……应该怎么办？缺失的想让emby刮，不缺的就用本地的（从网盘同步）

**Comment by chen3861229** [comment]
那就保持最初的配置情况不做变动就行了，最初的设置是没问题的，仅仅只是被 nginx 缓存导致的这个 媒体库显示是有图像的 影响到了，其余都是 emby server 的符合需求情况的一个现象，需要手动更新 nginx 缓存文件的话，这里有几种方案

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#21%E5%9B%A0%E4%B8%BA%E5%9B%BE%E7%89%87%E7%BC%93%E5%AD%98%E5%AF%BC%E8%87%B4%E6%9B%B4%E6%96%B0%E6%B5%B7%E6%8A%A5%E4%B8%8D%E7%94%9F%E6%95%88

**Comment by Moe8383** [comment]
> 那就保持最初的配置情况不做变动就行了，最初的设置是没问题的，仅仅只是被 nginx 缓存导致的这个 媒体库显示是有图像的 影响到了，其余都是 emby server 的符合需求情况的一个现象，需要手动更新 nginx 缓存文件的话，这里有几种方案
> 
> 
> 
> https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#21%E5%9B%A0%E4%B8%BA%E5%9B%BE%E7%89%87%E7%BC%93%E5%AD%98%E5%AF%BC%E8%87%B4%E6%9B%B4%E6%96%B0%E6%B5%B7%E6%8A%A5%E4%B8%8D%E7%94%9F%E6%95%88

感谢感谢！
