### ISSUE TITLE
Jellyfin 多版本适配 fileball ios客户端

### ISSUE THREAD

**Issue by zsbai** [bpking1/embyExternalUrl#3]
Jellyfin多个视频版本都只会重定向到默认版本，如某个电视剧有720p和1080p两个版本，不论选哪一个都重定向到720p的链接
Onedrive存储

**Comment by bpking1** [comment]
应该是njs还不支持这个语法，请求有mediasourceid就能定位到正确的版本了，所以只返回一个结果是正常的，不需要etag来区分
