### ISSUE TITLE
有人在外面的vps上布置115直链吗

### ISSUE THREAD

**Issue by chaomarks** [bpking1/embyExternalUrl#300]
好像不能网页播放，和没有播放记录，配置和阿里云一样

**Comment by chen3861229** [comment]
> 好像不能网页播放

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#6115-%E5%86%85%E5%AE%B9%E6%97%A0%E6%B3%95-web-%E7%AB%AF%E6%92%AD%E6%94%BEhtmlvideoplayer-%E8%B7%A8%E5%9F%9F

> 和没有播放记录

这个需要保证 emby server 有正常扫描出媒体的编码和时长信息，媒体详情页的副标题/次标题，可以看到时长信息，且详情页最下方必须出现媒体信息的详细描述

**Comment by chaomarks** [comment]
> > 好像不能网页播放
> 
> https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#6115-%E5%86%85%E5%AE%B9%E6%97%A0%E6%B3%95-web-%E7%AB%AF%E6%92%AD%E6%94%BEhtmlvideoplayer-%E8%B7%A8%E5%9F%9F
> 
> > 和没有播放记录
> 
> 这个需要保证 emby server 有正常扫描出媒体的编码和时长信息，媒体详情页的副标题/次标题，可以看到时长信息，且详情页最下方必须出现媒体信息的详细描述

我测试将strm内容换成docker的内网地址http://172.17.0.1:5244/d/开头,同样的配置然后有这么几种情况网页播放
阿里云的服务器：阿里云域名可以且有记录可继续播放，CF域名不可以，IP+端口可以且有记录可继续播放
外面的VPS服务器：CF域名可以，IP+端口可以且都没有记录
不知道是不是115的问题

**Comment by chen3861229** [comment]
应该和 115 没啥关系，它只复杂传输媒体内容，播放记录和进度是由 emby 管理的，感觉像是这块的接口稳定性不行，不过 emby 的播放进度记录分为两块，具体我也不是很清楚重要等级
1.只在首次进入 emby 时客户端会发送一个 socket 到服务器进行长连接，如果成功，部分进度信息会通过此长连接汇报，假如连接失败，貌似也不影响功能，且长连接之后不会再进行重试
```
# Proxy sockets traffic for jellyfin-mpv-shim and webClient
    location ~* /(socket|embywebsocket) {
        # Proxy emby/jellyfin Websockets traffic
        proxy_pass $emby;
        ## WEBSOCKET SETTINGS ## Used to pass two way real time info to and from emby and the client.
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_connect_timeout 1h;
        proxy_send_timeout 1h;
        proxy_read_timeout 1h;
        tcp_nodelay on;  ## Sends data as fast as it can not buffering large chunks, saves about 200ms per request.
    }
```

2.第二种就是播放过程中每隔几秒会发送 http 普通请求接口上报播放进度，不过也不是 100 % 汇报，我这边也遇到过没有调用
/Sessions/Playing 接口的情况，不过是属于小概率事件 
```
# Sessions Playing Stats
    location ~* /Sessions/Playing
```

**Comment by chaomarks** [comment]
问题找到了，是emby容器在谷歌云里用bridge模式就无法访问外面网络也无法刮削，host模式就可以还可以有播放记录，不知道什么原因
