### ISSUE TITLE
无法使用emby内置搜索功能及手动搜刮元数据无效。

### ISSUE THREAD

**Issue by zackfair1993** [bpking1/embyExternalUrl#301]
使用docker版本部署，原可以使用emby的搜索功能定位影片，但使用自动更新后，新版本搜索无效。需要会退版本。同时手动搜刮元数据功能也无法触发。跳转非代理可正常搜刮。

**Comment by chen3861229** [comment]
> 新版本搜索无效

1.试了下是搜索功能是没问题的，不过因为这几天确实给搜索栏加了个交互性指令的新功能，默认是关闭的，前天代码有些小问题，需要等段时间稳定了再更新吧

> 同时手动搜刮元数据功能也无法触发。跳转非代理可正常搜刮。

2.没动过这个 emby api 的修改，请问是指在剧集上右键，编辑元数据，这个选项吗？

**Comment by zackfair1993** [comment]
大神，验证过windows客户端和安卓端，确定搜索有问题。然后元数据问题，检验后安卓端版本的bug导致。

**Comment by chen3861229** [comment]
感觉还是大概率与前几天我这边过大的更改有关，如果方便的话先暂时使用可用的版本吧，等构建那边同步了新代码应该就没问题了

**Comment by fengero** [comment]
同最新docker版 无法使用搜索，infuse也是 贴上log

##### emby网页版
2024/07/23 19:07:13 [error] 25#25: *440 js exception: Error: unhandled promise rejection: TypeError: cannot get property "interactiveEnableRule" of undefined
    at searchHandle (/etc/nginx/conf.d/modules/emby-search.js:20)
, client: 192.168.10.1, server: default, request: "GET /emby/Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?SearchTerm=%E5%A4%A7%E6%98%8E%E7%8E%8B%E6%9C%9D1566+%282007%29&Recursive=true&Fields=PrimaryImageAspectRatio%2CPremiereDate%2CProductionYear&EnableUserData=false&GroupProgramsBySeries=true&Limit=30&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+macOS&X-Emby-Device-Id=8411bf90-8c5f-460a-a66b-62f18f234e52&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=1ea94032216443b99de3cfe617d3cb48&X-Emby-Language=zh-cn HTTP/1.1", host: "xxxx.xxxxxx.top:xxxxxx"
192.168.10.1 - - [23/Jul/2024:19:07:13 +0000] "GET /emby/Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?SearchTerm=%E5%A4%A7%E6%98%8E%E7%8E%8B%E6%9C%9D1566+%282007%29&Recursive=true&Fields=PrimaryImageAspectRatio%2CPremiereDate%2CProductionYear&EnableUserData=false&GroupProgramsBySeries=true&Limit=30&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+macOS&X-Emby-Device-Id=8411bf90-8c5f-460a-a66b-62f18f234e52&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=1ea94032216443b99de3cfe617d3cb48&X-Emby-Language=zh-cn HTTP/1.1" 500 572 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"

##### infuse

2024/07/23 19:09:17 [error] 26#26: *493 js exception: Error: unhandled promise rejection: TypeError: cannot get property "interactiveEnableRule" of undefined
    at searchHandle (/etc/nginx/conf.d/modules/emby-search.js:20)
, client: 192.168.10.1, server: default, request: "GET /Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?ExcludeLocationTypes=Virtual&Fields=DateCreated,Etag,Genres,MediaSources,AlternateMediaSources,Overview,ParentId,Path,People,ProviderIds,SortName,RecursiveItemCount,ChildCount,CommunityRating,OfficialRating,PremiereDate&SearchTerm=%E7%81%AB%E6%98%9F%E6%95%91%E6%8F%B4&Recursive=true&Limit=50 HTTP/1.1", host: "xxxx.xxxx.top"
192.168.10.1 - - [23/Jul/2024:19:09:17 +0000] "GET /Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?ExcludeLocationTypes=Virtual&Fields=DateCreated,Etag,Genres,MediaSources,AlternateMediaSources,Overview,ParentId,Path,People,ProviderIds,SortName,RecursiveItemCount,ChildCount,CommunityRating,OfficialRating,PremiereDate&SearchTerm=%E7%81%AB%E6%98%9F%E6%95%91%E6%8F%B4&Recursive=true&Limit=50 HTTP/1.1" 500 170 "-" "Infuse-Direct/7.8" "-"

**Comment by fengero** [comment]
> 同最新docker版 无法使用搜索，infuse也是 贴上log
> 
> ##### emby网页版
> 2024/07/23 19:07:13 [error] 25#25: *440 js exception: Error: unhandled promise rejection: TypeError: cannot get property "interactiveEnableRule" of undefined at searchHandle (/etc/nginx/conf.d/modules/emby-search.js:20) , client: 192.168.10.1, server: default, request: "GET /emby/Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?SearchTerm=%E5%A4%A7%E6%98%8E%E7%8E%8B%E6%9C%9D1566+%282007%29&Recursive=true&Fields=PrimaryImageAspectRatio%2CPremiereDate%2CProductionYear&EnableUserData=false&GroupProgramsBySeries=true&Limit=30&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+macOS&X-Emby-Device-Id=8411bf90-8c5f-460a-a66b-62f18f234e52&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=1ea94032216443b99de3cfe617d3cb48&X-Emby-Language=zh-cn HTTP/1.1", host: "xxxx.xxxxxx.top:xxxxxx" 192.168.10.1 - - [23/Jul/2024:19:07:13 +0000] "GET /emby/Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?SearchTerm=%E5%A4%A7%E6%98%8E%E7%8E%8B%E6%9C%9D1566+%282007%29&Recursive=true&Fields=PrimaryImageAspectRatio%2CPremiereDate%2CProductionYear&EnableUserData=false&GroupProgramsBySeries=true&Limit=30&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+macOS&X-Emby-Device-Id=8411bf90-8c5f-460a-a66b-62f18f234e52&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=1ea94032216443b99de3cfe617d3cb48&X-Emby-Language=zh-cn HTTP/1.1" 500 572 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" "-"
> 
> ##### infuse
> 2024/07/23 19:09:17 [error] 26#26: *493 js exception: Error: unhandled promise rejection: TypeError: cannot get property "interactiveEnableRule" of undefined at searchHandle (/etc/nginx/conf.d/modules/emby-search.js:20) , client: 192.168.10.1, server: default, request: "GET /Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?ExcludeLocationTypes=Virtual&Fields=DateCreated,Etag,Genres,MediaSources,AlternateMediaSources,Overview,ParentId,Path,People,ProviderIds,SortName,RecursiveItemCount,ChildCount,CommunityRating,OfficialRating,PremiereDate&SearchTerm=%E7%81%AB%E6%98%9F%E6%95%91%E6%8F%B4&Recursive=true&Limit=50 HTTP/1.1", host: "xxxx.xxxx.top" 192.168.10.1 - - [23/Jul/2024:19:09:17 +0000] "GET /Users/cbb3fca2d6f94bf18e2315e235129ebf/Items?ExcludeLocationTypes=Virtual&Fields=DateCreated,Etag,Genres,MediaSources,AlternateMediaSources,Overview,ParentId,Path,People,ProviderIds,SortName,RecursiveItemCount,ChildCount,CommunityRating,OfficialRating,PremiereDate&SearchTerm=%E7%81%AB%E6%98%9F%E6%95%91%E6%8F%B4&Recursive=true&Limit=50 HTTP/1.1" 500 170 "-" "Infuse-Direct/7.8" "-"

临时在constan.js内补上定义解决
```
const searchConfig = {
  // 开启脚本的部分交互性功能
  interactiveEnable: false,
  // 限定交互性功能的隔离,取值来源为带参数的 request_uri 字符串
  // 不带协议与域名,仅作包含匹配,多个值为或的关系,空数组为不隔离
  interactiveEnableRule: [
    // "ac0d220d548f43bbb73cf9b44b2ddf0e", // request_uri path level userId
    // "2d427412-43e1-49e4-a1db-fa17c04d49db", // X-Emby-Device-Id
  ],
};

# 末尾
export default {
###
searchConfig,
}
```

**Comment by chen3861229** [comment]
嗯，这样也可以，抱歉了，这几天在忙其它的
