### ISSUE TITLE
有个不成熟的想法

### ISSUE THREAD

**Issue by EscapeDG** [bpking1/embyExternalUrl#302]
alist网页直接播放媒体文件时选择aliyun video previewer播放可以选择sd\hd\qhd三种清晰度,在获取直连时能否直接获取这种转码后的链接进行播放，这样在需要转码的情况下直接调用

**Comment by chen3861229** [comment]
应该不会做这个，主要原因在于以下几点

1.alist 开放 API 中没找到此特定的实现，不过抓 alist 的网络请求应该可以试试，但这不是重点，以下有几个难实现的地方 https://alist-v3.apifox.cn

2.emby/jellyfin/plex 所以客户端的代码都是本地分开的，所以没有一个兼容性良好的交互方式，例如选择清晰度这个，实现起来工作量较大

3.还有是暂时有些偏离项目初衷了，脚本主要是实现直链的，我的个人理解是非原盘下，文件的画质拉到顶，个人强迫症是原文件不做任何损失转码之类的，所以 sd\hd 的选项不好理解，而 qhd 因国内各大互联网厂的惯犯，虽然没实际对比过，但我粗略认为应该还是要比原文件画质有所损失，从感觉上来说有些缺憾

4.阿里云盘最近口碑崩盘，人尽皆知言而无信，作为内测用户我也转到 115 上了，所以对于特定网盘的特定功能的对接动力不是很强，费劲加上了可能用不了多久

以上只是当前时间点的感受，如果之后有相同需求的人多了，可能会研究一下，抱歉了

**Comment by EscapeDG** [comment]
> 不应该做这个，主要目的在于以下几点
> 
> 1.alist开放API中没有找到这个特定的实现，不过抓alist的网络请求应该可以尝试，但不是重点，以下有几个难实现的地方https://alist-v3.apifox.cn
> 
> 2.emby/jellyfin/plex 所以客户端的代码都是本地分开的，所以没有一个兼容良好的交互方式，例如选择这个结构，实现了工作量增大
> 
> 3.还有一些暂时有些项目初衷了，剧本主要是实现直链的，我的个人理解是非原盘下，文件的画质拉到顶，个人强迫症是原文件不做任何损失转码之类的，所以 sd\hd 的选项不好理解，而 qhd 因国内一大互联网厂的惯性犯，虽然没有实际对比过，我粗略认为还是应该凑合，但原文件画质有所损失，感觉从上来说有些损失缺少遗憾
> 
> 4.阿里云盘最近口碑崩盘，人尽皆知言而无信，内测用户我也转到115上了，所以对于特定网盘的特定功能的对接动力不是最庞大，费劲加上了可能用不了多久
> 
> 以上只是当前时间点的感受，如果之后有相同需求的人多了，可能会研究一下，抱歉了

感谢解答，本人也是阿里内测用户，现在入115了，这个想法的产生是源于不开第三方流量包，默认sd清晰度

**Comment by itinybad** [comment]
> 应该不会做这个，主要原因在于以下几点
> 
> 1.alist 开放 API 中没找到此特定的实现，不过抓 alist 的网络请求应该可以试试，但这不是重点，以下有几个难实现的地方 https://alist-v3.apifox.cn
> 
> 2.emby/jellyfin/plex 所以客户端的代码都是本地分开的，所以没有一个兼容性良好的交互方式，例如选择清晰度这个，实现起来工作量较大
> 
> 3.还有是暂时有些偏离项目初衷了，脚本主要是实现直链的，我的个人理解是非原盘下，文件的画质拉到顶，个人强迫症是原文件不做任何损失转码之类的，所以 sd\hd 的选项不好理解，而 qhd 因国内各大互联网厂的惯犯，虽然没实际对比过，但我粗略认为应该还是要比原文件画质有所损失，从感觉上来说有些缺憾
> 
> 4.阿里云盘最近口碑崩盘，人尽皆知言而无信，作为内测用户我也转到 115 上了，所以对于特定网盘的特定功能的对接动力不是很强，费劲加上了可能用不了多久
> 
> 以上只是当前时间点的感受，如果之后有相同需求的人多了，可能会研究一下，抱歉了

我也有这个需求，昨晚搭好了给朋友用，但是她家的宽带极其的拉，萌生了清晰度的想法（内置转码考虑过，但是用的公司闲置电脑搭建，亮机卡转480p都费劲），花了一上午研究alist和115搓出来个获取清晰度的直链，但是有几个问题存在：

- alist用的如果是非Web Cookie，没有办法获取清晰度直链，两个获取清晰度的接口都对Cookie极为严格，APP的接口因为加密+APP加固没办法爬出来
- 搓的Golang代码只考虑了功能性加上不会React以及上述Cookie问题，大概率是合不进alist主库的

又研究了一下emby.js和alist的115接口，倒是可以在emby.js里更方便的实现清晰度直链获取，但是不清楚如何用获取到的链接替换emby自带的清晰度选择，请问是否有意实现该功能？
