### ISSUE TITLE
Alist别名模式挂载的夸克无法播放

### ISSUE THREAD

**Issue by lpdswing** [bpking1/embyExternalUrl#306]
我用alist别名模式聚合了夸克，天翼云的电影在一个文件夹，生成的strm链接在浏览器都可以正常下载文件，天翼云在emby播放正常，夸克表现就是播放按钮开始暂停状态不停的切换。不知道是不是配置问题，我只改了配置文件上面几行必填的，后面啥都没改

**Comment by chen3861229** [comment]
已经修复

**Comment by lpdswing** [comment]
> 已经修复

目前 host：8091播放已经没问题了， 我用Nginx proxy manger 做了个反向代理， domain：8443  转发到 host：8091， 又出现之前描述的那种情况了， 这种情况下需要改什么配置吗

**Comment by chen3861229** [comment]
1.注意下日志中 fetchAlistPathApi add Host: 这个关键字的内容呢？预期打印出来的情况应该是，这个配置变量的 172.17.0.1:5244 这部分字符串，

emby2Alist\nginx\conf.d\config\constant-mount.js
```js
const alistAddr = "http://172.17.0.1:5244"; 
```
假如不对的话，可以尝试将 alistAddr 值改为和 alistPublicAddr 一样的公网域名地址试试
``js
const alistPublicAddr = "http://youralist.com:5244";
```

2.还有种可能是上级反代没传递一些约定俗称的反代标识头，虽然感觉在当前特定 bug 下此种情况不太可能，因为查询 alist 的 Host 标头目前是手动截取出来的，和上级反代标头传递无关，不过也可以尝试测试一下，代理标头可参考 emby2Alist\nginx\conf.d\includes\proxy-header.conf 或 alist 官方文档中也有相关示例

**Comment by lpdswing** [comment]
<img width="1147" alt="image" src="https://github.com/user-attachments/assets/f7514f99-803a-49bc-9285-69aee93a2b88">
<img width="860" alt="image" src="https://github.com/user-attachments/assets/256352dc-bb75-49fd-add9-f05ed53ba3ff">
alistaddr获取的是内网地址， 我填的配置alistPublicAddr是最外面的constant.js， 我试试是不是改constant-mount.js才生效

**Comment by lpdswing** [comment]
alistAddr和alistPublicAddr 都设置成域名：端口，实际获取到的播放链接还是10.10.10.3:5244xxx

**Comment by lpdswing** [comment]
1. 原来的日志中 fetchAlistPathApi 关键字出现的确实是我配置的最外层constant.js中的10.10.10.3:5244
2. 我销毁容器重新创建，用了一会日志中没有grep到fetchAlistPathApi 
3. 关于反向代理问题，现在公网访问的alist视频是可以正常播放的，之前没有配置location /下的参数确实有问题
4. 现在的问题应该转化为了没有根据内网访问还是公网访问获取到正确的alist addr问题了

**Comment by chen3861229** [comment]
现在是正常的吗？不过 alist 假如有公网域名的话，还是建议将 alistAddr 值改为和 alistPublicAddr 一样的公网域名地址，这样好理解和排错一点

**Comment by lpdswing** [comment]
alist公网可以访问, 我试了这2值都改成公网域名, 获取到的还是内网地址, 难道这个和strm写的url里是内网地址有关吗, 不打算折腾了

**Comment by chen3861229** [comment]
> 难道这个和strm写的url里是内网地址有关吗

确实是这个原因，strm 这边默认情况下仅是简单的将内部文本链接响应给客户端而已，虽然用 mediaPathMapping 路径映射可以手动干预一下，不过就变复杂了一些，确实是能用就行了
