### ISSUE TITLE
【求助】希望出个视频教程

### ISSUE THREAD

**Issue by bike3097a** [bpking1/embyExternalUrl#307]
有望今年出个视频教程，包括软链接，emby或piex都可以，谢谢

目前我的影视目录在/movies下
目录如下
cd2挂载115网盘路径是
/movies/115
alist挂载115网盘路径是
/115
我改成如下所示
const mediaMountPath = ["/movies"];

其他也设置好了，去emby客户端访问如图所示
![114832](https://github.com/user-attachments/assets/18fb72c2-e0da-4935-82ab-db0a81ad2051)
![114834](https://github.com/user-attachments/assets/d506aed1-d3ca-48c6-8d44-8329cc953d28)

不知道怎么弄了，小白第一次搞这个，希望有人帮助我。

**Comment by bike3097a** [comment]
https://blog.nanako.vip/?p=162
我是按照上面的博文教程，一步一步操作的，也不能播放。

**Comment by chen3861229** [comment]
> 目前我的影视目录在/movies下
> 目录如下
> cd2挂载115网盘路径是
> /movies/115
> alist挂载115网盘路径是
> /115
> 我改成如下所示
> const mediaMountPath = ["/movies"];

这些的配置是没问题的，看到用到了 alist ，当然 软链接 默认也是用的 alist ,所以 alist 的一些配置项也需要填一下的，
emby2Alist\nginx\conf.d\config\constant-mount.js 

然后基本看 ../nginx/log:/var/log/nginx 下的 error.log 日志中的关键字基本能判断了

**Comment by hiahia250** [comment]
请问有plex的配置教程博文吗？还有我是已经用nginx proxy manager实现了plex反代了，关于nginx那块不知道如何设置

**Comment by chen3861229** [comment]
> 请问有plex的配置教程博文吗？还有我是已经用nginx proxy manager实现了plex反代了，关于nginx那块不知道如何设置

我这边的写得偏简单，因为很多东西和 emby 那边的配置是一样的，关于提到的有个前置代理 nginx proxy manager 的话，plexHost 还是填实际的 plex 内网地址，nginx proxy manager 中添加一个匹配路径或端口反代 plex2Alist 的 8091 即可，这样入口使用 nginx proxy manager 中的 http 证书管理之类的

https://github.com/bpking1/embyExternalUrl/blob/main/plex2Alist/README.md#%E6%AD%A5%E9%AA%A4
