### ISSUE TITLE
plex2alist问题

### ISSUE THREAD

**Issue by GtxFury** [bpking1/embyExternalUrl#312]
使用alist 115直链后播放内容无法拖动进度条。。而且就算更改完设置里面指向8091端口，实际上还是会绕过nginx，需要手动在客户端设置里面指定为8091端口

**Comment by chen3861229** [comment]
> 使用alist 115直链后播放内容无法拖动进度条。。

1.如果客户端是 Infuse 的话，这个暂时无解，https://github.com/bpking1/embyExternalUrl/issues/308

1.1 以下是一个默认尝试兼容的配置，播放还是直链，但是部分情况也是对拖动 bug 不太完美，
emby2Alist\nginx\conf.d\config\constant-mount.js
```js
// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为 Alist 接口返回的链接 raw_url
// 参数3: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const cilentSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
];
```
1.2 以下是进一步兼容，强制 Infuse + 115 请求走回源中转处理，播放非直链，
https://github.com/bpking1/embyExternalUrl/issues/308#issuecomment-2250651600

1.3 两种都是脚本这边已经尽了最大努力了，根源可能出在 Infuse 自身对于播放链接的默认并发加载线程 > 2 ,这个只能等 Infuse 官方进行修复了

2.这个需要在 Plex 服务端设置 => 网络 => 自定义服务区访问 URL 中填写下带 nginx 端口的地址，客户端一般就不用手动设置了
https://github.com/bpking1/embyExternalUrl/issues/59#issuecomment-2029842984
