### ISSUE TITLE
embyAddExternalUrl可以添加mpc-be播放器的支持吗？

### ISSUE THREAD

**Issue by lw6644700** [bpking1/embyExternalUrl#313]
embyAddExternalUrl可以添加mpc-be播放器的支持吗？

**Comment by chen3861229** [comment]
查询历史 issus 得知此播放器不支持 Http Scheme 方式调用，所以 Web 是无法拉起的，故无法支持
https://github.com/Aleksoid1978/MPC-BE/issues/439
