### ISSUE TITLE
可以加速strm加载速度吗？

### ISSUE THREAD

**Issue by xianglongwei** [bpking1/embyExternalUrl#316]
在播放strm文件，加载时间在15秒到1分钟左右。大佬有没有办法提高加载速度呢？gpt给的方案是给nginx加缓存，奈何不会代码没法测试。😭😭😭

**Comment by chen3861229** [comment]
这个总体上应该是优化不了，strm 耗时体现在两阶段，一是 emby 在首次播放 strm 前会获取链接的流数据进行一些分析，补充媒体详细数据入库，而补充完之后的第二次之后就没有此过程，前提是 strm 内部文本链接的填写格式为官方文档中的方式，即 http 开头的远程直链，二是慢在服务提供方那边，即 strm 内部远程链接指向的文件的提供方的响应速度上，二的总比最多，一只有编码信息为空时才耗时，是否首次播放可以通过查看媒体详情页下方的媒体编码信息确认，
所以有了几种优化方向，不确定是否有效，因为我这边没实际测试过

1.保证 strm 文件都拥有媒体编码信息，免去一的耗时，当然这个也是需要权衡的，因为选择 strm 方式就是抛弃了扫库入库之类的 emby 内部优化，妥协方案是忍受首次播放加载慢的情况，前提是同一个媒体，第二次后就会快一些

2.使用 emby 插件库中的 StrmExtract 进行定时批量提前补充媒体编码信息，这个没实际使用过，不确定能否有预期效果，且这个又属于扫库了，与 strm 轻量便捷特性冲突，还不如直接挂载网盘入库，这个需要执行权衡了

3.strm 文件全部使用第三方播放器，以规避官方 emby 客户端存在的首次补充 strm 媒体编码信息这个耗时阶段

4.尝试优化 strm 指向文件提供方的目录结构，例如减少目录层级，同级目录下不要放置过多的文件夹或文件

5.这个属于没办法的情况下，换 软链接/挂载工具 之类的文件系统方式吧，毕竟这样才是真正符合 emby/jellyfin/plex 的管理方式，它们对此的兼容和优化方式比较多

6.开启 enableL2，即提到的 给nginx加缓存 ，这个对于 strm 是有前提的，普通情况下是直接响应 strm 内部的远程链接，即缓存的这个链接无意义，因为不耗时，然后需要填写 redirectStrmLastLinkRule 来让 nginx 来获取 strm 跳转一次后的链接，这里假设的前提是获取跳转一次后的链接已经涵盖最大的耗时时间，设置这两个后，理想情况下达到进入详情页的同时(这个是限制条件)就缓存了访问速度较快的链接结果，假如如此测试后播放开始时间仍未提升多少，那就只能还原设置，使用前面提到的方案了

emby2Alist\nginx\conf.d\config\constant-pro.js
emby2Alist\nginx\conf.d\config\constant-strm.js
```js
// 路由缓存配置
const routeCacheConfig = {
  // 总开关,是否开启路由缓存,此为一级缓存,添加阶段为 redirect 和 proxy 之前
  // 短时间内同客户端访问相同资源不会再做判断和请求 alist,有限的防抖措施,出现问题可以关闭此选项
  enable: true,
  // 二级缓存开关,仅针对直链,添加阶段为进入单集详情页,clientSelfAlistRule 中的和首页直接播放的不生效
  enableL2: true,
  // 缓存键表达式,默认值好处是命中范围大,但会导致 routeRule 中针对设备的规则失效,多个变量可自行组合修改,冒号分隔
  // 注意 jellyfin 是小写开头 mediaSourceId
  keyExpression: "r.uri:r.args.MediaSourceId", // "r.uri:r.args.MediaSourceId:r.args.X-Emby-Device-Id"
};

// 指定是否转发由 njs 获取 strm/远程链接 重定向后直链地址的规则,例如 strm/远程链接 内部为局域网 ip 或链接需要验证
// 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数2: 匹配类型或来源(字符串参数类型),默认为 "filePath": mediaPathMapping 映射后的 strm/远程链接 内部链接
// ,有分组时不可省略填写,可为表达式
// 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
const redirectStrmLastLinkRule = [
  [0, strHead.lanIp.map(s => "http://" + s)],
  [0, ["http://strm内部远程链接的开头前缀", ]],
];
```

**Comment by xianglongwei** [comment]
谢谢
