### ISSUE TITLE
大佬救救我，软链接的时候呢，我是可以成功播放的，但是使用strm就是不行，以下是日志

### ISSUE THREAD

**Issue by jinhua523** [bpking1/embyExternalUrl#318]
2024/08/02 02:36:00 [warn] 36#36: *13 js: redirect2Pan, UA: VidHub/1.7.4
2024/08/02 02:36:00 [info] 36#36: *13 js: redirect2Pan cacheKey: /emby/videos/91384/stream.strm:280601971b44153953c9496428c5d2eb
2024/08/02 02:36:00 [info] 36#36: *13 js: not found from cache routeL1Dict, skip
2024/08/02 02:36:00 [info] 36#36: *13 js: not found from cache routeL2Dict, skip
2024/08/02 02:36:00 [warn] 36#36: *13 js: itemInfoUri: http://192.168.10.18:6096/Items?Ids=280601971b44153953c9496428c5d2eb&Fields=Path,MediaSources&Limit=1&api_key=xxx
2024/08/02 02:36:00 [warn] 36#36: *13 js: 7ms, fetchEmbyFilePath async function cost
2024/08/02 02:36:00 [info] 36#36: *13 js: embyRes: {"message":"success","path":"/volume1/NASTOOL/CD2/cloud115/115/Sylink/剧综漫/儿童/铁甲小宝 (1997)/Season 1/铁甲小宝.1997.S01E02.第 2 集.DVDRip.mkv","itemName":"足球对抗赛","notLocal":true}
2024/08/02 02:36:00 [warn] 36#36: *13 js: notLocal: true
2024/08/02 02:36:00 [warn] 36#36: *13 js: notLocal decodeURIComponent embyRes.path
2024/08/02 02:36:00 [warn] 36#36: *13 js: mount emby file path: /volume1/NASTOOL/CD2/cloud115/115/Sylink/剧综漫/儿童/铁甲小宝 (1997)/Season 1/铁甲小宝.1997.S01E02.第 2 集.DVDRip.mkv
2024/08/02 02:36:00 [info] 36#36: *13 js: getRouteMode proxyRules: []
2024/08/02 02:36:00 [warn] 36#36: *13 js: getRouteMode: redirect
2024/08/02 02:36:00 [warn] 36#36: *13 js: mediaPathMapping: [[0,1,"/volume1/NASTOOL/CD2/cloud115",""]]
2024/08/02 02:36:00 [warn] 36#36: *13 js: strMapping replace: /volume1/NASTOOL/CD2/cloud115 => 
2024/08/02 02:36:00 [warn] 36#36: *13 js: mapped emby file path: /115/Sylink/剧综漫/儿童/铁甲小宝 (1997)/Season 1/铁甲小宝.1997.S01E02.第 2 集.DVDRip.mkv
2024/08/02 02:36:00 [info] 36#36: *13 js: clientSelfAlistRuleFilter onKey: true, typeof: string
2024/08/02 02:36:00 [warn] 36#36: *13 js: sourceStrValue, alistRes = /115/Sylink/剧综漫/儿童/铁甲小宝 (1997)/Season 1/铁甲小宝.1997.S01E02.第 2 集.DVDRip.mkv
2024/08/02 02:36:00 [warn] 36#36: *13 js: fetchAlistPathApi add Host: my-alist:5243
2024/08/02 02:36:00 [warn] 36#36: *13 js: 248ms, fetchAlistPathApi async function cost
2024/08/02 02:36:00 [warn] 36#36: *13 js: fetchAlistPathApi, UA: VidHub/1.7.4
2024/08/02 02:36:00 [info] 36#36: *13 js: getRouteMode proxyRules: []
2024/08/02 02:36:00 [info] 36#36: *13 js: clientSelfAlistRuleFilter onKey: true, typeof: string
2024/08/02 02:36:00 [warn] 36#36: *13 js: sourceStrValue, alistRes = https://cdnfhnfile.115.com/5e751d8bfa5f6aff3dad2a9803b59d455e8da7f5/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D.1997.S01E02.%E7%AC%AC%202%20%E9%9B%86.DVDRip.mkv?xxx
2024/08/02 02:36:00 [warn] 36#36: *13 js: hit clientSelfAlistRule: [2,"115.com","https://my-alist:5243"]
2024/08/02 02:36:00 [warn] 36#36: *13 js: redirect to: https://my-alist:5243/d/115/Sylink/%E5%89%A7%E7%BB%BC%E6%BC%AB/%E5%84%BF%E7%AB%A5/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D%20(1997)/Season%201/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D.1997.S01E02.%E7%AC%AC%202%20%E9%9B%86.DVDRip.mkv
2024/08/02 02:36:00 [info] 36#36: *13 js: redirectAfter cacheKey: /emby/videos/91384/stream.strm:280601971b44153953c9496428c5d2eb
2024/08/02 02:36:00 [warn] 36#36: *13 js: routeL1Dict add: [/emby/videos/91384/stream.strm:280601971b44153953c9496428c5d2eb] : [https://my-alist:5243/d/115/Sylink/%E5%89%A7%E7%BB%BC%E6%BC%AB/%E5%84%BF%E7%AB%A5/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D%20(1997)/Season%201/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D.1997.S01E02.%E7%AC%AC%202%20%E9%9B%86.DVDRip.mkv]
2024/08/02 02:36:00 [warn] 36#36: *13 js: success: fetchNotificationsAdmin: {"Name":"【emby2Alist】","Description":"cache routeL1Dict added, redirect: success"}
192.168.10.18 - - [02/Aug/2024:02:36:00 +0000] "GET /emby/videos/91384/stream.strm?AutoOpenLiveStream=false&UserId=db1bca3e3e42405cb0e9fc6698780c99&MaxStreamingBitrate=500000000&reqformat=json&IsPlayback=false&api_key=0f922defb5104c8f87f0371d2f6424c6&MediaSourceId=280601971b44153953c9496428c5d2eb&PlaySessionId=ed967fdfffdd46d6b988f3921e090b8a&Static=true&X-Emby-Token=xxx HTTP/1.1" 302 138 "-" "VidHub/1.7.4" "14.150.210.64"
2024/08/02 02:36:00 [warn] 36#36: *13 js: === redirect2Pan: /emby/videos/91384/stream.strm, the NJS VM is destroyed ===
![image](https://github.com/user-attachments/assets/adcc08ff-fa90-480d-9314-4094baeb8758)
![image](https://github.com/user-attachments/assets/693a5bee-3b7a-43a1-81f7-2c960836f14a)

**Comment by chen3861229** [comment]
配置和日志中都是符合预期的，没啥问题，不过 alist 的签名是开启状态吗？直接浏览器访问日志中的这个地址试一下，
```js
redirect to: https://my-alist:5243/d/115/Sylink/%E5%89%A7%E7%BB%BC%E6%BC%AB/%E5%84%BF%E7%AB%A5/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D%20(1997)/Season%201/%E9%93%81%E7%94%B2%E5%B0%8F%E5%AE%9D.1997.S01E02.%E7%AC%AC%202%20%E9%9B%86.DVDRip.mkv
```
1.原始域名做了隐私化替换需要自己补齐，假如是 alist 返回了 401 的 code , 则需要配置下 emby2Alist\nginx\conf.d\config\constant-mount.js 中，alistSignExpireTime 具体的值需要参照 alist 服务端控制台中设置，默认值是 0，永不过期，假如浏览器可以直接访问链接内容，那可以还原上述更改
```js
// alist 是否启用了 sign
const alistSignEnable = true;

// alist 中设置的直链过期时间,以小时为单位
const alistSignExpireTime = 0;
```
2.感觉大概率是 1 的问题，假如不是，可以尝试注释 clientSelfAlistRule  中的 [2, strHead["115"], alistPublicAddr],
但是"Emby for iOS"和"Infuse"对于 115 的进度条依赖这个，假如没用进度条拖动有 bug 的客户端，这样注释配置后，将响应原始的 115 直链给客户端，而不是响应 alist 的 /d 地址
emby2Alist\nginx\conf.d\config\constant-mount.js
```js
// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
// ,有分组时不可省略填写,可为表达式
// 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
// 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const clientSelfAlistRule = [
  // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  // [2, strHead["115"], alistPublicAddr],
  // [2, strHead.ali, alistPublicAddr],
  // 优先使用 filePath,可省去一次查询 alist,如驱动为 alias,则应使用 alistRes
  // ["115-local", "filePath", 0, "/mnt/115", alistPublicAddr],
  // ["115-local", "r.args.X-Emby-Client", 0, strHead.xEmbyClients.seekBug], // 链接入参,客户端类型
  // ["115-alist", "alistRes", 2, strHead["115"], alistPublicAddr],
  // ["115-alist", "r.args.X-Emby-Client", 0, strHead.xEmbyClients.seekBug],
];
```

**Comment by jinhua523** [comment]
非常感谢大佬，虽然我的alist后台是没有开启sign的，但是nginx开启了sign后就能正常播放了，非常感谢解答
