### ISSUE TITLE
最新的脚本里软连接没有这个embyPathMapping参数了吗

### ISSUE THREAD

**Issue by chaomarks** [bpking1/embyExternalUrl#319]
我生成的软连接用旧版本的下面这个参数可以获取直链
const embyPathMapping = [
   [0, 0, "/media/cd2/666", "/115188"],
  // [0, 2, "http:", "https:"], 
  // [0, 2, ":5244", "/alist"], 
  // [0, 0, "D:", "F:"],
  // [0, 0, /blue/g, "red"], // 此处正则不要加引号
  // [1, 1, `${alistPublicAddr}/d`],
  // [2, 2, "?xxx"],
];
新版本的我改这个参数好像不行
const mediaMountPath = [[0,0,"/media/cd2/666","/115188"]];

改这个constant-symlink.js也不行
// 参数1: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数2: 匹配目标,对象为媒体服务入库的文件路径(Item.Path)
const symlinkRule = [
   [0, "/media/cd2/666"],
];

export default {
  symlinkRule,
}

**Comment by chen3861229** [comment]
新版本的之前为了和 plex2Alist 统一，变更了变量名，之前的内容不用改，embyPathMapping => mediaPathMapping 
```js
const mediaPathMapping = [
[0, 0, "/media/cd2/666", "/115188"],
// [0, 2, "http:", "https:"],
// [0, 2, ":5244", "/alist"],
// [0, 0, "D:", "F:"],
// [0, 0, /blue/g, "red"], // 此处正则不要加引号
// [1, 1, ${alistPublicAddr}/d],
// [2, 2, "?xxx"],
];
```
其余和之前保持一样就行了，即下面两段配置不用加
