### ISSUE TITLE
cd2配置 后  strm 后播放无法302 

### ISSUE THREAD

**Issue by Solmonz** [bpking1/embyExternalUrl#320]
大佬 请教一下 我配置完 strm 后播放他直接走cd2了，没办法走302 ，未配置strm前 nignx 可以走302 
以下为日志
[error.log](https://github.com/user-attachments/files/16477003/error.log)

alist + cd2 +emby
<img width="1195" alt="image" src="https://github.com/user-attachments/assets/29eb0284-023e-49f2-8f59-cf00212bfb6f">

**Comment by NASA0719** [comment]
cd2不支持302，strm里面的内容应该是alist的链接

**Comment by Solmonz** [comment]
我是安装了alist +cd2 +emby +strm 
思路是：cd2 挂载本地 给strm 给EMBY，emby播放电影时，nginx 劫持 strm 给 alist 302

**Comment by chen3861229** [comment]
确实如上所说，根据日志判断出 strm 内部文本链接为 http://192.168.31.150:19798/static/http/192.168.31.150:19798/False/ 开头，是 cd2 的访问链接，cd2不支持 302，以下是修改方法，

1.规范些的，是把 strm 内部文本链接生成为 http://你的AList公网域名:端口/d/... 这样形式的，但需要批量修改和重新入库

2.1 使用脚本中的路径映射参数，将 cd2 访问链接转换为 alist 的文件直接访问路径，
emby2Alist\nginx\conf.d\config\constant-pro.js
```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  [0, 2, "http://192.168.31.150:19798/static/http/192.168.31.150:19798/False/"
    , "http://你的AList公网域名:端口/d"
  ],
];
```

2.2 与 2.1 的区别为此种方式是 nginx 中去查询 alist 并获取网盘商的公网直链再响应给客户端，而 2.1 仅是将 http://你的AList公网域名:端口/d/... 这个链接响应给客户端访问，会对路由缓存的直链有一些区别，2.2 响应的网盘商的公网直链缓存才能节省耗时，但可能会有新问题，例如无进度记录或不准确的问题，两种需要权衡并测试下
```js
const mediaPathMapping = [
  [0, 2, "http://192.168.31.150:19798/static/http/192.168.31.150:19798/False/", ""],
];
```

**Comment by Solmonz** [comment]
大佬 我尝试用alist 想要一劳永逸，避免出现您说的延迟
目前对比下来 就目录会不一样 其他都正常 
http://192.168.31.150:5244/115/d%2Fmovie%2F%E5%8D%8E%E8%AF%AD%E7%94%B5%E5%BD%B1%2FHello%21%20%E6%A0%91%E5%85%88%E7%94%9F%20%282011%29%2FHello%21%20%E6%A0%91%E5%85%88%E7%94%9F%20%282011%29%20-%202160p.mkv

http://192.168.31.150:5244/115/movie/%E5%8D%8E%E8%AF%AD%E7%94%B5%E5%BD%B1/Hello!%20%E6%A0%91%E5%85%88%E7%94%9F%20(2011)/Hello!%20%E6%A0%91%E5%85%88%E7%94%9F%20(2011)%20-%202160p.mkv

URL STRM  1: /115/d/movie/华语电影/Hello! 树先生 (2011)/Hello! 树先生 (2011) - 2160p.mkv
URL alist网页目录  2: /115/movie/华语电影/Hello! 树先生 (2011)/Hello! 树先生 (2011) - 2160p.mkv

这个d 可以删除吗 
还是有别的含义

**Comment by chen3861229** [comment]
emby2Alist\nginx\conf.d\config\constant-mount.js
1.对于 alist 的配置文件全部按实际情况填写，alistAddr 和 alistPublicAddr 填写为相同的值，统一写成公网域名端口形式，nginx 开启 https 需要手动改下这里的注释，然后改下证书和私钥文件的路径
![image](https://github.com/user-attachments/assets/123a5c19-9ff6-4e1c-abf7-f2e0d2464998)
![image](https://github.com/user-attachments/assets/cbbcd8b6-8083-484f-a7f2-1ad7e66da922)

2.这边为了解耦，所以没有编写自动申请域名或续期的功能，需要手动将证书和私钥文件每三个月替换一次(假如是普通证书的话)，或者使用其它证书续签工具，然后将宿主机上的证书目录映射到容器内，这样更新证书仅需手动重启下 nginx 就行

**Comment by Solmonz** [comment]
好嘞 感谢大佬，大佬方便问下您有TG吗

**Comment by Solmonz** [comment]
我感觉确实转换了链接🔗，转换到alist 但是还是有点卡卡 不知道是不是没有跳转302 （会不会是我alist 套cf的问题） 不过我用的是ip:post 应该不会

**Comment by chen3861229** [comment]
1.是有，不过一般晚上上得比较少，用户名是同 github

2.302 成功还是失败和套 cf 没太大关系，nginx 的 error.log 日志中可以搜索关键字 redirect to 出现就是 302 成功了，日志中也有一些接口请求耗时的打印，套 cf 只会延迟请求 alist 查询这一步，应该没太大问题

**Comment by Solmonz** [comment]
Id:@Bpking10 ?
