### ISSUE TITLE
可以考虑加一个根据码率来判断是否走直链的路由规则呢？

### ISSUE THREAD

**Issue by smartutu** [bpking1/embyExternalUrl#328]
如果视频码率低于设定的某个数值，那么走本地代理，这样起播速度会快很多 而且上传刚好可以支撑流畅播放。如果码率大于设定的数值那么会走302模式，这样码率比较大的就用直链来播放。

**Comment by chen3861229** [comment]
这个思考了下，是可以实现的，不过逻辑是反过来的，因为路由规则里没匹配到任何规则是默认走直链的，所以后续实现这个逻辑，应该指定的是走转码的规则，实现这个需要稍微等一段时间了

**Comment by smartutu** [comment]
嗯 指定给走转码规则应该更合适，命中这个规则的，如果不开启转码相当于proxy的效果，期待期待！感谢大佬在百忙之中的回复！

**Comment by chen3861229** [comment]
这边只是简单测试了下，应该是没问题的，调试判断结果，可网页上查看 PlaybackInfo 接口的返回值字段，XRouteMode 来快速得知
```js
const routeRule = [
  // 此条规则代表大于等于 3Mbps 码率的走转码,xMediaSource 为固定值,平方使用双星号表示
  ["transcode", "r.xMediaSource.Bitrate", ">=", 3 * 1024 ** 2],
];

// 转码配置,默认 false,将按之前逻辑禁止转码处理并移除转码选项参数,与服务端允许转码配置有相关性
const transcodeConfig = {
  enable: true, // 此大多数情况下为允许转码的总开关
  ...
};
```

**Comment by smartutu** [comment]
我尝试加了这条规则，
`["proxy","r.xMediaSource.Bitrate", "<=", 10 * 1024 ** 2],` 目的是让低码率的直接走proxy，高码率的默认直链
然后在constant-transcode.js 开启了转码（配置如下），但是emby用户转码权限没有开启

`// 转码配置,默认 false,将按之前逻辑禁止转码处理并移除转码选项参数,与服务端允许转码配置有相关性
const transcodeConfig = {
  enable: true, // 此大多数情况下为允许转码的总开关
  enableStrmTranscode: false, // 默认禁用 strm 的转码,体验很差,仅供调试使用
  type: "distributed-media-server", // 负载类型,可选值, ["nginx", "distributed-media-server"]
  maxNum: 3, // 单机最大转码数量,有助于加速轮询, 参数暂无作用,接口无法查询转码情况,忽略此参数
  redirectTransOptEnable: false, // 是否保留码率选择,不保留官方客户端将无法手动切换至转码
  targetItemMatchFallback: "proxy", // 目标服务媒体匹配失败后的降级后路由措施,可选值, ["redirect", "proxy"]`

**此时，XRouteMode判定也是proxy ，但是日志在判定为proxy后 转头又回到了直链** 

`2024/08/15 04:34:51 [notice] 20#20: *284 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000039, client: 203.69.23.30, server: default, request: "POST /emby/Items/840256/PlaybackInfo?UserId=06fe27b075db42afa113b8c9031ae3ad&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=1434999&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=481e416f-d22c-47b0-8a5f-19b1845f0e88&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=4ad3db79a4814c3dbac69370348e06c3&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1", host: "4kone.cn:8096"
2024/08/15 04:34:51 [warn] 20#20: *284 js: playbackinfo proxy uri: /proxy/emby/Items/840256/PlaybackInfo
2024/08/15 04:34:51 [warn] 20#20: *284 js: playbackinfo proxy query string: UserId=06fe27b075db42afa113b8c9031ae3ad&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=1434999&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=481e416f-d22c-47b0-8a5f-19b1845f0e88&X-Emby-Client-Version=4.8.8.0&X-Emby-Token=4ad3db79a4814c3dbac69370348e06c3&X-Emby-Language=zh-cn&reqformat=json
2024/08/15 04:34:51 [warn] 20#20: *284 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"35f2aba0324eb8910c73548bf5114fc8","Path":"/mnt/nvme0n1-4/CloudNAS/media/正在热映/沙漏 (2024)/沙陋.2024.1080p.WEB-DL.H264.AAC-OurTV.mp4","Type":"Default","Container":"mp4","Size":5901039523,"Name":"沙陋.2024.1080p.WEB-DL.H264.AAC-OurTV","IsRemote":false,"HasMixedProtocols":false,"RunTimeTicks":66176430000,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[{"Codec":"h264","CodecTag":"avc1","Language":"und","ColorTransfer":"smpte428","ColorPrimaries":"smpte431","ColorSpace":"bt709","TimeBase":"1/90000","VideoRange":"SDR","DisplayTitle":"1080p H264","NalLengthSize":"4","IsInterlaced":false,"BitRate":7001203,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":25,"RealFrameRate":25,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false,"ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0},{"Codec":"aac","CodecTag":"mp4a","Language":"chi","TimeBase":"1/48000","DisplayTitle":"Chinese Simplified AAC stereo (默认)","DisplayLanguage":"Chinese Simplified","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":125375,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0}],"Formats":[],"Bitrate":7133705,"RequiredHttpHeaders":{},"Dir
2024/08/15 04:34:51 [warn] 20#20: *284 js: modify direct play supports all true
2024/08/15 04:34:51 [warn] 20#20: *284 js: sourceStrValue, r.xMediaSource.Bitrate = 7133705
2024/08/15 04:34:51 [warn] 20#20: *284 js: strMatches result: true, type: <=, number source: 7133705, number target: 10485760
2024/08/15 04:34:51 [warn] 20#20: *284 js: hit proxy: ["r.xMediaSource.Bitrate","<=",10485760]
**2024/08/15 04:34:51 [warn] 20#20: *284 js: playbackinfo routeMode: proxy**
2024/08/15 04:34:51 [warn] 20#20: *284 js: modify direct play info
2024/08/15 04:34:51 [warn] 20#20: *284 js: 9ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"35f2aba0324eb8910c73548bf5114fc8","Path":"/正在热映/沙漏 (2024)/沙陋.2024.1080p.WEB-DL.H264.AAC-OurTV.mp4","Type":"Default","Container":"mp4","Size":5901039523,"Name":"沙陋.2024.1080p.WEB-DL.H264.AAC-OurTV","IsRemote":false,"HasMixedProtocols":false,"RunTimeTicks":66176430000,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[{"Codec":"h264","CodecTag":"avc1","Language":"und","ColorTransfer":"smpte428","ColorPrimaries":"smpte431","ColorSpace":"bt709","TimeBase":"1/90000","VideoRange":"SDR","DisplayTitle":"1080p H264","NalLengthSize":"4","IsInterlaced":false,"BitRate":7001203,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":25,"RealFrameRate":25,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false,"ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0},{"Codec":"aac","CodecTag":"mp4a","Language":"chi","TimeBase":"1/48000","DisplayTitle":"Chinese Simplified AAC stereo (默认)","DisplayLanguage":"Chinese Simplified","IsInterlaced":false,"ChannelLayout":"stereo","BitRate":125375,"Channels":2,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0}],"Formats":[],"Bitrate":7133705,"RequiredHttpHeaders":
2024/08/15 04:34:51 [warn] 20#20: *284 js: === transferPlaybackInfo: /emby/Items/840256/PlaybackInfo, the NJS VM is destroyed ===
2024/08/15 04:34:52 [warn] 20#20: *270 js: redirect2Pan, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0
2024/08/15 04:34:52 [warn] 20#20: *270 js: itemInfoUri: http://192.168.100.1:8096/Items?Ids=35f2aba0324eb8910c73548bf5114fc8&Fields=Path,MediaSources&Limit=1&api_key=4ad3db794814370348e06c3
2024/08/15 04:34:52 [warn] 20#20: *270 js: 6ms, fetchEmbyFilePath async function cost
2024/08/15 04:34:52 [warn] 20#20: *270 js: notLocal: false
2024/08/15 04:34:52 [warn] 20#20: *270 js: mount emby file path: /mnt/nvme0n1-4/CloudNAS/media/正在热映/沙漏 (2024)/沙陋.2024.1080p.WEB-DL.H264.AAC-OurTV.mp4
2024/08/15 04:34:52 [warn] 20#20: *270 js: sourceStrValue, r.xMediaSource.Bitrate = undefined
2024/08/15 04:34:52 [warn] 20#20: *270 js: getRouteMode: redirect
2024/08/15 04:34:52 [warn] 20#20: *270 js: mediaPathMapping: [[0,0,"/mnt/nvme0n1-4/CloudNAS/media","/电影/4K"]]
2024/08/15 04:34:52 [warn] 20#20: *270 js: strMapping replace: /mnt/nvme0n1-4/CloudNAS/media => /电影/4K
2024/08/15 04:34:52 [warn] 20#20: *270 js: mapped emby file path: /正在热映/沙漏 (2024)/沙陋.2024.1080p.WEB-DL.H264.AAC-OurTV.mp4
2024/08/15 04:34:52 [warn] 20#20: *270 js: fetchAlistPathApi add Host: 223.76.99.146:5244
2024/08/15 04:34:58 [warn] 20#20: *270 js: 6304ms, fetchAlistPathApi async function cost
2024/08/15 04:34:58 [warn] 20#20: *270 js: fetchAlistPathApi, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0
2024/08/15 04:34:58 [warn] 20#20: *270 js: sourceStrValue, r.xMediaSource.Bitrate = undefined
2024/08/15 04:34:58 [warn] 20#20: *270 js: redirect to: https://cdnfhnfile.115.com/111
2024/08/15 04:34:58 [warn] 20#20: *270 js: === redirect2Pan: /emby/videos/840256/stream.mp4, the NJS VM is destroyed ===`

大概原因是高码率和低码率视频都在下面的mediaPathMapping中的目录匹配条件中，即高码率和低码率视频的路径开头包含在
mediaPathMapping里，所以mediaPathMapping 又让他走直链去了，盖过了本该走的proxy。如果删除掉下面的mediaPathMapping 规则，那么高码率将无法走直链。 请问大佬这个问题应该如何解决呢？还是说我这样实现的方法不太对

除此之外还有个小细节，就是 js: sourceStrValue, r.xMediaSource.Bitrate = undefined 码率判断这里经常会出现未定义，不知道是哪里的原因。

**Comment by chen3861229** [comment]
> 请求这个问题应该如何解决呢？还是说我这样实现的方法不太对
> 除此之外还有个小细节，就是 js: sourceStrValue, r.xMediaSource.Bitrate = undefined 码率判断这里经常会出现未定义，不知道是哪里的原因。

1.抱歉这是我代码上的问题，虽然之前实现的时候考虑到这种可能了，不过偷了个小懒，没管实际播放串流接口中的路由判断`redirect2Pan`，这段时间实现 115 转码直链去了，之后将修复这个问题

**Comment by smartutu** [comment]
按照码率来判断是否走直链问题已完美解决，感谢大佬！
