### ISSUE TITLE
求助大佬，用的最新版emby2alist无法加载外挂字幕

### ISSUE THREAD

**Issue by erbukuawu** [bpking1/embyExternalUrl#33]
![image](https://github.com/bpking1/embyExternalUrl/assets/39191744/a9ac3bb7-2926-41a4-9479-8e873d4cf44d)
![image](https://github.com/bpking1/embyExternalUrl/assets/39191744/296d9e94-c4d4-4226-8566-3698f317d5ac)
如图，下载的最新版代码，播放时已经选择字幕，但是字幕不会显示 ，或者字幕错乱，比如明明选择的是英文版字幕但是显示的是中文版，选择的是中文版字幕却没有出现字幕，求助大佬是什么原因，感觉是bug,因为我用之前版本的代码可以正确显示字幕，但是之前那个版本不支持直播源直接播放，所以更新到新版就出现了上述问题

**Comment by AmbitiousJun** [comment]
目前确实有bug，可以先用回老版本，有电视直播的需求的话请先删除emby.conf文件里面这段配置:
```text

# Redirect the stream to njs
    location ~* /Items/(.*)/PlaybackInfo {
        js_content emby2Pan.transferPlaybackInfo;
    }

```
暂时别用web端

**Comment by erbukuawu** [comment]
> 目前确实有bug，可以先用回老版本，有电视直播的需求的话请先删除emby.conf文件里面这段配置:
> 
> ```
> 
> # Redirect the stream to njs
>     location ~* /Items/(.*)/PlaybackInfo {
>         js_content emby2Pan.transferPlaybackInfo;
>     }
> ```
> 
> 暂时别用web端

好的，坐等大佬修复🫡

**Comment by erbukuawu** [comment]
> > 目前确实有bug，可以先用回老版本，有电视直播的需求的话请先删除emby.conf文件里面这段配置:
> > ```
> > 
> > # Redirect the stream to njs
> >     location ~* /Items/(.*)/PlaybackInfo {
> >         js_content emby2Pan.transferPlaybackInfo;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 暂时别用web端
> 
> 好的，坐等大佬修复🫡

大佬，最新版好像又有bug,我用这个版本的emby2alist之后所有页面打开都显示Content no longer available.
![image](https://github.com/bpking1/embyExternalUrl/assets/39191744/838e69f1-e310-4ab9-8417-7ecf4c3810b5)
![image](https://github.com/bpking1/embyExternalUrl/assets/39191744/7c2d9b6f-4e74-4842-89da-c3722481f732)

**Comment by AmbitiousJun** [comment]
> > > 目前确实有bug，可以先用回老版本，有电视直播的需求的话请先删除emby.conf文件里面这段配置:
> > > ```
> > > 
> > > # Redirect the stream to njs
> > >     location ~* /Items/(.*)/PlaybackInfo {
> > >         js_content emby2Pan.transferPlaybackInfo;
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 暂时别用web端
> > 
> > 
> > 好的，坐等大佬修复🫡
> 
> 大佬，最新版好像又有bug,我用这个版本的emby2alist之后所有页面打开都显示Content no longer available. ![image](https://user-images.githubusercontent.com/39191744/272802818-838e69f1-e310-4ab9-8417-7ecf4c3810b5.png) ![image](https://user-images.githubusercontent.com/39191744/272803576-7c2d9b6f-4e74-4842-89da-c3722481f732.png)

页面都没法展示的话就没办法了，可以用回老版兼容版：https://github.com/bpking1/embyExternalUrl/pull/31#issuecomment-1735465882

**Comment by AmbitiousJun** [comment]
> > > 目前确实有bug，可以先用回老版本，有电视直播的需求的话请先删除emby.conf文件里面这段配置:
> > > ```
> > > 
> > > # Redirect the stream to njs
> > >     location ~* /Items/(.*)/PlaybackInfo {
> > >         js_content emby2Pan.transferPlaybackInfo;
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 暂时别用web端
> > 
> > 
> > 好的，坐等大佬修复🫡
> 
> 大佬，最新版好像又有bug,我用这个版本的emby2alist之后所有页面打开都显示Content no longer available. ![image](https://user-images.githubusercontent.com/39191744/272802818-838e69f1-e310-4ab9-8417-7ecf4c3810b5.png) ![image](https://user-images.githubusercontent.com/39191744/272803576-7c2d9b6f-4e74-4842-89da-c3722481f732.png)

页面都没法展示的话就没办法了，可以用回老版兼容版：https://github.com/bpking1/embyExternalUrl/pull/31#issuecomment-1735465882

**Comment by erbukuawu** [comment]
> > > > 目前确实有bug，可以先用回老版本，有电视直播的需求的话请先删除emby.conf文件里面这段配置:
> > > > ```
> > > > 
> > > > # Redirect the stream to njs
> > > >     location ~* /Items/(.*)/PlaybackInfo {
> > > >         js_content emby2Pan.transferPlaybackInfo;
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 暂时别用web端
> > > 
> > > 
> > > 好的，坐等大佬修复🫡
> > 
> > 
> > 大佬，最新版好像又有bug,我用这个版本的emby2alist之后所有页面打开都显示Content no longer available. ![image](https://user-images.githubusercontent.com/39191744/272802818-838e69f1-e310-4ab9-8417-7ecf4c3810b5.png) ![image](https://user-images.githubusercontent.com/39191744/272803576-7c2d9b6f-4e74-4842-89da-c3722481f732.png)
> 
> 页面都没法展示的话就没办法了，可以用回老版兼容版：[#31 (comment)](https://github.com/bpking1/embyExternalUrl/pull/31#issuecomment-1735465882)

用了老版兼容版电影和电视都可以走直链播放了，但是emby升级到最新测试版，比如4.8.0.48，4.8.0.49，4.8.0.51这些版本后走的是我内网穿透的流量，我将emby降级到4.8.0.39就可以走直链了，感谢大佬的付出。

**Comment by chen3861229** [comment]
新版已做初步兼容修复，我这边测试没问题，有时间的话可以更新试试。
