### ISSUE TITLE
重定向失败，求大佬看看

### ISSUE THREAD

**Issue by Jz1028** [bpking1/embyExternalUrl#335]
emby 总显示 playback failed source error
下面这个log是对的吗？

  2024/08/14 14:16:00 [warn] 20#20: *7 js: redirect to: http://xxxx/d/115/%E8%B0%8D%E5%BD%B1%E9%87%8D%E9%87%8D1-5%E9%83%A8%E5%90%88%E9%9B%86%204K%20REMUX/%E8%B0%8D%E5%BD%B1%E9%87%8D%E9%87%8D1%204K%20REMUX%5B2002%5D/The.Bourne.Identity.2002.2160p.BluRay.REMUX.HEVC.DTS-X.7.1.mkv
  2024/08/14 14:16:00 [warn] 20#20: *7 js: routeL1Dict add: [/emby/videos/176/stream.mkv:a6ccd96b2037cf32fb76f954985e163d] : [http://xxxx/d/115/%E8%B0%8D%E5%BD%B1%E9%87%8D%E9%87%8D1-5%E9%83%A8%E5%90%88%E9%9B%86%204K%20REMUX/%E8%B0%8D%E5%BD%B1%E9%87%8D%E9%87%8D1%204K%20REMUX%5B2002%5D/The.Bourne.Identity.2002.2160p.BluRay.REMUX.HEVC.DTS-X.7.1.mkv]
  2024/08/14 14:16:00 [warn] 20#20: *7 js: === redirect2Pan: /emby/videos/176/stream.mkv, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
1.日志中出现`redirect to`关键字就已经是响应重定向指示成功了，可以复制下后边的 alist /d 地址到浏览器中手动访问下，假如返回 401 之类的，需要填写下`emby2Alist\nginx\conf.d\config\constant-mount.js`中的 sign 签名参数

> emby 总显示 playback failed source error

2.更准确可能是`playbackinfo subrequest failed, status`这个吗？假如是这个，可以参考下这个
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#32embyhost

**Comment by Jz1028** [comment]
EMBY+CD2+ALIST可以正常转发观看了。
然后今天配置了一下as，媒体信息也是对的，但是观看的时候又错了，
![image](https://github.com/user-attachments/assets/bdcdceb6-dc8d-43fc-ba73-a16bf2aafe88)
2024/08/15 05:35:24 [warn] 25#25: *232 js: redirect2Pan, UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:24 [info] 25#25: *232 js: redirect2Pan cacheKey: /emby/videos/1183/stream.mkv:292f99b49528edef92c9fd8c9d0df9f5
2024/08/15 05:35:24 [warn] 25#25: *232 js: hit cache routeL1Dict: @root
2024/08/15 05:35:24 [info] 25#25: *232 js: internalRedirect to: @root
42.80.101.254 - - [15/Aug/2024:05:35:24 +0000] "GET /emby/videos/1183/stream.mkv?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=2147483647&api_key=c4331a323fa346e88a5d7235f52b03ca&MediaSourceId=292f99b49528edef92c9fd8c9d0df9f5&PlaySessionId=2242aa3970134ce2b923c16499949dfd&Static=true HTTP/1.1" 401 35 "-" "Yamby/1.2.5.8(Android" "-"
2024/08/15 05:35:24 [warn] 25#25: *232 js: === redirect2Pan: /emby/videos/1183/stream.mkv, the NJS VM is destroyed ===
2024/08/15 05:35:25 [warn] 25#25: *232 js: redirect2Pan, UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:25 [info] 25#25: *232 js: redirect2Pan cacheKey: /emby/videos/1183/stream.mkv:292f99b49528edef92c9fd8c9d0df9f5
2024/08/15 05:35:25 [warn] 25#25: *232 js: hit cache routeL1Dict: @root
2024/08/15 05:35:25 [info] 25#25: *232 js: internalRedirect to: @root
42.80.101.254 - - [15/Aug/2024:05:35:25 +0000] "GET /emby/videos/1183/stream.mkv?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=2147483647&api_key=c4331a323fa346e88a5d7235f52b03ca&MediaSourceId=292f99b49528edef92c9fd8c9d0df9f5&PlaySessionId=2242aa3970134ce2b923c16499949dfd&Static=true HTTP/1.1" 401 35 "-" "Yamby/1.2.5.8(Android" "-"
2024/08/15 05:35:25 [warn] 25#25: *232 js: === redirect2Pan: /emby/videos/1183/stream.mkv, the NJS VM is destroyed ===
2024/08/15 05:35:26 [warn] 25#25: *232 js: redirect2Pan, UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:26 [info] 25#25: *232 js: redirect2Pan cacheKey: /emby/videos/1183/stream.mkv:292f99b49528edef92c9fd8c9d0df9f5
2024/08/15 05:35:26 [warn] 25#25: *232 js: hit cache routeL1Dict: @root
2024/08/15 05:35:26 [info] 25#25: *232 js: internalRedirect to: @root
42.80.101.254 - - [15/Aug/2024:05:35:26 +0000] "GET /emby/videos/1183/stream.mkv?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=2147483647&api_key=c4331a323fa346e88a5d7235f52b03ca&MediaSourceId=292f99b49528edef92c9fd8c9d0df9f5&PlaySessionId=2242aa3970134ce2b923c16499949dfd&Static=true HTTP/1.1" 401 35 "-" "Yamby/1.2.5.8(Android" "-"
2024/08/15 05:35:26 [warn] 25#25: *232 js: === redirect2Pan: /emby/videos/1183/stream.mkv, the NJS VM is destroyed ===
2024/08/15 05:35:28 [warn] 25#25: *232 js: redirect2Pan, UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:28 [info] 25#25: *232 js: redirect2Pan cacheKey: /emby/videos/1183/stream.mkv:292f99b49528edef92c9fd8c9d0df9f5
2024/08/15 05:35:28 [warn] 25#25: *232 js: hit cache routeL1Dict: @root
2024/08/15 05:35:28 [info] 25#25: *232 js: internalRedirect to: @root
42.80.101.254 - - [15/Aug/2024:05:35:28 +0000] "GET /emby/videos/1183/stream.mkv?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=2147483647&api_key=c4331a323fa346e88a5d7235f52b03ca&MediaSourceId=292f99b49528edef92c9fd8c9d0df9f5&PlaySessionId=2242aa3970134ce2b923c16499949dfd&Static=true HTTP/1.1" 401 35 "-" "Yamby/1.2.5.8(Android" "-"
2024/08/15 05:35:28 [warn] 25#25: *232 js: === redirect2Pan: /emby/videos/1183/stream.mkv, the NJS VM is destroyed ===
2024/08/15 05:35:30 [warn] 25#25: *232 js: getOS UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:30 [warn] 25#25: *232 js: api_key: 7980541e60d04bf2ac99634dc04740f3
2024/08/15 05:35:30 [warn] 25#25: *232 js: domain: http://10.10.10.10:8091/emby/videos/1183
2024/08/15 05:35:30 [warn] 25#25: *232 js: flags.last: false , data.length: 3142
2024/08/15 05:35:30 [warn] 25#25: *232 js: getOS UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:30 [warn] 25#25: *232 js: api_key: 7980541e60d04bf2ac99634dc04740f3
2024/08/15 05:35:30 [warn] 25#25: *232 js: domain: http://10.10.10.10:8091/emby/videos/1183
2024/08/15 05:35:30 [warn] 25#25: *232 js: flags.last: false , data.length: 4096
2024/08/15 05:35:30 [warn] 25#25: *232 js: getOS UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:30 [warn] 25#25: *232 js: api_key: 7980541e60d04bf2ac99634dc04740f3
2024/08/15 05:35:30 [warn] 25#25: *232 js: domain: http://10.10.10.10:8091/emby/videos/1183
2024/08/15 05:35:30 [warn] 25#25: *232 js: flags.last: false , data.length: 596
2024/08/15 05:35:30 [warn] 25#25: *232 js: getOS UA: Yamby/1.2.5.8(Android
2024/08/15 05:35:30 [warn] 25#25: *232 js: api_key: 7980541e60d04bf2ac99634dc04740f3
2024/08/15 05:35:30 [warn] 25#25: *232 js: domain: http://10.10.10.10:8091/emby/videos/1183
2024/08/15 05:35:30 [warn] 25#25: *232 js: flags.last: true
2024/08/15 05:35:30 [warn] 25#25: *232 js: data.length: 7742
2024/08/15 05:35:30 [warn] 25#25: *232 js: osType: android
2024/08/15 05:35:30 [warn] 25#25: *232 js: chisubINdex: -1
2024/08/15 05:35:30 [warn] 25#25: *232 js: subIndex: 3
2024/08/15 05:35:30 [warn] 25#25: *232 js: addUrldata.length: 11644
42.80.101.254 - - [15/Aug/2024:05:35:30 +0000] "GET /emby/Users/ee3ae92a69bf4c82b63cb89e22cb7931/Items/1183 HTTP/1.1" 200 3150 "-" "Yamby/1.2.5.8(Android" "-"
2024/08/15 05:35:30 [notice] 25#25: *232 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000025, client: 42.80.101.254, server: default, request: "POST /emby/Items/1183/PlaybackInfo?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&StartTimeTicks=0&MaxStreamingBitrate=2147483647 HTTP/1.1", host: "10.10.10.10:8091"
2024/08/15 05:35:30 [warn] 25#25: *232 js: playbackinfo proxy uri: /proxy/emby/Items/1183/PlaybackInfo
2024/08/15 05:35:30 [warn] 25#25: *232 js: playbackinfo proxy query string: UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&StartTimeTicks=0&MaxStreamingBitrate=2147483647
2024/08/15 05:35:30 [info] 25#25: *232 js: main request headersOut: {}
2024/08/15 05:35:30 [info] 25#25: *232 js: subrequest headersOut: {"Content-Type":"application/json; charset=utf-8","Content-Length":"3610","Access-Control-Allow-Headers":"Accept, Accept-Language, Authorization, Cache-Control, Content-Disposition, Content-Encoding, Content-Language, Content-Length, Content-MD5, Content-Range, Content-Type, Date, Host, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since, Origin, OriginToken, Pragma, Range, Slug, Transfer-Encoding, Want-Digest, X-MediaBrowser-Token, X-Emby-Token, X-Emby-Client, X-Emby-Client-Version, X-Emby-Device-Id, X-Emby-Device-Name, X-Emby-Authorization","Access-Control-Allow-Methods":"GET, POST, PUT, DELETE, PATCH, OPTIONS","Access-Control-Allow-Origin":"*","Cross-Origin-Resource-Policy":"cross-origin","Access-Control-Allow-Private-Network":"true","Private-Network-Access-Name":"Media Server Movie","Private-Network-Access-Id":"b4dbe7d4265040b0a2156acdd93d4da5"}
2024/08/15 05:35:30 [warn] 25#25: *232 js: origin playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"292f99b49528edef92c9fd8c9d0df9f5","Path":"/mnt/alist/115/超感神探/The.Mentalist.S01.1080p.AMZN.WEBRip.DDP5.1.x264-ViSUM[rartv]/The.Mentalist.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv","Type":"Default","Container":"mkv","Size":3773343159,"Name":"The.Mentalist.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM","IsRemote":false,"HasMixedProtocols":false,"RunTimeTicks":27091230000,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[{"Codec":"h264","ColorTransfer":"bt709","ColorPrimaries":"bt709","ColorSpace":"bt709","TimeBase":"1/1000","VideoRange":"SDR","DisplayTitle":"1080p H264","NalLengthSize":"4","IsInterlaced":false,"BitRate":11142626,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false,"ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0},{"Codec":"eac3","Language":"eng","TimeBase":"1/1000","DisplayTitle":"English EAC3 5.1 (默认)","DisplayLanguage":"English","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":640000,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0},{"Codec":"subrip","Language":"eng","TimeBase":"1/1000","DisplayTitle":"English (SUBRIP)","DisplayLanguage"
2024/08/15 05:35:30 [warn] 25#25: *232 js: modify direct play supports all true
2024/08/15 05:35:30 [warn] 25#25: *232 js: modify direct play info
2024/08/15 05:35:30 [warn] 25#25: *232 js: 5ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"292f99b49528edef92c9fd8c9d0df9f5","Path":"/mnt/alist/115/超感神探/The.Mentalist.S01.1080p.AMZN.WEBRip.DDP5.1.x264-ViSUM[rartv]/The.Mentalist.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM.mkv","Type":"Default","Container":"mkv","Size":3773343159,"Name":"The.Mentalist.S01E01.1080p.AMZN.WEB-DL.DDP5.1.H.264-ViSUM","IsRemote":false,"HasMixedProtocols":false,"RunTimeTicks":27091230000,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[{"Codec":"h264","ColorTransfer":"bt709","ColorPrimaries":"bt709","ColorSpace":"bt709","TimeBase":"1/1000","VideoRange":"SDR","DisplayTitle":"1080p H264","NalLengthSize":"4","IsInterlaced":false,"BitRate":11142626,"BitDepth":8,"RefFrames":1,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Height":1080,"Width":1920,"AverageFrameRate":23.976025,"RealFrameRate":23.976025,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","PixelFormat":"yuv420p","Level":40,"IsAnamorphic":false,"ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0},{"Codec":"eac3","Language":"eng","TimeBase":"1/1000","DisplayTitle":"English EAC3 5.1 (默认)","DisplayLanguage":"English","IsInterlaced":false,"ChannelLayout":"5.1","BitRate":640000,"Channels":6,"SampleRate":48000,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Protocol":"File","ExtendedVideoType":"None","ExtendedVideoSubType":"None","ExtendedVideoSubTypeDescription":"None","AttachmentSize":0},{"Codec":"subrip","Language":"eng","TimeBase":"1/1000","DisplayTitle":"English (SUBRIP)","DisplayLa
42.80.101.254 - - [15/Aug/2024:05:35:30 +0000] "POST /emby/Items/1183/PlaybackInfo?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&IsPlayback=false&AutoOpenLiveStream=false&StartTimeTicks=0&MaxStreamingBitrate=2147483647 HTTP/1.1" 200 3982 "-" "Yamby/1.2.5.8(Android" "-"
2024/08/15 05:35:30 [warn] 25#25: *232 js: === transferPlaybackInfo: /emby/Items/1183/PlaybackInfo, the NJS VM is destroyed ===
42.80.101.254 - - [15/Aug/2024:05:35:30 +0000] "GET /emby/Shows/1413/Episodes?UserId=ee3ae92a69bf4c82b63cb89e22cb7931&SeasonId=1413&Fields=BasicSyncInfo%2CCanDelete%2CCanDownload%2CCommunityRating%2COfficialRating%2CPrimaryImageAspectRatio%2CProductionYear&EnableUserData=true HTTP/1.1" 200 684 "-" "Yamby/1.2.5.8(Android" "-"
