### ISSUE TITLE
有没有支持emby直链的AndroidTv客户端，求指路

### ISSUE THREAD

**Issue by jiemo9527** [bpking1/embyExternalUrl#344]
Android手机，windows，web端都支持；tv找了好久 没有合适的

**Comment by jiemo9527** [comment]
> 官方客户端都是直接支持的，emby TV 端有旧版和新版两个，旧版官方停更了貌似，新版就直接是 Android 手机版，同一个，旧版的区别是 UI 老一些，低性能的电视操作流畅性好一点，版本全是，tg 群，小秘版，的

小秘，魔改都有问题，没有一个达到正常使用的标准。等个正式点的

**Comment by smartutu** [comment]
最新版是不是在安卓tv 2.0版本中打不开视频呢？之前的旧脚本可以兼容 安卓手机 win web ios没问题

**Comment by chen3861229** [comment]
已确认是上周重构时漏掉了`老TV客户端`的兼容导致的，已经测试复现并修复
