### ISSUE TITLE
请求添加图片302的功能

### ISSUE THREAD

**Issue by mhxygu2018** [bpking1/embyExternalUrl#345]
https://szxiot.com/2024/07/25/clouddrive2-alist-strm-302-emby-5/

**Comment by chen3861229** [comment]
额，这个之前考虑过，不过现阶段应该不会实现这个，https://github.com/bpking1/embyExternalUrl/blob/main/emby2Alist/README.md#2024-06-16
，第 4 点，对于网盘这块当初放弃实现的主要原因是: 

1.对于部分限制比较严格的网盘风险会很大，因为相当于把网盘当图床用了，请求加载数量会很大，而且是等于各客户端数量的乘积，且访问的 IP 会更加分散，理论上只有`OneDrive`安全点儿

2.体验可能不是太好，一般图片服务默认都遵守空间(多级缓存)换时间(速度/安全)的策略，引用中最后提到的第二点，确实也是 emby 服务端对于图片默认有一个缩放优化，再加上 4.8 之后新增的媒体库设置中可选的[在服务器的元数据文件夹中保留图像的缓存副本]功能也是一项优化，加上图片 302 会使 emby 自身的多项优化失效，其实反向用时间换空间了，感觉有些弊大于利

3.实现后真正操作起来会比之前麻烦很多，emby 也是如引用中最后提到的第 1 点，入库的时候

3.1 如果媒体文件/STRM旁边不存在图片文件，emby 服务端会通过选择的刮削器将图片默认下载到它内部的一个元数据目录保存，只有媒体库勾选了[将媒体图像保存到媒体文件夹中]后才会下载到媒体旁，假如此媒体目录是网盘挂载的，这样大量的写入请求也对网盘安全有些影响，不过假如是纯本地目录内部放置 STRM 文件的，此时这样需要和网盘用第三方同步软件保持同步

3.2 如果媒体文件/STRM旁边存在图片文件，此时的图片文件路径才会正确存入 emby 数据库中，这种才能实现在访问时获取图片路径进行映射并 302 重定向到网盘中

4.稍微与 emby 自身的一些操作逻辑冲突，例如手动更换封面，上传至服务端存储目的地也是受[将媒体图像保存到媒体文件夹中]选项的影响，假如为默认的未勾选状态，同样也是存在 emby 内部的元数据文件夹中，这种情况就无法获取到真实的网盘路径了，当然这种可以脚本中判断出来从而不走 302 重定向，但是补救措施可能不仅这一处

5.最后最重要的，应该是属于违背了成熟同类媒体软件的一个默认倾向，emby/jellyfin/plex，各播放器，各刮削软件，均是将图片和 NFO 视为临时文件，存在多级缓存来降低顶部 IMDB/TMDB/FanART 的访问压力，而不是引用直接显示它们的图源和数据，
此点是梯子与否无关，虽然我也觉得这样实时性太差了，考虑过提到的图片 302 重定向，不过最终还是遵守这个惯例，因为大佬们统一的多级缓存设计理念肯定比我强
