### ISSUE TITLE
新版本是需要修改什么配置吗？

### ISSUE THREAD

**Issue by xianglongwei** [bpking1/embyExternalUrl#347]
使用的是上个版本的constant.js，其他文件都是使用的最新版本，但是出现下面图片情况。是需要修改哪里吗？
![image](https://github.com/user-attachments/assets/0b297529-6be1-4186-b4a6-455850a21dee)

最新版本为；[fix(emby2Alist): 修复已多版本的转码直链](https://github.com/bpking1/embyExternalUrl/commit/4f5315aa36291788351c28210f18553d91b34b26)

**Comment by xianglongwei** [comment]
7/PlaybackInfo, the NJS VM is destroyed ===
192.168.10.100 - - [24/Aug/2024:22:42:57 +0800] "POST /emby/Items/174617/PlaybackInfo?UserId=42d57fc3f73a4fd0b1e527b30889e0d9&StartTimeTicks=0&IsPlayback=false&AutoOpenLiveStream=false&MaxStreamingBitrate=200000000&X-Emby-Client=Emby+Web&X-Emby-Device-Name=Chrome+Windows&X-Emby-Device-Id=7a35ce78-c505-4b31-9752-eb42f775f912&X-Emby-Client-Version=4.9.0.29&X-Emby-Token=0563bccf6b264482b27e309002676d57&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 500 572 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
![image](https://github.com/user-attachments/assets/e8a04371-62dc-48db-83f5-5eebdee96a8d)

**Comment by chen3861229** [comment]
感觉是新功能添加的配置变量未定义导致的，可能需要手动检查下这两个文件了
`emby2Alist\nginx\conf.d\config\constant-ext.js`
```js
// 115网盘 web cookie, 会覆盖从 alist 获取到的 cookie
const webCookie115 = "";
// 网盘转码直链配置,当前仅支持 115(必填 webCookie115) 和 emby 挂载媒体环境
const directHlsConfig = {
  enable: false,
  // 仅在首次占位未获取清晰度时,默认播放最小,开启后默认播放最大,版本缓存有效期内客户端自行选择
  defaultPlayMax: false,
  // 启用规则,仅在 enable = true 时生效
  enableRule: ruleRef.directHlsEnable ?? [],
};

export default {
  imageCachePolicy,
  embyNotificationsAdmin,
  embyRedirectSendMessage,
  itemHiddenRule,
  streamConfig,
  searchConfig,
  webCookie115,
  directHlsConfig,
}
```
`emby2Alist\nginx\conf.d\constant.js`
![image](https://github.com/user-attachments/assets/4c7c2044-317e-4c66-a8ae-39af4b628a7d)

**Comment by chen3861229** [comment]
[fix(emby2Alist): 兼容历史配置](https://github.com/bpking1/embyExternalUrl/commit/43425bb2b47d2147b900a0e969b3ce84064847e4)
 中应该已经修复了
