### ISSUE TITLE
希望重定向获取的alist直链失效时，用emby客户端推流

### ISSUE THREAD

**Issue by bigmouse0001** [bpking1/embyExternalUrl#349]
1. alist挂载分享链接，
2. 有些分享链接会失效或和谐一部分内容，
3. 这时候redirect获取的alist直链就失效了，返回给客户端会无法播放

所以希望增加一个检测： 
在”脚本返回直链给客户端“ 之前，如果redirect获取的alist直链无效，则转为用emby推流原始地址

为什么要用分享链接，而不用自己网盘？
答：302全走自己网盘风险太大了，改为挂分享链接风险会小很多

**Comment by chen3861229** [comment]
这个可以加，实现起来应该也比较简单，因为之前考虑过`路由缓存`那边加这个有效性检测，但那边是自动行为获取不到用户`UA`，所以暂时搁置了，而此次是播放前检测一遍，是没问题的
