### ISSUE TITLE
[BUG] 反代PlaybackInfo导致响应内容缺少加载字幕相关的必须字段

### ISSUE THREAD

**Issue by chen3861229** [bpking1/embyExternalUrl#35]
1.此为注释反代PlaybackInfo路径后，外挂ass字幕的mkv文件测试，电脑Web浏览器播放条件。
![49b983a0d03ea038c3f8af3fcc5affbc](https://github.com/bpking1/embyExternalUrl/assets/42368856/3eb0a1a5-fd21-4a62-989d-98d78f0164a5)
![47a5a31bb8705058ed835aa644740a1e](https://github.com/bpking1/embyExternalUrl/assets/42368856/2a1c5f2a-8275-4fb6-bed4-9ccc057fcad4)

2.此为放开反代PlaybackInfo路径后，外挂ass字幕的mkv文件测试，电脑Web浏览器播放条件。
![237dbe339a400116d23892fcac9a64ce](https://github.com/bpking1/embyExternalUrl/assets/42368856/ce63ce6e-8767-4fa4-bbe7-c68168301b63)
![94c35c34775b73be46b3a296ba404511](https://github.com/bpking1/embyExternalUrl/assets/42368856/e4ddfdae-d7e2-4a64-ad32-5f98e2683d9f)

2.1 此为放开反代PlaybackInfo路径后，内挂ass字幕的mkv文件测试，电脑Web浏览器播放条件。
![ed8aea36acf85fc02e4d60b6267d6aac](https://github.com/bpking1/embyExternalUrl/assets/42368856/b00735ce-e31c-42bb-9927-08bc638a72c6)

3.此为Emby的Web端判断逻辑。
![a57e5cba4d1a8128af0f01a34df38baa](https://github.com/bpking1/embyExternalUrl/assets/42368856/85edd6bf-d4f5-42ab-a60e-f623828d6e97)

@AmbitiousJun，希望能抽空修复下transferPlaybackInfo的逻辑，或者在constant.js中加一个开关控制也行，多谢了

**Comment by AmbitiousJun** [comment]
感谢截图，反代playbackinfo确实有很多细节要处理，我这两天修复一下。目前的话完全可以先去掉playbackinfo的反代，影响不是很大。只是如果有电视直播的需求的话会导致web端播放影视触发转容器无法播放。

**Comment by chen3861229** [comment]
好的，麻烦了
