### ISSUE TITLE
新版本直连失效，需要修改什么配置吗

### ISSUE THREAD

**Issue by as932256** [bpking1/embyExternalUrl#352]
从24-07-03这个版本升级上来的

日志显示2024/08/26 15:06:38 [warn] 20#20: *52 js: mediaPathMapping: [[0,0,"/volume1/CloudNAS/alist",""]]
2024/08/26 15:06:38 [warn] 20#20: *52 js: strMapping replace: /volume1/CloudNAS/alist => 
2024/08/26 15:06:38 [warn] 20#20: *52 js: mapped emby file path: /115/媒体库/电视/大陆剧集/琉璃 (2020) {tmdb-96128} [tmdbid=96128]/Season 1/琉璃 - S01E05 - 第5集.mp4
2024/08/26 15:06:38 [warn] 20#20: *52 js: sourceStrValue, alistRes = /115/媒体库/电视/大陆剧集/琉璃 (2020) {tmdb-96128} [tmdbid=96128]/Season 1/琉璃 - S01E05 - 第5集.mp4
2024/08/26 15:06:38 [warn] 20#20: *52 js: strMatches result: false, type: 2, string source: /115/媒体库/电视/大陆剧集/琉璃 (2020) {tmdb-96128} [tmdbid=96128]/Season 1/琉璃 - S01E05 - 第5集.mp4, string target: 115.com
2024/08/26 15:06:38 [warn] 20#20: *52 js: fetchAlistPathApi add Host: 127.0.0.1:5244
2024/08/26 15:06:43 [warn] 20#20: *52 js: 4805ms, fetchAlistPathApi async function cost
2024/08/26 15:06:43 [warn] 20#20: *52 js: fetchAlistPathApi, UA: libmpv
2024/08/26 15:06:43 [warn] 20#20: *52 js: sourceStrValue, alistRes = ttps://cdnfhnfile.115.com/1111111/%E7%90%89%E7%92%83%20-%20S01E05%20-%20%E7%AC%AC5%E9%9B%86.mp4
2024/08/26 15:06:43 [warn] 20#20: *52 js: strMatches result: true, type: 2, string source: https://cdnfhnfile.115.com/1111111/%E7%90%89%E7%92%83%20-%20S01E05%20-%20%E7%AC%AC5%E9%9B%86.mp4, string target: 115.com
2024/08/26 15:06:43 [warn] 20#20: *52 js: hit clientSelfAlistRule: [2,"115.com","https://域名"]
2024/08/26 15:06:43 [warn] 20#20: *52 js: redirect to: https://域名/d/115/%E5%AA%92%E4%BD%93%E5%BA%93/%E7%94%B5%E8%A7%86/%E5%A4%A7%E9%99%86%E5%89%A7%E9%9B%86/%E7%90%89%E7%92%83%20(2020)%20%7Btmdb-96128%7D%20%5Btmdbid=96128%5D/Season%201/%E7%90%89%E7%92%83%20-%20S01E05%20-%20%E7%AC%AC5%E9%9B%86.mp4
2024/08/26 15:06:43 [warn] 20#20: *52 js: routeL1Dict add: [/emby/videos/79724/stream.mp4:c2119e7e217b7af360f2ba0274402358] : [https://域名/d/115/%E5%AA%92%E4%BD%93%E5%BA%93/%E7%94%B5%E8%A7%86/%E5%A4%A7%E9%99%86%E5%89%A7%E9%9B%86/%E7%90%89%E7%92%83%20(2020)%20%7Btmdb-96128%7D%20%5Btmdbid=96128%5D/Season%201/%E7%90%89%E7%92%83%20-%20S01E05%20-%20%E7%AC%AC5%E9%9B%86.mp4]
2024/08/26 15:06:43 [warn] 20#20: *52 js: === redirect2Pan: /emby/videos/79724/stream.mp4, the NJS VM is destroyed ===
2024/08/26 15:07:11 [notice] 27#27: http file cache: /var/cache/nginx/emby/images 1148.859M, bsize: 4096
2024/08/26 15:07:11 [notice] 27#27: http file cache: /var/cache/nginx/emby/subtitles 0.289M, bsize: 4096

表现为https://域名/d/115/%E5%AA%92%E4%BD%93%E5%BA%93/%E7%94%B5%E8%A7%86/%E5%A4%A7%E9%99%86%E5%89%A7%E9%9B%86/%E7%90%89%E7%92%83%20(2020)%20%7Btmdb-96128%7D%20%5Btmdbid=96128%5D/Season%201/%E7%90%89%E7%92%83%20-%20S01E05%20-%20%E7%AC%AC5%E9%9B%86.mp4  这个链接播放显示无效

回退旧版本正常

安装方式是git整个项目后用docker-compose安装

**Comment by chen3861229** [comment]
确认此版本是有`handleAlistRawUrl`，这个在之前的重构中合并迁移了一下，
https://github.com/bpking1/embyExternalUrl/blob/d59ab45beb9b0ede9e8f06b83ae3cfd37a6cf0e5/emby2Alist/nginx/conf.d/emby.js#L411

可以参考，https://github.com/bpking1/embyExternalUrl/issues/291#issuecomment-2233466159
需要修改的配置文件为`emby2Alist\nginx\conf.d\config\constant-mount.js`，配置文件需要手动更改下，一般更新代码应该没动历史配置文件

cilentSelfAlistRule
=> il 之前大意写反了
clientSelfAlistRule
