### ISSUE TITLE
最新的代码yamby302直连失败

### ISSUE THREAD

**Issue by kevinBobo** [bpking1/embyExternalUrl#353]
看日志是调用emby的获取路径的时候401了，好像和客户端有关系，vidhub貌似没事
<img width="1374" alt="image" src="https://github.com/user-attachments/assets/be0d57b6-c1e7-4410-b0c0-ce908cfd8339">

**Comment by chen3861229** [comment]
貌似没啥问题，
![image](https://github.com/user-attachments/assets/e199af17-4ba9-4f03-ad30-136b952d68d9)
有更新到这一版吗？https://github.com/bpking1/embyExternalUrl/commit/c1ca6bc7bdf308a6f3c9e50a64965a67adbb8238
这版应该修复了 老 TV 客户端之类的 401 问题

**Comment by kevinBobo** [comment]
> 貌似没啥问题， ![image](https://private-user-images.githubusercontent.com/42368856/361523244-e199af17-4ba9-4f03-ad30-136b952d68d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ3Mjc1NjEsIm5iZiI6MTcyNDcyNzI2MSwicGF0aCI6Ii80MjM2ODg1Ni8zNjE1MjMyNDQtZTE5OWFmMTctNGJhOS00ZjAzLWFkMzAtMTM2Yjk1MmQ2OGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI3VDAyNTQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ODM0NzlkYjNlY2IzZGRiNDMzNTYxNzE3NTQ5MTJlNDg4ZDFjM2NjNDRhM2Q1MGFjNDJlOTExODY5NGRlZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l-oOWmJLrg4aL_x9iPucKN3q4upFkbavr6OH-cZHA7s) 有更新到这一版吗？[c1ca6bc](https://github.com/bpking1/embyExternalUrl/commit/c1ca6bc7bdf308a6f3c9e50a64965a67adbb8238) 这版应该修复了 老 TV 客户端之类的 401 问题

我看昨天刚更新的，我用最新的再试一下

**Comment by kevinBobo** [comment]
更新到最新代码，问题已修复，yamby可以正常播放
