### ISSUE TITLE
回源到115的CD2挂载目录，下载流量数据过高导致CPU负载过大问题？

### ISSUE THREAD

**Issue by Bear5074** [bpking1/embyExternalUrl#355]
首先感谢作者的努力奉献，项目非常好用。

我使用了CD2+115已经有快两年了。新增作者项目一段时间，发现一个问题一直存在，就是在回源的时候回导致下载流量过高，CPU使用率过高。

场景一：emby+CD2
emby请求的数据和CD2下载的数据对等，比如播放请求多少电影文件数据CD2会下载多少，此时上下载数据基本对等，流量比较均匀。

场景二：emby+CD2+作者项目nginx
所有媒体文件夹指定到在const mediaPathMapping的目录内，此时一切正常，数据上下载对等。
若是某个文件夹并未被指定到const mediaPathMapping的目录内（因为我想部分文件夹不走直链），这部分回源的数据，就会瞬间请求过大的数据流量，并导致CPU负载过高。
我把本地目录挂载到alits，再放入在const mediaPathMapping内，此时流量一切正常，数据上下载对等。

场景三：作者更新了码率判定（这个相当相当的牛逼）
此时判定回本地的数据，没办法指定某个目录了，只能回源，然后又出现之前问题。

我从我的角度得出的测试结果是
emby➡️CD2挂载目录， 拉取的数据是正常的
emby➡️nginx➡️alist➡️CD2挂载目录， 数据也是正常的
emby➡️nginx➡️CD2挂载目录， 数据就开始有点不正常了 拉取量非常大

可否优化一下nginx读取CD2挂载目录的流量请求？
或者给码率判定或者回源的数据文件 指定一个目录，比如指定到alist里的本地存储挂载？

再次感谢作者，另外作者能不能留下一个支付渠道想给作者捐献一点微薄的力量已表对项目的支持

**Comment by chen3861229** [comment]
> 若是某个文件夹并未被指定到const mediaPathMapping的目录内（因为我想部分文件夹不走直链），这部分回源的数据，就会瞬间请求过大的数据流量，并导致CPU负载过高。

1.`反代回源`的流量确实是`nginx`中转了一次，原本流量路径为，播放客户端 <= emby <= 挂载层`CD2`，此时为 播放客户端 <= nginx 反代回源 <= emby <= 挂载层 CD2，这会导致网速或流量统计软件呈现出双倍的带宽和流量，这个是正常现象，反代的基础依赖这个行为，不过对于`emby`和`CD2`读取网盘的流量还是一次，重点可能出现在`CPU负载过高`这一现象上，nginx 反代默认流式传输文件是内存中缓存一些同时转发，不过很久之前在所有涉及到大文件量的反代接口的`location`块中添加了`proxy_buffering off;`，以此禁用了这一默认行为，关闭后应该是不使用额外的内存缓存了，而是将上游(emby)接收到的分块文件实时传输给客户端，不清楚是否是这一改动导致的，可以尝试下将`emby.conf`中所有的`proxy_buffering off;`改为`# proxy_buffering off;`注释掉对比下`CPU负载情况`，我这边查询下 nginx 文件看是否还有其它优化空间

> 此时判定回本地的数据，没办法指定某个目录了，只能回源，然后又出现之前问题。

2.`路由规则`中这个新增的码率判定，是同一个分组规则内的一个`与`/`并且`/`&&`的效果，可以和之前的`指定某个目录`同时工作的，更详细的示例如下
```js
// 路由规则,注意有先后顺序,"proxy"规则优先级最高,其余依次,千万注意规则不要重叠,不然排错十分困难,字幕和图片走了缓存,不在此规则内
// 参数1: 指定处理模式,单规则的默认值为"proxy",但是注意整体规则都不匹配默认值为"redirect",然后下面参数序号-1
// "proxy": 原始媒体服务器处理(中转流量), "redirect": 直链302, "transcode": 转码, "block": 只是屏蔽播放
// "transcode",稍微有些歧义,大部分情况等同于"proxy",这里只是不做转码参数修改,具体是否转码由 emby 客户端自己判断上报或客户端手动切换码率控制
// 参数2: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数3: 匹配类型或来源(字符串参数类型) "filePath": 文件路径(Item.Path), "alistRes": alist返回的链接
// 参数4: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数5: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
const routeRule = [
  // 假如单条规则,不需要其它逻辑判断,这里写法是无省略的可读性更好
  ["proxy", "走回源-local-01", "filePath", "startsWith", "/01文件夹不走直链"],
  // 假如需要和其它逻辑条件,例如大于等于 3Mbps 码率的走代理回源中转,以下代表组内同时满足才生效
  ["proxy", "走回源-local-02", "filePath", "startsWith", "/02文件夹不走直链"],
  ["proxy", "走回源-local-02", "r.XMedia.Bitrate", ">=", 3 * 1024 ** 2],
];
```

> 可否优化一下nginx读取CD2挂载目录的流量请求？

3.这个如 1 中的，会尝试优化一下

> 或者给码率判定或者回源的数据文件 指定一个目录，比如指定到alist里的本地存储挂载？

4.这个如 2 中的，应该是可以精细化逻辑判断了，不过这个`比如指定到alist里的本地存储挂载？`最好不要这样做，意味着需要使用`mediaPathMapping`路径映射功能了，变得更加复杂和不容易排查了，其实这句的同等方法`我把本地目录挂载到alits，再放入在const mediaPathMapping内，此时流量一切正常，数据上下载对等。`已经解决了且更加简单


> 另外作者能不能留下一个支付渠道想给作者捐献一点微薄的力量已表对项目的支持

5.这个倒是不用了，多谢认可就行，毕竟我也是基于`bpking1`大佬修改的，最重要也是平时需要自用

**Comment by Bear5074** [comment]
感谢作者的认真讲解回答，经过一晚上的测试，结果如下：
1.将emby.conf中所有的proxy_buffering off;改为# proxy_buffering off;注释掉对比下CPU负载情况
结果：CPU占用并没有减轻什么变化。和修改之前数值是一致的。新旧版本都测试过了

2.回源到指定目录我可能没有表达清楚，我想说的是能否有两个mediaPathMapping，
比如mediaPathMapping-A和mediaPathMapping-B，两个文件内部文件路径结构都是一致的，但是主体形式不一致。
判定码率大于xx数值的走mediaPathMapping-A，判定码率小于xx数值的走mediaPathMapping-B。
这样应该能有效减少判定后回源本地的CPU占用问题，就是不知是否能够方便实现。

**Comment by Bear5074** [comment]
测试环境为openwrt docker版本 配置为i7 12代 内存32G
1.走mediaPathMapping指定目录（alist中的本地存储目录），播放本地流量视频单个任务消耗CPU占用百分之3左右，多人在线观看CPU峰值百分之20左右（最高20个任务）
2.不设置指定目录mediaPathMapping，让数据自动回源，单个任务消耗CPU占比百分之20左右，多人在线观看CPU峰值直接拉满百分之百（最高五六个任务差不多就死机了）

修改proxy_buffering off前后对比没有区别，更换新版本也一样没有区别

**Comment by chen3861229** [comment]
1.多谢详细的测试数据了，回源 CPU 占用稍高的问题估计不太好解决，之后我这边模拟多测试一下

> 2.回源到指定目录我可能没有表达清楚，我想说的是能否有两个mediaPathMapping，
> 比如mediaPathMapping-A和mediaPathMapping-B，两个文件内部文件路径结构都是一致的，但是主体形式不一致。
> 判定码率大于xx数值的走mediaPathMapping-A，判定码率小于xx数值的走mediaPathMapping-B。
> 这样应该能有效减少判定后回源本地的CPU占用问题，就是不知是否能够方便实现。

2.不好意思，之前眼花理解错了，已有这个前提的话`两个文件内部文件路径结构都是一致的`是可以很简单实现`判定码率大于xx数值的走mediaPathMapping-A，判定码率小于xx数值的走mediaPathMapping-B`条件的，之前增强过一版`mediaPathMapping`所以也是支持从`r.XMedia.Bitrate`判断的，不过需要明确下使用条件

2.1 首先需要更新下代码，之前重构导致漏掉了`r`参数的传递，马上会进行修复

2.2 建议简单环境下使用，即`mediaPathMapping`路径映射数组中的 mediaPathMapping-A 和 mediaPathMapping-B ... 多个单条规则，做路径字符串的替换最好不要写得太复杂，例如源路径和目标路径层级或者文件名差异过大，不然可能日志不太好排查，当然仅是建议，假如其它手段无法更简单解决，还是可以使用

3.3 以下是基于`回源导致CPU负载过高`和`比如指定到alist里的本地存储挂载`的需求，仅为示例配置

```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数?.1: 生效规则三维数组,有时下列参数序号加一,优先级在参数2之后,需同时满足,多个组是或关系(任一匹配)
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  // [0, 0, "/aliyun-01", "/aliyun-02"],
  // [0, 2, "http:", "https:"],
  // [0, 2, ":5244", "/alist"],
  // [0, 0, "D:", "F:"],
  // [0, 0, /blue/g, "red"], // 此处正则不要加引号
  // [1, 1, `${alistPublicAddr}/d`],
  // [2, 2, "?xxx"],
  // 此条是一个规则变量引用,方便将规则汇合到同一处进行管理
  // [ruleRef.mediaPathMappingGroup01, 0, 0, "/aliyun-01", "/aliyun-02"],
  // 路径映射多条规则会从上至下依次执行,如下有同一个业务关系集的,注意带上区间的闭合条件,不然会被后续重复替换会覆盖
  // 以下是按码率条件进行路径映射,全用户设备强制,区分用户和设备可再精确添加条件
  [[["4K 目录映射到 1080P 目录", "r.XMedia.Bitrate", ">", 10 * 1000 ** 2],
  ], 0, 0, "/4K/", "/1080P/"],
  [[["1080P 目录映射到 720P 目录", "r.XMedia.Bitrate", ">", 6 * 1000 ** 2],
    ["1080P 目录映射到 720P 目录", "r.XMedia.Bitrate", "<=", 10 * 1000 ** 2],
  ], 0, 0, "/1080P/", "/720P/"],
  [[["720P 目录映射到 480P 目录", "r.XMedia.Bitrate", ">", 3 * 1000 ** 2],
    ["720P 目录映射到 480P 目录", "r.XMedia.Bitrate", "<=", 6 * 1000 ** 2],
  ], 0, 0, "/720P/", "/480P/"],
];
```

**Comment by Bear5074** [comment]
感谢作者，已经完美实现 膜拜大神
