### ISSUE TITLE
关于软链接直链和 strm 直链的问题

### ISSUE THREAD

**Issue by enjoyO** [bpking1/embyExternalUrl#360]
我仔细对比过 strm 直链和软链接直链时候nginx 中的日志，有些不太一样，因为之前一直 strm 现在向换成软链 ，
strm 直链的日志如下：
![6521724995198_ pic](https://github.com/user-attachments/assets/316b2324-23c1-43be-ad0e-da91993710a8)

软链接 直链的日志如下：
![6501724993818_ pic](https://github.com/user-attachments/assets/f8b5bd42-1a22-41de-81d8-90e338b58ca5)

自己直观的使用感受是好像 strm 直链更好一些， 软链接直链的时候最后又返回了局域网 alist 的文件地址，请问一下，我这个是不是软连接的时候配置不对呢？ 看日志的话两种方式都配置合适了吗？ 请大佬空闲里帮忙解惑一下哈

**Comment by enjoyO** [comment]
> 软链接配置是对的，只有获取到了指向文件的原始路径就是生效的，关于提到的差一点，主要是这个`clientSelfAlistRule `参数影响的，下边也提到的了几个特殊的客户端，假如不存在客户端拖动进度条花屏问题时，可以注释下方默认的规则禁用，这样和 strm 的日志行为应该就是差不多的了，strm 直链和软链接直链这两种各有优缺点，需要自己主观感觉选择了
> 
> ```js
> // 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
> // 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
> // 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
> // 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
> // ,有分组时不可省略填写,可为表达式
> // 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
> // 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
> // 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
> const clientSelfAlistRule = [
>   // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
>   // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
>   [2, strHead["115"], alistPublicAddr],
> ];
> ```

好的 ，谢谢您的解惑

**Comment by enjoyO** [comment]
> 软链接配置是对的，只有获取到了指向文件的原始路径就是生效的，关于提到的差一点，主要是这个`clientSelfAlistRule `参数影响的，下边也提到的了几个特殊的客户端，假如不存在客户端拖动进度条花屏问题时，可以注释下方默认的规则禁用，这样和 strm 的日志行为应该就是差不多的了，strm 直链和软链接直链这两种各有优缺点，需要自己主观感觉选择了
> 
> ```js
> // 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
> // 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
> // 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
> // 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
> // ,有分组时不可省略填写,可为表达式
> // 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
> // 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
> // 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
> const clientSelfAlistRule = [
>   // "Emby for iOS"和"Infuse"对于 115 的进度条拖动依赖于此
>   // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
>   [2, strHead["115"], alistPublicAddr],
> ];
> ```

大佬 还有个事情请教一下，我现在这种情况把 115 用 cd2 挂载到本地 nas，然后  如果用symlink 软连接， 生成的软连接生成到nas 本地硬盘上面，这样 emby 在扫软连接的时候也跟 strm 一样 减少对网盘挂载的扫库的吗？ 还是有些想换成软链接，之前是看您有推荐用软链接来着

**Comment by chen3861229** [comment]
> 这样 emby 在扫软连接的时候也跟 strm 一样 减少对网盘挂载的扫库的吗？

1.虽然理论上`软链接`会减少自动扫库，不过是取决于该`软链接`这个文件本身的`最后修改时间`不会发生变化，这个需要自己留意下的，我这边并没有过多测试过`软链接`和`STRM`，自用一直是使用最老的挂载媒体的方式，媒体量太多已经无法轻易切换了

> 还是有些想换成软链接

2.是的，单论`软链接`和`STRM`，还是推荐`软链接`，推荐理由是比较符合这些媒体服务器的文件系统方式，而`STRM`仅在 emby 上支持较好，jellyfin/plex 体验上会差点儿(每次播放都会慢一点)，所以说推荐`软链接`仅是考虑`可迁移性`和`潜在的兼容性`稍微好点儿，假如暂时不用考虑这几点，`STRM`也是可以日常使用的

**Comment by enjoyO** [comment]
> > 这样 emby 在扫软连接的时候也跟 strm 一样 减少对网盘挂载的扫库的吗？
> 
> 1.虽然理论上`软链接`会减少自动扫库，不过是取决于该`软链接`这个文件本身的`最后修改时间`不会发生变化，这个需要自己留意下的，我这边并没有过多测试过`软链接`和`STRM`，自用一直是使用最老的挂载媒体的方式，媒体量太多已经无法轻易切换了
> 
> > 还是有些想换成软链接
> 
> 2.是的，单论`软链接`和`STRM`，还是推荐`软链接`，推荐理由是比较符合这些媒体服务器的文件系统方式，而`STRM`仅在 emby 上支持较好，jellyfin/plex 体验上会差点儿(每次播放都会慢一点)，所以说推荐`软链接`仅是考虑`可迁移性`和`潜在的兼容性`稍微好点儿，假如暂时不用考虑这几点，`STRM`也是可以日常使用的

好的  谢谢哈
