### ISSUE TITLE
plex最近发现外挂字幕无法加载

### ISSUE THREAD

**Issue by EscapeDG** [bpking1/embyExternalUrl#361]
plex最近发现外挂字幕无法加载，包括plex自带的搜索字幕也无法加载，内封的没有问题

**Comment by chen3861229** [comment]
1.脚本对于 plex 基础功能这块有很长时间没有太大变更了，不过这个`包括plex自带的搜索字幕也无法加载`看起来好像和上个月的 plex.tv 国内被墙可能有些关系，可以尝试将搜索字幕的域名也科学一下试试

2.然后剩下的媒体自带的字幕相关的话，这个问题倒是从第一版就是存在的，具体原因是 plex 官方客户端对于复杂特效或很多字幕格式不支持导致的，很久之前网友协助对比测试过，内封字幕也会有问题，我的测试文件是`马里奥`，当时测试，内封的外文都是`srt`的无特效字幕，安卓 plex 是可以切换显示出来的，片源内封的繁中也是没问题，不过外挂简中的`ass`或`srt`，仅有部分样式简单的可以切换出来，例如涉及高级样式或额外字体的，都是显示空的，切换选中无用，所以对字幕支持这块最好还是用第三方专业的播放器
