### ISSUE TITLE
大神能否增加一个禁止infuse或者vidhub等第三方播放器，下载文件的开关？

### ISSUE THREAD

**Issue by Bear5074** [bpking1/embyExternalUrl#363]
大神能否增加一个禁止infuse或者vidhub等第三方播放器，下载文件的开关？

emby客户端用户那里虽然可以关闭下载功能，但是通过infuse或者vidhub还是可以进行下载，有没有方法可以过滤掉下载请求呢？只通过播放请求

**Comment by Bear5074** [comment]
谢谢，因为没有这个功能的话，后台有某个人下载，特别是连续剧会占用十几个线路，马上就115账号就被风险踢掉线了

**Comment by chen3861229** [comment]
这边因为之前的`路由规则`本身带一个屏蔽功能，所以仅仅是简单拓展了一下，并没有进行实际测试，所以需要麻烦更新代码打开以下注释自测一下了，示例规则位于`emby2Alist\nginx\conf.d\config\constant-pro.js`
```js
// 路由规则,注意有先后顺序,"proxy"规则优先级最高,其余依次,千万注意规则不要重叠,不然排错十分困难,字幕和图片走了缓存,不在此规则内
// 参数1: 指定处理模式,单规则的默认值为"proxy",但是注意整体规则都不匹配默认值为"redirect",然后下面参数序号-1
// "proxy": 原始媒体服务器处理(中转流量), "redirect": 直链 302,
// "transcode": 转码,稍微有些歧义,大部分情况等同于"proxy",这里只是不做转码参数修改,具体是否转码由 emby 客户端自己判断上报或客户端手动切换码率控制,
// "block": 屏蔽媒体播放和下载, "blockDownload": 只屏蔽下载, "blockPlay": 只屏蔽播放,
// 参数2: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数3: 匹配类型或来源(字符串参数类型) "filePath": 文件路径(Item.Path), "alistRes": alist返回的链接
// 参数4: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数5: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
const routeRule = [
  // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
  ["blockDownload", "屏蔽下载", "r.headersIn.User-Agent", "includes", strHead.xUAs.clients3rdParty],
];
```

**Comment by Bear5074** [comment]
感谢大神，经过测试，infuse依然可以下载。
我配置好以后，注释掉了第一条
  // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
  ["blockDownload", "屏蔽下载", "r.headersIn.User-Agent", "includes", strHead.xUAs.clients3rdParty],
  // 非必须,该分组内细分为用户 id 白名单,结合上面一条代表 "屏蔽指定标识客户端的非指定用户的下载"
  // ["blockDownload", "屏蔽下载", "r.args.UserId", "startsWith:not", ["ac0d220d548f43bbb73cf9b44b2ddf0e"]],
  // 非必须,该分组内细分为入库路径黑名单,结合上面两条代表 "屏蔽指定标识客户端的非指定用户的指定入库路径的下载"
  // ["blockDownload", "屏蔽下载", "filePath", "startsWith", ["/mnt/115"]],
];

但是，在infuse中并没有生效，依然可以添加下载任务

**Comment by Bear5074** [comment]
我又尝试打开第三条注释，并设置了目录，但是依旧没有什么变化，infuse还是可以下载。
  // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
  ["blockDownload", "屏蔽下载", "r.headersIn.User-Agent", "includes", strHead.xUAs.clients3rdParty],
  // 非必须,该分组内细分为用户 id 白名单,结合上面一条代表 "屏蔽指定标识客户端的非指定用户的下载"
  // ["blockDownload", "屏蔽下载", "r.args.UserId", "startsWith:not", ["ac0d220d548f43bbb73cf9b44b2ddf0e"]],
  // 非必须,该分组内细分为入库路径黑名单,结合上面两条代表 "屏蔽指定标识客户端的非指定用户的指定入库路径的下载"
  ["blockDownload", "屏蔽下载", "filePath", "startsWith", ["/mnt"]],
];

**Comment by chen3861229** [comment]
用接口测试工具模拟了下，是没问题的，建议排查下业务日志`error.log`，不知是否是`emby2Alist\nginx\conf.d\emby.conf`中漏掉了一些新增的接口标识呢？
配置的话，只用了这一条
```js
const routeRule = [
  // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
  ["blockDownload", "屏蔽下载", "r.headersIn.User-Agent", "includes", strHead.xUAs.clients3rdParty],
];
```
![image](https://github.com/user-attachments/assets/658d4b41-7652-4ff4-837f-a3445e05e971)
![image](https://github.com/user-attachments/assets/fbd59ae5-9e88-40a4-bdbf-e9f0099832c2)

**Comment by Bear5074** [comment]
2024/09/14 15:41:36 [warn] 21#21: *126 js: hit blockDownload, group: 屏蔽下载
2024/09/14 15:41:36 [warn] 21#21: *126 js: getRouteMode: blockDownload, apiType: VideoStreamPlay

好像是这里不一样 你那里是ItemsDownload 我这里是VideoStreamPlay

具体为何不一样我就不太懂了😄

**Comment by chen3861229** [comment]
那关键就在于这里了，是之前提到的，这样看来`Infuse`没有遵循`Emby`的接口规范使用`下载接口`，而是通过`串流/播放`接口直接下载的，这样没法在脚本中轻易禁用了，不然可能会误伤`Infuse 的播放功能`，混在一起了

> 前提是这些播放器遵守使用了下载的 API 接口，即location ~* /Items/([^/]+)/Download或location ~* /Sync/JobItems/(.*)/File，而不是使用播放请求(串流)接口直接下载的，即location ~* /videos/(.*)/(stream|original)，因为本质上串流和下载都可以拿到完整的文件

```js
# Redirect the stream to njs
    location ~* /videos/(.*)/(stream|original) {
        set $apiType "VideoStreamPlay";
        # limit_req zone=one;
        # some packaged 3rd party players called intent has bug, concurrent 2 req, disable one of them
        # if ($http_user_agent ~* "dandanplay/android") {
    	# 	return 200;
    	# }
        rewrite ^(.*)/stream/(.*)$ $1/stream break; # revert modified path "/stream/xxx.mp4"
        if ($request_method = "HEAD") {
            proxy_pass $emby;
        }
        # Cache alist direct link
        add_header Cache-Control max-age=3600;
        js_content emby2Pan.redirect2Pan;
    }
```

**Comment by chen3861229** [comment]
`main`分支最新代码已经修复实现，我这边测试`Infuse 8.0.2`和`Infuse 8.0.3`是没问题了，只禁止下载，对正常播放没影响，https://github.com/bpking1/embyExternalUrl/pull/421/commits/1e4e46a9885cc6d686018fa985e515d7c7e192ae
```js
const routeRule = [
  // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
  ["blockDownload", "屏蔽下载01", "r.headersIn.User-Agent", "includes", ["Infuse-Download"]],
];
```

**Comment by EndlessJY** [comment]
> `main`分支最新代码已经修复实现，我香料测试`Infuse 8.0.2`和`Infuse 8.0.3`没问题了，只禁止下载，对正常播放没影响，[1e4e46a](https://github.com/bpking1/embyExternalUrl/commit/1e4e46a9885cc6d686018fa985e515d7c7e192ae)
> 
> const routeRule = [
>   // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
>   ["blockDownload", "屏蔽下载01", "r.headersIn.User-Agent", "includes", ["Infuse-Download"]],
> ];

作者您好，感谢开源 先生大爱！
目前迫切的需要infise限制下载功能，调用外部播放反而不是刚需；想请教下 如果仅适配限制下载功能需要怎么配置呀
有偿求教 辛苦大佬告知 不胜感激！ base64(TG)：aHR0cHM6Ly90Lm1lL3p6NDIz

**Comment by chen3861229** [comment]
只需要在配置文件`emby2Alist\nginx\conf.d\config\constant-pro.js`下的`routeRule`数组中添加上述的配置即可, 
```js
const routeRule = [
    // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
    ["blockDownload", "屏蔽下载01", "r.headersIn.User-Agent", "includes", ["Infuse-Download"]],
];
```
具体是这条
```js
["blockDownload", "屏蔽下载01", "r.headersIn.User-Agent", "includes", ["Infuse-Download"]],
```

**Comment by Daziax** [comment]
请教下这个屏蔽只针对infuse吗，对其他播放器生效吗？例如vidhub，网易爆米花

**Comment by Daziax** [comment]
> 只需要在配置文件`emby2Alist\nginx\conf.d\config\constant-pro.js`下的`routeRule`数组中添加上述的配置即可, 
> ```js
> const routeRule = [
>     // 精确屏蔽指定功能,注意同样是整体规则都不匹配默认走"redirect",即不屏蔽,建议只用下方一条,太复杂的话需要自行测试
>     ["blockDownload", "屏蔽下载01", "r.headersIn.User-Agent", "includes", ["Infuse-Download"]],
> ];
> ```
> 具体是这条
> ```js
> ["blockDownload", "屏蔽下载01", "r.headersIn.User-Agent", "includes", ["Infuse-Download"]],
> ```

请教下这个如何限制其他的播放器

**Comment by chen3861229** [comment]
1.是的，示例配置仅针对**Infuse**播放器

2.其他播放器例如vidhub，网易爆米花... 需要自己参考下`emby2Alist\nginx\conf.d\docs\UA.txt`中的User-Agent尝试下了，在`["Infuse-Download"]`这里用英文逗号续写，不过需要注意它们的下载行为可能和Infuse不太一样，假如没法用User-Agent区分，只能等过段时间我测试下了

**Comment by Daziax** [comment]
> 1.是的，示例配置仅针对**Infuse**播放器
> 
> 2.其他播放器例如vidhub，网易爆米花... 需要自己参考下`emby2Alist\nginx\conf.d\docs\UA.txt`中的User-Agent尝试下了，在`["Infuse-Download"]`这里用英文逗号续写，不过需要注意它们的下载行为可能和Infuse不太一样，假如没法用User-Agent区分，只能等过段时间我测试下了
您好，很奇怪的是，infuse命中后，还是会继续下载。apiType: VideoStreamPlay。

<img width="1066" alt="Image" src="https://github.com/user-attachments/assets/5c7bf7b9-5896-48fe-822e-9fce959ea232" />

我试了vidhub，命中后就正常不下载了。apiType:ItemDownload.

<img width="1054" alt="Image" src="https://github.com/user-attachments/assets/6af7a764-5aae-46ee-bc99-f81a4cc3aff7" />

**Comment by NextEmby** [comment]
VIDHUB你不用管吧，后台下载权限关闭了，Vidhub就不能下载的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Thor Hsu ***@***.***&gt;
发送时间: 2025年4月2日 20:56
收件人: bpking1/embyExternalUrl ***@***.***&gt;
抄送: Bear5074 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bpking1/embyExternalUrl] 大神能否增加一个禁止infuse或者vidhub等第三方播放器，下载文件的开关？ (Issue #363)



    
1.是的，示例配置仅针对Infuse播放器
 
2.其他播放器例如vidhub，网易爆米花... 需要自己参考下emby2Alist\nginx\conf.d\docs\UA.txt中的User-Agent尝试下了，在["Infuse-Download"]这里用英文逗号续写，不过需要注意它们的下载行为可能和Infuse不太一样，假如没法用User-Agent区分，只能等过段时间我测试下了
 您好，很奇怪的是，infuse命中后，还是会继续下载。apiType: VideoStreamPlay。
  image.png (view on web) 
我试了vidhub，命中后就正常不下载了。apiType:ItemDownload.
 image.png (view on web)
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  Daziax left a comment (bpking1/embyExternalUrl#363)
  
1.是的，示例配置仅针对Infuse播放器
 
2.其他播放器例如vidhub，网易爆米花... 需要自己参考下emby2Alist\nginx\conf.d\docs\UA.txt中的User-Agent尝试下了，在["Infuse-Download"]这里用英文逗号续写，不过需要注意它们的下载行为可能和Infuse不太一样，假如没法用User-Agent区分，只能等过段时间我测试下了
 您好，很奇怪的是，infuse命中后，还是会继续下载。apiType: VideoStreamPlay。
  image.png (view on web) 
我试了vidhub，命中后就正常不下载了。apiType:ItemDownload.
 image.png (view on web)

**Comment by Daziax** [comment]
> VIDHUB你不用管吧，后台下载权限关闭了，Vidhub就不能下载的
> 
> 
> 
> 发自我的iPhone
> […](#)

是在哪里，emby后台吗设置吗

**Comment by NextEmby** [comment]
是的，你只管infuse就行了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Thor Hsu ***@***.***&gt;
发送时间: 2025年4月3日 10:25
收件人: bpking1/embyExternalUrl ***@***.***&gt;
抄送: Bear5074 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bpking1/embyExternalUrl] 大神能否增加一个禁止infuse或者vidhub等第三方播放器，下载文件的开关？ (Issue #363)

**Comment by frankk007** [comment]
网易爆米花下载可以通过UA区分吗
