### ISSUE TITLE
emby的nginx代理端口不显示图片

### ISSUE THREAD

**Issue by chaomarks** [bpking1/embyExternalUrl#364]
如题，emby是8096，nginx代理后的端口可以访问但是看不到海报墙图片，不晓得什么原因

**Comment by z-x-f** [comment]
你是说的这个现象吗？https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

**Comment by chaomarks** [comment]
> 你是说的这个现象吗？https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#13%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B5%B7%E6%8A%A5%E5%85%A8%E9%83%A8%E8%A3%82%E5%BC%80

哈哈，对的，品牌NAS就是麻烦，各种权限
