### ISSUE TITLE
emby挂载115的strm电影软链接，只有在网页端播放一次后，才会出现调用播放器的图标

### ISSUE THREAD

**Issue by zctest666** [bpking1/embyExternalUrl#365]
emby挂载115的strm电影软链接，只有在网页端播放一次后，才会出现调用播放器的图标

**Comment by chen3861229** [comment]
是[embyExternalUrl](https://github.com/bpking1/embyExternalUrl/blob/main/embyWebAddExternalUrl/embyLaunchPotplayer.js)吗? 很久之前修复过了，但是没有发布到`篡改猴`脚本管理器更新中，需要手动覆盖下了

https://github.com/bpking1/embyExternalUrl/commit/c0ffac66667d455174cd24e3cacca3f45556a55b

**Comment by zctest666** [comment]
> 是[embyExternalUrl](https://github.com/bpking1/embyExternalUrl/blob/main/embyWebAddExternalUrl/embyLaunchPotplayer.js)吗? 很久之前修复过了，但是没有发布到`篡改猴`脚本管理器更新中，需要手动覆盖下了
> 
> [c0ffac6](https://github.com/bpking1/embyExternalUrl/commit/c0ffac66667d455174cd24e3cacca3f45556a55b)

感谢大佬
