### ISSUE TITLE
播放记录重复问题

### ISSUE THREAD

**Issue by LunaticXJ** [bpking1/embyExternalUrl#366]
使用本地strm方式（以/开头）访问CD2挂载alist 115盘（走302直链），经常偶发性出现播放记录重复的问题，也没有报错日志，不知道怎么排查，大家有没有类似的情况呀
![WechatIMG1436](https://github.com/user-attachments/assets/aa583a92-ca81-47cd-bfa0-ffc4957abf5a)

**Comment by chen3861229** [comment]
这个有两种原因，因为之前测试遇到过

1.假如是库中存在未合并的多版本视频，这种是 emby 的业务原本是如此设计的，https://github.com/bpking1/embyExternalUrl/issues/359

2.还有一种是不存在未合并的多版本视频，确定库中只有这一部视频，但是之前存在过其他版本的视频(即 TMDB 或 IMDB 之类的唯一值相同)，多余的版本视频已经移除掉了，但是 emby 自身内部的元数据中可能有残留，不过这也属于 emby 原本自身的问题了，影响不大，只能等 emby 官方修复了

https://github.com/chen3861229/embyExternalUrl/issues/68

**Comment by LunaticXJ** [comment]
感谢，现在搞清楚了，就是emby库中存在重复的视频～
