### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by saarjoye** [bpking1/embyExternalUrl#367]
大佬你好，我遇到部份剧里有几集会播放不了。从CD2和alist中播放有时会转圈圈很久后能播放，有时一直显示重连。有时直接就播放不了，但是使用网盘播放是正常可播的，大佬，这种问题我需要排查哪个环节。已经遇到过3部剧有这种情况，最早我只需要把这部剧全删掉后重新下载入库就可以播放。现在这个方法没办法解决了

**Comment by saarjoye** [comment]
2024/09/09 17:08:42 [warn] 21#21: *3641 js: 3ms, transfer playbackinfo: {"MediaSources":[{"Protocol":"File","Id":"************","Path":"/downloads/115/媒体库/电视剧/国产剧/长乐曲 (2024)/Season 1/长乐曲 - S01E26 - 第 26 集.mp4","Type":"Default","Container":"mp4","Size":0,"Name":"长乐曲 - S01E26 - 第 26 集","IsRemote":false,"HasMixedProtocols":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/65449/stream.mp4?


2024/09/09 17:10:45 [error] 21#21: *3661 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.1.99, server: default, request: "POST /emby/Items/65449/PlaybackInfo?



看到error.log日志报错内容如上

**Comment by chen3861229** [comment]
关键可能在于`upstream timed out`，可以先尝试下改，https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#32embyhost

**Comment by saarjoye** [comment]
> 关键可能在于`upstream timed out`，可以先尝试下改，https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#32embyhost
大佬。我的配置文件中。使用的是NAS的内网IP。但还是会有这个错误
![image](https://github.com/user-attachments/assets/79e37e80-feb4-4fab-b478-841602cb1338)
![image](https://github.com/user-attachments/assets/2c09f761-b18d-4642-b8a6-9ef056941bae)

**Comment by saarjoye** [comment]
![image](https://github.com/user-attachments/assets/99810494-40a2-415e-848a-d0b9aa1cb54b)
我在emby中尝试下载可以获得是115的链接。但是就是无法播放。

**Comment by saarjoye** [comment]
![image](https://github.com/user-attachments/assets/d7d470dc-fe9f-420e-96ea-06c09f2e5836)

**Comment by chen3861229** [comment]
图一说明不是引用链接中导致的问题，根据图二和描述感觉是媒体音视频编码的问题，再结合最初提到的`已经遇到过3部剧有这种情况`，不知这个是否说明其他媒体格式编码有能成功播放的，假如 web 浏览器播放是有能成功的，那么就是 web 浏览器支持的媒体格式和编码较少(这个问题也是长期普遍存在的)，建议使用对应平台客户端播放相同的集数，以上是倾向于直链的方案，假如倾向于播放成功率，可以开启允许转码参数，转码与直链是互斥的行为，`emby2Alist\nginx\conf.d\config\constant-transcode.js`
```js
// 转码配置,默认 false,将按之前逻辑禁止转码处理并移除转码选项参数,与服务端允许转码配置有相关性
const transcodeConfig = {
  enable: true, // 此大多数情况下为允许转码的总开关
  enableStrmTranscode: false, // 默认禁用 strm 的转码,体验很差,仅供调试使用
  type: "distributed-media-server", // 负载类型,可选值, ["nginx", "distributed-media-server"]
  maxNum: 3, // 单机最大转码数量,有助于加速轮询, 参数暂无作用,接口无法查询转码情况,忽略此参数
  redirectTransOptEnable: true, // 是否保留码率选择,不保留官方客户端将无法手动切换至转码
  targetItemMatchFallback: "redirect", // 目标服务媒体匹配失败后的降级后路由措施,可选值, ["redirect", "proxy"]
  // 如果只需要当前服务转码,enable 改为 true,server 改为下边的空数组
  server: [],
};
```
