### ISSUE TITLE
有几率出现图片映射错误

### ISSUE THREAD

**Issue by huodongjiaren** [bpking1/embyExternalUrl#372]
封面 演员头像等媒体图片有几率出现映射到另外错误的媒体图片

**Comment by chen3861229** [comment]
不知是否是频繁修改服务端的这些图片导致的，可能是手动或 emby 服务端自动刮削之类的，脚本中确实默认缓存了 emby 服务端的图片和字幕，有效期是 30 天，这个缓存主要是针对网盘环境以免频繁读取都击穿到原网盘端导致被风控一段时间，可以尝试临时禁用下脚本对于图片的缓存功能，`emby2Alist\nginx\conf.d\config\constant-ext.js`
```js
// 图片缓存策略,包括主页、详情页、图片库的原图,路由器 nginx 请手动调小 conf 中 proxy_cache_path 的 max_size
// 0: 不同尺寸设备共用一份缓存,先访问先缓存,空间占用最小但存在小屏先缓存大屏看的图片模糊问题
// 1: 不同尺寸设备分开缓存,空间占用适中,命中率低下,但契合 emby 的图片缩放处理
// 2: 不同尺寸设备共用一份缓存,空间占用最大,移除 emby 的缩放参数,直接原图高清显示
// 3: 关闭 nginx 缓存功能,已缓存文件不做处理
const imageCachePolicy = 3;
```
假如不在出现问题，但需要此缓存功能的话，可以自定义下缓存的有效期，位于`emby2Alist\nginx\conf.d\emby.conf`
```js
## FileSystem Cache, images, subtitles
proxy_cache_path /var/cache/nginx/emby/images levels=1:2 keys_zone=emby_images:100m max_size=10g inactive=30d use_temp_path=off;
proxy_cache_path /var/cache/nginx/emby/subtitles levels=1:2 keys_zone=emby_subtitles:10m max_size=1g inactive=30d use_temp_path=off;
```

**Comment by huodongjiaren** [comment]
> 不知是否是频繁修改服务端的这些图片导致的，可能是手动或 emby 服务端自动刮削之类的，脚本中确实默认缓存了 emby 服务端的图片和字幕，有效期是 30 天，这个缓存主要是针对网盘环境以免频繁读取都击穿到原网盘端导致被风控一段时间，可以尝试临时禁用下脚本对于图片的缓存功能，`emby2Alist\nginx\conf.d\config\constant-ext.js`
> 
> ```js
> // 图片缓存策略,包括主页、详情页、图片库的原图,路由器 nginx 请手动调小 conf 中 proxy_cache_path 的 max_size
> // 0: 不同尺寸设备共用一份缓存,先访问先缓存,空间占用最小但存在小屏先缓存大屏看的图片模糊问题
> // 1: 不同尺寸设备分开缓存,空间占用适中,命中率低下,但契合 emby 的图片缩放处理
> // 2: 不同尺寸设备共用一份缓存,空间占用最大,移除 emby 的缩放参数,直接原图高清显示
> // 3: 关闭 nginx 缓存功能,已缓存文件不做处理
> const imageCachePolicy = 3;
> ```
> 
> 假如不在出现问题，但需要此缓存功能的话，可以自定义下缓存的有效期，位于`emby2Alist\nginx\conf.d\emby.conf`
> 
> ```js
> ## FileSystem Cache, images, subtitles
> proxy_cache_path /var/cache/nginx/emby/images levels=1:2 keys_zone=emby_images:100m max_size=10g inactive=30d use_temp_path=off;
> proxy_cache_path /var/cache/nginx/emby/subtitles levels=1:2 keys_zone=emby_subtitles:10m max_size=1g inactive=30d use_temp_path=off;
> ```
> 
> 和
> 
> ```js
> proxy_cache_valid 200 30d;
> ```

清空Nginx缓存+浏览器缓存映射成功了 感谢大佬的耐心回复
