### ISSUE TITLE
plex https问题

### ISSUE THREAD

**Issue by Yan-nian** [bpking1/embyExternalUrl#374]
求大佬写个https的教程 plex三方客户端苹果用的多

**Comment by chen3861229** [comment]
1.更改`plex2Alist\nginx\conf.d\plex.conf`第 25-26 行，注释默认的 http 访问方式，打开 https 的访问
```js
    ## Include the http and https configs, better don't use same port
    # include /etc/nginx/conf.d/includes/http.conf;
    include /etc/nginx/conf.d/includes/https.conf;
```
2.注意下`plex2Alist\nginx\conf.d\includes\https.conf`中第 12-13 行的，证书文件，证书密钥的路径位置与文件名
```js
ssl_certificate      /etc/nginx/conf.d/cert/fullchain.pem;  ## Location of your public PEM file.
ssl_certificate_key  /etc/nginx/conf.d/cert/privkey.key;  ## Location of your private PEM file.
```
3.假如不更改 2 中的证书路径和文件名，直接将证书文件，证书密钥，改为 2 中的默认文件名，然后放置到`plex2Alist\nginx\conf.d\cert`目录下即可

4.配置文件更改完成后，需要终端执行`nginx -s reload`或直接重启 nginx 服务刷新配置文件生效

5.此时通过默认 https 脚本中默认的`8095`端口访问，`http.conf`中的`8091`端口已经被释放无法访问，假如是`Docker`环境，需要检查下容器是否正确映射出了`8095`到`宿主机`上，假如`路由器需要做端口映射`开放在公网上，也需要检查下路由器中的设置

6.plex 需要额外在服务端和客户端设置一下，这个在文档中有了，https://github.com/bpking1/embyExternalUrl/blob/main/plex2Alist/README.md#5-plex-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8E%A7%E5%88%B6%E5%8F%B0%E8%AE%BE%E7%BD%AE

**Comment by Yan-nian** [comment]
我大概设置好了nginx的https 但是plex那边不太懂 是需要将加密链接改为必须吗 远程访问端口改为8095 lucky反代的也是8095端口吗 我这样试了 发现webui直接显示502了

**Comment by chen3861229** [comment]
lucky 反代是用来做 https 的吗？如果这个上面做了，nginx 可以不用配置 https 了，不然三个月的证书分散到太多地方了，而且假如 lucky 是外网至内网的入口，nginx 最好不要做 https ，证书配置到 lucky 这个前置反代上，lucky 反代 nginx 的 8091 的 http 即可，当然这样的话上述配置需要改回去了，此时 webui 使用 lucky 管理的域名 + 端口访问，就是 https 的了，plex 客户端上的`加密链接`不用更改，默认就是仅允许`加密/https`的访问方式，只是 plex 服务端那里，必须设置-网络-自定义服务器访问 URL: [https://自己的域名:自己的端口号],以发布到 plex.tv 发现服务器，自己的端口号指的是 lucky 反代(连接)到 nginx 的端口号，应该不是 8091

**Comment by Yan-nian** [comment]
![Snipaste_2024-09-16_00-02-17](https://github.com/user-attachments/assets/9a491e4a-0c13-4303-a420-957804f73098)
按照你说的改了 log就显示这样 是不是不支持 我用的mac端的infuse

**Comment by Yan-nian** [comment]
192.168.1.132, server: default, request: "GET /hubs/promoted?count=20&excludeContinueWatching=1&contentDirectoryID=3 HTTP/1.1", subrequest: "/hubs/promoted", upstream: "http://192.168.1.132:32400/hubs/promoted?count=20&excludeContinueWatching=1&contentDirectoryID=3", host: 
2024/09/15 16:06:34 [warn] 20#20: *924 js: === plexApiHandler: /hubs/promoted, the NJS VM is destroyed ===
2024/09/15 16:07:35 [warn] 20#20: *936 js: === plexApiHandler: /library/metadata/2163, the NJS VM is destroyed ===
2024/09/15 16:07:36 [warn] 20#20: *937 js: === plexApiHandler: /hubs/promoted, the NJS VM is destroyed ===
改好了 显示这些 njs有问题吗？

**Comment by chen3861229** [comment]
没问题，这些只是提示信息

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
