### ISSUE TITLE
配置后直链没有生效

### ISSUE THREAD

**Issue by SuperrNaruto** [bpking1/embyExternalUrl#375]
我配置了这几个地方
![IMG_5284](https://github.com/user-attachments/assets/977d41fd-a4e0-4240-8f68-cbd1bb91bd19)
![IMG_5287](https://github.com/user-attachments/assets/eaef3126-30f2-441d-b3e6-7ac9742ad7ff)
因为我已经装过 alist 了我就把 docker-compose.yml 哪里 Alist 注释掉了。
![IMG_5283](https://github.com/user-attachments/assets/b8425637-2d78-4cbc-9b54-33f84dddad87)
include 的 listen 我看着也好像不用改
![IMG_5285](https://github.com/user-attachments/assets/4a4aa0b5-97fc-4f5b-a968-84706faad29a)
![IMG_5286](https://github.com/user-attachments/assets/24727b0a-a175-4bf4-8f00-72cf3a795a21)
结果通过端口 8091 没有走直链，以下是 error 
![IMG_5282](https://github.com/user-attachments/assets/78a0e771-55e3-48cf-aee6-7298cce90b05)
和 access
![IMG_5288](https://github.com/user-attachments/assets/1615195e-285a-454f-ad12-1908a5fd4390)
emby 是通过 strm 的
emby，Alist 部署在香港的 vps 上系统是 Ubuntu 22.04.3 LTS，纯小白，都是问 chatgpt 该怎么做的😂😂

**Comment by SuperrNaruto** [comment]
测试了一下不用 strm 链接液无法用直链
![IMG_5288](https://github.com/user-attachments/assets/4ff29438-6624-48e6-b7da-0022b26ebb93)

**Comment by chen3861229** [comment]
1.根据日志中的`@root`判断，应该是查询 emby 项目详情，或 alist 查询文件信息时出错了，导致失败回退到转给原始 emby 服务处理了

2.结合配置截图，应该是`mediaMountPath`配置缺少了`STRM`的配置
```js
// 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理
// 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
const mediaMountPath = ["/share/Drive/WebDav"];
```

3.`STRM`的路径映射处理，需要使用另外一个升级的参数设置，位于`emby2Alist\nginx\conf.d\config\constant-pro.js`中的`mediaPathMapping`，默认简单版的`mediaMountPath`仅相当于`0: 默认做字符串替换replace一次` + `0: 默认只处理/开头的路径且不为 strm`，故解决方案为留空简单版的路径映射参数`const mediaMountPath = [""];`，然后使用`mediaPathMapping`就行更精确的配置，假设前提是`STRM`内部为标准远程链接的情况
```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数?.1: 生效规则三维数组,有时下列参数序号加一,优先级在参数2之后,需同时满足,多个组是或关系(任一匹配)
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  // [0, 0, "/aliyun-01", "/aliyun-02"],
  [2, 0, "/share/Drive/WebDav", ""],
];
```

**Comment by SuperrNaruto** [comment]
> 1.根据日志中的`@root`判断，应该是查询 emby 项目详情，或 alist 查询文件信息时出错了，导致失败回退到转给原始 emby 服务处理了
> 
> 2.结合配置截图，应该是`mediaMountPath`配置缺少了`STRM`的配置
> 
> ```js
> // 挂载工具 rclone/CD2 多出来的挂载目录, 例如将 od,gd 挂载到 /mnt 目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
> // 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始 emby 处理
> // 如果没有挂载,全部使用 strm 文件,此项填[""],必须要是数组
> const mediaMountPath = ["/share/Drive/WebDav"];
> ```
> 
> 3.`STRM`的路径映射处理，需要使用另外一个升级的参数路径映射设置，位于`emby2Alist\nginx\conf.d\config\constant-pro.js`中的`mediaPathMapping`，默认简单版的`mediaMountPath`仅相当于`0: 默认做字符串替换replace一次` + `0: 默认只处理/开头的路径且不为 strm`，故解决方案为留空简单版的路径映射参数`const mediaMountPath = [""];`，然后使用`mediaPathMapping`进行更精确的配置，假设前提是`STRM`内部为标准远程链接的情况
> 
> ```js
> // 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
> // 参数?.1: 生效规则三维数组,有时下列参数序号加一,优先级在参数2之后,需同时满足,多个组是或关系(任一匹配)
> // 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> // 参数3: 来源, 参数4: 目标
> const mediaPathMapping = [
>   // [0, 0, "/aliyun-01", "/aliyun-02"],
>   [2, 0, "/share/Drive/WebDav", ""],
> ];
> ```
谢谢(🙏ˊᗜˋ*)，但是改了之后我发现 
![IMG_5294](https://github.com/user-attachments/assets/eaa3c228-a2c3-43cf-85ed-d0627a857eeb)
Alist 里的原文件路径是这样的
![IMG_5295](https://github.com/user-attachments/assets/15ff373c-9a97-4157-b7b0-559a945f0478)
strm 文件是这样的，emby 刮的就是 strm 文件。strm 是 auto_symlink 创建的，应该对得上
![IMG_5296](https://github.com/user-attachments/assets/340283b3-194c-4d24-804d-1f055834a565)
cd2 挂载路径是这样的
![IMG_5298](https://github.com/user-attachments/assets/b5aeba62-9f83-48c6-bd23-45cf8ea48d5f)
![IMG_5297](https://github.com/user-attachments/assets/a7fa570e-f3f6-49f8-87e7-33e47affef6b)
难道 mediaPathMapping 不应填 **"/share/Drive/WebDav"？** “fetch alist path from
/115/share/Drive/WebDAV/115/media/色色/Jav/已刮削/aiav-008” 这里 "/share/Drive/WebDav"怎么插在 115 后面，多了“/115/share/Drive/WebDav”

**Comment by chen3861229** [comment]
粗略看了下，应该是大小写的问题，`mediaPathMapping`应该填`/share/Drive/WebDAV`，原始的为`WebDav`，图中划线的第二处是首次 alist 查询失败后的补偿重试措施，查询 alist 驱动获取的路径拼接的，映射正常的情况下不会出现第二处的`try to fetch`，可以不用管这个第二处的路径内容

**Comment by SuperrNaruto** [comment]
> 粗略看了下，应该是大小写的问题，`mediaPathMapping`应该填`/share/Drive/WebDAV`，原始的为`WebDav`，图中划线的第二处是首次 alist 查询失败后的补偿重试措施，查询 alist 驱动获取的路径拼接的，映射正常的情况下不会出现第二处的`try to fetch`，可以不用管这个第二处的路径内容

哇大佬这么晚还能回复(ﾟДﾟ≡ﾟдﾟ)!?，太感谢了！我太粗心了，明天再试试。

**Comment by SuperrNaruto** [comment]
> 粗略看了下，应该是大小写的问题，`mediaPathMapping`应该填`/share/Drive/WebDAV`，原始的为`WebDav`，图中划线的第二处是首次 alist 查询失败后的补偿重试措施，查询 alist 驱动获取的路径拼接的，映射正常的情况下不会出现第二处的`try to fetch`，可以不用管这个第二处的路径内容

不行改完大写，还是显示找不到路径
![IMG_5303](https://github.com/user-attachments/assets/d24fa174-c1e8-4579-b5b7-fde2489311ed)

**Comment by chen3861229** [comment]
解决了吗？还是再加一个`[0, 0, "/share/Drive/WebDAV", ""]`比较稳妥，因为 strm 的类型和路径在 emby 中的结构很混乱
```js
// 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
// 参数?.1: 生效规则三维数组,有时下列参数序号加一,优先级在参数2之后,需同时满足,多个组是或关系(任一匹配)
// 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
// 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
// 参数3: 来源, 参数4: 目标
const mediaPathMapping = [
  [0, 0, "/share/Drive/WebDAV", ""],
  [2, 0, "/share/Drive/WebDAV", ""],
];
```

**Comment by SuperrNaruto** [comment]
好了谢谢大佬> 解决了吗？还是再加一个`[0, 0, "/share/Drive/WebDAV", ""]`比较稳妥，因为 strm 的类型和路径在 emby 中的结构很混乱
> 
> ```js
> 
> // 路径映射,会在 mediaMountPath 之后从上到下依次全部替换一遍,不要有重叠,注意 /mnt 会先被移除掉了
> 
> // 参数?.1: 生效规则三维数组,有时下列参数序号加一,优先级在参数2之后,需同时满足,多个组是或关系(任一匹配)
> 
> // 参数1: 0: 默认做字符串替换replace一次, 1: 前插, 2: 尾插, 3: replaceAll替换全部
> 
> // 参数2: 0: 默认只处理/开头的路径且不为 strm, 1: 只处理 strm 内部为/开头的相对路径, 2: 只处理 strm 内部为远程链接的
> 
> // 参数3: 来源, 参数4: 目标
> 
> const mediaPathMapping = [
> 
>   [0, 0, "/share/Drive/WebDAV", ""],
> 
>   [2, 0, "/share/Drive/WebDAV", ""],
> 
> ];
> 
> ```
