### ISSUE TITLE
需求2个EMBY，请问如何设置

### ISSUE THREAD

**Issue by saarjoye** [bpking1/embyExternalUrl#378]
需求2个EMBY放不同资源
现在遇到的问题是如何更改8091端口。替换另一个

**Comment by chen3861229** [comment]
目前建议方式一

1.直接部署两个 nginx 的容器，这样比较简单且业务日志是分开来的文件，自查排错之类的方便些，缺点就是占用了两份服务资源，但是 nginx 的内存性能占用之类的本身很小，大概 38 M 左右，然后配置更新起来可能比较重复，假如是容器，各自映射不同的端口到宿主机上即可

2.共用同一个 nginx 程序/容器，这个需要等下后期将针对此需求进一步拆分下重复的配置，目前这种配置文件有太多重复且不合理的地方

> 现在遇到的问题是如何更改8091端口。替换另一个

看起来是已经使用了方式一，改`nginx`的监听端口在`emby2Alist/nginx/conf.d/includes/http.conf`中的`listen`监听端口，同目录下还有个`emby2Alist/nginx/conf.d/includes/https.conf`，具体取决与`emby2Alist/nginx/conf.d/emby.conf`第 44 行，`include`的对应的那一个
