### ISSUE TITLE
emby2alist这个方案疑似会导致infuse识别错误

### ISSUE THREAD

**Issue by clggwater** [bpking1/embyExternalUrl#38]
已经测试过的有web、fileball、Terminus Player正常播放，但是infuse pro最近的几个版本链接上8095或者8096端口后，都会将所有的电视剧资源识别成“其他”，导致首页无法分类，尚不清楚是infuse的问题还是这个方案的问题

<img width="594" alt="image" src="https://github.com/bpking1/embyExternalUrl/assets/23073985/7bc3fc60-4f72-4d58-aaa7-d1bb0ccc3ab9">
<img width="774" alt="image" src="https://github.com/bpking1/embyExternalUrl/assets/23073985/50058504-0cc8-4939-93ae-8aebda89cb57">
<img width="793" alt="image" src="https://github.com/bpking1/embyExternalUrl/assets/23073985/f06b72d1-cb2b-43b0-9479-cf2609cd8de0">

emby2alist这个方案会导致8096这个端口没法被infuse pro正确识别吗？

然后有个问题问下，我这边用docker命令能看到redirect到直链，日志如下，是运行成功了吗？

<img width="1167" alt="image" src="https://github.com/bpking1/embyExternalUrl/assets/23073985/8912d742-57cf-401e-8ade-ddba26e91061">

**Comment by AmbitiousJun** [comment]
问题已尝试修复，可以到我的个人仓库里面下载代码试试，可以的话反馈一下哈，感谢

**Comment by AmbitiousJun** [comment]
目前的话我用infuse是能正常分类的
