### ISSUE TITLE
请问怎么样在主机已经有nginx的情况下，开启https访问，并且使用域名访问而不是主机的IP地址访问emby？

### ISSUE THREAD

**Issue by ethuh** [bpking1/embyExternalUrl#380]
我现在按照如下图里更改的https、http文件，http端口用的8131，https用的8095，为了保证证书能使用，我把原来的证书复制到了本机的nginx还有容器内同一个目录下，并改名为https内要求的名字，重启nginx容器，在本机运行nginx -s reload，但是https://IP:8095无法访问，反过来取消http文件内的注释，https://IP:8132就可以正常访问，卡在了https访问这里。

我还不知道下一步应该在哪里添加子域名配置（https://eb.xxxxxx.xyz这样来访问)，防火墙端口都已经开放了的。本机我之前装的nginx配置文件内，增加子域名用的都是图5里的方法，是否能在这个项目的nginx.conf直接添加这部分配置呢？

![](https://image.hhisgg.xyz/img/2024/10/04/66ffeb4a47066.png)
![](https://image.hhisgg.xyz/img/2024/10/04/66ffedd61e808.png)
![](https://image.hhisgg.xyz/img/2024/10/04/66ffebc7bc260.png)
![](https://image.hhisgg.xyz/img/2024/10/04/66ffebf064078.png)
![](https://image.hhisgg.xyz/img/2024/10/04/66ffed3717466.png)

**Comment by chen3861229** [comment]
> https://IP:8095无法访问，反过来取消http文件内的注释，https://IP:8132就可以正常访问，卡在了https访问这里。

1.根据这个描述，应该是`emby2Alist\nginx\conf.d\emby.conf`中第 44 行默认`include`包含是`http.conf`导致的，注释 44 行，打开 45 行注释即可
```js
## Include the http and https configs, better don't use same port
    # include /etc/nginx/conf.d/includes/http.conf;
    include /etc/nginx/conf.d/includes/https.conf;
```

> 下一步应该在哪里添加子域名配置 https://eb.xxxxxx.xyz 这样来访问

2.这个域名到 IP 的解析过程，是外部因素，DNS 解析那边提供的，假如该脚本所在服务的宿主机上级的路由器上配置有`DDNS`的话，https://eb.xxxxxx.xyz 等同于所绑定的 ip 地址

3.图 5 中的 server server_name 那里并不是直接绑定域名到此 nginx 服务上的方式，类似于一个别名/注释的作用，具体还是取决于 2 中提到的，server_name 填 default 或不填也是可以的

> 是否能在这个项目的nginx.conf直接添加这部分配置呢？

4.可以的，应为本质上都是基于 nginx 的，配置方式一样
