### ISSUE TITLE
请问下电视盒子的安卓TV客户端无法进行播放，显示没有兼容的流

### ISSUE THREAD

**Issue by fayswing** [bpking1/embyExternalUrl#381]
首先谢谢大佬开发了115直链这么好的项目。

就是电视盒子安卓TV的emby无法进行播放 ，用的是反代端口登录的emby安卓TV客户端，显示没有兼容的流。

然后换成域名登录，当emby识别成外网地址的时候可以进行播放，

当emby识别成内网地址的时候，同样显示没有兼容的流。

以上问题安卓手机   安卓平板   苹果平板都没问题，就只有安卓TV有问题

恳请大佬解惑。谢谢大佬

**Comment by fayswing** [comment]
这个是错误日志      麻烦大佬了

![image](https://github.com/user-attachments/assets/9a20d87a-5a03-43fb-a75d-e5aa644bec94)

**Comment by chen3861229** [comment]
> 然后换成域名登录，当emby识别成外网地址的时候可以进行播放，
> 当emby识别成内网地址的时候，同样显示没有兼容的流。

基本可以认定是客户端的局域网网络发现功能导致强制走了局域网下的原媒体服务端口了，从而被绕过了 nginx 的端口上的反代处理，可以参考下这个，一般只需要尝试其中提到的第一个方式即可，我目前是这样使用的，https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#19%E5%B1%80%E5%9F%9F%E7%BD%91%E4%B8%8B%E5%8F%AF%E8%83%BD%E5%AD%98%E5%9C%A8%E7%BB%95%E8%BF%87-nginx-%E5%A4%84%E7%90%86%E7%9A%84%E9%97%AE%E9%A2%98

**Comment by fayswing** [comment]
> > 然后换成域名登录，当emby识别成外网地址的时候可以进行播放，
> > 当emby识别成内网地址的时候，同样显示没有兼容的流。
> 
> 基本可以认定是客户端的局域网网络发现功能导致强制走了局域网下的原媒体服务端口了，从而被绕过了 nginx 的端口上的反代处理，可以参考下这个，一般只需要尝试其中提到的第一个方式即可，我目前是这样使用的，https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#19%E5%B1%80%E5%9F%9F%E7%BD%91%E4%B8%8B%E5%8F%AF%E8%83%BD%E5%AD%98%E5%9C%A8%E7%BB%95%E8%BF%87-nginx-%E5%A4%84%E7%90%86%E7%9A%84%E9%97%AE%E9%A2%98

谢谢大佬百忙之中的回复，尝试了一下把emb的docker网络模式改为桥接(bridge),只开放默认的 8096 端口出来，
但是盒子的emby客户端还是会自动显示出8096的服务器，还是被广播出来了。删了以后一会又自动冒出来了，
确认了是个顽疾。

大佬能教下下面的第二个方式应该怎么操作吗 ，是在路由器的防火墙里禁止
还是NAS上的防火墙禁止呢，麻烦大佬了。

2.或者尝试防火墙禁止 emby 默认的 UDP 广播发现端口 7359,注意是 UDP,而不是 TCP 协议 https://dev.emby.media/doc/restapi/Locating-the-Server.html?q=UDP

**Comment by chen3861229** [comment]
准确应该是 emby 服务所在的 NAS 上吧，这样可以把切断 emby 默认的 UDP 广播发现端口 7359 与路由器直到客户端这条链路上的通信，但是这个方式只是理论可行，我这边没有实际操作过

**Comment by fayswing** [comment]
> 准确应该是 emby 服务所在的 NAS 上吧，这样可以把切断 emby 默认的 UDP 广播发现端口 7359 与路由器直到客户端这条链路上的通信，但是这个方式只是理论可行，我这边没有实际操作过

谢谢大佬的回复，虽然emby for android Tv这个APK还是不行   但是用普通的emby安卓应用已经没问题了  其实用起来都差不多
再次表达下感谢之情，顺便想请问下大佬首页能不能贴个支付宝或者微信二维码，想请大佬喝个咖啡啥的表示下自己的谢意。
能用上大佬这么好的项目，并且遇到问题还能得到大佬的亲切指导，心存感激。。。Thanks♪(･ω･)ﾉ

**Comment by chen3861229** [comment]
嗯，能正常使用了就行，二维码就不必了，也是多谢 bpking1 大佬提供最初的思路
