### ISSUE TITLE
TV emby没有快进，只有暂停播放。

### ISSUE THREAD

**Issue by xianglongwei** [bpking1/embyExternalUrl#384]
使用最新版本。
问题：
但是使用TV版本的EMBY没有快进，播放页面只有暂停
设备：
安卓电视
其他说明：
使用手机播放器正常。使用infues正常。安卓手机使用emby和其他第三方播放器都正常、苹果手机都正常
电视品牌小米、乐视、长虹、TCL都尝试过都是这样。小蜜版，官方版本都尝试过。没有快进。
配置文件只修改了这些，其他都是默认。请作者大佬，和各位有遇到同样情况的大佬指点一下吧
![image](https://github.com/user-attachments/assets/1a28e985-fe02-4256-84c3-f3722fc703aa)

**Comment by chen3861229** [comment]
> 但是使用TV版本的EMBY没有快进，播放页面只有暂停

1.非请求接口渲染的 UI 界面是客户端显示的，此脚本除了 emby 对接 115 转码直链功能，动态返回视频的多版本选择，其余所有界面相关都属于客户端自身的行为

2.不知道是不是指的老 tv 客户端，版本号以 g 结尾的，我这边测试的第三方版本是可以的，版本：2.0.83g
![image](https://github.com/user-attachments/assets/3cd0d76f-f3ee-43c4-96ca-22e08837d83d)

**Comment by xianglongwei** [comment]
我尝试了2.0.95与2.1.09g都不行，我又尝试不用转发直连EMBY服务器，却是正常的。

**Comment by chen3861229** [comment]
通过`const mediaMountPath = [""];`猜测，媒体是用的`strm`方式的吗？

版本相同，2.0.83g，我这边通过 strm 媒体复现出来了，这样的话结论很明显了，因为 strm 本身在 emby 中没有经过扫库/入库的过程，之前是知道这种 emby 服务端媒体元信息中是没有`runTimeTicks`可播放时长信息的，估计是这个原因导致了，没有了播放进度相关的操作按钮，这个属于 emby 自身的问题了

![image](https://github.com/user-attachments/assets/a68369a2-8403-425e-93bd-76cd30c2a832)

**Comment by xianglongwei** [comment]
确实我是使用的是直接指alist，
alist关闭sign
我脚本关闭sign无法正常转发，只有开启才能播放。但是没有快进按键。也就是我必须脚本配置文件必须开启sign
还有大佬，我想问下你这边alist和emby服务器版本吗？

**Comment by chen3861229** [comment]
1.emby 服务端，4.8.10.0，alist v3.38.0，和这两个版本是没关系的

2.alist 关闭 sign ，这个仅是在确实是 Strm 内部文本链接指向 alist 且文本链接中没有携带 sign 参数且alist 开启了 sign 验证后，才需要这样尝试下的

3.假如确实符合 2 中的描述，alist 中 sign 参数总共有两个地方，一是在 alist 设置 => 全局 => 签名所有，这个就是 sign ，取消勾选，二是存储设置详情页中 => 编辑 => 启用签名，取消勾选

4.以上取消了 alist 的链接的 sign 签名验证，可能稍微会带来一些安全风险，例如链接泄露被其他人恶意刷流量之类的，可在测试完成后酌情是否开启或关闭，假如都是可信环境下的使用，关闭这个签名倒是问题不大，因为 alist 老版本中是没这个选项的

**Comment by xianglongwei** [comment]
作者大佬，无比感激，详细的帮忙分析。问题已解决，确实是sign问题，alist中需要两处均需要关闭，我之前只关闭了存储页面的sign。现在完美解决问题。
