### ISSUE TITLE
发现通过8901显示的海报封面会变模糊

### ISSUE THREAD

**Issue by dddd64693** [bpking1/embyExternalUrl#389]
如题，使用8906端口显示的海报封面很清晰
![image](https://github.com/user-attachments/assets/7e53b520-66da-47b3-b58e-5dee535a1cee)
但是通过8901端口显示的海报封面jiu'h就会变得模糊
![image](https://github.com/user-attachments/assets/62c94aa5-337d-4a77-b180-225af956a6b3)
使用的是emby2Alistz这个项目,文件如图中所示
![image](https://github.com/user-attachments/assets/3ba3f3c9-a9dd-4667-a97c-1b98e5f77c71)

**Comment by chen3861229** [comment]
1.0.0.1 稍微有些老了，之前懒了点儿，没做 release 的发行维护了，可直接使用默认 main 分支中的文件进行重复部署下

2.新版本中，参数`imageCachePolicy`可以进行选择，默认的 0 是等同于描述的现象，这里可根据缓存占用和必要性进行设置，
位于`emby2Alist\nginx\conf.d\config\constant-ext.js`
```js
// 图片缓存策略,包括主页、详情页、图片库的原图,路由器 nginx 请手动调小 conf 中 proxy_cache_path 的 max_size
// 0: 不同尺寸设备共用一份缓存,先访问先缓存,空间占用最小但存在小屏先缓存大屏看的图片模糊问题
// 1: 不同尺寸设备分开缓存,空间占用适中,命中率低下,但契合 emby 的图片缩放处理
// 2: 不同尺寸设备共用一份缓存,空间占用最大,移除 emby 的缩放参数,直接原图高清显示
// 3: 关闭 nginx 缓存功能,已缓存文件不做处理
const imageCachePolicy = 0;
```

**Comment by dddd64693** [comment]
请教一下，这个const imageCachePolicy要调整的话，可以调整到多少呢，有没有建议，另外nginx 请手动调小 conf 中 proxy_cache_path 的 max_size需要一起调整吗，谢谢

**Comment by chen3861229** [comment]
1.这个根据缓存占用空间选择的，我这边硬盘够用，所以`const imageCachePolicy = 2;`

> nginx 请手动调小 conf 中 proxy_cache_path 的 max_size

2.这个是针对硬盘空间过小的设备说的，其余情况不用改这两个值

3.也可以直接`const imageCachePolicy = 3;`，关闭 nginx 的图片缓存，这样和源 emby 就是一样的了

**Comment by dddd64693** [comment]
> 1.这个根据缓存占用空间选择的，我这边硬盘够用，所以`const imageCachePolicy = 2;`，因为缓存的是原图，图片缓存占了我 15 GB 了
> 
> > nginx 请手动调小 conf 中 proxy_cache_path 的 max_size
> 
> 2.这个是针对硬盘空间过小的设备说的，其余情况不用改这两个值
> 
> 3.也可以直接`const imageCachePolicy = 3;`，关闭 nginx 的图片缓存，这样和源 emby 就是一样的了

作者，我用最新的版本重新部署了，但是发现8091端口无法访问，也没有被进程占用，以下是一些信息
![image](https://github.com/user-attachments/assets/0183a0f4-e51c-4bf2-bb7e-a29cb6ae9779)
![image](https://github.com/user-attachments/assets/6cc9a703-b22b-41b0-924a-72388f755a4d)
![image](https://github.com/user-attachments/assets/df514f10-b430-4b95-9bb6-842b7c24baf1)
![image](https://github.com/user-attachments/assets/674d3ef3-40c9-45f3-8942-4d87a00bb2a7)
![image](https://github.com/user-attachments/assets/cc68de3f-cb65-4223-a098-7ff566f601b6)
