### ISSUE TITLE
embyAddExternal不能拉起mpv会是什么原因呢

### ISSUE THREAD

**Issue by dddd64693** [bpking1/embyExternalUrl#390]

**Comment by dddd64693** [comment]
网页端可以拉起potpalyer，拉mpv的时候跳转到一个链接就没有反应了，win客户端直接没显示外链链接，可能是什么原因导致的呢

**Comment by chen3861229** [comment]
因为官方 mpv 是一个偏命令行的播放器，加了一层播放器 UI，而官方没有添加过多功能，例如对`Deeplink/URL Scheme`的支持，也就是不支持拉起，需要依赖一个第三方处理就行专用链的拉起兼容
//桌面端需要额外设置,使用这个项目: https://github.com/akiirui/mpv-handler

**Comment by dddd64693** [comment]
这个我有安装过，但是配置文件不知道对不对，也执行handler-install.bat了，现在是可以有弹窗的提醒，但是mpv播放器没有被成功开起来
![image](https://github.com/user-attachments/assets/112ecfa2-20ca-4d85-b10c-2170063b59fb)

**Comment by dddd64693** [comment]
解决了，删掉配置文件第一行的#号重新注册就好了
