### ISSUE TITLE
emby网页版播放视频，只要点视频播放一段时间再退出就会显示播放完毕，且无法精确显示播放进度。（挂载的115）

### ISSUE THREAD

**Issue by mrc321** [bpking1/embyExternalUrl#391]

**Comment by chen3861229** [comment]
这个是 emby 服务端自身问题，入库的媒体跳过了扫库的必要步骤，导致库中没有媒体的编码信息和**可播放时长**，所以播放进度方面存在问题，验证方式为详情页最下方没有媒体编码信息和时长之类的数据

https://github.com/chen3861229/embyExternalUrl/issues/36
https://github.com/chen3861229/embyExternalUrl/issues/45
https://github.com/chen3861229/embyExternalUrl/issues/47

**Comment by mrc321** [comment]
好的，确实是没有媒体编码信息。目测是ffprobe 无法正常工作：
ffprobe version 5.1-emby_2023_06_25 Copyright (c) 2007-2022 the FFmpeg developers and softworkz for Emby LLC
  built with gcc 10.3.0 (crosstool-NG 1.25.0)
/mnt/115网盘/电视剧/走向共和/Season 01/走向共和.S01E01.mkv: Input/output error

我目前是使用的cd2挂载115网盘到本地，看了您下面列举的issue，请问我是否需要更换为rclone挂载才能解决问题？

**Comment by chen3861229** [comment]
换`rclone`倒不至于，只是问题点是相同的，我自用也是`CD2`，检查下是否误添加了`进程黑名单=ffprobe`就行了，还有可能是扫库的时候`CD2`的挂载挂掉了，确认没问题后，在 emby 服务端的该媒体下右键重新`扫描媒体库文件`即可
