### ISSUE TITLE
调用401和显示问题求教

### ISSUE THREAD

**Issue by sky9639** [bpking1/embyExternalUrl#393]
有两个问题请教一下各位高手，RT所示，点击外链播放器显示401怎么破解？另一个问题为啥我这装完插件背景色是白的，看不清楚，是那里设置错误导致的么？
![image](https://github.com/user-attachments/assets/cd05aafc-046d-4135-8ccd-d2b3f85b75df)
![image](https://github.com/user-attachments/assets/fadb30f3-e134-4000-8f3c-bea92c3f515d)

**Comment by chen3861229** [comment]
1.截图中的`稍后播放`按钮看起来不像是原本的,[embyLaunchPotplayer.js](https://github.com/bpking1/embyExternalUrl/blob/main/embyWebAddExternalUrl/embyLaunchPotplayer.js)，因为没有过这个按钮，应该是其他作者的修改版本

2.通过截图下半的提示可知`api_key`未设置正确，这里猜测可能是脚本代码中需要手动设置变量值，可以在你使用的这份脚本中搜索`api_key`关键字

**Comment by sky9639** [comment]
上面说的对，是我很早之前装了 个油猴插件导致的，时间太长都忘记了，把插件删了用服务器端的旧OK 了
