### ISSUE TITLE
使用potplayer打开提示无法播放。 该文件不存在或被锁定。在渲染下列 Pin 时失败了。(您可通过切换选择菜单了解更多信息)

### ISSUE THREAD

**Issue by ste0815** [bpking1/embyExternalUrl#394]
之前使用都好好的，现在突然发现无法使用potplayer打开视频了，都是这个提示。换成emby客户端，外部调用potplayer就可以，但是网页打开不行，用的浏览器插件1.1.0版本
![image](https://github.com/user-attachments/assets/afcc368d-7894-4782-bf2e-f9a0e31a944a)

**Comment by chen3861229** [comment]
这个是浏览器自动升级了的问题，
https://github.com/AlistGo/alist/issues/7360

**Comment by FYYXS** [comment]
和你问题一样，昨天出现的

**Comment by ste0815** [comment]
原来是浏览器的锅。。。。感谢~
