### ISSUE TITLE
docker一键部署emby搜索报错

### ISSUE THREAD

**Issue by liangrenjing** [bpking1/embyExternalUrl#397]
报错日志如下：
2024/10/22 14:15:16 [error] 27#27: *2760 js exception: Error: unhandled promise rejection: TypeError: cannot get property "interactiveEnableRule" of undefined
    at searchHandle (/etc/nginx/conf.d/modules/emby-search.js:41)
, client: fd00:db7::1, server: default, request: "GET /emby/Users/996d798ff8bd41a9864bbe9f1a50046d/Items?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo%2CCanDelete%2CCanDownload%2CContainer%2CPrimaryImageAspectRatio%2CProductionYear%2CStatus%2CEndDate%2CPath%2CCommunityRating%2COfficialRating&StartIndex=0&EnableImageTypes=Primary%2CBackdrop%2CThumb&ImageTypeLimit=1&Recursive=true&SearchTerm=s%25&IncludeItemTypes=Movie%2CSeries%2CBoxSet&GroupProgramsBySeries=true&Limit=50&EnableTotalRecordCount=true HTTP/1.1", host: "nas.liangrenjing.cn:8091"
fd00:db7::1 - - [22/Oct/2024:14:15:16 +0800] "GET /emby/Users/996d798ff8bd41a9864bbe9f1a50046d/Items?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo%2CCanDelete%2CCanDownload%2CContainer%2CPrimaryImageAspectRatio%2CProductionYear%2CStatus%2CEndDate%2CPath%2CCommunityRating%2COfficialRating&StartIndex=0&EnableImageTypes=Primary%2CBackdrop%2CThumb&ImageTypeLimit=1&Recursive=true&SearchTerm=s%25&IncludeItemTypes=Movie%2CSeries%2CBoxSet&GroupProgramsBySeries=true&Limit=50&EnableTotalRecordCount=true HTTP/1.1" 500 170 "-" "Yamby/1.4.0.6(Android" "-"
2024/10/22 14:15:19 [error] 27#27: *2763 js exception: Error: unhandled promise rejection: TypeError: cannot get property "interactiveEnableRule" of undefined
    at searchHandle (/etc/nginx/conf.d/modules/emby-search.js:41)
, client: fd00:db7::1, server: default, request: "GET /emby/Users/996d798ff8bd41a9864bbe9f1a50046d/Items?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo%2CCanDelete%2CCanDownload%2CContainer%2CPrimaryImageAspectRatio%2CProductionYear%2CStatus%2CEndDate%2CPath%2CCommunityRating%2COfficialRating&StartIndex=0&EnableImageTypes=Primary%2CBackdrop%2CThumb&ImageTypeLimit=1&Recursive=true&SearchTerm=s%25&IncludeItemTypes=Movie%2CSeries&GroupProgramsBySeries=true&Limit=50&EnableTotalRecordCount=true HTTP/1.1", host: "nas.liangrenjing.cn:8091"
fd00:db7::1 - - [22/Oct/2024:14:15:19 +0800] "GET /emby/Users/996d798ff8bd41a9864bbe9f1a50046d/Items?SortBy=SortName&SortOrder=Ascending&Fields=BasicSyncInfo%2CCanDelete%2CCanDownload%2CContainer%2CPrimaryImageAspectRatio%2CProductionYear%2CStatus%2CEndDate%2CPath%2CCommunityRating%2COfficialRating&StartIndex=0&EnableImageTypes=Primary%2CBackdrop%2CThumb&ImageTypeLimit=1&Recursive=true&SearchTerm=s%25&IncludeItemTypes=Movie%2CSeries&GroupProgramsBySeries=true&Limit=50&EnableTotalRecordCount=true HTTP/1.1" 500 170 "-" "Yamby/1.4.0.6(Android" "-"

**Comment by chen3861229** [comment]
1.历史配置文件中没有这个新增的参数导致的，稍后将修复下

2.暂时的处理方案是手动先在`emby2Alist\nginx\conf.d\config\constant-ext.js`下添加上之前新增的参数`searchConfig`
![image](https://github.com/user-attachments/assets/ae3b5e70-a0d6-47f7-96ab-a907589805b7)
