### ISSUE TITLE
plex2alist 电视剧可以看一集直链 然后接下来就不能触发直链了 不知道为什么

### ISSUE THREAD

**Issue by Yan-nian** [bpking1/embyExternalUrl#405]
2024/10/31 10:34:47 [warn] 21#21: *705 js: === redirect2Pan: /library/parts/26595/1730370360/file.mkv, the NJS VM is destroyed ===
2024/10/31 10:34:49 [warn] 21#21: *709 js: === plexApiHandler: /status/sessions, the NJS VM is destroyed ===
2024/10/31 11:03:53 [warn] 22#22: *1379 js: === plexApiHandler: /library/metadata/20910, the NJS VM is destroyed ===
2024/10/31 11:04:00 [warn] 19#19: *1387 js: redirect2Pan, UA: libmpv
2024/10/31 11:04:00 [warn] 19#19: *1387 js: getPlexItemInfo r.uri: /library/parts/26597/1730370360/file.mkv
2024/10/31 11:04:00 [warn] 19#19: *1387 js: !!! not expect, will fallback search
2024/10/31 11:04:00 [warn] 19#19: *1387 js: 113ms, getPlexItemInfo async function cost
2024/10/31 11:04:00 [warn] 19#19: *1387 js: itemInfoUri: http://192.168.1.132:32400/search?query=%E4%BD%A0%E7%9A%84%E8%B0%8E%E8%A8%80%E4%B9%9F%E5%8A%A8%E5%90%AC.A.Beautiful.Lie.S01E16.2024.2160p.WEB-DL.H265.DDP5.1-ADWeb&X-Plex-Token=EzLg6Qhq4deXk44wLYfg
2024/10/31 11:04:00 [warn] 19#19: *1387 js: 30ms, fetchPlexFilePath async function cost
2024/10/31 11:04:00 [error] 19#19: *1387 js: fail to fetch fetchPlexFilePath: error: plex_api not found search results,fallback use original link
2024/10/31 11:04:00 [warn] 19#19: *1387 js: use original link
2024/10/31 11:04:00 [warn] 19#19: *1387 js: routeL1Dict add: [/library/parts/26597/1730370360/file.mkv] : [@root]
2024/10/31 11:04:03 [warn] 19#19: *1387 js: === redirect2Pan: /library/parts/26597/1730370360/file.mkv, the NJS VM is destroyed ===
2024/10/31 11:04:12 [warn] 19#19: *1391 js: === plexApiHandler: /library/metadata/20910, the NJS VM is destroyed ===
2024/10/31 11:09:42 [warn] 19#19: *1399 js: redirect2Pan, UA: libmpv
2024/10/31 11:09:42 [warn] 19#19: *1399 js: hit cache routeL1Dict: @root
2024/10/31 11:09:45 [warn] 19#19: *1399 js: === redirect2Pan: /library/parts/26597/1730370360/file.mkv, the NJS VM is destroyed ===
2024/10/31 11:09:47 [warn] 19#19: *1401 js: === plexApiHandler: /library/metadata/20910, the NJS VM is destroyed ===

**Comment by chen3861229** [comment]
1.因为 nginx 没缓存到对应媒体的路径信息，请问是从哪个入口播放(首页继续观看/完整进入剧集=>季度=>单集)的第一集呢？然后第二集是自动下一集的还是手动点击下一集的？
```js
2024/10/31 11:04:00 [warn] 19#19: *1387 js: getPlexItemInfo r.uri: /library/parts/26597/1730370360/file.mkv
2024/10/31 11:04:00 [warn] 19#19: *1387 js: !!! not expect, will fallback search
```

2.临时解决方案可能有用，完整进入剧集详情页中再点击播放

**Comment by Yan-nian** [comment]
也许和播放器有关 我是用的hamhub 首页正在观看进去的 是正在看的电视剧下面的控制栏手动点的下一集

**Comment by chen3861229** [comment]
`hamhub`可能调用的`continueWatching`首页继续观看列表的接口可能有些差异，nginx 中没添加到对应的`Part`媒体的路径缓存，暂时还是需要从首页继续观看中手动点击进剧集详情页了(而不是首页继续观看中直接点击媒体播放按钮)

**Comment by Yan-nian** [comment]
👌 谢谢大佬
