### ISSUE TITLE
embyWebAddExternalUrl和emby2alist共存

### ISSUE THREAD

**Issue by Inori44** [bpking1/embyExternalUrl#410]
embyWebAddExternalUrl可不可以不通过安装在服务器的方法，合并进emby2alist的反向代理代码

**Comment by z-x-f** [comment]
你说的是这个意思吗？[README](https://github.com/bpking1/embyExternalUrl/blob/main/README.md#%E4%BA%8C%E4%B8%8E-emby2alist-%E6%95%B4%E5%90%88%E5%B9%B6%E5%85%B1%E5%AD%98)

**Comment by Inori44** [comment]
> 你说的是这个意思吗？ [README](https://github.com/bpking1/embyExternalUrl/blob/main/README.md#%E4%BA%8C%E4%B8%8E-emby2alist-%E6%95%B4%E5%90%88%E5%B9%B6%E5%85%B1%E5%AD%98)

是这个意思，只看到了用客户端的那个，没看到这个网页版的，我想把网页版的合进去

**Comment by chen3861229** [comment]
1.`embyWebAddExternalUrl`这个按原作者提到的部署到服务端上就行了,

> 推荐直接将js脚本部署到emby_server,这样就不需要油猴了: 以linux为例,在/opt/emby-server/system/dashboard-ui目录下新建externalPlayer.js文件,将本脚本内容复制到里面,然后在当前目录下的index.html的 /body上面引入脚本即可

2.详细为修改服务端的`../emby-server/system/dashboard-ui/index.html`最下方，</body> 标签上，`<script src="apploader.js" defer></script>`这行的下方
```js
...
    <script src="apploader.js" defer></script>
    <script src="https://emby-external-url.7o7o.cc/embyWebAddExternalUrl/embyLaunchPotplayer.js" defer></script>
</body>
```

3.不过需要注意因为 emby 除了 web 端是直接加载的服务端前端文件，可以这样用，其他所有客户端都是直接使用本地前端文件的，即不会生效，这点是和`embyAddExternalUrl`最主要的区别

4.非 web 客户端想要添加`embyWebAddExternalUrl`需要解包各客户端引入，方式和 2 中一样，打包后还需要自签名，才能安装到对应设备中
