### ISSUE TITLE
网页播放只有画面没有声音

### ISSUE THREAD

**Issue by zhui22222** [bpking1/embyExternalUrl#411]
没有挂载，用alist转strm文件扫描入库的，用了docker版一键安装，网页播放用8096端口可以正常播放，8091只有画面没有声音，客户端播放都正常，请教怎么解决

**Comment by zhui22222** [comment]
> 8096播放的时候是不是经过服务器转码了？
是的，8091直链除了网页播放没声音，其他都正常。

**Comment by chen3861229** [comment]
1.应为 web 浏览器支持的音频格式太少，不建议使用，建议使用`Emby Theater`客户端，这样还是可以直链播放，或可以开启允许转码，这样不支持的编码格式将走原`emby`服务端进行转码传输，此时网速将受服务端机器所在的上行带宽限制

https://github.com/bpking1/embyExternalUrl/issues/273

**Comment by zhui22222** [comment]
看来web是真的无解了，调用转码可以播放但是字幕老是加载不到，调用外部播放器又不能保存播放进度
