### ISSUE TITLE
atv上infuse和emby无法使用

### ISSUE THREAD

**Issue by JZMAST** [bpking1/embyExternalUrl#416]
作者你好，我的alist安装在家里的软路由上，内网穿透得到了一个公网地址，emby和emby2list部署在外部的vps上，使用的是alist的公网地址。在外面emby客户端、网页端包括infuse都可以正常使用，但是家里就使用不了。atv上的infuse和emby都可以连接到emby服务器，并且日志中可以转到alist，但是播放不了，请问可能是什么原因？

**Comment by JZMAST** [comment]
![日志](https://github.com/user-attachments/assets/f1c494d9-1a52-4961-b547-982cb69af80d)
部分日志截图

**Comment by chen3861229** [comment]
1.感觉是内网软路由`alist`的域名`DNS`在`局域网下`解析有问题的样子，复现排查的话可以使用相同环境，用手机或PC的 ping 一下域名，看能不能 dns 解析到 ip 地址上(这个 ip 地址可能为动态公网 ip )，这块我也不是太熟，不过建议使用下面的方法直接避免掉这种情况

2.注释掉`emby2Alist\nginx\conf.d\config\constant-mount.js`中`clientSelfAlistRule`的`// [2, strHead["115"], alistPublicAddr],`,
这段配置的初衷为`IOS 客户端对于 115 的进度条拖动可能依赖于此`，以前`infuse < 8.0`也会拖动进度条导致 115 网盘的黑屏问题，不过最新实测，`infuse 8.0.3`，是可以随意拖动的，注释这段后，播放客户端将直接访问 115 直链，而不是默认的跳转`alist`直链，然后再跳转一次 115 直链
```js
// 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
// 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
// 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
// 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
// ,有分组时不可省略填写,可为表达式
// 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
// 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
// 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
const clientSelfAlistRule = [
  // IOS 客户端对于 115 的进度条拖动可能依赖于此
  // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
  // [2, strHead["115"], alistPublicAddr],
];
```

**Comment by JZMAST** [comment]
> 1.感觉是内网软路由`alist`的域名`DNS`在`局域网下`解析有问题的样子，复现排查的话可以使用相同环境，用手机或PC的 ping 一下域名，看能不能 dns 解析到 ip 地址上(这个 ip 地址可能为动态公网 ip )，这块我也不是太熟，不过建议使用下面的方法直接避免掉这种情况
> 
> 2.注释掉`emby2Alist\nginx\conf.d\config\constant-mount.js`中`clientSelfAlistRule`的`// [2, strHead["115"], alistPublicAddr],`, 这段配置的初衷为`IOS 客户端对于 115 的进度条拖动可能依赖于此`，以前`infuse < 8.0`也会拖动进度条导致 115 网盘的黑屏问题，不过最新实测，`infuse 8.0.3`，是可以随意拖动的，注释这段后，播放客户端将直接访问 115 直链，而不是默认的跳转`alist`直链，然后再跳转一次 115 直链
> 
> ```js
> // 指定客户端自己请求并获取 alist 直链的规则,代码优先级在 redirectStrmLastLinkRule 之后
> // 特殊情况使用,则此处必须使用域名且公网畅通,用不着请保持默认
> // 参数1: 分组名,组内为与关系(全部匹配),多个组和没有分组的规则是或关系(任一匹配),然后下面参数序号-1
> // 参数2: 匹配类型或来源(字符串参数类型),优先级高"filePath": 文件路径(Item.Path),默认为"alistRes": alist 返回的链接 raw_url
> // ,有分组时不可省略填写,可为表达式
> // 参数3: 0: startsWith(str), 1: endsWith(str), 2: includes(str), 3: match(/ain/g)
> // 参数4: 匹配目标,为数组的多个参数时,数组内为或关系(任一匹配)
> // 参数5: 指定转发给客户端的 alist 的 host 前缀,兼容 sign 参数
> const clientSelfAlistRule = [
>   // IOS 客户端对于 115 的进度条拖动可能依赖于此
>   // 如果 nginx 为 https,则此 alist 也必须 https,浏览器行为客户端会阻止非 https 请求
>   // [2, strHead["115"], alistPublicAddr],
> ];
> ```

感谢解答！应该是家里DNS解析的问题，使用方法2就能够正常播放了。
