### ISSUE TITLE
emby2Alist更新后，不能访问

### ISSUE THREAD

**Issue by qq328508474** [bpking1/embyExternalUrl#424]
我是Win版的Alist和emby，在openwrt的docker上安装的emby2Alist。
以前的版本用的都正常，最近这几个版本更新docker的nginx能运行，就是网页不能访问。最后一个正常的版本好像是11月11号之前的，我docker的nginx目录显示创建时间是11-10号。
error.log内容，我看不懂。

2024/11/23 12:26:17 [notice] 1#1: using the "epoll" event method
2024/11/23 12:26:17 [notice] 1#1: nginx/1.27.2
2024/11/23 12:26:17 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
2024/11/23 12:26:17 [notice] 1#1: OS: Linux 5.10.221
2024/11/23 12:26:17 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/11/23 12:26:17 [notice] 1#1: start worker processes
2024/11/23 12:26:17 [notice] 1#1: start worker process 20
2024/11/23 12:26:17 [notice] 1#1: start worker process 21
2024/11/23 12:26:17 [notice] 1#1: start worker process 22
2024/11/23 12:26:17 [notice] 1#1: start worker process 23
2024/11/23 12:26:17 [notice] 1#1: start worker process 24
2024/11/23 12:26:17 [notice] 1#1: start worker process 25
2024/11/23 12:26:17 [notice] 1#1: start worker process 26
2024/11/23 12:26:17 [notice] 1#1: start worker process 27
2024/11/23 12:26:17 [notice] 1#1: start cache manager process 28
2024/11/23 12:26:17 [notice] 1#1: start cache loader process 29
2024/11/23 12:26:40 [notice] 1#1: signal 3 (SIGQUIT) received, shutting down
2024/11/23 12:26:40 [notice] 21#21: gracefully shutting down
2024/11/23 12:26:40 [notice] 20#20: gracefully shutting down
2024/11/23 12:26:40 [notice] 24#24: gracefully shutting down
2024/11/23 12:26:40 [notice] 22#22: gracefully shutting down
2024/11/23 12:26:40 [notice] 25#25: gracefully shutting down
2024/11/23 12:26:40 [notice] 21#21: exiting
2024/11/23 12:26:40 [notice] 26#26: gracefully shutting down
2024/11/23 12:26:40 [notice] 20#20: exiting
2024/11/23 12:26:40 [notice] 28#28: exiting
2024/11/23 12:26:40 [notice] 24#24: exiting
2024/11/23 12:26:40 [notice] 22#22: exiting
2024/11/23 12:26:40 [notice] 25#25: exiting
2024/11/23 12:26:40 [notice] 26#26: exiting
2024/11/23 12:26:40 [notice] 23#23: gracefully shutting down
2024/11/23 12:26:40 [notice] 23#23: exiting
2024/11/23 12:26:40 [notice] 29#29: exiting
2024/11/23 12:26:40 [notice] 27#27: gracefully shutting down
2024/11/23 12:26:40 [notice] 27#27: exiting
2024/11/23 12:26:40 [notice] 21#21: exit
2024/11/23 12:26:40 [notice] 25#25: exit
2024/11/23 12:26:40 [notice] 22#22: exit
2024/11/23 12:26:40 [notice] 23#23: exit
2024/11/23 12:26:40 [notice] 26#26: exit
2024/11/23 12:26:40 [notice] 20#20: exit
2024/11/23 12:26:40 [notice] 24#24: exit
2024/11/23 12:26:40 [notice] 27#27: exit
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 28
2024/11/23 12:26:40 [notice] 1#1: cache manager process 28 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: cache loader process 29 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: signal 29 (SIGIO) received
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 26
2024/11/23 12:26:40 [notice] 1#1: worker process 26 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: signal 29 (SIGIO) received
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 27
2024/11/23 12:26:40 [notice] 1#1: worker process 20 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: worker process 21 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: worker process 23 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: worker process 27 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: signal 29 (SIGIO) received
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 23
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 24
2024/11/23 12:26:40 [notice] 1#1: worker process 24 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: worker process 25 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: signal 29 (SIGIO) received
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 25
2024/11/23 12:26:40 [notice] 1#1: signal 17 (SIGCHLD) received from 22
2024/11/23 12:26:40 [notice] 1#1: worker process 22 exited with code 0
2024/11/23 12:26:40 [notice] 1#1: exit
2024/11/23 12:27:23 [notice] 1#1: using the "epoll" event method
2024/11/23 12:27:23 [notice] 1#1: nginx/1.27.2
2024/11/23 12:27:23 [notice] 1#1: built by gcc 13.2.1 20240309 (Alpine 13.2.1_git20240309) 
2024/11/23 12:27:23 [notice] 1#1: OS: Linux 5.10.221
2024/11/23 12:27:23 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/11/23 12:27:23 [notice] 1#1: start worker processes
2024/11/23 12:27:23 [notice] 1#1: start worker process 20
2024/11/23 12:27:23 [notice] 1#1: start worker process 21
2024/11/23 12:27:23 [notice] 1#1: start worker process 22
2024/11/23 12:27:23 [notice] 1#1: start worker process 23
2024/11/23 12:27:23 [notice] 1#1: start worker process 24
2024/11/23 12:27:23 [notice] 1#1: start worker process 25
2024/11/23 12:27:23 [notice] 1#1: start worker process 26
2024/11/23 12:27:23 [notice] 1#1: start worker process 27
2024/11/23 12:27:23 [notice] 1#1: start cache manager process 28
2024/11/23 12:27:23 [notice] 1#1: start cache loader process 29
2024/11/23 12:28:25 [notice] 29#29: http file cache: /var/cache/nginx/emby/images 0.000M, bsize: 4096
2024/11/23 12:28:25 [notice] 29#29: http file cache: /var/cache/nginx/emby/subtitles 0.000M, bsize: 4096
2024/11/23 12:28:25 [notice] 1#1: signal 17 (SIGCHLD) received from 29
2024/11/23 12:28:25 [notice] 1#1: cache loader process 29 exited with code 0
2024/11/23 12:28:25 [notice] 1#1: signal 29 (SIGIO) received

**Comment by chen3861229** [comment]
> 2024/11/23 12:26:17 [notice] 1#1: nginx/1.27.2

1.暂时不要用 njs 0.8.6 内置版本的，这个版本 njs 引擎自身存在内存泄漏问题，换成`image: nginx:1.27.1`，不清楚是不是这个原因引起的，之前测试的情况是，启动就会内存泄漏到 1GB ，然后 nginx -s reload 被阻塞住了无法执行
services:
    service.nginx-emby:
      image: nginx:1.27.1

**Comment by qq328508474** [comment]
> > 2024/11/23 12:26:17 [notice] 1#1: nginx/1.27.2
> 
> 1.暂时不要用 njs 0.8.6 内置版本的，这个版本 njs 引擎自身存在内存泄漏问题，换成`image: nginx:1.27.1`，不清楚是不是这个原因引起的，之前测试的情况是，启动就会内存泄漏到 1GB ，然后 nginx -s reload 被阻塞住了无法执行 services: service.nginx-emby: image: nginx:1.27.1
> 
> 2.还可能有一个原因，刚起了下环境测试最新代码，发现浏览器卡首页转圈了，是这个现象吗？假如是的话，和 1 中无关系，是浏览器缓存的问题，因为将地址粘贴到隐私窗口中可以访问，解决方案，卡在首页时，打开浏览器控制台/F12，切换到应用程序 tab，点击本地存储下的自己的服务器域名，点击右边的全部清除，然后刷新页面重新登录即可

感谢回复，是第一个的问题，更换镜像解决了。第二个卡首页我知道，emby重装后就卡首页，缓存问题，哈哈。
