### ISSUE TITLE
无法保存播放进度，只要播放过的视频就会被标记为已播放完成

### ISSUE THREAD

**Issue by dddd64693** [bpking1/embyExternalUrl#432]
无法保存播放进度，只要播放过的视频就会被标记为已播放完成，不知道是不是因为emby服务端升级了导致的，之前都是正常的，目前服务端版本为4.7.14.0

**Comment by chen3861229** [comment]
该媒体的入库信息不完整，缺失`runtimeTicks/可播放时长`字段，历史 issus 中很多这个问题，假如是挂载的，需要重新刷新该媒体信息，假如是`strm`需要保证连接畅通，即 emby server 自身能访问，常见是 alist 需要关闭 sign 使用

**Comment by dddd64693** [comment]
> 该媒体的入库信息不完整，缺失`runtimeTicks/可播放时长`字段，历史 issus 中很多这个问题，假如是挂载的，需要重新刷新该媒体信息，假如是`strm`需要保证连接畅通，即 emby server 自身能访问，常见是 alist 需要关闭 sign 使用

感谢回复，挂载的需不需要alist 关闭 sign，还是说重新扫库就行，貌似我用直链后进行过扫库操作的

**Comment by liubin21** [comment]
用的是strm，alist也关闭sign，任然无法保存播放进度，一播放就显示已播放
