### ISSUE TITLE
我想让电视直播不走直链，全部都由emby中转处理应该如何操作？

### ISSUE THREAD

**Issue by erbukuawu** [bpking1/embyExternalUrl#434]
如题，我有些电视台是国外的，需要翻墙才能看，而我家里路由有装openclash，所以在家能观看国外台。
由于有公网，所以我想通过公网在外面直接观看由emby中转的国外台，不让电视直播走302，这样我每台登陆emby的客户端不需要再翻墙就能观看国外台了，需要如何操作才能实现上述功能，请大佬赐教

**Comment by free-150** [comment]
同问

**Comment by hulkihu** [comment]
我建议使用 xsteve 或 StreamMaster 来解决这个问题

**Comment by chen3861229** [comment]
1.暂无便捷设置，临时可将`emby2Alist\nginx\conf.d\emby.conf`中的`js_content embyLive.directLive;`替换为`proxy_pass $emby;`

2.之后将在设置中新增设置项

**Comment by erbukuawu** [comment]
> 1.暂无便捷设置，临时可将`emby2Alist\nginx\conf.d\emby.conf`中的`js_content embyLive.directLive;`替换为`proxy_pass $emby;`
> 
> 2.之后将在设置中新增设置项

![image](https://github.com/user-attachments/assets/5a8eb7a1-1d26-4782-9521-7c193cd19ab9)
将上面这串代码中的两个js_content embyLive.directLive;都改为proxy_pass $emby;然后重启服务是吧

**Comment by erbukuawu** [comment]
终于可以了，困扰了我几个月的问题终于解决了，感谢大佬
![image](https://github.com/user-attachments/assets/31f3166c-e8bd-4768-8b12-265782af8ddd)
