### ISSUE TITLE
我想将图片改为访问网盘内的链接，请指教

### ISSUE THREAD

**Issue by zeltp** [bpking1/embyExternalUrl#436]
目前已知可实现的有通过反代特定目录到alist端，可以直接加载，但是emby的图片路径规则未能获取
请大佬们指教

**Comment by chen3861229** [comment]
https://github.com/bpking1/embyExternalUrl/issues/345

请问是想图片 302 重定向到网盘吗？假如是，上述有更详细的解释，最主要图片这种大量小文件不适合实现，对网盘商那边整瘫痪了就不好了，最好还是放在本地，默认 emby nginx 有开启图片缓存，符合静态文件多级缓存倾向

**Comment by zeltp** [comment]
> #345
> 
> 请问是想图片 302 重定向到网盘吗？假如是，上述有更详细的解释，最主要图片这种大量小文件不适合实现，对网盘商那边整瘫痪了就不好了，最好还是放在本地，默认 emby nginx 有开启图片缓存，符合静态文件多级缓存倾向
