### ISSUE TITLE
URL编码有问题导致无法302跳转

### ISSUE THREAD

**Issue by LeeSinGOST** [bpking1/embyExternalUrl#437]
发现115网盘有部分视频走了代理之后无法播放，
查看error.log，对比了下redirect to: 链接和原链接，发现视频文件名有个字符 "**#**" 在rediriect to链接里未进行url编码，链接打开也是无法跳转，将"#"换成跟原链接一样的"%23"才可正常跳转。
应该是这块出岔子了，麻烦作者看看如何解决。

**Comment by chen3861229** [comment]
请求，redirect to: 链接 ，这个目的地是哪个服务，之前整个 URL 编码范围太大，导致了一些错误，所以目前是只针对`is CloudDrive/AList link, encodeURIComponent filePathPart`，测试正则: https://regex101.com/r/Gd3JUH/2

**Comment by LeeSinGOST** [comment]
目的服务是alist，文件类型是strm
![{158D12EF-BFB3-4B4F-8D99-B8E77BD15F6D}](https://github.com/user-attachments/assets/5afe535f-eef1-4066-a66f-e2b850d85247)

## 这是昨天的日志，
2024/12/06 04:08:33 [warn] 20#20: *28776 js: sourceStrValue, filePath = /mnt/alist/幺幺五/Anime/葬送的芙莉莲 (2023)/Season 1/S01E13 [AI-Raws] 葬送のフリーレン #13 (BD HEVC 1920x1080 FLAC 日本語字幕)[1B8D8F5C].mkv
2024/12/06 04:08:33 [warn] 20#20: *28776 js: strMatches result: false, type: 0, string source: /mnt/alist/幺幺五/Anime/葬送的芙莉莲 (2023)/Season 1/S01E13 [AI-Raws] 葬送のフリーレン #13 (BD HEVC 1920x1080 FLAC 日本語字幕)[1B8D8F5C].mkv, string target: /alist/WD10
2024/12/06 04:08:33 [warn] 20#20: *28776 js: getRouteMode: redirect, apiType: VideoStreamPlay
2024/12/06 04:08:33 [warn] 20#20: *28776 js: mediaPathMapping: [[0,0,"/alist",""],[0,1,"/mnt/alist",""]]
2024/12/06 04:08:33 [warn] 20#20: *28776 js: strMapping replace: /mnt/alist => 
2024/12/06 04:08:33 [warn] 20#20: *28776 js: mapped emby file path: /幺幺五/Anime/葬送的芙莉莲 (2023)/Season 1/S01E13 [AI-Raws] 葬送のフリーレン #13 (BD HEVC 1920x1080 FLAC 日本語字幕)[1B8D8F5C].mkv
2024/12/06 04:08:33 [warn] 20#20: *28776 js: sourceStrValue, alistRes = /幺幺五/Anime/葬送的芙莉莲 (2023)/Season 1/S01E13 [AI-Raws] 葬送のフリーレン #13 (BD HEVC 1920x1080 FLAC 日本語字幕)[1B8D8F5C].mkv
2024/12/06 04:08:33 [warn] 20#20: *28776 js: strMatches result: false, type: 2, string source: /幺幺五/Anime/葬送的芙莉莲 (2023)/Season 1/S01E13 [AI-Raws] 葬送のフリーレン #13 (BD HEVC 1920x1080 FLAC 日本語字幕)[1B8D8F5C].mkv, string target: 115.com
2024/12/06 04:08:33 [warn] 20#20: *28776 js: fetchAlistPathApi add Host: 127.0.0.1:8244
2024/12/06 04:08:33 [warn] 20#20: *28776 js: 281ms, fetchAlistPathApi async function cost
2024/12/06 04:08:33 [warn] 20#20: *28776 js: fetchAlistPathApi, UA: Emby/3.2.32-17.41 (Linux;Android 15) ExoPlayerLib/2.13.2
2024/12/06 04:08:33 [warn] 20#20: *28776 js: sourceStrValue, filePath = https://cdnfhnfile.115.com/66a52665bdbaedb9a8bcaf4de7ba1cda58cdef3e/S01E13%20%5BAI-3lhuucvzli5-1&c=2&f=1&k=b00c6cae7027416c52157e74c0d14&us=5242880000&uc=10&v=1
2024/12/06 04:08:33 [warn] 20#20: *28776 js: strMatches result: false, type: 1, string source: https://cdnfhnfile.115.com/66a52665bdbaedb9a8bcaf4de7ba1cda58cdef3e/S01E13%20%5BAI-3lhuucvzli5-1&c=2&f=1&k=b00c6cae7027416c52157e74c0d14&us=5242880000&uc=10&v=1, string target: theme.mp3
2024/12/06 04:08:33 [warn] 20#20: *28776 js: sourceStrValue, filePath = https://cdnfhnfile.115.com/66a52665bdbaedb9a8bcaf4de7ba1cda58cdef3e/S01E13%20%5BAI-3lhuucvzli5-1&c=2&f=1&k=b00c6cae7027416c52157e74c0d14&us=5242880000&uc=10&v=1
2024/12/06 04:08:33 [warn] 20#20: *28776 js: sourceStrValue, alistRes = https://cdnfhnfile.115.com/66a52665bdbaedb9a8bcaf4de7ba1cda58cdef3e/S01E13%20%5BAI-3lhuucvzli5-1&c=2&f=1&k=b00c6cae7027416c52157e74c0d14&us=5242880000&uc=10&v=1
2024/12/06 04:08:33 [warn] 20#20: *28776 js: strMatches result: true, type: 2, string source: https://cdnfhnfile.115.com/66a52665bdbaedb9a8bcaf4de7ba1cda58cdef3e/S01E13%20%5BAI-3lhuucvzli5-1&c=2&f=1&k=b00c6cae7027416c52157e74c0d14&us=5242880000&uc=10&v=1, string target: 115.com
2024/12/06 04:08:33 [warn] 20#20: *28776 js: hit clientSelfAlistRule: [2,"115.com","https://pan.domain.cc"]
2024/12/06 04:08:33 [warn] 20#20: *28776 js: redirect to: https://pan.domain.cc/d/%E5%B9%BA%E5%B9%BA%E4%BA%94/Anime/%E8%91%AC%E9%80%81%E7%9A%84%E8%8A%99%E8%8E%89%E8%8E%B2%20(2023)/Season%201/S01E13%20%5BAI-Raws%5D%20%E8%91%AC%E9%80%81%E3%81%AE%E3%83%95%E3%83%AA%E3%83%BC%E3%83%AC%E3%83%B3%20#13%20(BD%20HEVC%201920x1080%20FLAC%20%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%AD%97%E5%B9%95)%5B1B8D8F5C%5D.mkv
2024/12/06 04:08:33 [warn] 20#20: *28776 js: routeL1Dict add: [/emby/videos/15389/stream.mkv:b46ecc8be80adcfc7e1d1500dbf50198] : [https://pan.domain.cc/d/%E5%B9%BA%E5%B9%BA%E4%BA%94/Anime/%E8%91%AC%E9%80%81%E7%9A%84%E8%8A%99%E8%8E%89%E8%8E%B2%20(2023)/Season%201/S01E13%20%5BAI-Raws%5D%20%E8%91%AC%E9%80%81%E3%81%AE%E3%83%95%E3%83%AA%E3%83%BC%E3%83%AC%E3%83%B3%20#13%20(BD%20HEVC%201920x1080%20FLAC%20%E6%97%A5%E6%9C%AC%E8%AA%9E%E5%AD%97%E5%B9%95)%5B1B8D8F5C%5D.mkv]
2024/12/06 04:08:33 [warn] 20#20: *28776 js: === redirect2Pan: /emby/videos/15389/stream.mkv, the NJS VM is destroyed ===

在最后的redirect to {{alist链接}}出现了“#“，从log看似乎是出现了115直链，我不清楚里边的逻辑，怀疑是最后的{{alist链接}}有误，造成emby播放失败。手动将“#“字符全部修改掉之后视频代理播放恢复正常。

## 尝试其他带“#“文件名视频，又出现不同情况。
2024/12/07 01:36:01 [warn] 22#22: *333 js: redirect2Pan, UA: Emby/3.2.32-17.41 (Linux;Android 15) ExoPlayerLib/2.13.2
2024/12/07 01:36:01 [warn] 22#22: *333 js: itemInfoUri: http://127.0.0.1:8096/Items?Ids=28212a6fa545950258209e239988dfa1&Fields=Path,MediaSources&Limit=1&api_key=8fb1929a903f4d52943e3ae845ff279e
2024/12/07 01:36:01 [warn] 22#22: *333 js: 8ms, fetchEmbyFilePath async function cost
2024/12/07 01:36:01 [warn] 22#22: *333 js: notLocal: true
2024/12/07 01:36:01 [warn] 22#22: *333 js: mount emby file path: /mnt/alist/幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv
2024/12/07 01:36:01 [warn] 22#22: *333 js: add emby/jellyfin MediaSource to r
2024/12/07 01:36:01 [warn] 22#22: *333 js: sourceStrValue, filePath = /mnt/alist/幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv
2024/12/07 01:36:01 [warn] 22#22: *333 js: strMatches result: false, type: 1, string source: /mnt/alist/幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv, string target: theme.mp3
2024/12/07 01:36:01 [warn] 22#22: *333 js: sourceStrValue, filePath = /mnt/alist/幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv
2024/12/07 01:36:01 [warn] 22#22: *333 js: getRouteMode: redirect, apiType: VideoStreamPlay
2024/12/07 01:36:01 [warn] 22#22: *333 js: mediaPathMapping: [[0,1,"/mnt/alist",""]]
2024/12/07 01:36:01 [warn] 22#22: *333 js: strMapping replace: /mnt/alist => 
2024/12/07 01:36:01 [warn] 22#22: *333 js: mapped emby file path: /幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv
2024/12/07 01:36:01 [warn] 22#22: *333 js: sourceStrValue, alistRes = /幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv
2024/12/07 01:36:01 [warn] 22#22: *333 js: strMatches result: false, type: 2, string source: /幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv, string target: 115.com
2024/12/07 01:36:01 [warn] 22#22: *333 js: fetchAlistPathApi add Host: 127.0.0.1:8244
2024/12/07 01:36:01 [warn] 22#22: *333 js: 9ms, fetchAlistPathApi async function cost
2024/12/07 01:36:01 [warn] 22#22: *333 js: fetchAlistPathApi, UA: Emby/3.2.32-17.41 (Linux;Android 15) ExoPlayerLib/2.13.2
2024/12/07 01:36:01 [warn] 22#22: *333 js: alistRes: error500: alist_path_api 500 object not found
2024/12/07 01:36:01 [warn] 22#22: *333 js: will req alist /api/fs/list to rerty
2024/12/07 01:36:01 [warn] 22#22: *333 js: fetchAlistPathApi add Host: 127.0.0.1:8244
2024/12/07 01:36:05 [warn] 22#22: *333 js: try to fetch alist path from /幺幺五/幺幺五/Anime/迷宫饭 (2024)/Season 1/S01E03 [AI-Raws] ダンジョン飯 #03 (BD HEVC 1920x1080 FLAC)[EA79DCE4].mkv
2024/12/07 01:36:05 [warn] 22#22: *333 js: fetchAlistPathApi add Host: 127.0.0.1:8244
2024/12/07 01:36:05 [error] 22#22: *333 js: fail to fetch alist resource: not found,fallback use original link
2024/12/07 01:36:05 [warn] 22#22: *333 js: use original link
2024/12/07 01:36:05 [warn] 22#22: *333 js: routeL1Dict add: [/emby/videos/15999/stream.mkv:28212a6fa545950258209e239988dfa1] : [@root]
2024/12/07 01:36:05 [warn] 22#22: *333 js: === redirect2Pan: /emby/videos/15999/stream.mkv, the NJS VM is destroyed ===

此处的错误好像更合理，error500: alist_path_api 500 object not found。
修改"#"为“E”，代理播放同样恢复正常。

临时解决方案文件名映射估计涉及到挺多改动，暂未尝试。

**Comment by chen3861229** [comment]
多谢详细的日志，应该已经修复

**Comment by LeeSinGOST** [comment]
> 多谢详细的日志，应该已经修复

可以了，多谢
