### ISSUE TITLE
url汉字编码问题

### ISSUE THREAD

**Issue by Jz1028** [bpking1/embyExternalUrl#439]
现在用新程序生成strm的内容里面是，alist地址如：http://alist.com/d/%E7%99%BD%E5%A4%9C%E7%A0%B4%E6%99%93/s02e02.mp4，然后我把ip替换成 /mnt/alist

1.strm内容是 /mnt/alist/%E7%99%BD%E5%A4%9C%E7%A0%B4%E6%99%93/s02e02.mp4，好像无法解析，看不了视频

2.strm内容是 ip+地址好，还是 /mnt/alist+地址 这个好？

3.infuse emby观看115 strm，上面两种形式，拖拽进度条视频都会卡死，这个是因为115官方的原因所以无法解决吗？
但是web端跳转infuse观看，进度条可以正常拖拽播放

4.我发现现在web页面也可以直接观看直链视频了，这是咋回事？

感谢大佬🙏

**Comment by chen3861229** [comment]
1.已经修复，确认是前一个版本的其他修复引起的，https://github.com/bpking1/embyExternalUrl/pull/442/commits/164ab15cb36d451ef3c7f82115d753262f51a459

2.受限于 emby server 对于 / 开头的 strm 貌似兼容性不太好，服务端**好像**没法读取到这样文件进行媒体编码信息的扫库，
会导致各种问题，例如详情页下方不会有编码详情，无播放时长，点击播放就是直接完成，没有恢复播放的进度，但是正常播放属于脚本魔改，假如不存在上述问题，倒是可以选择，/ 开头的文件系统地址，这样变化不会太大，而且假如是 alist 也无关 sign 参数的问题了

3.这个是 Infuse + 115 的经典问题了，可能是 115 的链接最大只最大支持 2 线程加载，而 Infuse 拖拽进度条用到了 > 2 的进程加载，web端跳转infuse可以正常拖拽，可能是 Infuse 内部对于不同的播放形式加载的线程数有区别，这种属于播放器的串流播放，这个没啥太好的解决方案，因为脚本无法干预外部客户端内部的行为，之前尝试过一些兼容方案，效果也不太理想，不过可以尝试升级到`Infuse-Direct/8.0.3`试试看
https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#36ios-%E5%87%A0%E4%B9%8E%E5%85%A8%E9%83%A8%E5%AE%A2%E6%88%B7%E7%AB%AF%E6%92%AD%E6%94%BE-115-%E9%83%BD%E4%BC%9A%E6%8B%96%E5%8A%A8%E8%BF%9B%E5%BA%A6%E6%9D%A1%E9%BB%91%E5%B1%8F

4.因为已经默认反代修改了 web 的媒体跨域支持，https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#6115-%E5%86%85%E5%AE%B9%E6%97%A0%E6%B3%95-web-%E7%AB%AF%E6%92%AD%E6%94%BEhtmlvideoplayer-%E8%B7%A8%E5%9F%9F
