### ISSUE TITLE
反代端口直接打不开

### ISSUE THREAD

**Issue by chaomarks** [bpking1/embyExternalUrl#448]
有时候反代端口直接打不开不知道什么原因，一直转圈，自身的端口没问题，浏览器缓存清除路由器重启了还是不行，不知道什么原因
浏览器的打不开，手机客户端倒是可以

**Comment by chaomarks** [comment]
> 是域名形式的访问方式吗？假如是的话，有时候客户端设备所在网络 DNS 解析存在问题的话，会导致无法访问

是局域网的地址192.168的，containst文件是172.17.0.1:8096，电脑浏览器不能，但是手机能，手机浏览器也能，照片那个embyCache文件夹删除完了都不顶用，不知道问题在哪

**Comment by chen3861229** [comment]
1.embyhost 是在路由器下，建议直接添加`192.168`开头的，不要使用 172.17 之类的 docker 网段的 ip 地址

https://github.com/bpking1/embyExternalUrl/blob/main/FAQ.md#32embyhost

2.和这个`embyCache文件夹删除`是无关的，这个是封面图反代的缓存而已
