### ISSUE TITLE
Content no longer available.  这个问题真的是我独有的bug吗！

### ISSUE THREAD

**Issue by felix-klk** [bpking1/embyExternalUrl#46]
![image](https://github.com/bpking1/embyExternalUrl/assets/52670643/527dc13c-1e87-4d2f-914a-7fa278fb736d)
如果是的话真的 没办法了 旧版本用到废  麻了

**Comment by xx-super** [comment]
我也是这样的问题，不知道怎么解决，我emby用的是4.8.0.52b

**Comment by felix-klk** [comment]
> 我也是这样的问题，不知道怎么解决，我emby用的是4.8.0.52b

我用4.8.0.39  搭配旧版 反代可以完美的 上个月更新后一直存在这个报错  害

**Comment by chen3861229** [comment]
临时解决方案，先把emby.conf中playbackinfo两个路径的反代注释掉，bug有合作者还在修
see: bpking1/embyExternalUrl#35

**Comment by felix-klk** [comment]
> location ~* /Items/(.*)/PlaybackInfo

想问问 这个新版本的修复了吗

**Comment by erbukuawu** [comment]
> > location ~* /Items/(.*)/PlaybackInfo
> 
> 想问问 这个新版本的修复了吗

刚试了下最新版的，问题依然存在

**Comment by AmbitiousJun** [comment]
要用新版的功能的话，就只能这么做了：

> emby.conf中location ~* /Items/(.*)/PlaybackInfo路径的反代注释掉

没办法，我自己的 vps 一切正常，测不出来问题，目前来看应该就是在软路由搭就不行

**Comment by felix-klk** [comment]
> 要用新版的功能的话，就只能这么做了：
> 
> > emby.conf中location ~* /Items/(.*)/PlaybackInfo路径的反代注释掉
> 
> 没办法，我自己的 vps 一切正常，测不出来问题，目前来看应该就是在软路由搭就不行

这样做的后果是导致什么服务不正常吗

**Comment by xx-super** [comment]
> 要用新版的功能的话，就只能这么做了：
> 
> > emby.conf中location ~* /Items/(.*)/PlaybackInfo路径的反代注释掉
> 
> 没办法，我自己的 vps 一切正常，测不出来问题，目前来看应该就是在软路由搭就不行

我也是vps上面搭建的啊！不过是arm的vps

**Comment by AmbitiousJun** [comment]
> > 要用新版的功能的话，就只能这么做了：
> > > emby.conf中location ~* /Items/(.*)/PlaybackInfo路径的反代注释掉
> > 
> > 
> > 没办法，我自己的 vps 一切正常，测不出来问题，目前来看应该就是在软路由搭就不行
> 
> 这样做的后果是导致什么服务不正常吗

其实影响不大，就是避免播放视频的时候emby自动给你转容器，尤其是用web播放的话就经常出现这问题，如果你是用其他客户端播的，那就无所谓了，直接注释掉就行

**Comment by chen3861229** [comment]
新版已做初步兼容修复，我这边测试没问题，有时间的话可以更新试试。

**Comment by erbukuawu** [comment]
> 新版已做初步兼容修复，我这边测试没问题，有时间的话可以更新试试。

确实可以了，emby升级到4.8.0.55测试版，视频和直播均能正常播放，谢谢大佬
![image](https://github.com/bpking1/embyExternalUrl/assets/39191744/251edaf6-d601-4377-ba73-4432d6f4bfa8)
