### ISSUE TITLE
【emby2Alist】怎么设置才能senplayer、vidhub等APP搜索时候不返回演员信息

### ISSUE THREAD

**Issue by 907739769** [bpking1/embyExternalUrl#460]
怎么设置才能senplayer、vidhub等APP搜索时候不返回演员信息，比如搜索成龙，会搜出成龙历险记和演员成龙，怎么设置才能不返回演员信息

**Comment by chen3861229** [comment]
1.这个逻辑是媒体服务器原本是如此实现的，我猜测官方没有提供这个细致的个性化选项，因为是类似聚合搜索，和常见搜索引擎一样，**官方**客户端结果出来后可以切换 tab 来选择类型，而这些第三方 app 并没有对接这个 tab 分类的功能

2.感觉由脚本没办法很好的实现这个需求，因为涉及到 UI 交互，有很多种分类，服务端脚本写死过滤逻辑不太好
![image](https://github.com/user-attachments/assets/14226c37-e619-434c-b8de-84d2a5a334f7)
