### ISSUE TITLE
直链失败，总是碰到缓存

### ISSUE THREAD

**Issue by fayswing** [bpking1/embyExternalUrl#461]
大佬   我又来问问题了 

我最近在我软路由的docker里面配置了  直链    但是播放的时候直链失败

cd2上有流量在跑     看log显示是总是触发了路由器的缓存    不知道是什么原因

请问有什么办法解决吗      日志图片如下    麻烦大佬了

![image](https://github.com/user-attachments/assets/16d4dadd-54eb-4a9a-952a-26f266b839c5)

**Comment by chen3861229** [comment]
1.截图中的直链/路由缓存是无关的，重点还是查询 alist 路径报错了，这个路径在 alist 是真实存在的吗？
![image](https://github.com/user-attachments/assets/91fcad5e-2024-4078-9803-c3b1a77de41e)

**Comment by fayswing** [comment]
> 1.截图中的直链/路由缓存是无关的，重点还是查询 alist 路径报错了，这个路径在 alist 中是真实存在的吗？ ![image](https://private-user-images.githubusercontent.com/42368856/398991199-91fcad5e-2024-4078-9803-c3b1a77de41e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDgwNzIsIm5iZiI6MTczNTM0Nzc3MiwicGF0aCI6Ii80MjM2ODg1Ni8zOTg5OTExOTktOTFmY2FkNWUtMjAyNC00MDc4LTk4MDMtYzNiMWE3N2RlNDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDAxMDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5YjdkMzk2YmUzNjZlZDg2MzgwN2NlN2VmOTc0MjNkMjY1YzVjMzQ2YTBmMjUwZTJiNDJmNmIyYThjNmE1OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F4ovws-ZgNhpl0RJxCW8dNf5nkwFYVVRhso9PPpxt_4)

谢谢大佬的回复       根据大佬的指示排查了一下    alist   cookies挂载失效了   重新挂载以后直连成功了
感谢感谢
