### ISSUE TITLE
MKV文件播放失败

### ISSUE THREAD

**Issue by yu-xinx** [bpking1/embyExternalUrl#48]
<html>
<body>
<!DOCTYPE html><p cid="n0" mdtype="paragraph" class="md-end-block md-p md-focus" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="image" data-src="https://s2.loli.net/2023/10/17/6o3eiz7PuXL9Apr.png" class="md-image md-img-loaded md-expand" style="box-sizing: border-box; min-width: 10px; min-height: 10px; position: relative; word-break: break-all; font-family: monospace; display: inline-block; width: 1140px;"><img referrerpolicy="no-referrer" alt="QQ截图20231017231009.png" src="https://s2.loli.net/2023/10/17/6o3eiz7PuXL9Apr.png" onerror="onImageErrorFunc(event)" onload="onLoadedFuncForQuickAction(event)" style="box-sizing: border-box; border-width: 0px 4px 0px 2px; border-top-style: initial; border-right-style: solid; border-bottom-style: initial; border-left-style: solid; border-top-color: initial; border-right-color: transparent; border-bottom-color: initial; border-left-color: transparent; border-image: initial; vertical-align: middle; max-width: 100%; image-orientation: from-image; cursor: default; display: block; margin: auto;"></span></p><p cid="n3" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span md-inline="plain" class="md-plain" style="box-sizing: border-box;">MKV文件在电脑网页播放失败在手机上可以正常播放</span></p><p cid="n8" mdtype="paragraph" class="md-end-block md-p" style="box-sizing: border-box; line-height: inherit; orphans: 4; margin: 0.8em 0px; white-space: pre-wrap; position: relative; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></p><figure class="md-table-fig table-figure" cid="n12" mdtype="table" style="box-sizing: border-box; margin: 1.2em 0px; overflow-x: auto; max-width: calc(100% + 16px); padding: 0px; cursor: default; color: rgb(51, 51, 51); font-family: &quot;Open Sans&quot;, &quot;Clear Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;Segoe UI Emoji&quot;, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

2023/10/17 23:59:27 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:27 +0000] "GET /emby/Items/141/Images/Primary?maxHeight=300&maxWidth=200&tag=3ae4d2a2e73173d54d3175cab2d40576&quality=90 HTTP/1.1" 200 18582 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
-- | -- | --
2023/10/17 23:59:27 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:27 +0000] "GET /emby/Items/143/Images/Primary?maxHeight=225&maxWidth=400&tag=6daf82ab69e6c12aa1b9591af9ba1c93&quality=90 HTTP/1.1" 200 13640 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:26 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:26 +0000] "POST /emby/Sessions/Playing/Stopped?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:26 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:26 +0000] "POST /emby/Videos/ActiveEncodings/Delete?deviceId=44bf517f-740a-48c2-a310-39c961bc071d&PlaySessionId=63fac4ecc2ba4004a99a401afa98b907&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:20 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:20 +0000] "GET /emby/videos/143/master.m3u8?DeviceId=44bf517f-740a-48c2-a310-39c961bc071d&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&StartTimeTicks=1377690&PlaySessionId=8e24a8570b9c4991bbba92c739173020&api_key=541c89a2936849f7af1c692543ec3d66&VideoCodec=h264,h265,hevc&AudioCodec=mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&AudioStreamIndex=1&TranscodingMaxAudioChannels=2&SegmentContainer=m4s,ts&MinSegments=1&BreakOnNonKeyFrames=True&SubtitleStreamIndexes=-1&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=62&TranscodeReasons=DirectPlayError&allowVideoStreamCopy=false&allowAudioStreamCopy=false HTTP/1.1" 302 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:20 | stderr | 2023/10/17 15:59:20 [warn] 20#20: *2106 js: redirect to: http://192.168.50.170:5244/p/Videos/Animes/Anne%20Happy/Season%201/%5BSumiSora&CASO&FLsnow%5D%20Unhappy%20%20-%20S01E02%20-%20.mkv
2023/10/17 23:59:20 | stderr | 2023/10/17 15:59:20 [warn] 20#20: *2106 js: mount emby file path: /Videos/Animes/Anne Happy/Season 1/[SumiSora&CASO&FLsnow] Unhappy - S01E02 - .mkv
2023/10/17 23:59:20 | stderr | 2023/10/17 15:59:20 [warn] 20#20: *2106 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?MediaSourceId=fec3ecd10c6604008b6d9725752cee28&api_key=541c89a2936849f7af1c692543ec3d66
2023/10/17 23:59:20 | stderr | 2023/10/17 15:59:20 [warn] 20#20: *2106 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?api_key=541c89a2936849f7af1c692543ec3d66&AutoOpenLiveStream=true
2023/10/17 23:59:20 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:20 +0000] "POST /emby/Videos/ActiveEncodings/Delete?deviceId=44bf517f-740a-48c2-a310-39c961bc071d&PlaySessionId=63fac4ecc2ba4004a99a401afa98b907&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:20 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:20 +0000] "POST /emby/Items/143/PlaybackInfo?UserId=61f35782e03f452d9b7e1a7d6f0f3ab1&StartTimeTicks=1377690&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&SubtitleStreamIndex=40&EnableDirectPlay=false&EnableDirectStream=false&AllowVideoStreamCopy=false&AllowAudioStreamCopy=false&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&MaxStreamingBitrate=140000000&CurrentPlaySessionId=63fac4ecc2ba4004a99a401afa98b907&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 200 26027 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:20 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:20 +0000] "POST /emby/Videos/ActiveEncodings/Delete?deviceId=44bf517f-740a-48c2-a310-39c961bc071d&PlaySessionId=4d2c1e597a414ac19040b2c0cd8e3af7&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:13 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:13 +0000] "GET /emby/videos/143/master.m3u8?DeviceId=44bf517f-740a-48c2-a310-39c961bc071d&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&StartTimeTicks=1377690&PlaySessionId=63fac4ecc2ba4004a99a401afa98b907&api_key=541c89a2936849f7af1c692543ec3d66&VideoCodec=h264,h265,hevc&AudioCodec=mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&AudioStreamIndex=1&TranscodingMaxAudioChannels=2&SegmentContainer=m4s,ts&MinSegments=1&BreakOnNonKeyFrames=True&SubtitleStreamIndexes=-1&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=62&TranscodeReasons=DirectPlayError&allowVideoStreamCopy=false HTTP/1.1" 302 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:13 | stderr | 2023/10/17 15:59:13 [warn] 20#20: *2106 js: redirect to: http://192.168.50.170:5244/p/Videos/Animes/Anne%20Happy/Season%201/%5BSumiSora&CASO&FLsnow%5D%20Unhappy%20%20-%20S01E02%20-%20.mkv
2023/10/17 23:59:13 | stderr | 2023/10/17 15:59:13 [warn] 20#20: *2106 js: mount emby file path: /Videos/Animes/Anne Happy/Season 1/[SumiSora&CASO&FLsnow] Unhappy - S01E02 - .mkv
2023/10/17 23:59:13 | stderr | 2023/10/17 15:59:13 [warn] 20#20: *2106 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?MediaSourceId=fec3ecd10c6604008b6d9725752cee28&api_key=541c89a2936849f7af1c692543ec3d66
2023/10/17 23:59:13 | stderr | 2023/10/17 15:59:13 [warn] 20#20: *2106 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?api_key=541c89a2936849f7af1c692543ec3d66&AutoOpenLiveStream=true
2023/10/17 23:59:13 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:13 +0000] "POST /emby/Videos/ActiveEncodings/Delete?deviceId=44bf517f-740a-48c2-a310-39c961bc071d&PlaySessionId=4d2c1e597a414ac19040b2c0cd8e3af7&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:13 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:13 +0000] "POST /emby/Items/143/PlaybackInfo?UserId=61f35782e03f452d9b7e1a7d6f0f3ab1&StartTimeTicks=1377690&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&SubtitleStreamIndex=40&EnableDirectPlay=false&EnableDirectStream=false&AllowVideoStreamCopy=false&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&MaxStreamingBitrate=140000000&CurrentPlaySessionId=4d2c1e597a414ac19040b2c0cd8e3af7&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 200 26000 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:13 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:13 +0000] "POST /emby/Videos/ActiveEncodings/Delete?deviceId=44bf517f-740a-48c2-a310-39c961bc071d&PlaySessionId=aa2c7b1a1c7c441b90f9fbceed99752b&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /web/modules/fonts/GoNotoCurrent.woff2 HTTP/1.1" 200 5439980 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/Videos/143/fec3ecd10c6604008b6d9725752cee28/Subtitles/40/0/Stream.ass?api_key=541c89a2936849f7af1c692543ec3d66 HTTP/1.1" 200 44711 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /web/bower_components/javascriptsubtitlesoctopus/dist/subtitles-octopus-worker.wasm HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /web/bower_components/javascriptsubtitlesoctopus/dist/subtitles-octopus-worker.wasm HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /web/bower_components/javascriptsubtitlesoctopus/dist/subtitles-octopus-worker.wasm HTTP/1.1" 200 1922230 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /web/bower_components/javascriptsubtitlesoctopus/dist/subtitles-octopus-worker.js HTTP/1.1" 200 433549 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/videos/143/master.m3u8?DeviceId=44bf517f-740a-48c2-a310-39c961bc071d&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&StartTimeTicks=1377690&PlaySessionId=4d2c1e597a414ac19040b2c0cd8e3af7&api_key=541c89a2936849f7af1c692543ec3d66&VideoCodec=h264,h265,hevc&AudioCodec=mp3,aac&VideoBitrate=139808000&AudioBitrate=192000&AudioStreamIndex=1&TranscodingMaxAudioChannels=2&SegmentContainer=m4s,ts&MinSegments=1&BreakOnNonKeyFrames=True&SubtitleStreamIndexes=-1&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=62&TranscodeReasons=DirectPlayError HTTP/1.1" 302 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2106 js: redirect to: http://192.168.50.170:5244/p/Videos/Animes/Anne%20Happy/Season%201/%5BSumiSora&CASO&FLsnow%5D%20Unhappy%20%20-%20S01E02%20-%20.mkv
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2106 js: mount emby file path: /Videos/Animes/Anne Happy/Season 1/[SumiSora&CASO&FLsnow] Unhappy - S01E02 - .mkv
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2106 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?MediaSourceId=fec3ecd10c6604008b6d9725752cee28&api_key=541c89a2936849f7af1c692543ec3d66
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2106 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?api_key=541c89a2936849f7af1c692543ec3d66&AutoOpenLiveStream=true
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "POST /emby/Videos/ActiveEncodings/Delete?deviceId=44bf517f-740a-48c2-a310-39c961bc071d&PlaySessionId=aa2c7b1a1c7c441b90f9fbceed99752b&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "POST /emby/Items/143/PlaybackInfo?UserId=61f35782e03f452d9b7e1a7d6f0f3ab1&StartTimeTicks=1377690&IsPlayback=true&AutoOpenLiveStream=true&AudioStreamIndex=1&SubtitleStreamIndex=40&EnableDirectPlay=false&EnableDirectStream=false&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&MaxStreamingBitrate=140000000&CurrentPlaySessionId=aa2c7b1a1c7c441b90f9fbceed99752b&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 200 25973 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "POST /emby/Sessions/Playing/Progress?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/Items/15/Images/Primary?height=512&tag=efa010e75418a8efb2ce55ae227d75ef&quality=90 HTTP/1.1" 200 43586 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/Items/15/Images/Primary?height=192&tag=efa010e75418a8efb2ce55ae227d75ef&quality=90 HTTP/1.1" 200 9716 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "POST /emby/Sessions/Playing?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/videos/143/stream.mkv?DeviceId=44bf517f-740a-48c2-a310-39c961bc071d&MediaSourceId=fec3ecd10c6604008b6d9725752cee28&Static=true&PlaySessionId=aa2c7b1a1c7c441b90f9fbceed99752b&api_key=541c89a2936849f7af1c692543ec3d66 HTTP/1.1" 302 145 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2103 js: redirect to: http://192.168.50.170:5244/p/Videos/Animes/Anne%20Happy/Season%201/%5BSumiSora&CASO&FLsnow%5D%20Unhappy%20%20-%20S01E02%20-%20.mkv
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2103 js: mount emby file path: /Videos/Animes/Anne Happy/Season 1/[SumiSora&CASO&FLsnow] Unhappy - S01E02 - .mkv
2023/10/17 23:59:06 | stderr | 2023/10/17 15:59:06 [warn] 20#20: *2103 js: itemInfoUri: http://192.168.50.170:8931/Items/143/PlaybackInfo?MediaSourceId=fec3ecd10c6604008b6d9725752cee28&api_key=541c89a2936849f7af1c692543ec3d66
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "POST /emby/Items/143/PlaybackInfo?UserId=61f35782e03f452d9b7e1a7d6f0f3ab1&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 200 25544 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/Users/61f35782e03f452d9b7e1a7d6f0f3ab1?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 200 1048 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/Users/61f35782e03f452d9b7e1a7d6f0f3ab1/Items/143?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 200 3480 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
2023/10/17 23:59:06 | stdout | 172.23.0.1 - - [17/Oct/2023:15:59:06 +0000] "GET /emby/Users/61f35782e03f452d9b7e1a7d6f0f3ab1?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Google%20Chrome%20Windows&X-Emby-Device-Id=44bf517f-740a-48c2-a310-39c961bc071d&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=541c89a2936849f7af1c692543ec3d66&X-Emby-Language=zh-cn HTTP/1.1" 200 1048 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36" "-"
  |   |  

</figure><br class="Apple-interchange-newline">
</body>
</html>

**Comment by bpking1** [comment]
试试不用直链能正常播放吗，应该是web解码不支持的问题，不是直链的问题
https://jellyfin.org/docs/general/clients/codec-support/

**Comment by bpking1** [comment]
h265编码的视频建议用客户端或者外部播放器
