### ISSUE TITLE
[BUG] 电视直播无法调用

### ISSUE THREAD

**Issue by tsvico** [bpking1/embyExternalUrl#5]
![image](https://user-images.githubusercontent.com/32492304/224527313-5c20a2c2-aaf8-424e-8bcf-b3c1751b4597.png)
电视直播无法调用播放器，报错如图

**Comment by erbukuawu** [comment]
我也是这样，大佬有找到解决办法吗

**Comment by chen3861229** [comment]
已经修复
3bbcd39a54631dd3f534b17be6fe232c6b103bb8
