### ISSUE TITLE
AList 和阿里云 webdav 都是阿里云官方接口，能否简化步骤？

### ISSUE THREAD

**Issue by juneix** [bpking1/embyExternalUrl#51]
如题，AList 和阿里云 webdav 目前都是使用阿里云的官方开放平台接口，小白想问下为什么要先用阿里云 webdav 挂载了，再用 AList ➕nginx中转，理由是什么？能否简化一下流程，去掉阿里云 webdav。

在 GitHub 看到另一个[类似方案](https://github.com/zxcvbnmzsedr/docker_env/tree/master/emby)，原理应该一样，直接用 AList➕nginx 的，只是作者很久没更新项目了，不确定还用么。

**Comment by bpking1** [comment]
是的用alist的webdav挂载也可以，不一定需要aliwebdav来挂载，这个"类似"的方案应该是直接copy的这里的代码
