### ISSUE TITLE
播放器图标有白色问号，还有乱码

### ISSUE THREAD

**Issue by Darth12** [bpking1/embyExternalUrl#52]
![8254b30b7e953bf7723c0a1facc1b18](https://github.com/bpking1/embyExternalUrl/assets/125036431/32cf28e1-33ea-4c65-b72d-fe62196378d1)

**Comment by chen3861229** [comment]
1.文字乱码的是中文，查看下原始js的内的中文和注释是否正常，确保是utf-8编码
2.更新下仓库脚本，加了本地base64图片的方式，不知道对图标乱码是否有帮助
