### ISSUE TITLE
视频直链播放正常，海报图片不显示

### ISSUE THREAD

**Issue by juneix** [bpking1/embyExternalUrl#55]
用alist➕rclone的方案，根据教程修改相关配置，有点小问题求教一下。

用8096端口访问：
- 海报和演员图片正常
- 无法播放视频，显示没有兼容的流

用8095端口或绑定的域名访问：
- 海报和演员图片无法显示
- 视频正常播放，而且是阿里云直链

![海报异常](https://s2.loli.net/2023/11/06/De8Vw9zy1O3HsYq.jpg)

**Comment by chen3861229** [comment]
之前有遇到过图片全部裂开的情况，当时我的问题看emby日志是读取不到这些图片文件，然后我的情况是图片和nfo全部存到阿里云盘上了，用的是cd2＋Alist的组合，出现我这种情况是重启了cd2套件但是没重启emby导致的，你可以尝试多次重启下emby服务，如果不管用，删除下nginx的缓存文件试试，挂载出来的embyCache这个目录，如果还是解决不了那我就不清楚了。

**Comment by ershouqingge** [comment]
nginx缓存问题

**Comment by chen3861229** [comment]
删了缓存就好了么？如果存在这个问题我有时间能复现的话修复一下吧

**Comment by juneix** [comment]
> 之前有遇到过图片全部裂开的情况，当时我的问题看emby日志是读取不到这些图片文件，然后我的情况是图片和nfo全部存到阿里云盘上了，用的是cd2＋Alist的组合，出现我这种情况是重启了cd2套件但是没重启emby导致的，你可以尝试多次重启下emby服务，如果不管用，删除下nginx的缓存文件试试，挂载出来的embyCache这个目录，如果还是解决不了那我就不清楚了。

可是我embyCache目录下是没有文件，没有缓存？只有 images 和 subtitles 两个空文件夹

**Comment by chen3861229** [comment]
重启emby服务几次，现在海报还是裂开的吗？

**Comment by juneix** [comment]
> 重启emby服务几次，现在海报还是裂开的吗？

我换成 cd2+alist 了，现在 8096 端口播放视频也正常了，但是 8095 端口的图片还是不显示。

**Comment by chen3861229** [comment]
啊，这，不用折腾换底层的，cd2就是小白一些，也有其他bug的，比如挂载后emby不支持天翼云盘直链，rclone更好用一点，方便把emby错误日志贴出来一下吗？

**Comment by chen3861229** [comment]
你的海报图片是提前削刮好的存在云盘上，还是emby削刮的？

**Comment by chen3861229** [comment]
给你一个排查的思路吧，我这边尝试复现了下，在emby运行期间重启CD2套件就会导致emby原始端口和反代端口海报全部裂开，而且全部读取不到文件，无法播放，然后再重启下emby服务就会正常，但是这情况和你不一样。
1.看下emby日志，有没有System.IO.IOException: System.IO.IOException: Transport endpoint is not connected这个错误，有的话排查下文件夹权限或者重启下emby服务。
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/86feb8d7-149c-49ec-b46b-9e1b93b53790)

2.如果怀疑是nginx缓存问题，可以手动删除下~/nginx-emby2alist/embyCache/images下面的子目录，或者尝试注释下配置文件中的这段，然后重启nginx服务(不要用重载配置文件方式)，看下能不能恢复正常。
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/c8a6d2e2-a64d-4aa3-a8fe-1b866a2a098d)

**Comment by ershouqingge** [comment]
![image](https://github.com/bpking1/embyExternalUrl/assets/96559099/2825f560-0bc9-448f-8a19-2ac2d01bba50)
先8095本地看行不行，本地都行了，再下一步检查反代。

你反代缓存没挂载出来吧，没挂载出来就在root目录下，检查一下缓存，你这个八成就是是缓存的问题。

**Comment by juneix** [comment]
> 你的海报图片是提前削刮好的存在云盘上，还是emby削刮的？

最开始用 emby 搜刮，速度慢的跟蜗牛一样，准确率也低；后面换成 tmm 匹配元数据了，8096 海报和播放都正常的，8095 还是无法显示图片。很奇怪的是，我的～/embyCache/images下面没有任何文件。

**Comment by chen3861229** [comment]
感觉是nginx没有此缓存目录的写入权限
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/54733b51-cf25-4008-b6b4-922381dac0ea)

或者尝试更改nginx.conf中默认的
````
user  nginx;
````
为
````
user root;
````
