### ISSUE TITLE
调用potplayer 无法播放 iso原盘

### ISSUE THREAD

**Issue by bulesky89857** [bpking1/embyExternalUrl#57]
求教,调用potplayer 无法播放 iso原盘

**Comment by chaomarks** [comment]
ISO原盘本来播放就限制多多

**Comment by chen3861229** [comment]
1.去alist获取下直链直接放在potplayer中看能不能播放，ios估计太大了或者格式不支持串流播放
2.配置禁用直链规则交给媒体服务转码播放
