### ISSUE TITLE
关于视频直播跨域的问题

### ISSUE THREAD

**Issue by sweet271168603** [bpking1/embyExternalUrl#60]
我是基于python的flask框架重写了您的emby.js 和 emby-live.js; 因为搭建环境比较复杂还有实在不懂js，就没有复现环境。现在重写之后，视频重定向完全没问题，但是直播的时候，会出现跨域的问题。请求一下，emby-live.js 我看里面没有解决跨域的问题，您是如何解决跨域的。

**Comment by hsuyelin** [comment]
@sweet271168603 

你的flask代码方便开源参考下么

**Comment by chen3861229** [comment]
我不是作者，不过帮你找了下，你应该是直播的服务端没返回允许跨域标识吧。
1.这是emby服务的接口，全部带了
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/8c3208f8-8987-4fd5-833b-b8e9ac6c3828)
2.这是阿里云盘的直链，阿里那边响应也带上了
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/46f683d5-70ad-438b-9919-1acacdfca1b0)

**Comment by chen3861229** [comment]
1.浏览器装拓展修改响应头解决，客户端一般没做访问跨域限制
https://github.com/bpking1/embyExternalUrl/blob/main/emby2Alist/README.md
