### ISSUE TITLE
请教大佬，emby对接115直链报错

### ISSUE THREAD

**Issue by whistle003** [bpking1/embyExternalUrl#61]
![image](https://github.com/bpking1/embyExternalUrl/assets/64147479/6bbf36b1-bea6-4c46-bd03-b4ec60b62bbf)

**Comment by sjtuross** [comment]
按照一位大佬的说法：115直链需要获取直链的user-agent和下载时一致，不知道在nginx反代中能不能实现，至少alist通过web和webdav播放115直链是可以的

**Comment by whistle003** [comment]
> 按照一位大佬的说法：115直链需要获取直链的user-agent和下载时一致，不知道在nginx反代中能不能实现，至少alist通过web和

是滴，alist现在可以直接挂115的302重定向，但是到emby就不行了，很难受。希望有大佬赶快适配

**Comment by chen3861229** [comment]
用官方的alist proxy，cf worker一下是可以的，我这里wifi带宽上限只有100Mbps跑满，稳定性方面暂时未作测试。
![89c81b643e91dd0721d33ff0dd022200](https://github.com/bpking1/embyExternalUrl/assets/42368856/00df2697-190e-4775-9d67-7ad5f6feaa9f)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/6bbe7981-06f8-425e-9337-1d31122c0f63)

**Comment by chen3861229** [comment]
新版本已做初步适配，等合并后可以测试一下。

**Comment by whistle003** [comment]
> 新版本已做初步适配，等合并后可以测试一下。

期待

**Comment by EscapeU** [comment]
> 新版本已做初步适配，等合并后可以测试一下。

大概什么时候会发布

**Comment by chen3861229** [comment]
其实改动不是很大，如果急的话，可以参照166897f3e0968020659ab29806d256399eac3827添加一下

**Comment by EscapeU** [comment]
> 其实改动不是很大，如果急的话，可以参照添加一下 [166897f](https://github.com/bpking1/embyExternalUrl/commit/166897f3e0968020659ab29806d256399eac3827)
我尝试更改了代码但依旧不能直链播放，他跳转播放到了这个地址
![1704645998845](https://github.com/bpking1/embyExternalUrl/assets/125351094/2eccd96d-46ec-4295-bb76-7c1a62eae13d)

**Comment by chen3861229** [comment]
抱歉，疏忽了，还有一行地方改到了，不过直接整体换掉比较保险
https://github.com/chen3861229/embyExternalUrl/tree/dev

**Comment by EscapeU** [comment]
> 抱歉，疏忽了，还有一行地方改到了，不过直接整体换掉比较保险 https://github.com/chen3861229/embyExternalUrl/tree/dev
> 
> 115直链这种方式的话配置文件中alist地址必须要改用域名形式了
![1704702474646](https://github.com/bpking1/embyExternalUrl/assets/125351094/6014a760-73b5-48f6-9483-c1c9a87be8d0)
貌似用域名会110报错

**Comment by chen3861229** [comment]
你alist域名是https的吗？nginx和alist能不能请求通
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/3a41e4cd-aca8-46c0-8325-85b41d60fa82)

**Comment by EscapeU** [comment]
> 你alist域名是https的吗？nginx和alist是否网络畅通(我的环境暂时是三个组件都在同一局域网下,所以有些情况无法模拟)，图中请求alist超时了，花了30s+，明显网络不通了 ![image](https://private-user-images.githubusercontent.com/42368856/294876175-3a41e4cd-aca8-46c0-8325-85b41d60fa82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzkwNDEsIm5iZiI6MTcwNDczODc0MSwicGF0aCI6Ii80MjM2ODg1Ni8yOTQ4NzYxNzUtM2E0MWU0Y2QtYWNhOC00NmMwLTgzMjUtODViNDFkNjBmYTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE4MzIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMWQ3NjU3ZDI0N2VhMmE5MWU3MjBmMTdjMWIxYzA0MTYxN2E5MjMwZTY2YjU3OTU5NjY4ZTEzNzczNWZkZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GX0SrgZmwJpX4oiYPyFSwY1PIUqfYUuHSJJGT1GnO0c)
> 
> 对了，还有一个可能，fetch域名nginx需要配置dns解析，多添加几个试试，或者你的alist是ipv6的？ ![image](https://private-user-images.githubusercontent.com/42368856/294879477-26f46131-62f1-42f4-abff-707cd342c86b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MzkwNDEsIm5iZiI6MTcwNDczODc0MSwicGF0aCI6Ii80MjM2ODg1Ni8yOTQ4Nzk0NzctMjZmNDYxMzEtNjJmMS00MmY0LWFiZmYtNzA3Y2QzNDJjODZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDE4MzIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYzE5ZWE4Y2VjMTI3ZjFmNjM4NDUwMjFmZmQ0MGYyOGJiNWM4MTg5YTJjMWU5Y2YxZThmZTdjYWVlZDE0ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JyT9DGpI3Vc3ENgqgTouc0DE43F62mozUK05cywImxU)

貌似无法解决115直链播放的问题/d这个路径还是要鉴权的，
![1704738844657](https://github.com/bpking1/embyExternalUrl/assets/125351094/f04d9f17-cc85-41cd-ab35-69dbc2d3a151)
上面那个图可以看到后面是有sign做判断的，在您更改的js脚本中拼接后的路径并没有后面的sign内容导致不能使用

**Comment by chen3861229** [comment]
![Screenshot_2024-01-09-10-14-17-793_com.microsoft.emmx.jpg](https://github.com/bpking1/embyExternalUrl/assets/42368856/7f5624e7-8e63-4e39-a66c-ffe7e1da9c3a)

查看3.20的alist更新日志发现为了安全默认启用了签名所有参数，这个在之前版本是默认false，因为我是从老版本升级上去的，所以默认还是false，然后115驱动设置里还有个签名，不确定是不是这个导致的，我的环境是不需要sign这个参数的

**Comment by fzlzl** [comment]
我的播放115直链也不行，期待大佬修好

**Comment by chen3861229** [comment]
签名所有参数已做兼容，有的话会自动带上
https://github.com/bpking1/embyExternalUrl/pull/62/commits/2cb9ef3ffd77eed6d13b6bcedb4cd79cc8fa313b

**Comment by luxikakashi** [comment]
就是把你发那个分支里的全部替换了依旧不行，哈哈😆

**Comment by fzlzl** [comment]
> 就是把你发那个分支里的全部替换了依旧不行，哈哈😆

alist地址全换成域名试试，我的成功了

**Comment by luxikakashi** [comment]
> > 就是把你发那个分支里的全部替换了依旧不行，哈哈😆
> 
> 
> 
> alist地址全换成域名试试，我的成功了

域名不会弄呢，具体是在哪一块改域名呀，小白不是很懂呢呜呜🥹

**Comment by luxikakashi** [comment]
我擦居然成功了，alist地址改成外网ip，在启用签名就成了，反正瞎折腾一通

**Comment by Autolenuants** [comment]
> 我擦居然成功了，alist地址改成外网ip，在启用签名就成了，反正瞎折腾一通

可以具体一点么，我也直链不了

**Comment by luxikakashi** [comment]
> > 我擦居然成功了，alist地址改成外网ip，在启用签名就成了，反正瞎折腾一通
> 
> 
> 
> 可以具体一点么，我也直链不了

就是alist的115那里设置打开签名，然后文档里不是有改数据的部分，alist的地址不用docker内部的网址，改成vps本机的ip地址，我是做了这些改动，然后整个e2a的文件全部替换成大佬的这个版本的文件https://github.com/chen3861229/embyExternalUrl/tree/dev/emby2Alist

**Comment by nqxing** [comment]
> 新版本已做初步适配，等合并后可以测试一下。

大佬我替换了你dev分支nginx文件，然后在网页版还是无法播放，这是为啥呢？下面是报错截图
控制台：
![image](https://github.com/bpking1/embyExternalUrl/assets/37923544/d01573eb-c57f-493b-9d6a-f696de4818a2)
网络里的：
![image](https://github.com/bpking1/embyExternalUrl/assets/37923544/8d48a3a4-3b8c-447a-a021-9269dabdeeb4)

**Comment by chen3861229** [comment]
浏览器不装插件不行的，你这是被跨域拦截了，换客户端使用吧，或者用浏览器插件
https://github.com/bpking1/embyExternalUrl/pull/62

**Comment by cnpilot** [comment]
> > > 我擦居然成功了，alist地址改成外网ip，在启用签名就成了，反正瞎折腾一通
> > 
> > 
> > 可以具体一点么，我也直链不了
> 
> 就是alist的115那里设置打开签名，然后文档里不是有改数据的部分，alist的地址不用docker内部的网址，改成vps本机的ip地址，我是做了这些改动，然后整个e2a的文件全部替换成大佬的这个版本的文件https://github.com/chen3861229/embyExternalUrl/tree/dev/emby2Alist

请问都是用docker安装alist ，emby 吗，
