### ISSUE TITLE
mbylaunchpotplayer篡改猴脚本安装已启用，但emby网页版打开后显示脚本没有运行中的脚本

### ISSUE THREAD

**Issue by Zhaodoudou** [bpking1/embyExternalUrl#63]
我想问一下embylaunchpotplayer篡改猴脚本安装已启用，但emby网页版打开后显示脚本没有运行中的脚本，如何解决？

**Comment by chen3861229** [comment]
检查下你的路径是否匹配
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/733daf98-c54a-4258-8a23-3e301ee6e0a4)

**Comment by newday-life** [comment]
> 我想问一下embylaunchpotplayer篡改猴脚本安装已启用，但emby网页版打开后显示脚本没有运行中的脚本，如何解决？
. strm文件？

**Comment by chen3861229** [comment]
已做修复
c0ffac66667d455174cd24e3cacca3f45556a55b
