### ISSUE TITLE
外挂字幕

### ISSUE THREAD

**Issue by FromtoLight** [bpking1/embyExternalUrl#64]
外挂字幕的视频外部播放器播放没有字幕，要下载下来

**Comment by chen3861229** [comment]
这个没办法修复，是各个播放器对串流视频的字幕支持情况不同，只测试出了mx player(安卓版)是会自己获取并加载串流的字幕地址，翻了官方文档也没找到它是如何实现的，大部分播放器并没有做这个处理，目前妥协方案只能进emby网页版手动下载字幕并选择。。。
