### ISSUE TITLE
只支持strm，本地cd2挂载的无法播放

### ISSUE THREAD

**Issue by YanTaocheng** [bpking1/embyExternalUrl#66]
是否只支持strm的直连播放，我用cd2挂载本地的无法播放

我看nginx那边没有拦截挂载本地挂载的视频  /video/(.*)/original.mp4

**Comment by chen3861229** [comment]
支持的，在线播放走的是这个匹配 location ~* /videos/(.*)/stream
建议排查下nginx日志和config配置文件是否正常

**Comment by chen3861229** [comment]
额，115这个问题的话pr里有做兼容，暂时还未合并，需要耐心等等了。

**Comment by chen3861229** [comment]
https://github.com/chen3861229/embyExternalUrl/tree/dev

**Comment by YanTaocheng** [comment]
> https://github.com/chen3861229/embyExternalUrl/tree/dev

感谢，已部署，不用自己改脚本了＾-＾
