### ISSUE TITLE
emby 4.8.1.0 不支持直链播放

### ISSUE THREAD

**Issue by shiji5824666** [bpking1/embyExternalUrl#67]
1. emby 4.8.1.0 不支持直链播放，4.7.14.0 是支持的
2. 4.7.14.0 对strm不太友好，同文件夹下，如果 a.mp4 与 a.strm 同时存在，然后进详情页服务器必死机，播放 strm 文件 (路径非直链)，服务器有时会失联，估计是死机了
3. 用了一段时间，发现 4.8.1.0 挺稳定的，bug都改了...... 
4. 请问是否能支持一下 4.8.1.0，谢谢！

**Comment by chen3861229** [comment]
这边升级4.8.1.0简单测试了下，之前的基本功能没问题，包括[embyAddExternalUrl]也是可用的
1.新版兼容
2.这个问题我有时间再复现测试下

**Comment by anyingxiuluo** [comment]
我这边也是刚从4.7.14升级到了4.8.1.0直链播放失效了，用docker logs -f -n 10 emby-nginx 2>&1  | grep js:打印日志不显示任何内容

**Comment by chen3861229** [comment]
非access.log，搜一下error.log中的关键字，出现【redirect to】就是302成功了，njs的一些错误也会打印在里边
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/031374cb-6d11-4de7-8b0d-a82effb2b5bb)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/48ae8742-356f-4d15-85ac-7355124ec0dd)

**Comment by chen3861229** [comment]
长时间测试了下，确实web端和安卓端播十几秒钟会卡住，并且不会恢复播放，是因为onedrive国内访问不稳定，我这里电信宽带连接几百K到2M每秒网速波动很大，经常会卡住几秒钟无连接(通过idm下载测试出来的)，但是直链是成功了的，测试出来的解决方案是调用第三方播放器，会补偿这几秒中的无网络继续播放，永久解决方案是挂代理或者换其他网盘吧

**Comment by chen3861229** [comment]
长时间测试了下，确实web端和安卓端播十几秒钟会卡住，并且不会恢复播放，是因为onedrive国内访问不稳定，我这里电信宽带连接几百K到2M每秒网速波动很大，经常会卡住几秒钟无连接(通过idm下载测试出来的)，但是直链是成功了的，测试出来的解决方案是调用第三方播放器，会补偿这几秒中的无网络继续播放，永久解决方案是挂代理或者换其他网盘吧

**Comment by anyingxiuluo** [comment]
现在不是速度慢，是获取不到直链，直接走正常播放了，之前是可以的，我这边直链onedrive可以跑满宽带的

**Comment by chen3861229** [comment]
> 现在不是速度慢，是获取不到直链，直接走正常播放了，之前是可以的，我这边直链onedrive可以跑满宽带的

https://github.com/chen3861229/embyExternalUrl/tree/dev

**Comment by shiji5824666** [comment]
[v0.0.6]和main分支的最新更改，我都试过，4.8.1.0不支持直链播放，4.7.14.0是支持的，看log没有任何报错和警告，然后就直接走正常播放了，所以我从4.8.1.0换回4.7.14.0了......

**Comment by anyingxiuluo** [comment]
> > 现在不是速度慢，是获取不到直链，直接走正常播放了，之前是可以的，我这边直链onedrive可以跑满宽带的
> 
> 试试dev分支的更改吧，也不知道是不是隐性修复过了 https://github.com/chen3861229/embyExternalUrl/tree/dev

感谢大佬，使用dev分支可以正常获取到直链了，希望大佬能尽快发布新版本
![Uploading 微信截图_20240229100701.png…]()

**Comment by anyingxiuluo** [comment]
感谢大佬，使用dev分支可以正常获取到直链了，希望大佬能尽快发布新版本![微信截图_20240229100701](https://github.com/bpking1/embyExternalUrl/assets/125189022/431645ea-1561-42a7-afd9-e307ae116eeb)
