### ISSUE TITLE
plex直链播放

### ISSUE THREAD

**Issue by Mark-li521** [bpking1/embyExternalUrl#68]
目前alist上有两种115挂载方式，挂载自己的115连接，和别人分享的115链接。
目前状态：plex2alist中两种类型的视频的直链都可以获取到（plex2alist中有打印）
        但是，只能播放别人分享的115链接，直接访问自己挂载的那种方式的直链，http请求为
`Resolving cdnfhnfile.115.com (cdnfhnfile.115.com)... 140.249.62.213, 183.131.234.30, 140.249.62.215
Connecting to cdnfhnfile.115.com (cdnfhnfile.115.com)|140.249.62.213|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2024-02-28 21:42:58 ERROR 403: Forbidden.`

而在alist中115相关的视频是可以直接播放的，想问一下这个是alist的问题还是plex2alist的问题？

**Comment by Mark-li521** [comment]
> 是plex2alist的问题，~这个找我一个时间恢复修复下~ 对了，115的设备之前提交过，等待PRMK，或者去dev分支更新下新代码即可解决

很抱歉，我未在该项目中发现dev分支

**Comment by Mark-li521** [comment]
> https://github.com/chen3861229/embyExternalUrl/tree/dev

感谢，已经没问题了。
感觉目前的方案更好，使用js代替了，之前还需要多跑个进程

**Comment by Mark-li521** [comment]
> https://github.com/chen3861229/embyExternalUrl/tree/dev

报一个问题，目前电影类可以正常播放了，但是电视节目相关的，点进去以后报下面的问题，出不来详细的季和集
`10.0.0.8 - - [29/Feb/2024:08:16:58 +0800] "GET /library/metadata/55956?includeConcerts=1&includeExtras=1&includeOnDeck=1&includePopularLeaves=1&includePreferences=1&includeReviews=1&includeChapters=1&includeStations=1&includeExternalMedia=1&asyncAugmentMetadata=1&asyncCheckFiles=1&asyncRefreshAnalysis=1&asyncRefreshLocalMediaAgent=1 HTTP/1.1" 500 177 "-" "VidHub/2024022001 CFNetwork/1492.0.1 Darwin/23.3.0" "101.68.30.101"`。

我使用的是vidhub，因为客户端的视频兼容能力较差，vidhub和infuse一样，不需要转码
plex客户端是正常的

**Comment by Mark-li521** [comment]
我发现了普遍问题，在浏览器中，所有电视剧的打开都是出现错误。

**Comment by chen3861229** [comment]
因为用到了njs的新特性，不知道是不是这个影响到了
!!!此版本需要njs>=0.8.0,直接nginx:latest即可
如果还是不行，我晚上回去复现测试下

**Comment by Mark-li521** [comment]
> 因为用到了njs的新特性，不知道是不是这个影响到了 !!!此版本需要njs>=0.8.0,直接nginx:latest即可 如果还是不行，我晚上回去复现测试下

用的应该就是最新版
`nginx latest e4720093a3c1 2 weeks ago 187MB`

还是有问题  无法打开电视节目相关内容

**Comment by Mark-li521** [comment]
可能还是有些问题，看日志有时候会出现些404的保持信息，现在电视节目是可以进去了。但是部分视频播放还是有些问题
nginx的配置中我只改了conf中的constant.js中的 plexHost、plexMountPath、alistAddr、alistToken、alistPublicAddr这几项
可以麻烦帮忙看一下是什么原因吗？

```
10.0.0.8 - - [29/Feb/2024:22:35:59 +0800] "GET /photo/:/transcode?width=1920&height=1080&minSize=1&upscale=1&X-Plex-Token=e-mkLovewss93HNVVnke&url=/library/metadata/55085/art/1699922581 HTTP/1.1" 200 164378 "-" "VidHub/2024022001 CFNetwork/1492.0.1 Darwin/23.3.0" "101.68.30.101"
2024/02/29 22:36:01 [warn] 37#37: *1263 js: getPlexItemInfo r.uri: /library/parts/79259/1698555447/file.mkv
2024/02/29 22:36:01 [warn] 37#37: *1263 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E6%A0%91%E5%A4%A7%E6%A0%B9%E6%B7%B1%20-%20S01E01%20&X-Plex-Token=e-mkLovewss93HNVVnke
2024/02/29 22:36:02 [error] 37#37: *1263 js: error: plex_api No search results found
10.0.0.8 - - [29/Feb/2024:22:36:02 +0800] "GET /library/parts/79259/1698555447/file.mkv?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "Lavf/60.3.100" "101.68.30.101"
2024/02/29 22:36:03 [warn] 37#37: *1266 js: getPlexItemInfo r.uri: /library/parts/79259/1698555447/file.mkv
2024/02/29 22:36:03 [warn] 37#37: *1266 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E6%A0%91%E5%A4%A7%E6%A0%B9%E6%B7%B1%20-%20S01E01%20&X-Plex-Token=e-mkLovewss93HNVVnke
2024/02/29 22:36:04 [error] 37#37: *1266 js: error: plex_api No search results found
10.0.0.8 - - [29/Feb/2024:22:36:04 +0800] "GET /library/parts/79259/1698555447/file.mkv?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "libmpv" "101.68.30.101"
```

```
2024/02/29 22:45:39 [warn] 26#26: *2199 js: getPlexItemInfo r.uri: /library/parts/81327/1708863299/file.mp4
2024/02/29 22:45:40 [warn] 26#26: *2199 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E5%BC%80%E7%AB%AF.Reset.2022.E01.2160p.WEB-DL.H265.DV.DDP2.0-SeeWEB&X-Plex-Token=e-mkLovewss93HNVVnke
2024/02/29 22:45:41 [error] 26#26: *2199 js: error: plex_api No search results found
10.0.0.8 - - [29/Feb/2024:22:45:41 +0800] "GET /library/parts/81327/1708863299/file.mp4?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "Lavf/59.27.100" "101.68.30.101"
2024/02/29 22:45:41 [warn] 26#26: *2202 js: getPlexItemInfo r.uri: /library/parts/81327/1708863299/file.mp4
2024/02/29 22:45:41 [warn] 26#26: *2202 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E5%BC%80%E7%AB%AF.Reset.2022.E01.2160p.WEB-DL.H265.DV.DDP2.0-SeeWEB&X-Plex-Token=e-mkLovewss93HNVVnke
2024/02/29 22:45:42 [error] 26#26: *2202 js: error: plex_api No search results found
10.0.0.8 - - [29/Feb/2024:22:45:42 +0800] "GET /library/parts/81327/1708863299/file.mp4?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "libmpv" "101.68.30.101"
2024/02/29 22:45:55 [error] 26#26: *2205 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.8, server: default, request: "GET /:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM HTTP/1.1", upstream: "http://10.0.0.10:32400/:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM", host: "plex2.markc.top"
10.0.0.8 - - [29/Feb/2024:22:45:55 +0800] "GET /:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM HTTP/1.1" 502 157 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
2024/02/29 22:45:55 [error] 26#26: *2207 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.8, server: default, request: "GET /:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1", upstream: "http://10.0.0.10:32400/:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c", host: "plex2.markc.top"
10.0.0.8 - - [29/Feb/2024:22:45:55 +0800] "GET /:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1" 502 157 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
10.0.0.8 - - [29/Feb/2024:22:45:55 +0800] "GET /media/providers?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1" 200 5756 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
10.0.0.8 - - [29/Feb/2024:22:46:25 +0800] "GET /:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM HTTP/1.1" 400 5 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
10.0.0.8 - - [29/Feb/2024:22:46:25 +0800] "GET /:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1" 400 5 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
2024/02/29 22:46:26 [error] 27#27: *2215 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.8, server: default, request: "GET /:/websockets/notifications?X-Plex-Token=AM1g5wciP6qssL2UkwLg HTTP/1.1", upstream: "http://10.0.0.10:32400/:/websockets/notifications?X-Plex-Token=AM1g5wciP6qssL2UkwLg", host: "plex2.markc.top"
10.0.0.8 - - [29/Feb/2024:22:46:26 +0800] "GET /:/websockets/notifications?X-Plex-Token=AM1g5wciP6qssL2UkwLg HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "101.68.30.101"
10.0.0.8 - - [29/Feb/2024:22:46:27 +0800] "GET /media/providers?X-Plex-Product=Plex%20Web&X-Plex-Version=4.125.1&X-Plex-Client-Identifier=sga7fetumjpo8zyqx47fpbu5&X-Plex-Platform=Chrome&X-Plex-Platform-Version=122.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1180x822%2C1728x1117&X-Plex-Token=AM1g5wciP6qssL2UkwLg&X-Plex-Language=zh&X-Plex-Session-Id=93fe2988-1a62-4124-8b72-232a8478016d HTTP/1.1" 200 5756 "https://app.plex.tv/desktop/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "101.68.30.101"
```

**Comment by Mark-li521** [comment]
> 可能还是有些问题，看日志有时候会出现些404的保持信息，现在电视节目是可以进去了。但是部分视频播放还是有些问题 nginx的配置中我只改了conf中的constant.js中的 plexHost、plexMountPath、alistAddr、alistToken、alistPublicAddr这几项 可以麻烦帮忙看一下是什么原因吗？
> 
> ```
> 10.0.0.8 - - [29/Feb/2024:22:35:59 +0800] "GET /photo/:/transcode?width=1920&height=1080&minSize=1&upscale=1&X-Plex-Token=e-mkLovewss93HNVVnke&url=/library/metadata/55085/art/1699922581 HTTP/1.1" 200 164378 "-" "VidHub/2024022001 CFNetwork/1492.0.1 Darwin/23.3.0" "101.68.30.101"
> 2024/02/29 22:36:01 [warn] 37#37: *1263 js: getPlexItemInfo r.uri: /library/parts/79259/1698555447/file.mkv
> 2024/02/29 22:36:01 [warn] 37#37: *1263 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E6%A0%91%E5%A4%A7%E6%A0%B9%E6%B7%B1%20-%20S01E01%20&X-Plex-Token=e-mkLovewss93HNVVnke
> 2024/02/29 22:36:02 [error] 37#37: *1263 js: error: plex_api No search results found
> 10.0.0.8 - - [29/Feb/2024:22:36:02 +0800] "GET /library/parts/79259/1698555447/file.mkv?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "Lavf/60.3.100" "101.68.30.101"
> 2024/02/29 22:36:03 [warn] 37#37: *1266 js: getPlexItemInfo r.uri: /library/parts/79259/1698555447/file.mkv
> 2024/02/29 22:36:03 [warn] 37#37: *1266 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E6%A0%91%E5%A4%A7%E6%A0%B9%E6%B7%B1%20-%20S01E01%20&X-Plex-Token=e-mkLovewss93HNVVnke
> 2024/02/29 22:36:04 [error] 37#37: *1266 js: error: plex_api No search results found
> 10.0.0.8 - - [29/Feb/2024:22:36:04 +0800] "GET /library/parts/79259/1698555447/file.mkv?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "libmpv" "101.68.30.101"
> ```
> 
> ```
> 2024/02/29 22:45:39 [warn] 26#26: *2199 js: getPlexItemInfo r.uri: /library/parts/81327/1708863299/file.mp4
> 2024/02/29 22:45:40 [warn] 26#26: *2199 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E5%BC%80%E7%AB%AF.Reset.2022.E01.2160p.WEB-DL.H265.DV.DDP2.0-SeeWEB&X-Plex-Token=e-mkLovewss93HNVVnke
> 2024/02/29 22:45:41 [error] 26#26: *2199 js: error: plex_api No search results found
> 10.0.0.8 - - [29/Feb/2024:22:45:41 +0800] "GET /library/parts/81327/1708863299/file.mp4?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "Lavf/59.27.100" "101.68.30.101"
> 2024/02/29 22:45:41 [warn] 26#26: *2202 js: getPlexItemInfo r.uri: /library/parts/81327/1708863299/file.mp4
> 2024/02/29 22:45:41 [warn] 26#26: *2202 js: itemInfoUri: http://10.0.0.10:32400/search?query=%E5%BC%80%E7%AB%AF.Reset.2022.E01.2160p.WEB-DL.H265.DV.DDP2.0-SeeWEB&X-Plex-Token=e-mkLovewss93HNVVnke
> 2024/02/29 22:45:42 [error] 26#26: *2202 js: error: plex_api No search results found
> 10.0.0.8 - - [29/Feb/2024:22:45:42 +0800] "GET /library/parts/81327/1708863299/file.mp4?X-Plex-Token=e-mkLovewss93HNVVnke HTTP/1.1" 500 39 "-" "libmpv" "101.68.30.101"
> 2024/02/29 22:45:55 [error] 26#26: *2205 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.8, server: default, request: "GET /:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM HTTP/1.1", upstream: "http://10.0.0.10:32400/:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM", host: "plex2.markc.top"
> 10.0.0.8 - - [29/Feb/2024:22:45:55 +0800] "GET /:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM HTTP/1.1" 502 157 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
> 2024/02/29 22:45:55 [error] 26#26: *2207 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.8, server: default, request: "GET /:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1", upstream: "http://10.0.0.10:32400/:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c", host: "plex2.markc.top"
> 10.0.0.8 - - [29/Feb/2024:22:45:55 +0800] "GET /:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1" 502 157 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
> 10.0.0.8 - - [29/Feb/2024:22:45:55 +0800] "GET /media/providers?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1" 200 5756 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
> 10.0.0.8 - - [29/Feb/2024:22:46:25 +0800] "GET /:/websockets/notifications?X-Plex-Token=_XP2rkP4jALZzkTYJMbM HTTP/1.1" 400 5 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
> 10.0.0.8 - - [29/Feb/2024:22:46:25 +0800] "GET /:/websockets/notifications?X-Plex-Product=Plex%20for%20Mac&X-Plex-Version=1.88.1.96-c1c59fc1&X-Plex-Client-Identifier=v8bu1d25k1xf1935oj7lb4nd&X-Plex-Platform=macos&X-Plex-Platform-Version=14.3&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=standalone&X-Plex-Device-Name=lijiandeMacBook-Pro-2.local&X-Plex-Device-Screen-Resolution=1728x1080%2C1728x1117&X-Plex-Client-Profile-Name=Plex%20Desktop&X-Plex-Token=_XP2rkP4jALZzkTYJMbM&X-Plex-Language=zh&Accept-Language=zh&X-Plex-Session-Id=ae85861c-229f-4e9c-804c-95bfa02de16c HTTP/1.1" 400 5 "-" "Plex; 1.88.1.96-c1c59fc1; macOS 14.3" "101.68.30.101"
> 2024/02/29 22:46:26 [error] 27#27: *2215 upstream prematurely closed connection while reading response header from upstream, client: 10.0.0.8, server: default, request: "GET /:/websockets/notifications?X-Plex-Token=AM1g5wciP6qssL2UkwLg HTTP/1.1", upstream: "http://10.0.0.10:32400/:/websockets/notifications?X-Plex-Token=AM1g5wciP6qssL2UkwLg", host: "plex2.markc.top"
> 10.0.0.8 - - [29/Feb/2024:22:46:26 +0800] "GET /:/websockets/notifications?X-Plex-Token=AM1g5wciP6qssL2UkwLg HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "101.68.30.101"
> 10.0.0.8 - - [29/Feb/2024:22:46:27 +0800] "GET /media/providers?X-Plex-Product=Plex%20Web&X-Plex-Version=4.125.1&X-Plex-Client-Identifier=sga7fetumjpo8zyqx47fpbu5&X-Plex-Platform=Chrome&X-Plex-Platform-Version=122.0&X-Plex-Features=external-media%2Cindirect-media%2Chub-style-list&X-Plex-Model=hosted&X-Plex-Device=OSX&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1180x822%2C1728x1117&X-Plex-Token=AM1g5wciP6qssL2UkwLg&X-Plex-Language=zh&X-Plex-Session-Id=93fe2988-1a62-4124-8b72-232a8478016d HTTP/1.1" 200 5756 "https://app.plex.tv/desktop/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" "101.68.30.101"
> ```

我大概知道vidhub的逻辑，点开电视节目后，直接点击播放，播放第一集，应该和点击剧集在播放的逻辑不一样，点击具体的集数在播放是可以正常播放的。

**Comment by chen3861229** [comment]
是的，这是因为我这边实现方式的问题，没办法，受限于plex没有官方文档，目前官方客户端播放都是支持的，因为携带了挂载路径信息，但是下载和第三方客户端不进详情页播放特殊处理的，链接类似/library/parts/81327/1708863299/file.mp4，这个plex没提供直接的api查询出挂载路径，所以这边的处理是用进详情页的数据在nginx共享变量中缓存的，如果缓存没查到，就会用文件名调用plex的接口查询，和首页的查询接口同一个，所以对文件名带-的这种查询不出来，因为plex入库的时候会去掉-，目前想不出更合适的方案了，之前扒了几星期plex的接口。
目前的限制是第三方客户端注意必须进一次详情页，再点播放，不要直接点封面图上的播放按钮。
等有时间了，我再想想办法修复

**Comment by Mark-li521** [comment]
> 是的，这是因为我这边实现方式的问题，没办法，受限于plex没有官方文档，目前官方客户端播放都是支持的，因为携带了挂载路径信息，但是下载和第三方客户端不进详情页播放特殊处理的，链接类似/library/parts/81327/1708863299/file.mp4，这个plex没提供直接的api查询出挂载路径，所以这边的处理是用进详情页的数据在nginx共享变量中缓存的，如果缓存没查到，就会用文件名调用plex的接口查询，和首页的查询接口同一个，所以对文件名带-的这种查询不出来，因为plex入库的时候会去掉-，目前想不出更合适的方案了，之前扒了几星期plex的接口。 目前的限制是第三方客户端注意必须进一次详情页，再点播放，不要直接点封面图上的播放按钮。 等有时间了，我再想想办法修复

您好，我这边看了一下，获取的直链都是通过alistPublicAddr这个地址获取的，而且获取直链的速度较慢，大概在7-8秒左右，这是正常的时间吗？

**Comment by chen3861229** [comment]
是正常的，alist获取直链的接口是比较慢

**Comment by Mark-li521** [comment]
> 是正常的，alist获取直链的接口是比较慢。 不过我这边是alist和nginx还有媒体服务器在同一局域网下，稍微快一些 2024/02/28 21:34:12 [warn] 154#154: *161074 js: 2462ms, fetchAlistPathApi

你好  我发现alist的token2天就过期了，网上没有找到延长的方式，问下有考虑通过填写账户密码来获取alist的直链地址吗？

**Comment by chen3861229** [comment]
alist的令牌过期一般不存在的，除非去alist管理-设置-其他-重置令牌，当然之前也设想过某些人的alist主动权不在手里没有令牌，考虑过加一个账号密码的对接，其实最好排查下，是alist的sign参数，还是plex的token过期问题(这个之前有人反馈过，但是我主力使用emby的，所以没复现条件)，能确定就有方向改动了

**Comment by Mark-li521** [comment]
> alist的令牌过期一般不存在的，除非去alist管理-设置-其他-重置令牌，当然之前也设想过某些人的alist主动权不在手里没有令牌，考虑过加一个账号密码的对接，其实最好排查下，是alist的sign参数，还是plex的token过期问题(这个之前有人反馈过，但是我主力使用emby的，所以没复现条件)，能确定就有方向改动了

我的问题，不好意思，我使用的是auth登录接口获取的token，忘记了在设置-其他中还有一个永久期限的token。

**Comment by chen3861229** [comment]
嗯，没事，之后我加下注释，之前提到的plex首页无法播放的问题已经解决了，更新下dev代码就行了

**Comment by Mark-li521** [comment]
> ~是的，这是因为我这边实现方式的问题，没办法，受限于plex没有官方文档，目前官方客户端播放都是支持的，因为携带了挂载路径信息，但是下载和第三方客户端不进详情页播放特殊处理的，链接类似/library/parts/81327/1708863299/file.mp4，这个plex没提供直接的api查询出挂载路径，所以这边的处理是用进详情页的数据在nginx共享变量中缓存的，如果缓存没查到，就会用文件名调用plex的接口查询，和首页的查询接口同一个，所以对文件名带-的这种查询不出来，因为plex入库的时候会去掉-，目前想不出更合适的方案了，之前扒了几星期plex的接口。 目前的限制是第三方客户端注意必须进一次详情页，再点播放，不要直接点封面图上的播放按钮。 等有时间了，我再想想办法修复~
> 
> 现在不受限制了，可以直接首页点击播放

`10.0.0.8 - - [04/Mar/2024:21:01:01 +0800] "GET /library/streams/531868?X-Plex-Token=jUn2usixx_DmgjJrD7sG HTTP/1.1" 200 185796 "-" "VidHub/2024022901 CFNetwork/1492.0.1 Darwin/23.3.0" "101.68.30.101"
2024/03/04 21:01:01 [warn] 21#21: *93 js: itemInfoUri: http://10.0.0.10:32400undefined?X-Plex-Token=jUn2usixx_DmgjJrD7sG
2024/03/04 21:01:01 [error] 21#21: *93 js: error: plex_api fetch mediaItemInfo failed, Error: invalid url
10.0.0.8 - - [04/Mar/2024:21:01:01 +0800] "GET /library/parts/259765/1709090196/file.mkv%3FfilePath=/data/115/driver/%E7%94%B5%E5%BD%B1/%E5%93%A5%E6%96%AF%E6%8B%892%EF%BC%9A%E6%80%AA%E5%85%BD%E4%B9%8B%E7%8E%8B(2019)%204K%20HDR/Godzilla.King.of.the.Monsters.2019.BluRay.2160p.x265.10bit.HDR.2Audios.mUHD-FRDS.mkv?X-Plex-Token=jUn2usixx_DmgjJrD7sG HTTP/1.1" 500 62 "-" "Lavf/60.3.100" "101.68.30.101"
2024/03/04 21:01:01 [warn] 21#21: *94 js: itemInfoUri: http://10.0.0.10:32400undefined?X-Plex-Token=jUn2usixx_DmgjJrD7sG
2024/03/04 21:01:01 [error] 21#21: *94 js: error: plex_api fetch mediaItemInfo failed, Error: invalid url
10.0.0.8 - - [04/Mar/2024:21:01:01 +0800] "GET /library/parts/259765/1709090196/file.mkv%3FfilePath=/data/115/driver/%E7%94%B5%E5%BD%B1/%E5%93%A5%E6%96%AF%E6%8B%892%EF%BC%9A%E6%80%AA%E5%85%BD%E4%B9%8B%E7%8E%8B(2019)%204K%20HDR/Godzilla.King.of.the.Monsters.2019.BluRay.2160p.x265.10bit.HDR.2Audios.mUHD-FRDS.mkv?X-Plex-Token=jUn2usixx_DmgjJrD7sG HTTP/1.1" 500 62 "-" "libmpv" "101.68.30.101"`

现在彻底不能看了，vidhub中进行播放，所有的视频都500，链接处有一个undefined，不知道你有没有苹果设备，看看能不能测试一下。而且我mac上的plex客户端打开，经常出现闪退的情况。

**Comment by chen3861229** [comment]
尴尬，没苹果设备所以没测试出来，那还是先还原之前的版本吧，这个分支就是之前的方案https://github.com/chen3861229/embyExternalUrl/tree/feat/plex-server-cache-part

**Comment by Mark-li521** [comment]
> 尴尬，没苹果设备所以没测试出来，那还是先还原之前的版本吧，这个分支就是之前的方案https://github.com/chen3861229/embyExternalUrl/tree/feat/plex-server-cache-part

好的，原来的感觉已经差不多了，只是在vidhub上和剧集相关都功能都获取部分链接失败了，如开始播放、下一集、选集。但是选择了具体的剧集就没问题了，总的来说不是很影响使用。

**Comment by chen3861229** [comment]
主要还是强迫症导致的，多谢提供日志给定位到问题了，只能暂时不要更新plex的脚本了，我这边找设备多测试一下

**Comment by chen3861229** [comment]
主要还是强迫症导致的，多谢提供日志给定位到问题了，只能暂时不要更新plex的脚本了，我这边找设备多测试一下
