### ISSUE TITLE
如何设置点击emby的播放键直接调用本地MPV播放器，而不用通过二级目录中的MPV图标播放

### ISSUE THREAD

**Issue by Nanonosanma** [bpking1/embyExternalUrl#69]
通过二级目录中的mpv图标播放已经配置好，可以正常使用。不知道作者有没办法添加如题的配置

**Comment by chen3861229** [comment]
看了下作者代码，提到的这个无法实现，使用到了当前页面连接上的id参数，只有进入详情页才有这个参数，首页是没有的

**Comment by suraxiuxiu** [comment]
https://github.com/kjtsune/embyToLocalPlayer
可以看一下这个脚本

**Comment by Profitter** [comment]
目前点击二级目录中的mpv按钮能唤起mpvnet应用程序，但是不能解析mpv://的播放链接并正常播放。直接复制串流链接到mpvnet应用程序是可以播放的。想问下大佬们我这是哪里的问题。js脚本是直接嵌在服务端里的，我用的是amilys的开心版

**Comment by chen3861229** [comment]
看作者注释内容，桌面端可能另外需要一个插件吧
````
//桌面端需要额外设置,使用这个项目: https://github.com/akiirui/mpv-handler
````
