### ISSUE TITLE
strm中的内容已经是直连，是否能直接调用这个地址传给客户端播放

### ISSUE THREAD

**Issue by denglinfu** [bpking1/embyExternalUrl#71]
strm中的内容已经是https://.../d/...的形式，是alist的直连

**Comment by chen3861229** [comment]
脚本虽然做了兼容且302响应了这种远程链接，但是我自己的测试情况是，带alist账号密码会被浏览器以安全为由默认拦截(https://账号:密码@alist域名)，如果开启了sign签名，这个也是暂时没做兼容的，风险比较大，不太建议用这种。
https://github.com/bpking1/embyExternalUrl/issues/59#issuecomment-1871089258
