### ISSUE TITLE
emby播放小雅alsit中的strm视频，只有播放过一次之后才能出现按钮

### ISSUE THREAD

**Issue by jxyun99** [bpking1/embyExternalUrl#72]

**Comment by jxyun99** [comment]
![11](https://github.com/bpking1/embyExternalUrl/assets/61897787/d7997527-6758-42be-8259-0246501a8e3d)
未播放时
![22](https://github.com/bpking1/embyExternalUrl/assets/61897787/a8cecf21-bdcb-4372-baf1-a3299da38394)
点击播放过一次之后才会显示

**Comment by chen3861229** [comment]
已做修复
c0ffac66667d455174cd24e3cacca3f45556a55b
