### ISSUE TITLE
好像不支持4.8.3.X，希望大神再核实更新一下

### ISSUE THREAD

**Issue by Moe8383** [bpking1/embyExternalUrl#73]
我用AUTO_SYMLINK生成STRM，带远程反代地址，例如https://xxxx:????/d/...，然后在emby2Alist里面开启远程发送STRM，在EMBY4.8.0.39里面是可以远程直链的，但升级4.8.3后好像不行。另外，我看小雅的STRM写的是内部IP，但也可以推送到远程进行直链，是不是跟这个一个原理？如果我不在EMBY2ALIST中开启远程发送STRM，就不能直链了，是我理解错哪里了吗？刚接触，请大佬们解答一下。

**Comment by Moe8383** [comment]
用dev里面的可以支持直链了。请问有没方法可以在strm里面填写内网IP，然后推送alist直链地址到远程客户端？例如：STRM：http://192.168.1.1:5244/d/.....，目前这样填流量要走服务器。

**Comment by chen3861229** [comment]
可以比较简单的实现，也有几个人反馈需要这种方式的，之后我添加一个可选配置项来自定义

**Comment by Moe8383** [comment]
> 可以比较简单的实现，也有几个人反馈需要这种方式的，之后我添加一个可选配置项来自定义

👏👏👏

**Comment by chen3861229** [comment]
对于局域网["http://192.168.1.1:5244"]的这种strm也做了兼容，更新下代码应该就行了

**Comment by chaomarks** [comment]
4.8.3支持啊，网页可以支持阿里云，客户端支持115,123
