### ISSUE TITLE
请问有emby 4.9.0.12成功的吗

### ISSUE THREAD

**Issue by 277383761** [bpking1/embyExternalUrl#80]
我emby 4.6.4.0是直链没问题的,同样用于4.9.0.12死活不成功

**Comment by 277383761** [comment]
<img width="1817" alt="image" src="https://github.com/bpking1/embyExternalUrl/assets/49450669/bdf5eff5-779e-43d5-9e1b-ca50eee7fc02">

**Comment by chen3861229** [comment]
看日志上貌似挂载路径少填了个/开头？一般和emby版本无关，它的变动不会太大
看前两行推测，可能如下填写
````
// rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
// 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule
// 如果没有挂载,全部使用strm文件,此项填[""],必须要是数组
const embyMountPath = ["/CloudNAS/CloudDrive"];
````

**Comment by 277383761** [comment]
> 看日志上貌似挂载路径少填了个/开头？一般和emby版本无关，它的变动不会太大 看前两行推测，可能如下填写
> 
> ```
> // rclone 的挂载目录, 例如将od, gd挂载到/mnt目录下: /mnt/onedrive /mnt/gd ,那么这里就填写 /mnt
> // 通常配置一个远程挂载根路径就够了,默认非此路径开头文件将转给原始emby处理,不用重复填写至disableRedirectRule
> // 如果没有挂载,全部使用strm文件,此项填[""],必须要是数组
> const embyMountPath = ["/CloudNAS/CloudDrive"];
> ```

感谢你的回复,我刚刚测试了,修改路径也一样.主要是我同样的配方用在emby server 4.6.4上是ok的,唯独不同的地方就是两个emby的api不同.也注意了.
如果有空的话,你能临时创建一个最新测试版emby测试一下吗.如果你内边ok的话,就可能是我的问题了.
docker pull emby/embyserver:4.9.0.12

**Comment by chen3861229** [comment]
好的，晚上我回去用测试版试一下

**Comment by chen3861229** [comment]
最新测试版没有问题，检查下配置参数吧
```
2024/04/08 21:30:58 [warn] 22#22: *6 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/04/08 21:30:58 [warn] 22#22: *6 js: 0ms, mount emby file path: /AList/alias/[1]影视库/xxx/xxx/2024/4月/xxx (2015)/Season 3/xxx - S03E01 - 第1集.mkv
2024/04/08 21:30:58 [warn] 22#22: *6 js: embyPathMapping: [[0,0,"/AList",""]]
2024/04/08 21:30:58 [warn] 22#22: *6 js: strMapping replace: /AList => 
2024/04/08 21:30:58 [warn] 22#22: *6 js: mapped emby file path: /alias/[1]影视库/xxx/xxx/2024/4月/xxx (2015)/Season 3/xxx - S03E01 - 第1集.mkv
2024/04/08 21:30:58 [warn] 22#22: *6 js: 731ms, fetchAlistPathApi, UA: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
2024/04/08 21:30:58 [warn] 22#22: *6 js: redirect to: https://cn-beijing-data.aliyundrive.net/xxx?xxx
2024/04/08 21:30:59 [warn] 22#22: *6 js: success: fetchEmbySessionsMessage: {"Header":"【emby2Alist】","Text":"redirect success","TimeoutMs":0}
2024/04/08 21:30:59 [warn] 22#22: *6 js: success: fetchEmbyNotificationsAdmin: {"Name":"【emby2Alist】","Description":"redirect success"}
```

**Comment by chen3861229** [comment]
很有可能是embyPathMapping路径映射参数有重叠了，参数内的规则会从上至下依次替换执行，建议检查下

**Comment by 277383761** [comment]
> 很有可能是embyPathMapping路径映射参数有重叠了，参数内的规则会从上至下依次替换执行，建议检查下

...你能不能截图几张须要修改参数的地方?我现在看这个插件的新版里头的配置文件越来越多了.我只修改了constant.js文件里的顶上几行

**Comment by 277383761** [comment]
> 很有可能是embyPathMapping路径映射参数有重叠了，参数内的规则会从上至下依次替换执行，建议检查

成功了,确实是路径的问题.说来奇怪,我用旧版时针对emby 4.6.4的时候,那个emby2alist 0.0.1的压缩包时,就只填写一个/的路径即可,而现在要填写的路径却不一样.

**Comment by chen3861229** [comment]
嗯，成功了就好，因为改动比较大，兼容的情况变复杂了
