### ISSUE TITLE
const imageCachePolicy = 2;参数为2时，点击“修改图像”报错

### ISSUE THREAD

**Issue by NASA0719** [bpking1/embyExternalUrl#83]
emby镜像：amilys/embyserver:beta
使用最新脚本反代，const imageCachePolicy = 2;参数设置为2时，点击“修改图像”报错如下图，参数修改为 0或1正常.
<img width="285" alt="360截图16840926020209" src="https://github.com/bpking1/embyExternalUrl/assets/147677183/f090ab9c-94ba-4955-8b00-1059d91b28fe">
<img width="498" alt="360截图17040513474168" src="https://github.com/bpking1/embyExternalUrl/assets/147677183/b70893ec-7f53-4d4c-8e66-c3ceabd2a35f">

**Comment by chen3861229** [comment]
好的，多谢反馈，应该是我去除缩放参数范围太大把token也移除掉了，晚上回去我修复一下

**Comment by NASA0719** [comment]
> 已做修复
> 9d95aa561f84bc4a21d9bd11bf3963ad970e396f

收到，感谢回复。
