### ISSUE TITLE
main的远程直链不了，还是走服务器；dev的可以远程直链，是需要什么设置吗？

### ISSUE THREAD

**Issue by Moe8383** [bpking1/embyExternalUrl#84]
main的远程直链不了，还是走服务器；dev的可以远程直链，是需要什么设置吗？

**Comment by chen3861229** [comment]
可能是这个原因#85
需要麻烦再更新下代码了

**Comment by Moe8383** [comment]
> 可能是这个原因#85 需要麻烦再更新下代码了

大佬真是神速，因为docker-compose里面就是bridge模式的：）。另外，有个问题不知道是什么原因，我用fileball（IOS）接入自己反代的域名（远程），总会先尝试链接内网IP，一旦连上了（我用了代理回家）就走家里服务器的流量。如果先把回家代理关了，等内网IP链接失败后，就走正常的反代域名，之后就一切正常了。用infuse就没有这个问题，

**Comment by chen3861229** [comment]
>>因为docker-compose里面就是bridge模式的
多谢提醒

1.这个我之前遇到过类似的，但不完全相同，媒体服务都是有UDP广播局域网自动发现的，但是广域网走的是服务开放的接口获取服务器的ip以及端口信息，例如emby默认的8096端口，我路由器映射出去也是8096，这就导致接入了网络发现接口的客户端会擅自连接8096端口，而忽略连接nginx的反代端口8098之类的，尽管我是手动使用8098端口登录的也没用，我是用的官方emby安卓客户端。

我这边的解决方案是将路由器端口映射为8096=>7096，路由器这边的设置，emby是不可能知道的，表现形式为控制台端口还是8096，所以客户端在擅自连接8096不通时就会老实连接反代的8098了。

猜测fileball接口接入比较完善了，使用了媒体服务提供的网络发现接口，而infuse并没有调用此接口，以用户手动填写的为准

可以参考一下，不确定能不能解决你的问题

**Comment by Moe8383** [comment]
> 我这边的解决方案是将路由器端口映射为8096=>7096，路由器这边的设置，emby是不可能知道的，表现形式为控制台端口还是8096，所以客户端在擅自连接8096不通时就会老实连接反代的8098了。

感谢指点，又学到了新知识。我想同时保留8096的本地模式，没有在路由映射，只用反代，感觉这样可以少开一点端口。

**Comment by 277383761** [comment]
我刚刚成功,也遇到这个问题了,用手机流量走的直链没错,但是连接一次wifi后确实走了内网走,到目前没错,但是再关闭wifi重新用数据流量时emby官方客户端就会默认走服务端的端口号去了.就不直链了.

**Comment by 277383761** [comment]
> > 因为docker-compose里面就是bridge模式的
> 
> 多谢提醒
> 
> 1.这个我之前遇到过类似的，但不完全相同，媒体服务都是有UDP广播局域网自动发现的，但是广域网走的是服务开放的接口获取服务器的ip以及端口信息，例如emby默认的8096端口，我路由器映射出去也是8096，这就导致接入了网络发现接口的客户端会擅自连接8096端口，而忽略连接nginx的反代端口8098之类的，尽管我是手动使用8098端口登录的也没用，我是用的官方emby安卓客户端。
> 
> 我这边的解决方案是将路由器端口映射为8096=>7096，路由器这边的设置，emby是不可能知道的，表现形式为控制台端口还是8096，所以客户端在擅自连接8096不通时就会老实连接反代的8098了。
> 
> 猜测fileball接口接入比较完善了，使用了媒体服务提供的网络发现接口，而infuse并没有调用此接口，以用户手动填写的为准
> 
> 可以参考一下，不确定能不能解决你的问题

确实把原emby的端口号映射到别处去就行了

**Comment by chen3861229** [comment]
emby这个获取服务器信息(ip和端口)的接口也可以反代修改，因为没确定UDP广播的这个行为会不会优先级更高，而且改路由器端口映射已经解决，所以搁置下来了，等我有时间先把服务器信息接口反代加一下吧

**Comment by chen3861229** [comment]
可以更新尝试一下，不知道有没有效果
8fdf2b90ec3ab901f996249f9634d47fbbcc6ed2

**Comment by Moe8383** [comment]
> 可以更新尝试一下，不知道有没有效果
> 
> 8fdf2b90ec3ab901f996249f9634d47fbbcc6ed2

感谢感谢。另外请教，我Emby媒体库设了章节、纳入计划，但播放的时候，有时候可以选章节（不需要缩略图），有时候没有，要多重新播放多几次就可以显示章节，是什么原因呢？安卓电视

**Comment by chen3861229** [comment]
额，我没用过这个功能，感觉应该挺费性能的，猜测是文件比较多，可能还没分析完毕吧，播放的时候可能emby内部会提高优先级
