### ISSUE TITLE
emby劫持失败，无法获取直链

### ISSUE THREAD

**Issue by l648741695** [bpking1/embyExternalUrl#88]
大神是不是我安装的配置文件有问题，老版本可以劫持直链，现在不知道哪里配置出现了问题没法找到直链，安装环境为群晖
<html>
<body>

2024/04/09 21:37:12 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:12 +0000] "GET /embywebsocket?api_key=4974b2033051435abc44dfbc2b1311cb&deviceId=8a1d3408-888d-458c-b983-cd5396ee9f1f HTTP/1.1" 101 411 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
-- | -- | --
2024/04/09 21:37:10 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:10 +0000] "HEAD /emby/videos/148615/stream/%E9%A3%8E%E5%91%B3%E5%8E%9F%E4%BA%A7%E5%9C%B0%20S04E01.strm?UserId=d4fa5b7fd481430c8b5051e7a6f7fe11&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json&MediaSourceId=2af5f3f12a4280ed8402492cec3ce667&Static=true&filePath=http%253A%252F%252F192.168.11.1%253A5244%252F%25E9%2598%25BF%25E9%2587%258C%25E4%25BA%2591%25E7%259B%2598%252F%25E7%25BA%25AA%25E5%25BD%2595%25E7%2589%2587%252F%25E9%25A3%258E%25E5%2591%25B3%25E5%258E%259F%25E4%25BA%25A7%25E5%259C%25B0%25EF%25BC%25882019%25EF%25BC%2589%252FSeason%252004%252F%25E9%25A3%258E%25E5%2591%25B3%25E5%258E%259F%25E4%25BA%25A7%25E5%259C%25B0%2520S04E01.mp4&notLocal=1 HTTP/1.1" 302 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: redirect to: http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: fetchStrmLastLink response.status: 200
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: filePath hit redirectStrmLastLinkRule: [0,["http://172.","http://10.","http://192.","http://[fd00:"]]
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: mapped emby file path: http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: embyPathMapping: [[0,0,"/volume1/CloudNAS/CloudDrive2/WebDAV",""]]
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: 0ms, mount emby file path: http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
2024/04/09 21:37:10 | stderr | 2024/04/09 13:37:10 [warn] 23#23: *164 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "POST /emby/Sessions/Playing/Stopped?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "POST /emby/Sessions/Playing/Progress?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "POST /emby/Sessions/Playing?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 204 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "GET /emby/videos/148615/stream/%E9%A3%8E%E5%91%B3%E5%8E%9F%E4%BA%A7%E5%9C%B0%20S04E01.strm?UserId=d4fa5b7fd481430c8b5051e7a6f7fe11&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json&MediaSourceId=2af5f3f12a4280ed8402492cec3ce667&Static=true&filePath=http%253A%252F%252F192.168.11.1%253A5244%252F%25E9%2598%25BF%25E9%2587%258C%25E4%25BA%2591%25E7%259B%2598%252F%25E7%25BA%25AA%25E5%25BD%2595%25E7%2589%2587%252F%25E9%25A3%258E%25E5%2591%25B3%25E5%258E%259F%25E4%25BA%25A7%25E5%259C%25B0%25EF%25BC%25882019%25EF%25BC%2589%252FSeason%252004%252F%25E9%25A3%258E%25E5%2591%25B3%25E5%258E%259F%25E4%25BA%25A7%25E5%259C%25B0%2520S04E01.mp4&notLocal=1 HTTP/1.1" 302 138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: redirect to: http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: fetchStrmLastLink response.status: 200
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: filePath hit redirectStrmLastLinkRule: [0,["http://172.","http://10.","http://192.","http://[fd00:"]]
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: mapped emby file path: http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: embyPathMapping: [[0,0,"/volume1/CloudNAS/CloudDrive2/WebDAV",""]]
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: 0ms, mount emby file path: http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: cached PlaybackInfo path, will skip excess fetchEmbyFilePath
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "GET /emby/Users/d4fa5b7fd481430c8b5051e7a6f7fe11/Items/148615?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn HTTP/1.1" 200 1106 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "GET /emby/Users/d4fa5b7fd481430c8b5051e7a6f7fe11?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn HTTP/1.1" 200 1020 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: transfer playbackinfo: {"MediaSources":[{"Protocol":"Http","Id":"2af5f3f12a4280ed8402492cec3ce667","Path":"http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4","Type":"Default","Container":"strm","Size":0,"Name":"风味原产地 S04E01","IsRemote":true,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/148615/stream/%E9%A3%8E%E5%91%B3%E5%8E%9F%E4%BA%A7%E5%9C%B0%20S04E01.strm?UserId=d4fa5b7fd481430c8b5051e7a6f7fe11&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json&MediaSourceId=2af5f3f12a4280ed8402492cec3ce667&Static=true&filePath=http%253A%252F%252F192.168.11.1%253A5244%252F%25E9%2598%25BF%25E9%2587%258C%25E4%25BA%2591%25E7%259B%2598%252F%25E7%25BA%25AA%25E5%25BD%2595%25E7%2589%2587%252F%25E9%25A3%258E%25E5%2591%25B3%25E5%258E%259F%25E4%25BA%25A7%25E5%259C%25B0%25EF%25BC%25882019%25EF%25BC%2589%252FSeason%252004%252F%25E9%25A3%258E%25E5%2591%25B3%25E5%258E%259F%25E4%25BA%25A7%25E5%259C%25B0%2520S04E01.mp4&notLocal=1","ReadAtNativeFramerate":false,"OriginDirectStreamUrl":"/videos/148615/master.m3u8?DeviceId=8a1d3408-888d-458c-b983-cd5396ee9f1f&MediaSourceId=2af5f3f12a4280ed8402492cec3ce667&PlaySessionId=82c11468b7e242a5b8ad80370b2ed22e&api_key=4974b2033051435abc44dfbc2b1311cb&VideoCodec=h264&VideoBitrate=140000000&TranscodingMaxAudioChannels=2&SegmentContainer=m4s,ts&MinSegments=1&BreakOnNonKeyFrames=True&SubtitleStreamIndexes=-1&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=62
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: remove transcode config
2024/04/09 21:37:09 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:09 +0000] "POST /emby/Items/148615/PlaybackInfo?UserId=d4fa5b7fd481430c8b5051e7a6f7fe11&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1" 200 2076 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: modify direct play info
2024/04/09 21:37:09 | stderr | 2024/04/09 13:37:09 [warn] 23#23: *23 js: origin playbackinfo: {"MediaSources":[{"Protocol":"Http","Id":"2af5f3f12a4280ed8402492cec3ce667","Path":"http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4","Type":"Default","Container":"strm","Size":0,"Name":"风味原产地 S04E01","IsRemote":true,"SupportsTranscoding":true,"SupportsDirectStream":false,"SupportsDirectPlay":true,"IsInfiniteStream":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":false,"MediaStreams":[],"Formats":[],"RequiredHttpHeaders":{},"DirectStreamUrl":"/videos/148615/master.m3u8?DeviceId=8a1d3408-888d-458c-b983-cd5396ee9f1f&MediaSourceId=2af5f3f12a4280ed8402492cec3ce667&PlaySessionId=82c11468b7e242a5b8ad80370b2ed22e&api_key=4974b2033051435abc44dfbc2b1311cb&VideoCodec=h264&VideoBitrate=140000000&TranscodingMaxAudioChannels=2&SegmentContainer=m4s,ts&MinSegments=1&BreakOnNonKeyFrames=True&SubtitleStreamIndexes=-1&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=62&TranscodeReasons=ContainerNotSupported","TranscodingUrl":"/videos/148615/master.m3u8?DeviceId=8a1d3408-888d-458c-b983-cd5396ee9f1f&MediaSourceId=2af5f3f12a4280ed8402492cec3ce667&PlaySessionId=82c11468b7e242a5b8ad80370b2ed22e&api_key=4974b2033051435abc44dfbc2b1311cb&VideoCodec=h264&VideoBitrate=140000000&TranscodingMaxAudioChannels=2&SegmentContainer=m4s,ts&MinSegments=1&BreakOnNonKeyFrames=True&SubtitleStreamIndexes=-1&ManifestSubtitles=vtt&h264-profile=high,main,baseline,constrainedbaseline,high10&h264-level=62&TranscodeReasons=ContainerNotSupported","TranscodingSubProtocol":"hls","TranscodingContainer":"m4s,ts","ReadAtNativeFramerate":false}],"PlaySessionId":"82c11468b7e242a5b8ad80370b2ed22e"}
2024/04/09 21:37:08 | stderr | 2024/04/09 13:37:08 [warn] 23#23: *23 js: playbackinfo proxy query string: UserId=d4fa5b7fd481430c8b5051e7a6f7fe11&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby Web&X-Emby-Device-Name=Chrome Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json
2024/04/09 21:37:08 | stderr | 2024/04/09 13:37:08 [warn] 23#23: *23 js: playbackinfo proxy uri: /proxy/emby/Items/148615/PlaybackInfo
2024/04/09 21:37:08 | stderr | 2024/04/09 13:37:08 [notice] 23#23: *23 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: 172.19.0.1, server: default, request: "POST /emby/Items/148615/PlaybackInfo?UserId=d4fa5b7fd481430c8b5051e7a6f7fe11&StartTimeTicks=0&IsPlayback=true&AutoOpenLiveStream=true&MaxStreamingBitrate=140000000&X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn&reqformat=json HTTP/1.1", host: "192.168.11.193:8095"
2024/04/09 21:37:08 | stdout | 172.19.0.1 - - [09/Apr/2024:13:37:08 +0000] "GET /emby/System/Endpoint?X-Emby-Client=Emby%20Web&X-Emby-Device-Name=Chrome%20Windows&X-Emby-Device-Id=8a1d3408-888d-458c-b983-cd5396ee9f1f&X-Emby-Client-Version=4.7.14.0&X-Emby-Token=4974b2033051435abc44dfbc2b1311cb&X-Emby-Language=zh-cn HTTP/1.1" 200 36 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" "-"

</body>
</html>

**Comment by chen3861229** [comment]
不好意思，是前天添加的一个参数导致的，再次更新下代码就可以了
#85

**Comment by l648741695** [comment]
> 不好意思，是前天添加的一个参数导致的，再次更新下代码就可以了 #85

我是今天下载的代码，应该是没问题的。我检查了已经注释掉了参数，现在又用回1月份版本了

**Comment by l648741695** [comment]
> 这个链接有问题，不是直链，是alist的页面访问链接，需要登录的
> 
> ```
> http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
> ```
> 
> 正确应该是这样的
> 
> ```
> http://192.168.11.1:5244/d/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
> ```
> 
> 老版本为什么能生效没排查到原因。。。理论上错误的链接应该是读取不了的
> 
> 避免以后出现类似问题，做了补偿 [06319b3](https://github.com/bpking1/embyExternalUrl/commit/06319b3d6a98f06e269f9a5b839b326f07422565)

<html>
<body>

2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: redirect to: https://cn-beijing-data.aliyundrive.net/sPWdxKIl%2F2049818%2F606a3a1dcfe40946e3ad4f209e3feea92707fd9d%2F606a3a1d52ac35b36b3c4e0da7801974b5d5a316?callback=eyJjYWxsYmFja1VybCI6Imh0dHA6Ly9iajI5LmFwaS1ocC5hbGl5dW5wZHMuY29tL3YyL2ZpbGUvZG93bmxvYWRfY2FsbGJhY2siLCJjYWxsYmFja0JvZHkiOiJodHRwSGVhZGVyLnJhbmdlPSR7aHR0cEhlYWRlci5yYW5nZX1cdTAwMjZidWNrZXQ9JHtidWNrZXR9XHUwMDI2b2JqZWN0PSR7b2JqZWN0fVx1MDAyNmRvbWFpbl9pZD0ke3g6ZG9tYWluX2lkfVx1MDAyNnVzZXJfaWQ9JHt4OnVzZXJfaWR9XHUwMDI2ZHJpdmVfaWQ9JHt4OmRyaXZlX2lkfVx1MDAyNmZpbGVfaWQ9JHt4OmZpbGVfaWR9XHUwMDI2cGRzX3BhcmFtcz0ke3g6cGRzX3BhcmFtc30iLCJjYWxsYmFja0JvZHlUeXBlIjoiYXBwbGljYXRpb24veC13d3ctZm9ybS11cmxlbmNvZGVkIiwiY2FsbGJhY2tTdGFnZSI6ImJlZm9yZS1leGVjdXRlIiwiY2FsbGJhY2tGYWlsdXJlQWN0aW9uIjoiaWdub3JlIn0%3D&callback-var=eyJ4OmRvbWFpbl9pZCI6ImJqMjkiLCJ4OnVzZXJfaWQiOiIxZDYzYjNiZGVhNjE0MDUyYjg3MmEwYjdiMWJkZjBmMiIsIng6ZHJpdmVfaWQiOiIzNzU0MTU0MCIsIng6ZmlsZV9pZCI6IjY1OTZjZWVmYzVmZjk3M2FiZmIwNGY3ZDllYjRlZmRkZDBiNDU0YzciLCJ4OnBkc19wYXJhbXMiOiJ7XCJhcFwiOlwiNzY5MTdjY2NjZDQ0NDFjMzk0NTdhMDRmNjA4NGZiMmZcIn0ifQ%3D%3D&di=bj29&dr=37541540&f=6596ceefc5ff973abfb04f7d9eb4efddd0b454c7&pds-params=%7B%22ap%22%3A%2276917ccccd4441c39457a04f6084fb2f%22%7D&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E4%25B8%2580%25E4%25BA%25BA%25E4%25B9%258B%25E4%25B8%258B%2520-%2520S01E01%2520-%2520%25E5%25BC%2582%25E4%25BA%25BA%25E5%2588%2580%25E5%2585%25B5%25E8%25B5%25B7%25EF%25BC%258C%25E9%2581%2593%25E7%2582%2581%25E6%2590%25BA%25E9%2598%25B4%25E9%2598%25B3.mp4&security-token=CAIS8gF1q6Ft5B2yfSjIr5fhPtncqLQX0YTYbxOAjE0MOv1evqOagTz2IHhMf3NpBOkZvvQ1lGlU6%2Fcalq5rR4QAXlDfNW7Ed2jSqFHPWZHInuDox55m4cTXNAr%2BIhr%2F29CoEIedZdjBe%2FCrRknZnytou9XTfimjWFrXWv%2Fgy%2BQQDLItUxK%2FcCBNCfpPOwJms7V6D3bKMuu3OROY6Qi5TmgQ41Uh1jgjtPzkkpfFtkGF1GeXkLFF%2B97DRbG%2FdNRpMZtFVNO44fd7bKKp0lQLs0ARrv4r1fMUqW2X543AUgFLhy2KKMPY99xpFgh9a7j0iCbSGyUu%2FhqAAU4f%2FfY2oL78umCSvHdnvLpMSpzMkOFicdwuy2FdKGbZk1sYhGY0KQNMrtbx%2FasaO3xwMuerH6tO166gMUiqcZucd%2BL2FJIUIbijRlfjk7EPDHSGJMhLW
-- | -- | --
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: try to fetch alist path from /阿里云盘/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: try to fetch alist path from /迅雷网盘/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: try to fetch alist path from /百度网盘/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: try to fetch alist path from /夸克网盘/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: try to fetch alist path from /天翼云盘/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: 4ms, fetchAlistPathApi
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: mapped emby file path: 192.168.11.1:5244/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: embyPathMapping: []
2024/04/11 11:00:31 | stderr | 2024/04/11 03:00:31 [warn] 21#21: *231 js: 3ms, mount emby file path: 192.168.11.1:5244/动漫/一人之下 (2016)/Season 1/一人之下 - S01E01 - 异人刀兵起，道炁携阴阳.mp4


</body>
</html>

旧版本日志如上，他自己去找alist下挂的各个网盘对应的链接了

**Comment by l648741695** [comment]
> 这个链接有问题，不是直链，是alist的页面访问链接，需要登录的
> 
> ```
> http://192.168.11.1:5244/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
> ```
> 
> 正确应该是这样的
> 
> ```
> http://192.168.11.1:5244/d/阿里云盘/纪录片/风味原产地（2019）/Season 04/风味原产地 S04E01.mp4
> ```
> 
> 老版本为什么能生效没排查到原因。。。理论上错误的链接应该是读取不了的
> 
> 避免以后出现类似问题，做了补偿 [06319b3](https://github.com/bpking1/embyExternalUrl/commit/06319b3d6a98f06e269f9a5b839b326f07422565)

我拉了新的代码，8095也打不开了

**Comment by chen3861229** [comment]
1.看日志就清晰多了，已经回忆起是如何生效的了
2.新代码对默认端口进行了修改，以保证流量识别的准确性，如果是昨天更新的，nginx内部端口改为了8090，且如果是docker部署的，需要更改下docker容器的端口映射，之前为
````
ports:
  - 8095:80
````
需要更改为
````
ports:
  - 8095:8090
````
如果更新了今日的代码，默认nginx的反代端口改了8091，需要更改nginx容器为host(主机)网络模式，并取消docker容器的端口映射，直接使用8091访问即可

**Comment by l648741695** [comment]
> 1.看日志就清晰多了，已经回忆起是如何生效的了 2.新代码对默认端口进行了修改，以保证流量识别的准确性，如果是昨天更新的，nginx内部端口改为了8090，且如果是docker部署的，需要更改下docker容器的端口映射，之前为
> 
> ```
> ports:
>   - 8095:80
> ```
> 
> 需要更改为
> 
> ```
> ports:
>   - 8095:8090
> ```
> 
> 如果更新了今日的代码，默认nginx的反代端口改了8091，需要更改nginx容器为host(主机)网络模式，并取消docker容器的端口映射，直接使用8091访问即可

最新代码已经可以完美运行了，我把strm的链接加上了/d，感谢大佬！
