### ISSUE TITLE
如何安装不同反代代理emby以及jellyfin

### ISSUE THREAD

**Issue by l648741695** [bpking1/embyExternalUrl#98]
大佬下午好，我在我的nas安装了emby以及jellyfin，我尝试安装了两个反代，但会被覆盖，我怎么可以安装两个呢？该调整哪些设置，假设我的emby是8096端口，jellyfin是8097端口

**Comment by chen3861229** [comment]
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/75fb6325-ae19-474b-880b-7b138778e7c3)
![image](https://github.com/bpking1/embyExternalUrl/assets/42368856/a4fd3a21-ce35-4f79-8007-fbcda8720d82)

host(主机)网络模式，bridge(网桥)模式的容器端口映射需要自己核对一下
nginx-emby
````
emby.conf中server=>listen改为8091
constant.js中embyHost填写emby原始服务地址和端口,例如：
const embyHost = "http://192.168.31.200:8096";
路由器公网端口映射，8091 => 192.168.31.200:8091
局域网和公网全都使用8091访问emby
````

nginx-jellyfin
````
emby.conf中server=>listen改为8092
constant.js中embyHost填写emby原始服务地址和端口,例如：
const embyHost = "http://192.168.31.200:8097";
路由器公网端口映射，8092 => 192.168.31.200:8092
局域网和公网全都使用8092访问jellyfin
````

**Comment by l648741695** [comment]
可以安装，谢谢大佬
